### ISSUE TITLE
How to design an actor-critic network with two non-shared LSTMs that take separate inputs?

### ISSUE THREAD

**Issue by baiydaavi** [hill-a/stable-baselines#1002]
Is it possible to design an actor-critic network with separate LSTMs such that one of the LSTMs outputs value and the other outputs action? The two LSTMs also get different inputs. Thanks for your help in advance.

**Comment by Miffyli** [comment]
There is no pre-made solution for this and you have to create a [custom network](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html) for this. If by "separate inputs" you mean different observations, that is not supported per se but you can do tricks like [this](https://github.com/hill-a/stable-baselines/issues/133#issuecomment-561805417).

**Comment by baiydaavi** [comment]
Can I create a custom network without changing what an LSTM cell does? I thought in stable baselines, the LSTM cell always outputs policy and value. However, I want one LSTM to only compute policy and the other one to only compute the value. Also, by separate inputs I mean a different set of observations for the two LSTMs. I am attaching a cartoon depiction of what I wanna do. It's Supplementary Figure 9 from the nature meta-RL paper.
![2-lstm](https://user-images.githubusercontent.com/14941840/93139388-7c0ce000-f695-11ea-8d55-804a01a46f62.png)

**Comment by Miffyli** [comment]
With custom policies you can define a network of your liking, and I _think_ this should be doable, as long you manage to provide the two streams of input data with trickery through the example I linked above. The custom policy example in docs should provide a good starting point.
