### ISSUE TITLE
Retrain from updated environment

### ISSUE THREAD

**Issue by anguyenbus** [hill-a/stable-baselines#1003]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

[question].  

Hi,

my case is: if have a changing environment like a RNN network, and the reinforcement learning agent is to control whether I should mask the input. (input = input*mask) and mask is [0,1] discrete.

So what I did is that I train RNN for some epochs, and RNN is the observation of agent.

Agent will then train by model.learn(5000), RNN is in infernce mode when model is trained

Then I go back and train RNN with model.predict(deterministic= True) for predicting the mask.

I am not sure if the model will sample from the **updated** RNN environment?

**Comment by Miffyli** [comment]
Sounds like this should work, but without detailed code I can not be sure.

This sounds like it is not a stable-baselines issue/enhancement though and as written in issue template, we do not offer tech support for custom things like this.

**Comment by anguyenbus** [comment]
Thank you! The problem for me is that I want to try this task with stablebaseline, but I couldnot find the documentation detailing how buffer_replay being sampled from the updated environment. I am still search for it though on stablebaseline. So sorry if this one is a duplicated question.

**Comment by Miffyli** [comment]
I recommend you start going over the code and see if it matches what you expect, documentation likely does not contain answers for a custom case like this.

**Comment by anguyenbus** [comment]
Thank you!
