### ISSUE TITLE
[Question] SAC and PPO2: get episode info from buffer

### ISSUE THREAD

**Issue by prabhasak** [hill-a/stable-baselines#1006]
Hello. I am running SAC on a Gym env created using the ``make_vec_env`` function (which also wraps the env with a Monitor wrapper)

**Question 1**

1. I want to log the mean episode reward and length info. I see the values are already logged using ``self.ep_info_buff`` ([here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L499))
2. However, the buffer turned out empty, and led me to **[this](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L499)** line, which says "Retrieve reward and episode length if using Monitor wrapper." Which we are, afaik
3. Turns out the ``info`` from ``env.step`` is empty ([here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L410)). **It looks like info is typically ``{}`` for most Gym envs**. Any thoughts on how to get the values I need directly from, say, the Monitor wrapper? Or is there any other alternative?

In the case of PPO, it is the variable ``ep_infos`` that is empty ([here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L338)). Is there another way to get the episode reward and length?

**Question 2**

This is more of a TF question. I am using **TF 1.15** for the experiments and want to log the loss parameters ([here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L293)). However, to be able to log, it looks like I need to first convert the parameters to a numpy array. I tried to use ``tensor.eval(self.sess)`` and ``self.sess.run(tensor)`` on the loss tensors, but there's an error asking me to use placeholder variables, and the Internet wasn't of much help. **Could you please provide an example of converting one of the loss parameters to a numpy array?**

I know TF2 has an automatic .numpy() method, but I will have to stick to TF 1.15 because of other reasons. I could download the .csv from Tensorboard, but I'd like to log the values during training. The traceback for when I tried to convert the ``policy_loss`` tensor to a numpy with a ``policy_loss.eval(session=self.sess)`` and a ``self.sess.run(policy_loss)``:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input/input/Ob' with dtype double and shape [?,11]
         [[node input/input/Ob (defined at C:\Users\prabh\Miniconda3\envs\thesis\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
```

Thanks so much!

**Comment by Miffyli** [comment]
Question 1: Monitor wrapper should [add the `episode` item to info dictionary](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/bench/monitor.py#L107), and it should be shown in the verbose print as the training progresses. If you only need to analyse results after training you could open and process the monitor .csv files and print the results from there.

Question 2: The loss values [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L352) are in numpy objects, so you could stab the code [around this point](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L463) to capture the values you want to track and print out.

I realize you said you'd like to use TF 1.x, but for a future reference [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) is easier to hack around with its PyTorch nature.

**Comment by araffin** [comment]
>I want to log the mean episode reward and length info. I see the values are already logged using self.ep_info_buff (here)

The two are already being logged (as `ep_rew_mean` and  `ep_len_mean`), otherwise, you can access them using callbacks.

>However, the buffer turned out empty, and led me to this line, which says "Retrieve reward and episode length if using Monitor wrapper." Which we are, afaik

```python
from stable_baselines import SAC, PPO2
from stable_baselines.common.cmd_util import make_vec_env 

# model = PPO2("MlpPolicy", env, verbose=1)
model = SAC("MlpPolicy", env, verbose=1)
model.learn(10000)
```

If you run the code above, you can see the two values in the log.
As mentioned in the issue template, please provide a minimal working example to reproduce your issue next time ;)

>Question 2

As mentioned by @Miffyli , I would highly recommend to give SB3 a try ;) (it is now safe to use as we checked the performance on both Atari and PyBullet continuous envs).

**Comment by prabhasak** [comment]
Thank you for the quick replies. Turns out I was passing the model the env string instead of the ``make_vec_env()`` object, silly me!

@araffin FYI there might be a small bug. The minimal example throws a ``KeyError: 'r'``. I believe the keys for ``ep_info`` need to be ``'reward'`` and ``'length'`` instead of ``'r'`` and ``'l'`` (in both ``sac.py`` and ``ppo2.py``, maybe more). I have attached the traceback :)

```
  File "debug_monitor.py", line 7, in <module>
    model.learn(10000)
  File "C:\IL_UAV\masters-thesis-final\stable_baselines\sac\sac.py", line 527, in learn
    logger.logkv('ep_rewmean', safe_mean([ep_info['r'] for ep_info in self.ep_info_buf]))
  File "C:\IL_UAV\masters-thesis-final\stable_baselines\sac\sac.py", line 527, in <listcomp>
    logger.logkv('ep_rewmean', safe_mean([ep_info['r'] for ep_info in self.ep_info_buf]))
KeyError: 'r'
```

> Question 2: The loss values [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L352) are in numpy objects, so you could stab the code [around this point](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/sac/sac.py#L463) to capture the values you want to track and print out.

@Miffyli you just saved me a great deal of trouble with that tip. Thank you so much!

I am wrapping up my Master's Thesis end of this month, will definitely switch to SB3 after that. Kudos for the awesome repo, folks :)
