### ISSUE TITLE
Tensorboard Logging Issue after multiple consecutive calls to self.learn(..., reset_num_timesteps=False)

### ISSUE THREAD

**Issue by krishpop** [hill-a/stable-baselines#1007]
<img width="1388" alt="Screen Shot 2020-09-19 at 1 53 06 AM" src="https://user-images.githubusercontent.com/5395510/93663532-92ac9180-fa1d-11ea-9d6f-d9175e8f2570.png">

**Describe the bug**
`step` used to log self.summary when training SAC resets to 0 when `self.learn(reset_num_timesteps=False)` is run. This results in some tensorboard logs to become disconnected and have logging begin at step=0 again.

**Additional context**
This can be resolved by logging to tensorboard with self.num_timesteps instead of step passed into self._train_step.

**Comment by araffin** [comment]
Should be fixed in SB3: https://github.com/DLR-RM/stable-baselines3/issues/433
