### ISSUE TITLE
[Question] DDPG action space symmetric?

### ISSUE THREAD

**Issue by RGring** [hill-a/stable-baselines#102]
Hi again,
Why does the action space need to be symmetric in DDPG learning?

**Comment by araffin** [comment]
DDPG uses tanh before output (so its output lies in [-1, 1]) and then this output is rescaled.
Because of that, it can only handles symmetric  action spaces.

**Comment by RGring** [comment]
okay. Is it not possible to just remap; e.g.  [-1, 1] --> [0 , 1]?

**Comment by araffin** [comment]
Well, nothing prevent you from doing that in your env.

**Comment by csaroff** [comment]
@araffin Why not just rescale the agent's actions within the agent code to fit the bounds of the action space?  Seems like it would make the agent code more generic.

Any reason that you couldn't just apply a linear transformation?

```python
def rescale_actions(tanh_output, low, high):
    range = high - low
    return tanh_output * range / 2 + (low + (0.5 * range))
```

**Comment by yutao-li** [comment]
yes, I agree with @csaroff , it's cumbersome to do it ourselves
