### ISSUE TITLE
[question] Role of rewards in env outside training

### ISSUE THREAD

**Issue by Gistix** [hill-a/stable-baselines#1020]
I'm new to Stable Baselines/Open Gym/RL itself but I have created a custom gym env and trained it with a modified SAC for real time observation performance. 
So I wonder if rewards have any role outside of training process, my idea is to omit reward calculation during actual usage since said data won't be available in a real environment and for performance reasons too.
I apologize in advance if the answer is obvious but I'm still trying to grasp everything,

**Comment by Miffyli** [comment]
No, you do not need the reward signal when you are deploying/using the trained agent, you only need it to train the agent (unless you provide the reward signal as part of the observation).

**Comment by Gistix** [comment]
Thank you, I'll make sure to read it up!
