### ISSUE TITLE
[question] DQN: How to control number of samples we collect from the environment before doing an update? 

### ISSUE THREAD

**Issue by JessicaBorja** [hill-a/stable-baselines#1021]
Similar to as with DDPG where you can control the amount of timesteps we collect samples setting _nb_rollout_steps_ and the amount of update steps with _nb_train_steps_ , is there something similar for DQN? So far I've not been able to do so.

**Comment by Miffyli** [comment]
Yes, the parameter is `train_freq` for controlling number of steps before updating the network. The answer is in [docs](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html), but to be fair I understand that different parameter naming like this is confusing.

If you have no other questions/issues related to stable-baselines you may close this issue.

**Comment by JessicaBorja** [comment]
thanks!

**Comment by araffin** [comment]
To give a complement to the answer: best is to use [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) unless you need DQN extension. In addition to `train_freq`, you can specify `gradient_steps` (cf doc)
