### ISSUE TITLE
[question] Does LSTM state gets reset to all zeros for each episode, mini-batch, etc. ?

### ISSUE THREAD

**Issue by denyHell** [hill-a/stable-baselines#1022]
As titled. 

If not, how can we do that?

**Comment by Miffyli** [comment]
Related issue #759 

Hidden states are reset for each episode (but gradient is only computed over the currently collected batch of samples). For manually resetting state [see this comment](https://github.com/hill-a/stable-baselines/issues/759#issuecomment-604972847).

**Comment by denyHell** [comment]
yes i just the lines 
` cell_state = cell_state * (1 - mask)`
`hidden = hidden * (1 - mask)`
which does what you say.

Thanks a lot!
