### ISSUE TITLE
[question] Example for Cusom Policy for SAC with combined image and box type observation

### ISSUE THREAD

**Issue by ajishbabu** [hill-a/stable-baselines#1025]
I am trying to use SAC for a custom robot env which has both image and box type data as observations. The plan is to use a custom network which looks something like this.

![image](https://user-images.githubusercontent.com/7862559/96591498-99157e00-12e7-11eb-89a2-d22041335f29.png)

Does anyone have an example of how to implement this? Any help would be appreciated.

**Comment by araffin** [comment]
Hello,
Duplicate of https://github.com/hill-a/stable-baselines/issues/947 and https://github.com/hill-a/stable-baselines/issues/133#issuecomment-533806931

Anyway, I would recommend you to use [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) as such modifications should be easier to implement.

**Comment by ajishbabu** [comment]
@araffin Thanks a lot

**Comment by araffin** [comment]
Update for SB3: the fix will be merged with master soon ;)
https://github.com/DLR-RM/stable-baselines3/pull/198
