### ISSUE TITLE
How to get integer actions in PPO2 algorithm

### ISSUE THREAD

**Issue by yunTerry** [hill-a/stable-baselines#1027]
I defined action space as a set of integers in `MyEnv` class

```py
# MyEnv class
self.action_space = gym.spaces.Box(
            low=-10, high=10, shape=(1,), dtype=np.int)


# train model
env = DummyVecEnv([lambda: MyEnv(df, ...)])
model = PPO2(MlpPolicy, env, verbose=1)
model.learn(10000)
```
but when I train a model, it seems get float actions like this: 

![图片](https://user-images.githubusercontent.com/15991012/97172067-6ed12e00-17c9-11eb-8753-cac61b2bcdf8.png)

I don't know why

**Comment by Miffyli** [comment]
This is because you define action space as a `Box`, not as `Discrete`. `Box` space is a "continuous" space, where actions are supposed to be floats.

Note that this place is not for tech support, so if you do not have further questions/issues specifically related to stable-baselines you may close this issue.

**Comment by yunTerry** [comment]
but I've set `dtype=np.int`
![图片](https://user-images.githubusercontent.com/15991012/97172660-4ac21c80-17ca-11eb-9033-c3387d6291fb.png)

I don't use `Discrete` space because it does not support negative numbers

**Comment by Miffyli** [comment]
It is still considered as continuous space under the hood (this is a special case). I suggest you define a discrete space of `spaces.Discrete(n=21)` (+1 to include +10) and then inside your environment you offset this with -11 .

**Comment by yunTerry** [comment]
I don't think it's a good idea, I want to use dynamic action space, it's hard to do as you say

and why this can get integer action
```py
space = spaces.Box(
    low=-10, high=10, shape=(1,), dtype=np.int)

action = space.sample()
print(action)
```

**Comment by Miffyli** [comment]
Under the hood `Box` space is assumed to be continuous space (used by e.g. robotics/MuJoCo tasks) where you can choose any floating point number in the given range (a mean and standard deviation parametrize a distribution and then that is sampled/used to do updates). This kind of situations were not counted for. If you really need to support this type of behaviour you need to modify the code (I recommend checking out [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) for that).

**Comment by yunTerry** [comment]
So you mean no matter which type you set the `dtype` parameter in `Box` space, this stable-baselines library will always ignore it and still use the default float type?

**Comment by Miffyli** [comment]
Yes, no matter the `dtype` it will always be treated as float.

**Comment by yunTerry** [comment]
OK, I'll try to use `Discrete` space, thanks a lot
