### ISSUE TITLE
SAC with net_arch = [dict(vf=layers, pi=layers)]

### ISSUE THREAD

**Issue by pstansell** [hill-a/stable-baselines#1029]
[question]  [feature request]

In

`  stable_baselines/common/policies.py`

there is a way to specify different networks for the value function and the policy by using

`  net_arch = [dict(vf=[128, 128], pi=[64, 64])]`

I'd like to to specify different network architectures in SAC, but `net_arch` seems not to be implemented in 

`  stable_baselines/sac/policies.py`

which still uses

`  layers = [64, 64]`

I'm thinking of trying to implement the `net_arch` option myself in `sac/policies.py`, using the code in `common/policies.py` as a guide.

I'd be grateful for any comments or suggestions you may have that could help me.

Thanks

**Comment by araffin** [comment]
Hello,
Please use Stable-Baselines3 for that (cf doc on custom policies): https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#off-policy-algorithms
https://github.com/DLR-RM/stable-baselines3

**Comment by pstansell** [comment]
Thanks!  That's exactly what I wanted.
