### ISSUE TITLE
[question] make_vec_env --> how to include environment kwargs

### ISSUE THREAD

**Issue by langan7** [hill-a/stable-baselines#1032]
**Describe the bug/problem/question**
I am trying to use vectorised environment to get my code to run faster. I am trying to use "make_vec_env()", but I am struggling to include the kwargs that I need for the original environment. How can I add them?

**Code example**
It's quite a big project, so I can't really write all the code here... I am trying to run the following. I have "env_kwargs" in this piece of code which I think is the correct form, but I have also tried "kwargs", "wrapper_kwargs" and "vec_kwargs" just in case. I always get the same error.

```code
import gym
import numpy as np
from stable_baselines import PPO2
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.evaluation import evaluate_policy
from stable_baselines.common.cmd_util import make_vec_env
import matplotlib.pyplot as plt
from scripts.global_vars import Globals
from scripts.sim_data import get_experiment, sim_length, model_list
Globals.model_type = model_list[0]
from gym_onedof_fdmodel.envs.onedof_fdmodel_env import Onedof_fdmodelEnv

n = 60
num_episodes, observation_flag, reward_flag, scenario_par, control_par = get_experiment(n)

env_kwargs={'scenario':scenario_par, 'control':control_par, 'obs_flag':observation_flag, 'reward_flag':reward_flag}
env = make_vec_env('onedof_fdmodel-v0', n_envs=4, **env_kwargs)
model = PPO2(MlpPolicy, env, verbose=0)
model.learn(total_timesteps=int(sim_length)*num_episodes)
```

**additional info on code** - my environment has been registered as follows:
``` 
from gym.envs.registration import register
register(
    id='onedof_fdmodel-v0',
    entry_point='gym_onedof_fdmodel.envs:Onedof_fdmodelEnv',
    kwargs={'scenario':None, 'control':None, 'obs_flag':None, 'reward_flag':None, 'random_flag':None}
)
```

**TRACEBACK message:**
```bash
Traceback (most recent call last):
  File "folderpath/file_running.py", line 17, in <module>
    env = make_vec_env('onedof_fdmodel-v0', n_envs=4, **env_kwargs)
TypeError: make_vec_env() got an unexpected keyword argument 'scenario'
```

**System Info**
Describe the characteristic of your environment:
 * Mostly installing with conda, except for the bits that only allow pip
 * Python version: 3.7
 * Tensorflow version: 1.14
 * StableBaselines version: 2

**Additional context**
I think this is all that's needed to understand the problem, but let me know if not.

**Comment by araffin** [comment]
Hello,

Please use Stable-Baselines3, see https://github.com/DLR-RM/stable-baselines3/issues/188
or use the model class instead of the env id to instantiate the env.

Also, you should pass a dictionary (cf doc), so `env_kwargs=env_kwargs` (and not `**env_kwargs`)

**Comment by langan7** [comment]
> Hello,
> 
> Please use Stable-Baselines3, see [DLR-RM/stable-baselines3#188](https://github.com/DLR-RM/stable-baselines3/issues/188)
> or use the model class instead of the env id to instantiate the env.
> 
> Also, you should pass a dictionary (cf doc), so `env_kwargs=env_kwargs` (and not `**env_kwargs`)

Does make_vec_env() not work on version 2? I also tried adding kwargs like that, so doing: env_kwargs=env_kwargs. However, this didn't work. Traceback is:
```
Traceback (most recent call last):
  File "c:/Users/ag16887/OneDrive - University of Bristol/PhD/ReinforcementLearning/gym-onedof_fdmodel/bc_multi_test.py", line 21, in <module>
    env = make_vec_env('onedof_fdmodel-v0', n_envs=4, env_kwargs=env_kwargs)
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\stable_baselines\common\cmd_util.py", line 72, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 23, in __init__
    self.envs = [fn() for fn in env_fns]
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 23, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\stable_baselines\common\cmd_util.py", line 46, in _init
    env = gym.make(env_id)
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "C:\Users\ag16887\Miniconda3\envs\gym_oneDOFenv\lib\site-packages\gym\envs\registration.py", line 60, in make
    env = cls(**_kwargs)
  File "c:\users\ag16887\onedrive - university of bristol\phd\reinforcementlearning\gym-onedof_fdmodel\gym-onedof_fdmodel\gym_onedof_fdmodel\envs\onedof_fdmodel_env.py", line 40, in __init__
    self.controller = check_controller(control)()
  File "c:\users\ag16887\onedrive - university of bristol\phd\reinforcementlearning\gym-onedof_fdmodel\gym-onedof_fdmodel\gym_onedof_fdmodel\envs\onedof_fdmodel_env.py", line 18, in check_controller
    if hasattr(controllers,controller_name):
TypeError: hasattr(): attribute name must be string
```

And debugging I found that all the inputs to my environment were set to "None".

**Comment by langan7** [comment]
I finally got a solution from a colleague who also struggled with this. Solution to this problem is using a lambda function:

```
kwargs={'scenario':scenario_par, 'control':control_par, 'obs_flag':observation_flag, 'reward_flag':reward_flag}
env = make_vec_env(lambda : gym.make('onedof_fdmodel-v0', **kwargs), n_envs=4)
```

I will leave this open for a little longer till confirmation in case this is actually not a good solution.

**Comment by araffin** [comment]
>Does make_vec_env() not work on version 2? I also tried adding kwargs like that, so doing: env_kwargs=env_kwargs. However, this didn't work. Traceback is:if you

as mentioned in my previous comment, the env kwargs argument works with SB2 but only if you pass a env class (please read the linked issue), that what the lambda method allows.
In SB3, we made it work with env id too directly (again see linked issue).

We would appreciate a PR that port this feature (see https://github.com/DLR-RM/stable-baselines3/pull/189) to SB3, otherwise you may close the issue.
