### ISSUE TITLE
[question] Custom callback for logging action, observation, reward, info and done at each timestep

### ISSUE THREAD

**Issue by PierreExeter** [hill-a/stable-baselines#1037]
Hello,

I'd like to log the value of the following variables at each timesteps during training: action, observation, reward, info and done (for debugging an environment). I understand these values can be accessed with a custom callback. I had a look at the examples provided in the documentation but I couldn't adapt them to my problem. Here is a minimal example:

```python
from stable_baselines.common.callbacks import BaseCallback
from stable_baselines import PPO2

class LoggingCallback(BaseCallback):

    def __init__(self, verbose=0):
        super(LoggingCallback, self).__init__(verbose)

    def _on_step(self) -> bool:
        """
        How to print action, observation, reward, done and info from env.step() ?
        """
        return True

model = PPO2('MlpPolicy', 'Pendulum-v0', verbose=1)
model.learn(5000, callback=LoggingCallback())
```

I know that you don't do consulting but if you could point me in the right direction, that would be very appreciated. Is this the right approach? Are you aware of someone else who attempted something similar? Thanks.

**Comment by araffin** [comment]
Hello,
the information you are looking for is normally available in `self.locals` of the callback.
Anyway, I would recommend you to use [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) which has a cleaner code (and easier to tweak ;) ).

**Comment by PierreExeter** [comment]
Thanks I'll have a look at your suggestions.
