### ISSUE TITLE
What is a DQN policy?

### ISSUE THREAD

**Issue by nbro** [hill-a/stable-baselines#1038]
In the module `stable_baselines.deepq.policies`, you have a lot of policies for DQN. This is **all very nice**, but Q-learning (and DQN) is an off-policy and value-based method, which means that we should be learning a state-action value function with a behaviour policy (like epsilon-ungreedy) that is derived from that value function (which, of course, does not need parameters, apart from the greek letter), not a policy, so what the heck do these policies represent? Are they actually the state-action value function Q(s, a) (in the case of the DQN, a neural network), or what? That's the only thing in DQN that has parameters anyway, so I guess that all those "policies" there are actually neural networks that represent state-action value functions Q(s, a). Right? The documentation is as useless as it could ever be:

> Policy object that implements a DQN policy

Yes, I did **not** look at the code yet.

**Comment by araffin** [comment]
Hello,
We clarify that point in the developer guide of [Stable-Baselines3](https://stable-baselines3.readthedocs.io/en/master/guide/developer.html#policy-structure):

"When we refer to “policy” in Stable-Baselines, this is usually an abuse of language compared to RL terminology. In SB3, “policy” refers to the class that handles all the networks useful for training, so not only the network used to predict actions (the “learned controller”). For instance, the TD3 policy contains the actor, the critic and the target networks."

**Comment by nbro** [comment]
@araffin Thanks for the answer! 

I am not sure this is a good design choice. There is too much abstraction (huh??), in the sense that all RL concepts are lost, for someone that wants to tweak the code, but I guess baselines and stable baselines were not meant for this use case (i.e. to allow the customization of the existing code, models, algorithms, etc).

**Comment by araffin** [comment]
>I am not sure this is a good design choice. There is too much abstraction (huh??), in the sense that (almost) all "usual" RL concepts are lost, for someone that wants to tweak the code, but I guess baselines and stable baselines were not meant for this use case (i.e. to allow the customization of the existing code, models, algorithms, etc).

This is mostly to allow the nice one line syntax that is common to all algorithms. That way, you can use RL algorithms without a complete and detailed knowledge of each algorithm (for instance knowing that `SAC` has an actor and critic network and that the actor must have a squashing function).
But once you know what we mean by `policy` in the context of SB, the abuse of language should not be too hard to overcome ;)

If you want to tweak the code, please take a look at [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3), the internals are much cleaner than SB2 ;)

**Comment by nbro** [comment]
@araffin Ok, just to confirm that I understood. Policies are classes that contain either critics (value functions, in RL terminology) and actors (policies in RL terminology), or any other model that contains trainable parameters. If that's the case, then, e.g., in the case of DQN, you can do as follows (in SB2)

```
model = DQN(MlpPolicy)
model.learn(total_timesteps=10000)
```

and `MlpPolicy` contains the value function. What about DQN? Is this the algorithm you're talking about, in the SB3 documentation, that updates the actual value function?

**Comment by araffin** [comment]
>s this the algorithm you're talking about, in the SB3 documentation, that updates the actual value function?

yes

> So, is this class DQN the one actually responsible for collecting samples and training the MlpPolicy?

yes

> I think of the class DQN as the RL algorithm and as MlpPolicy as the "model" (either a policy or value function(s))?

yes, that's why we have a `BaseAlgorithm` and a `BaseModel` (and `BasePolicy` derives from `BaseModel`) ;) (as mentioned [here](https://stable-baselines3.readthedocs.io/en/master/guide/developer.html#where-to-start))

**Comment by sheila-janota** [comment]
Hi @araffin,
Thanks for the explanation. 
I would like to customize the Policy for the DQN algorithm, is it possible to do that? 
In fact i did try, but i got an error.

`from stable_baselines3 import DQN
from stable_baselines3.common.cmd_util import make_vec_env
import gym
import torch as th

env = CustomEnv()
env = make_vec_env(lambda: env, n_envs=1)

policy_kwargs = dict(activation_fn=th.nn.ReLU,
                     net_arch=[dict(pi=[4,], vf=[4,])])
model = DQN('MlpPolicy', env, policy_kwargs=policy_kwargs, verbose=1)`

I just want to test a neural network with 4 nodes as inputs (actions) and 4 nodes as outputs (actions).

This is the error that I'm having:
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by Miffyli** [comment]
@sheila-janota 

You have an extra "[...]" around your `net_arch` parameter value. Removing those should fix it.

Note that this does not set the number of inputs or outputs; only the sizes of the "hidden layers". The input and output sizes are automatically set to match whatever the environment requires/provides :)

**Comment by sheila-janota** [comment]
Hi @Miffyli,

Thanks for the insight.
So this means that when I set the environment with the observation space and action space they turn out to be the number of nodes for input and output?
In my case I'm not going to work with hidden layers.

I did visit the stable-baseline3 github, there is a lot of information, and I just want to implement something basic to really understand how it works.

**Comment by Miffyli** [comment]
Yes, that is right. Note that by default the network will use two (hidden) layers of 64 nodes, so you might want to change this if you believe it is not enough for your application.

**Comment by sheila-janota** [comment]
Can i set the hidden layers as None or zero?

**Comment by Miffyli** [comment]
You would have to try that, I can not say for sure it would work with `net_arch={"pi": [], "vf": []}`.

**Comment by sheila-janota** [comment]
Thanks, very much!

**Comment by araffin** [comment]
Note: dqn only has a q network, so it would be: `net_arch=[]`

**Comment by sheila-janota** [comment]
Hi @araffin,
Thanks. 
You mean that, when i use `net_arch=[]` the neural network architecture will be created without hidden layers, correct?

**Comment by Miffyli** [comment]
@sheila-janota Yup!
