### ISSUE TITLE
After loading PPO model actions outputs are not anymore in defined range

### ISSUE THREAD

**Issue by RGring** [hill-a/stable-baselines#104]
**Describe the bug**
I trained an PPO agent with the continuous actions space. When I reload that agent, the predictions are not anymore in the defined ranges of the action space. I created an example with the gym-env "'MountainCarContinuous-v0". Its actions are in the range of [-1, 1], reloading that agent and printing the actions show actions out of that range. Please run the provided example.

**Code example**

    env = gym.make('MountainCarContinuous-v0')
    env = DummyVecEnv([lambda: env])

    model = PPO1(MlpPolicy, env, verbose=1)
    model.learn(total_timesteps=25000)
    model.save("ppo1_mountain")

    del model # remove to demonstrate saving and loading

    model = PPO1.load("ppo1_mountain")

    obs = env.reset()
    while True:
        action, _states = model.predict(obs)
        print(action)
        obs, rewards, dones, info = env.step(action)
        env.render()

**Comment by araffin** [comment]
Hello
cf doc: https://stable-baselines.readthedocs.io/en/master/modules/policies.html

> For all algorithms (except DDPG), continuous actions are only clipped during training (to avoid out of bound error). However, you have to manually clip the action when using the predict() method.
