### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by nbro** [hill-a/stable-baselines#1041]
I installed SB with

```
pip install stable-baselines
```

However, it does not install TF, and I get the error in the title when I call `from stable_baselines.common.evaluation import evaluate_policy`. However, according to [this code](https://github.com/hill-a/stable-baselines/blob/master/setup.py#L18), it should install TF automatically.

I am on Mac OS X Catalina (version 10.15.7). The SB version that was installed is: `stable-baselines 2.10.1`. Of course, I can install TF manually, but this looks like a bug. Maybe that code in `setup.py` does not work for the mac.

**Comment by araffin** [comment]
So, the thing is pip runs  `setup.py` only when installing from source:
```
pip install git+https://github.com/hill-a/stable-baselines
```
As a result, there is no good way to avoid that issue (we cannot pin a version in `setup.py` as we don't want to overwrite users tensorflow version, especially if they don't have a GPU).

**Comment by nbro** [comment]
@araffin Can't you just install TF if it's not already installed? I guess you can do that.

**Comment by araffin** [comment]
>Can't you install TF only if it's not already installed? I guess you can do that.

This is what is already done when pip checks the env properly, that's what I meant by "So, the thing is pip runs setup.py only when installing from source".

> I guess you can do that.

If not installed from source, I tried several ways without success, but I would be obviously happy if you have a solution ;)
