### ISSUE TITLE
Improved sac version

### ISSUE THREAD

**Issue by xiao-hua-sheng** [hill-a/stable-baselines#1042]
Is sac version 1.0 only?Has version 2.0 of the V function been canceled.

**Comment by araffin** [comment]
>Is sac version 1.0 only?Has version 2.0 of the V function been canceled.

What do you mean?
Yes, we are using the variation with the V value.
If you want the one with two Q-values targets, you can take a look at [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3).
In practice, both implementations have similar performances: https://github.com/DLR-RM/stable-baselines3/issues/48

**Comment by xiao-hua-sheng** [comment]
okay, thank you
