### ISSUE TITLE
[feature request] add reccurent(sequentital) feature extractor

### ISSUE THREAD

**Issue by zhaopansong** [hill-a/stable-baselines#1043]
I notice current policy implementation does not include any sequentital related feature extractor.
For financial problem like investment or high-freq trading, datapoint  is often a set of nearest obervations in a time window. And informations between datapoint are not related, so current lstm-policy that pass information in hidden layer to next datapoint does not fit in this kind of problem.

**Comment by Miffyli** [comment]
We are not planning on updating stable-baselines with bigger new features in favour of improving [stable-baselines3](https://github.com/DLR-RM/stable-baselines3). I am also not sure I understood the description correctly. It sounds like these observations could be combined into one bigger observation inside the environment or with a wrapper.

**Comment by araffin** [comment]
closing this in favor of https://github.com/hill-a/stable-baselines/issues/1071
