### ISSUE TITLE
[Question] where is self.episode_reward updated in PPO2

### ISSUE THREAD

**Issue by zhaopansong** [hill-a/stable-baselines#1050]
I searched all files defined in the head of PPO2.py. Only find out self.episode_reward is defined in ActorCritic Model with shape[n_env,]. Dont know how it is calculated

**Comment by araffin** [comment]
Hello,
according to https://github.com/hill-a/stable-baselines/pull/635, it is only updated in the `total_episode_reward_logger`,
but again, this function is buggy, please consider using [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) or a `Monitor` wrapper (then `ep_rew_mean` will be computed) for proper computation of the episode reward.

**Comment by zhaopansong** [comment]
> Hello,
> according to #635, it is only updated in the `total_episode_reward_logger`,
> but again, this function is buggy, please consider using [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) or a `Monitor` wrapper (then `ep_rew_mean` will be computed) for proper computation of the episode reward.

OK I got it, list object passed is itself, not copy.
