### ISSUE TITLE
What exactly does the output printed to the standard output mean when verbose=1 in DQN?

### ISSUE THREAD

**Issue by nbro** [hill-a/stable-baselines#1053]
When `verbose== 1` in [`DQN`](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html), what exactly does the produced output represent? I haven't yet looked at the source code, and, of course, the answer lies there. The documentation for `verbose` only says

> verbose – (int) the verbosity level: 0 none, 1 training information, 2 tensorflow debug

Anyway, sometimes it produces some output like this

```
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 100      |
| mean 100 episode reward | -59.7    |
| steps                   | 1841     |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 200      |
| mean 100 episode reward | -15.3    |
| steps                   | 2452     |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 300      |
| mean 100 episode reward | -15.2    |
| steps                   | 3058     |
--------------------------------------
...
```
and sometimes it doesn't produce anything. I think this also depends on the number of training time steps. So, what exatly do these values mean? What does `episodes` represent? Is it the number of episodes passed until that point? If yes, does `mean 100 episode reward` mean the average of the returns obtained in all the last 100 episodes? What does `% time spent exploring` exactly mean? It's always 2 (apparently).

I was trying to compare this output with the output that is produced by the SB's monitor, but they are different, as SB's monitor writes the sum of rewards obtained in an episode, for all episodes.

**Comment by araffin** [comment]
>What does episodes represent?
> Is it the number of episodes passed until that point?

Yes, total number of episode down so far.

> If yes, does mean 100 episode reward mean the average of the returns obtained in all the last 100 episodes?

yes

>What does % time spent exploring exactly mean? It's always 2 (apparently).

this is the `epsilon` of the epsilon-greedy exploration used by DQN (percentage of random action taken). Please read more about RL and DQN if this is unclear to you.

>as SB's monitor writes the sum of rewards obtained in an episode, for all episodes.

You can easily recompute `mean 100 episode reward` using the Monitor file.
In fact, for other algorithms, `ep_rew_mean` is computed using the Monitor and is the mean over the last 100 episodes.

If you want more consistent logging, please take a look at [Stable-Baselines3](https://github.com/DLR-RM/stable-baselines3) ;)
(and please read the DQN section in the migration guide too).

**Comment by araffin** [comment]
closing in favor of https://github.com/DLR-RM/stable-baselines3/pull/803
