### ISSUE TITLE
Resnet Observation Policy Cannot Reload?#question#bug

### ISSUE THREAD

**Issue by yiwc** [hill-a/stable-baselines#1056]
Hi Stable Baselines Team,

Great work in developing this package, thanks a lot! However, I have met a problem.

I have a customized policy with the resnet v2 as the observation module. It shows a good convergence in the training. However, when I saved this module after training (for example, return=40, task success), and reload it in the evaluation, it shows bad performance (return = 10, no okey). 

I suspect this module is not well saved? or if you have a recommend way to integrate with resnet observation network?

Later, I will give you a minimum code to reproduce this issue.

If you have any idea what's could lead to this problem, pls share your opinion. Thanks!

**Comment by Miffyli** [comment]
Things that pop into mind without further details:
- Make sure evaluation environment matches training environment (e.g. observations are not generally different)
- If your resnet includes batch normalization layers or similar statistics-counting layers, make sure they do not update during evaluation. 
- It could be possible that all parameters are not stored correctly if you have highly custom layers. Run `model.get_parameters()` and see what keys the given dictionary has. All saved parameters are included in this dictionary, so if it does mention some layer parameters, then they are not saved.
