### ISSUE TITLE
Duplicate exp in action probability calculation

### ISSUE THREAD

**Issue by sunshineclt** [hill-a/stable-baselines#1058]
**Describe the bug**
For DiagGaussianProbabilityDistribution, the action probability calculation exponentiated the logstd twice in calculating action probability. 
Specifically, in [https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L240](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L240) self.proba_distribution.std is used as second part of _policy_proba. 
In [https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L842](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L842) the mean and std are calculated. 
However, in [https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L877](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L877) the std is treated as logstd and exponentiated again. 

**Suggest solution**
Change [https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L240](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L240) to be `self._policy_proba = [self.proba_distribution.mean, self.proba_distribution.logstd]` but need to confirm whether it will create other inconsistence.

**Comment by araffin** [comment]
Hello,

nice catch, looks like a bug (I think @hill-a wrote that code, no?).
The good news is that this code is not used inside SB2 and only provided to the user if needed.

>Suggest solution

I would rather change https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L877 

We would appreciate a PR that solves this issue ;)
(and please write a test to prevent regression if possible)

**Comment by sunshineclt** [comment]
Thanks @araffin for the fast response! I will work on it around this week :smiley:
