### ISSUE TITLE
Error in calculating log probability in base_class.py

### ISSUE THREAD

**Issue by sunshineclt** [hill-a/stable-baselines#1059]
**Describe the bug**
https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py#L880-L884 calculates the log probability of Diagonal Gaussian distribution but it is incorrect. The logstd is mistook as logvariance and std is mistook as variance. 
The original code: 
```
n_elts = np.prod(mean.shape[1:])  # first dimension is batch size
log_normalizer = n_elts / 2 * np.log(2 * np.pi) + 0.5 * np.sum(logstd, axis=1)

# Diagonal Gaussian action probability, for every action
logprob = -np.sum(np.square(actions - mean) / (2 * std), axis=1) - log_normalizer
```

**Suggest solution**
Two changes: 
```
n_elts = np.prod(mean.shape[1:])  # first dimension is batch size
log_normalizer = n_elts / 2.0 * np.log(2 * np.pi) + np.sum(logstd, axis=1)

# Diagonal Gaussian action probability, for every action
logprob = -np.sum(np.square(actions - mean) / (2 * np.square(std)), axis=1) - log_normalizer
```
https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/distributions.py#L403-L405 calculation is accurate.

**Comment by SVJayanthi** [comment]
Nice catch!

**Comment by araffin** [comment]
Hello,
nice catch ;)
Looks like something that could be fixed at the same time as https://github.com/hill-a/stable-baselines/issues/1058.
