### ISSUE TITLE
ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by aliamiri1380** [hill-a/stable-baselines#1062]
I created a custom env and vectorized it using SubprocVecEnv
during taking steps on each env if one of those vectorized envs reached the terminal state this error shows up (but if all of them reach the terminal state simultaneously this never happens)

ValueError                                Traceback (most recent call last)
<ipython-input-53-1d207a9f32b4> in <module>()
      4 for i in range(10):
4 for i in range(10):
      5     print(env.step([1,1]))
----> 6 print(env.step([0,1]))

/usr/local/lib/python3.6/dist-packages/stable_baselines/common/vec_env/base_vec_env.py in step(self, actions)
    148         """
    149         self.step_async(actions)
--> 150         return self.step_wait()
    151 
    152     def get_images(self) -> Sequence[np.ndarray]:

/usr/local/lib/python3.6/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py in step_wait(self)
    109         self.waiting = False
    110         obs, rews, dones, infos = zip(*results)
--> 111         return _flatten_obs(obs, self.observation_space), np.stack(rews), np.stack(dones), infos
    112 
    113     def seed(self, seed=None):

<__array_function__ internals> in stack(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    424     shapes = {arr.shape for arr in arrays}
    425     if len(shapes) != 1:
--> 426         raise ValueError('all input arrays must have the same shape')
    427 
    428     result_ndim = arrays[0].ndim + 1

ValueError: all input arrays must have the same shape

**Comment by Miffyli** [comment]
Check docs on [custom environments](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html): you should check your environment with `check_env` utility, which will be more informative about the error situations.

**Comment by aliamiri1380** [comment]
I did, that was ok

**Comment by Miffyli** [comment]
Also try with `check_env(env, warn=True)`. Without further info it is hard to say what could be wrong. If you think it is a bug, try to replicate it with a minimal environment that reproduces the error.

**Comment by aliamiri1380** [comment]
in gym envs that works well
but here is my own env, the data format is just like CartPole-v1 but still the error occurs
https://colab.research.google.com/drive/1Lfz1kPaTFcWHCJTgiXRClrjB1fs6NY8I?usp=sharing

**Comment by araffin** [comment]
Hello,
when running the env checker with the latest stable-baselines version, I obtain:
```
AssertionError: The reward returned by `step()` must be a float
```
this is your error.

Please fill up the issue template COMPLETELY next time ;)

Note: in colab (as shown in the example notebooks), you MUST do `pip install stable-baselines --upgrade`
