### ISSUE TITLE
Issue with MlpLstm policy

### ISSUE THREAD

**Issue by lorenzoschena** [hill-a/stable-baselines#1063]
Hello there,

I've been using different methods (A2C, PPO2, ACKTR, etc) in my custom environment, using an MlpPolicy and everything went fine. Now, I'd like to try other policies, MlpLstm for instance. 

After that I substitute the policy inside` .learn()` the simulation starts correctly (no errors are displayed) but, even waiting a lot of time (up to 8h or more), it does not yield to any results.

- I've checked that `verbose=1` 
- `stable-baselines==2.10.1`
- Some time references: using PPO2 with a MlpPolicy it took about 42min for 10M timesteps of evaluation. 
- I've also used `env.checker()` and everything seems in the right place.
- OS : Fedora32 
- `n_states = 18`, `n_actions=1`
- Definition of the actions and observations space:
`self.action_space = spaces.Box(low=-1, high=1,shape=(1,), dtype=np.float32)`
`self.observation_space= spaces.Box(low=-self.u_lim, high=self.u_lim, shape=(n_states,), dtype=np.float32)`

where `u_lim` is a a numerical constraint.

Can you help me in anyway? Do you need other information?

Thanks

**Comment by Miffyli** [comment]
Hmm hard to say based on this info. Could you provide a minimal (but runnable) example code of this bug happening? This would go a long way in helping to debug this :) . I would like to see an example of the "substitute the policy inside `.learn()`" part as I am not sure what you mean by this.

**Comment by lorenzoschena** [comment]
Thanks for your response :) 
Yeah, sure! Do you need a copy of the whole custom environment I'm running? 

In the meanwhile, here's what I meant before about the `.learn()`.

Using the `MlpPolicy` I used to wrote: 

```
    model = PPO2(MlpPolicy, env, verbose=1, n_cpu_tf_sess=None,n_steps = int(32000/num_cpu),
                 nminibatches = 1, noptepochs = 5, tensorboard_log="tenso")

    eval_callback = EvalCallback(Ambiente, best_model_save_path='./logs/',
                             log_path='./logs/', eval_freq=int(32000/num_cpu),
                             deterministic=True, render=False)

    # Model training
    
    time_steps = 10_000_000 # number of interaction w environment
    model.learn(total_timesteps=time_steps, callback=eval_callback)
```
    
And this works well. 
Now, in order to try different policies, I'm trying to do the same, using `MlpLstm` instead - after having correctly imported it: 
```

    model = PPO2(MlpLstmPolicy, env, verbose=1, n_cpu_tf_sess=None,n_steps = int(32000/num_cpu),
                 nminibatches = 1, noptepochs = 5, tensorboard_log="tenso")

    eval_callback = EvalCallback(Ambiente, best_model_save_path='./logs/',
                             log_path='./logs/', eval_freq=int(32000/num_cpu),
                             deterministic=True, render=False)

    # Model training
    time_steps = 10_000_000 # number of interaction w environment
    model.learn(total_timesteps=time_steps, callback=eval_callback)
```

In both cases I have defined `env` as follows: 

`env = SubprocVecEnv([lambda : Monitor(CustomEnv(),log_dir,allow_early_resets=True) for _ in range(num_cpu)])`


If I run this with `MlpLstm` I have a first feedback after 32k timesteps in a reasonable time and then, nothing else. Even if I let the simulation going on for up to several hours. 

I hope that now the issue is clearer, however let me know if you need more detailed information about my environment or anything else.

Thanks!

**Comment by Miffyli** [comment]
Looking at this everything seems right, so there might be a bug in the environment or in the combination of LSTM + EvalCallback. A full, runnable code with the custom environment would be nice for further debugging.

One thing you could check meanwhile: does your environment have a timeout? Maybe the MlpLstm policy is getting stuck somewhere and the game never ends during evaluation? Just a wild guess and I assume this has already been tried out ^^.

**Comment by lorenzoschena** [comment]
To be honest I did not tried before without the EvalCallback. However, I'm doing it now and it does not seem to affect the problem - the simulation is been running from more or less 1 hour but still, no results. 

For what concerns the timeout, at the moment, the agent exits the game if a specific constraint is not respected or if the number of steps is equal to the time interval I'm interested in evaluating. Was this the kind of timeout you were thinking of? Or was it linked to the time of evaluation instead?

I'm attaching here the environment and its launcher, in order to not paste here such a long code.
[advection_custom_environment.tar.gz](https://github.com/hill-a/stable-baselines/files/5718568/advection_custom_environment.tar.gz)

**Comment by Miffyli** [comment]
Hmm when I ran the `RL_advection.py` code it worked as expected (which you said works). When I changed `MlpPolicy` to `MlpLstmPolicy` in line 62 I got the following error:

```
Traceback (most recent call last):
  File ".\RL_advection.py", line 115, in <module>
    main()
  File ".\RL_advection.py", line 62, in main
    model = PPO2(MlpLstmPolicy, env, verbose=1, n_cpu_tf_sess=None,n_steps = int(32000/num_cpu), nminibatches = 100, noptepochs = 5)
  File "c:\users\anssi\desktop\stable-baselines\stable_baselines\ppo2\ppo2.py", line 97, in __init__
    self.setup_model()
  File "c:\users\anssi\desktop\stable-baselines\stable_baselines\ppo2\ppo2.py", line 125, in setup_model
    assert self.n_envs % self.nminibatches == 0, "For recurrent policies, "\
AssertionError: For recurrent policies, the number of environments run in parallel should be a multiple of nminibatches.
```

I fixed this with `nminibatches=5` and now code works.

I think I spotted the problem: you have very large `n_steps` and `nminibatches`. Computational requirement for LSTM increases a lot with larger `n_steps` (as it backpropagates through time over all `n_steps`), and with current settings it indeed takes very long. Try lower numbers, e.g. `n_steps=512`.

Note: I ran code on CPUs and removed tensorboard logging to make it work.

**Comment by lorenzoschena** [comment]
Yeah, in my tests I usually put `nminibatches=1` to avoid this issue. 
However, I've followed your suggestion removing tensorboard logging and reducing the number of steps and now the policy does work correctly! 

Thank you! 👍
