### ISSUE TITLE
How to blend the policy networks?

### ISSUE THREAD

**Issue by dongfangliu** [hill-a/stable-baselines#1064]
I've trained several SAC  networks with default settings.
Now I wish to blend the networks by defining a set of weights, like a weighted blending.
Just as  [this paper](https://www.youtube.com/redirect?v=n34gGhb7Qjo&event=video_description&q=http%3A%2F%2Farxiv.org%2Fabs%2F2012.05810&redir_token=QUFFLUhqbV9pcFd4b3c1RjJRSVZycjJ5SUVLSEJ1a0dBUXxBQ3Jtc0ttdWNrTnVtNW1mSUgwb3hJYnV2UUFVbmcxdzItOUg0VGRoYWctRkM2VjBmbEkwT3MxRXV4UXpnaGN4MUhVSmlCZVV5XzZXZ0FIZGFmUEQ4dk5vSDFzcXZUQlJvclJFWjc2Tzd1Yllpd1JPalo0c05yWQ%3D%3D) does.

It's a simple idea to learn to blend the policies, but I do not know how to correctly extract the policy networks and blend them as expected.

**Comment by Miffyli** [comment]
If you only wish to "blend" output actions, you can run [`action_probability`](https://stable-baselines.readthedocs.io/en/master/modules/sac.html#stable_baselines.sac.SAC.action_probability) for each separate policy and blend the probabilities manually and pick an action from there. However if you need to blend in network parameters then you need to start modifying network parameters, where you can use `get_parameters` and `load_parameters` functions to get network weights and modify them as you please.
