### ISSUE TITLE
How to set 'episode_lenght' when using 'generate_expert_traj'?

### ISSUE THREAD

**Issue by luigicampanaro** [hill-a/stable-baselines#1065]
Hi guys,

I'm using ```generate_expert_traj``` from ```stable_baselines.gail```, one of its inputs (```n_episodes```) allows to set the number of episodes, but I was wondering how to set the ```episode_lenght```?
Thank you very much for helping.

**Comment by araffin** [comment]
Hello,
how would you know in advance the length of a trajectory?

**Comment by luigicampanaro** [comment]
I see your point! So, I guess it stops when the `done` is triggered, I was trying to understand this bit. If you confirm, the issue can be closed :)

**Comment by araffin** [comment]
>So, I guess it stops when the done is triggered,

yes, that's the end of episode signal ;)

in some cases, when you don't have early termination and when you have a time limit (timeout), you can know in advance the length of an episode, but those cases are quite limited.

**Comment by luigicampanaro** [comment]
Great! Thank you very much! :)
