### ISSUE TITLE
docker build fails with FileNotFoundError: 'stable_baselines/version.txt'

### ISSUE THREAD

**Issue by anj1** [hill-a/stable-baselines#1066]
Following https://stable-baselines.readthedocs.io/en/master/guide/install.html, I tried:

```sh
docker pull stablebaselines/stable-baselines
make docker-gpu
```
But this fails with:
```
FileNotFoundError: [Errno 2] No such file or directory: 'stable_baselines/version.txt'
```

Manually entering the docker image and creating the `/root/code/stable-baselines/stable_baselines/version.txt` file solved the problem.

**Comment by araffin** [comment]
Hello,
thanks for pointing out this issue, the current docker file is apparently missing that line (present in Stable-Baselines3): https://github.com/DLR-RM/stable-baselines3/blob/master/Dockerfile#L31

We would appreciate a PR that solves this issue ;)

**Comment by anj1** [comment]
Cool https://github.com/hill-a/stable-baselines/pull/1067

**Comment by araffin** [comment]
Fixed in https://github.com/Stable-Baselines-Team/stable-baselines/pull/2
