### ISSUE TITLE
Pretrain dimension issue

### ISSUE THREAD

**Issue by jmm1-cmd** [hill-a/stable-baselines#1070]
I record data using the generate_expert_traj function taking the following shape:

actions (2633, 1)
obs (2633, 1, 24, 1)
rewards (2633,)
episode_returns (20,)
episode_starts (2633,)
Total trajectories: 1
Total transitions: 274
Average returns: 119.27605878425773
Std for returns: 7.912250069270531

My observation space is defined as follows:

self.observation_space = spaces.Box(low=-100, high=100,
                                        shape=(1,24,1), dtype=np.float32)

When I feed this dataset to pretrain using a DQN model using below command:

   dataset = ExpertDataset(expert_path = 'greedy.npz', traj_limitation=1,
                            batch_size=128)
    
    env = LoadEnv() # Load the environment for the agent
    
    policy_kwargs = dict(act_fun = tf.nn.relu, layers = [32, 32])

    model = DQN('MlpPolicy', env,policy_kwargs = policy_kwargs, gamma = 0.01, verbose=1, batch_size=128, learning_rate=1e-3, 
                             prioritized_replay=True, seed = 2)
    model.pretrain(dataset, n_epochs = 1000)
    model.learn(int(5e5))
    model.save("DQN_agent_5")

I get an error about the shape of the pretraining data:

**Note** : my observation only contains numerical values, not an image.

Pretraining with Behavior Cloning...
Pretraining with Behavior Cloning...
Traceback (most recent call last):

  File "[sic]", line 407, in <module>
    main()

  File "[sic]", line 359, in main
    model = train_agent() # Train the agent

  File "[sic]", line 312, in train_agent
    model.pretrain(dataset, n_epochs = 1000)

  File "C:\Users\joemm\anaconda3\lib\site-packages\stable_baselines\common\base_class.py", line 351, in pretrain
    train_loss_, _ = self.sess.run([loss, optim_op], feed_dict)

  File "C:\Users\joemm\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)

  File "C:\Users\joemm\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1149, in _run
    str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (128, 24) for Tensor 'deepq/input/Ob:0', which has shape '(?, 1, 24, 1)'

System Info
Describe the characteristic of your environment:

Python version: 3.7.6
Tensorflow version: 1.14.0
Versions of any other relevant libraries: stable-baselines 2.8.0; numpy 1.17.3

**Comment by jmm1-cmd** [comment]
I mainly want to know what shape the observation from the pre-training needs to be in order to work. My observation space has shape (1,24,1) and as far as I can tell that is what is being stored in the pre-training.

**Comment by Miffyli** [comment]
Without code I not say for certain, but I think issue lies in the odd shape of your observations. Try removing the "1" dimensions from your observation shape and only leave in `self.observation_space = spaces.Box(low=-100, high=100, shape=(24,), dtype=np.float32)`. 

Sidenote: Try to normalize your data to be in `[-1, 1]` for neural network's comfort.

**Comment by jmm1-cmd** [comment]
@Miffyli , based on your recommendation I modified the shape of the observation space. The pretraining worked! 

I plan to work on normalizing the data soon, this was an oversight on my part.

Thank you!
