### ISSUE TITLE
[question] Custom environment conflict with PyCuda

### ISSUE THREAD

**Issue by ivandrodri** [hill-a/stable-baselines#1073]
Hello, I have created a custom environment that uses pycuda for some calculations and I have the following error:

ERROR:
'''
Using cuda device
Traceback (most recent call last):
  File "simulation.py", line 65, in <module>
    model = PPO('MlpPolicy', env2, verbose=1, device="cuda").learn(1)
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/ppo/ppo.py", line 264, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 215, in learn
    total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 356, in _setup_learn
    self._last_obs = self.env.reset()
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 61, in reset
    obs = self.envs[env_idx].reset()
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/monitor.py", line 86, in reset
    return self.env.reset(**kwargs)
  File "/home/ivan/Documents/GIT_PROJECTS/RL_obstacle_avoidance/Environment/EnvironmentPyCuda.py", line 48, in reset
    func(a_gpu, block=(4,4,1))
  File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/pycuda/driver.py", line 436, in function_call
    func._set_block_shape(*block)
pycuda._driver.LogicError: cuFuncSetBlockShape failed: invalid resource handle
''' 

Please find below a simple Environment test case that reproduces the mentioned error. The check_env(env, warn=True) function works perfectly fine with the Environment below but the problem appears when I try to train a PPO algorithm and it seems it is coming from the kernel launched in the reset function (the reset function kernel works perfectly fine). If I comment the pycuda part everything works.  

CUSTOM ENVIRONMENT TEST:

'''
import numpy as np
import pycuda
import pycuda.autoinit
import pycuda.driver as drv
from pycuda.compiler import SourceModule

import gym
from gym import spaces

##Simple Cuda Kernel
mod = SourceModule("""
  __global__ void doublify(float *a)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] *= 2;
  }
  """)

class EnvironmentPyCuda(gym.Env):
    
    metadata = {'render.modes': ['human']}

    def __init__ (self):
        super(EnvironmentPyCuda, self).__init__()

        nActions = 3 
        self.action_space = spaces.Discrete(nActions)
        self.observation_space = spaces.Box(low=-10.0, high=10.0, shape=(8,), dtype=np.float32)

    def reset(self):
    
        ####### If I comment the pycuda part below everything works perfectly. ######
        a = np.random.randn(4,4)
        a = a.astype(np.float32)
        a_gpu = drv.mem_alloc(a.nbytes)
        drv.memcpy_htod(a_gpu, a)

        func = mod.get_function("doublify")
        func(a_gpu, block=(4,4,1))

        a_doubled = np.empty_like(a)
        drv.memcpy_dtoh(a_doubled, a_gpu)
        print (a_doubled)
        print (a)
        ########################
        
        obsState = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, 1.1, 1.2, 1.3 ]).astype(np.float32)
        return obsState

    def step(self, action):
        obsState = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, 1.1, 1.2, 1.3 ]).astype(np.float32)
        return obsState, 0, False, {}

    def render(self, mode='human'):
        print("RENDER")

    def close(self):
        pass
'''

I am training the algorithm in this way:

env = EnvironmentPyCuda()
check_env(env, warn=True)
env = make_vec_env(lambda: env, n_envs=1)

model = PPO('MlpPolicy', env, verbose=1, device="cuda").learn(1)

Thank you very much for any help!

**Comment by ivandrodri** [comment]
I forgot to mention that when I use the PPO with device="CPU" everything works, i.e.:

model = PPO('MlpPolicy', env, verbose=1, device="cpu").learn(1)

**Comment by Miffyli** [comment]
Seems like this is an issue outside stable-baselines, i.e. something related to how Tensorflow uses CUDA under the hood (which then prevents your code from working). We do not offer tech support in such cases and I suggest you look elsewhere, e.g. related issues on using Tensorflow + custom CUDA kernels.

**Comment by ivandrodri** [comment]
@Miffyli : Thank you very much for your quick response. Just a last question: Why could this be a tensorflow issue? I thought stable-baselines was written in pyTorch

**Comment by Miffyli** [comment]
@ivandrodri [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) is written in PyTorch, while this stable-baselines is written in Tensorflow (as was the original OpenAI Baselines).

**Comment by araffin** [comment]
See closing reason in https://github.com/DLR-RM/stable-baselines3/issues/300
