### ISSUE TITLE
Is it possible to add an auxiliary output to an algorithm?

### ISSUE THREAD

**Issue by mitchellostrow** [hill-a/stable-baselines#1078]
Hi! I am trying to add an auxiliary output predicting a feature of the state vector onto an A2C agent with an LSTM actor critic policy. However, my efforts so far have come up short. How can I do this? Thanks in advance.

**Comment by Miffyli** [comment]
Hey. These issues on Github are mainly for bugs and enhancement purposes, not for technical support. The only way to go about it is to see where [loss is created](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/a2c/a2c.py#L274) and trying to fit in your modifications there.

Also, if LSTM is not necessary, I suggest taking a look at [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) which is done in PyTorch. It should be much easier to modify.
