### ISSUE TITLE
mb_rewards is updated after the on_step callback

### ISSUE THREAD

**Issue by SolaWeng** [hill-a/stable-baselines#1082]
I am developing my custom callbacks to manipulate the minibatches during PPO2 training. However, unlike other minibatch data (`mb_obs`, `mb_actions`, etc) which gets updated before the `on_step` callback, the `mb_rewards` gets updated after the `on_step` callback which makes it one step behind compared to other minibatch data when accessing them using callbacks. Is it by design with specific purposes?

https://github.com/hill-a/stable-baselines/blob/259f27868f0d727d990f50e04da6e3a5d5367582/stable_baselines/ppo2/ppo2.py#L498

**Comment by araffin** [comment]
Hello,
I'm not sure what you want to do with the mini-batches.
It sounds more like you need to derive a custom PPO class from the PPO2 class and for that I would recommend you to take a look at [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) which has a much cleaner codebase ;)

**Comment by SolaWeng** [comment]
Thanks @araffin I will take a look!
