### ISSUE TITLE
How do ppo2 reset environment

### ISSUE THREAD

**Issue by dongfangliu** [hill-a/stable-baselines#1083]
I check through the ppo2 script for a whole day, add i did not see any code that resets the environment when the `step()` function return `dones=True`

That's really strange

**Comment by Miffyli** [comment]
This is done by [vectorized environments](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html). Any default environments will be wrapped into a vectorized environment of one, which then automatically resets episodes when they hit `done=True`.
