### ISSUE TITLE
Installing on macOS Big Sur 11.1 with Python 3.9

### ISSUE THREAD

**Issue by jemgodden** [hill-a/stable-baselines#1085]
Hi there,

I have been having some issues installing stable-baselines.
I am on a MacBook Air running macOS Big Sur 11.1.

When using
```
pip install stable-baselines
```

I am getting a verbose error. I think the key part is the following:

> The headers or library files could not be found for zlib,
>     a required dependency when compiling Pillow from source.

I believe the issue is that, currently, stable-baselines requires Pillow 7.2, which is only compatible with Python v3.5-3.8.
Unfortunately, Python 3.9 is the only version compatible with macOS Big Sur 11.1.

Are there any plans to update the version of Pillow being used?
Alternatively, am I missing anything in the installation process?

Thanks very much for any help!

**Comment by Miffyli** [comment]
Stable-baselines does not directly require Pillow, but some of the dependencies (or below them) seems to require it. As such this is bit outside stable-baselines.

A workaround you could try is pinpointing the library that calls for specific version of Pillow and installing that with `pip install --no-deps [library name]`, and then installing dependencies manually. Conda environments could also be of help here as they might provide more prebuilt packages and are more helpful resolving these kind of issues.
