### ISSUE TITLE
How can i save best model ?

### ISSUE THREAD

**Issue by mmterkc** [hill-a/stable-baselines#1087]
Hi, how can i save best model ? I want to save best reward not mean reward.

**Comment by Miffyli** [comment]
See [EvalCallback](https://stable-baselines.readthedocs.io/en/master/guide/callbacks.html#evalcallback), which allows storing best model seen with evaluation episodes. Alternatively you can use callbacks to check a Monitor file to see if the latest episode had highest reward and store that reward.

**Comment by mmterkc** [comment]
Thanx for your answer but how can i find highest reward in monitor ?

**Comment by Miffyli** [comment]
See [this example](https://stable-baselines.readthedocs.io/en/master/guide/examples.html) for exactly what you want. You may close this issue if that answers your question.

**Comment by mmterkc** [comment]
ok ts2xy give me total rewards but i want to learn last step reward

**Comment by Miffyli** [comment]
You could use a custom callback to achieve this.

Closing as "no tech support", as the answers you seek are either in docs or you have to modify stable-baselines to do this. These issues are for proposals and bug-reports.

**Comment by kk46328748237-hub** [comment]
I am wondering that is saving the model also saves the optimizer state for value and policy networks in stable baselines 3?
