### ISSUE TITLE
I get different rewards on same env and same steps and same model. Is it normal?

### ISSUE THREAD

**Issue by mmterkc** [hill-a/stable-baselines#1088]
I trained rl model but i get different reward values same env and same steps and same model. Is it normal ?

**Comment by mmterkc** [comment]
my model is ACKTR

**Comment by Miffyli** [comment]
See the docs on general tips on RL: Results vary wildly between runs. You have to set seeds correctly (see [this section](https://stable-baselines.readthedocs.io/en/master/guide/algos.html?highlight=reproducibility#reproducibility)).
