### ISSUE TITLE
A2C Performance with continuous actions

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#109]
A2C works well with discrete actions, however, it does not seem to train with continuous actions.

To reproduce: https://github.com/araffin/rl-baselines-zoo with LunarLanderContinuous-v2 for instance
Related: https://github.com/Sohojoe/MarathonEnvsBaselines/issues/6

**Comment by doviettung96** [comment]
Hi @araffin ,
Thanks for the suggestion. I have totally moved to PPO2 and work with the HumanoidFlagrunHarder again. However, the mean reward is around 1200 (maximum is 1800) which is quite low compared to the PPO paper.  I have tried every set up except the logstd = LinearAnneal(-0.7, -1.6) as in the paper. 
Do you have any suggestion?

**Comment by doviettung96** [comment]
Sorry for not make it clear. I use RoboschoolHumanoidFlagrunHarder-v1. I tried to replicate the result of the PPO paper. Yeah. There are 2 things that are different from them:
+ I use 32 works instead of 128 -> Batch size decrease 4 times.
+ Logstd = 0 instead of LinearAnneal because there is no implementation of that in stable-baselines nor openai baselines.
I have tried only 1 random seed which is 0. I will try more seeds. 
About normalization, I only normalize the observation, not the reward. But if I do normalize reward, I might need to change the way it plot the learning curve, right? Because as I have tried it once, the mean reward is around 10 while it is 1200 in the case of not normalizing reward.
About the demonstration, I did not use the render function. Let's see what it could archive.
Yeah. About the implementation, I did not know that PPO clips the value function.
So, what should be the case now?

**Comment by doviettung96** [comment]
For more details, this is my setting:
+ Policy and value network with same (no parameter is shared) architecture: 512, 256, 128 with relu activation. I have also tried other network setting such as MLP, (256, 128 with relu), selu. However, none of them reach the desired performance.
+ n_steps= 512
+ n_envs = 32
+ ent_coef = 0.0
+ learning_rate: I modified the code to use the adaptive learning rate based on KL divergence
+ nminibatchs = 4 -> minibatch_size = 4096
+ noptepochs = 15
+ Everything else is as default

Thanks for noticing.

**Comment by araffin** [comment]
> But if I do normalize reward, I might need to change the way it plot the learning curve, right? Because as I have tried it once, the mean reward is around 10 while it is 1200 in the case of not normalizing reward.

You have to use the monitor files to plot the right rewards, otherwise as you mentioned, it will be normalized (cf doc examples of logging).

>Logstd = 0 instead of LinearAnneal because there is no implementation of that in stable-baselines nor openai baselines.

in fact, the std is learned in the current implementation but it does not depends on the state.

>About the implementation, I did not know that PPO clips the value function.
So, what should be the case now?

This is a implementation variation introduced by openai when creating PPO2, it mentioned in [our documentation](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html), but I did not have to time to check its real impact on performance.

>512, 256, 128 with relu 

Where did you find this architecture?

>I use 32 works instead of 128 -> Batch size decrease 4 times.
>learning_rate: I modified the code to use the adaptive learning rate based on KL divergence

So, it seems you made non-trivial changes to the implementation. Then, it will be harder to reproduce the results.

**Comment by doviettung96** [comment]
About the architecture, the actual architecture is from this paper "GPU-Accelerated Robotic Simulation for DistributedReinforcement Learning". They use selu activation. I have tried both selu and relu which yields no difference. 
About the learning rate, fixed learning rate such as 3e-4 leads to worse result (I did not keep the figure). What I have done is just simply get the approxkl value of the logger in each update. You could find a similar implementation from line 208 of: https://github.com/joschu/modular_rl/blob/master/modular_rl/ppo.py
I use that as the learning rate function.
Maybe I should tried to use 128 workers and also try the reward normalization.

**Comment by doviettung96** [comment]
Hi @araffin,
I have tried 128 workers and also normalization of both observation and reward. However, the result seems unchanged.
One last thing to try is logstd=LinearAnneal.
As I printed the logstd in the policy, I got:
<tf.Variable 'model/pi/logstd:0' shape=(1, 17) dtype=float32_ref>
However, as I tried to add the following code to the end of PPO2 constructor:
with tf.variable_scope("model", reuse=True):
     self.logstd = tf.get_variable(name='pi/logstd:0') 

I got this:
ValueError: Variable model/pi/logstd:0 does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?
I had also just use the variable name "pi/logstd" but it was still failed.
How could I change the value of logstd during training?
Thanks.

**Comment by araffin** [comment]
Hello,
Please open an issue because this does not seem the right place anymore (here, it is supposed to be an issue about A2c).
Don't forget to use the issue template ;)

**Comment by doviettung96** [comment]
Sorry for making it not related to the title. I have already opened the new issue. #179
Thanks.

**Comment by araffin** [comment]
I think I found the bug:
https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/a2c/a2c.py#L325

As planned, this was very subtle. The actions were cast to int32 no matter what. I'll push a fix soon.
