### ISSUE TITLE
[question] How to rollout the learned policy?

### ISSUE THREAD

**Issue by GlennCeusters** [hill-a/stable-baselines#1098]
Hi,

I'm interested in "rolling out" the learned policy at a given state (e.g. using the transition function). Hence, plotting/printing the sequence of actions that maximized the expected future rewards at a given state/timestep (even though we would only execute the first action). Or in other words, predicting the future actions at a given state - before stepping through the environment (again, even though we would only execute the first action).

Many thanks for your replies!

Cheers,
/Glenn

**Comment by Miffyli** [comment]
This sounds more like model-based learning (stable-baselines focuses on model-free systems). There is no support for doing this directly, you need to input the states to agent to predict actions with `predict`.
