### ISSUE TITLE
Model training and testing the same dataset does not perform the same

### ISSUE THREAD

**Issue by yuvaleck** [hill-a/stable-baselines#1101]
Hi
I am using PPO2 model with a custom env
When the traing the model it can acheive a positive average value
It can be seen both in the tensorboard episode_reward chart and also by monitoring the env (from stable_baselines.bench import Monitor)
However, when passing the same dataset through the model the results are much worse... (average around zero)
Any possible explanation?
R,
yuvaleck 

![Capture](https://user-images.githubusercontent.com/80722317/111228002-cab71a80-85e3-11eb-8d0f-6967edbcb65e.JPG)

**Comment by Miffyli** [comment]
Hey. Could you provide full code to replicate the issue? This sounds like custom gym environment issue, for which we do not offer such tech support unless there is a bug / proposal for enhancement in the library itself.

**Comment by MariamDundua** [comment]
Is it possible to bound somehow observation in a stable-baseline? For example between  in 0-1

**Comment by araffin** [comment]
>Is it possible to bound somehow observation in a stable-baseline? For example between in 0-1

https://github.com/hill-a/stable-baselines/issues/1104

But your remarks seems unrelated to the original issue...

You may also take a look at VecNormalize (cf doc).
