### ISSUE TITLE
Error and not working - Mac - Using - spyder 4.1.5 - python 3.8 - please help?

### ISSUE THREAD

**Issue by elizmarg** [hill-a/stable-baselines#1107]
Hi, 

I have recently converted over to mac ( was previously using windows and a previous version of spyder and it was running perfectly).

Im now on Mac - Using - spyder 4.1.5 - python 3.8

It wont let me get a version of tensorflow installed below 2.

When running one of the cartepole codes as a test:

....................................

import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv

env = gym.make('CartPole-v1')

from stable_baselines import PPO2
model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)
print(model)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

...................................................

The output is:

Restarting kernel... 

 
[SpyderKernelApp] WARNING | No such comm: 78938414948411eb91321e003a348438

..................

I can bring back the env output: 

env
Out[1]: 
{'SHELL': '/bin/zsh',
 'TMPDIR': '/var/folders/1r/0wm_03dn1yb27v_01rq4_mt00000gn/T/',
 'CONDA_SHLVL': '1',
 'CONDA_PROMPT_MODIFIER': '(base) ',
 'LC_ALL': 'en_US.UTF-8',
 .. continues

.................................................................

but model produces error:

NameError: name 'model' is not defined

....................................................................

It says stable baselines is installed, but nothing runs:

pip show stable-baselines
Name: stable-baselines
Version: 2.10.1
Summary: A fork of OpenAI Baselines, implementations of reinforcement learning algorithms.
Home-page: https://github.com/hill-a/stable-baselines
Author: Ashley Hill
Author-email: ashley.hill@u-psud.fr
License: MIT
Location: /Users/name/opt/anaconda3/lib/python3.8/site-packages
Requires: opencv-python, numpy, matplotlib, cloudpickle, pandas, scipy, gym, joblib
Required-by: 
Note: you may need to restart the kernel to use updated packages.

pip show tensorflow
Name: tensorflow
Version: 2.4.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/name/opt/anaconda3/lib/python3.8/site-packages
Requires: astunparse, google-pasta, numpy, absl-py, opt-einsum, flatbuffers, tensorboard, wrapt, tensorflow-estimator, typing-extensions, protobuf, keras-preprocessing, six, wheel, grpcio, h5py, termcolor, gast
Required-by: 
Note: you may need to restart the kernel to use updated packages.

pip show gym
Name: gym
Version: 0.18.0
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Users/name/opt/anaconda3/lib/python3.8/site-packages
Requires: numpy, Pillow, pyglet, scipy, cloudpickle
Required-by: stable-baselines
Note: you may need to restart the kernel to use updated packages.

.................................................................

Please could someone help??

Thanks so much.

**Comment by Miffyli** [comment]
stable-baselines does not support Tensorflow 2.x. You need to install Tensorflow 1.x (e.g. 1.15).

**Comment by elizmarg** [comment]
Hi @Miffyli Thankyou so much for coming back to me.

So i have now gone back to spyder - 3.3.3 - python 3.7 - and have tensorflow as:

Name: tensorflow
Version: 1.15.3
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/name/anaconda3/lib/python3.7/site-packages
Requires: keras-applications, opt-einsum, tensorflow-estimator, six, wheel, grpcio, tensorboard, termcolor, keras-preprocessing, protobuf, numpy, google-pasta, absl-py, wrapt, astor, gast
Required-by: 
Note: you may need to restart the kernel to use updated packages.

all other packages downloaded are the same as what i had on my windows machine which ran fine with them.

Now when i run it.. no error is given however  - it just runs for a second and then nothing is outputted and then just goes back to the command line.

Then env is the same in that it still  produces:

env
Out[2]: 
{'SHELL': '/bin/zsh',
 'TMPDIR': '/var/folders/1r/0wm_03dn1yb27v_01rq4_mt00000gn/T/',
 'CONDA_SHLVL': '1',
 'CONDA_PROMPT_MODIFIER': '(base) ',
 'LC_ALL': 'en_US.UTF-8',
....

but nothing in the example above  is bought back for anythign related to stable-baselines:

e.g.

: NameError: name 'model' is not defined

do you know why this could be?

**Comment by Miffyli** [comment]
> Now when i run it.. no error is given however - it just runs for a second and then nothing is outputted and then just goes back to the command line.

This is to be expected if you do not provide `verbose=2` upon creating SB model. Without this command nothing is printed to the command line. Sounds like any remaining issues are with the environment you are using, for which we do not provide tech support. 

You may close the issue if no further bugs/issues related to stable-baselines occur.

**Comment by elizmarg** [comment]
Hi - sorry to come back

but...even with verbose set to 2 to see the output when building the SB model

i get the same issue 

import gym

from stable_baselines import DQN
from stable_baselines.common.evaluation import evaluate_policy


# Create environment
env = gym.make('LunarLander-v2')

# Instantiate the agent
model = DQN('MlpPolicy', env, learning_rate=1e-3, prioritized_replay=True, verbose=2)
# Train the agent

model
Traceback (most recent call last):

  File "<ipython-input-1-1f8a688cae5d>", line 1, in <module>
    model

NameError: name 'model' is not defined




model = DQN('MlpPolicy', env, learning_rate=1e-3, prioritized_replay=True, verbose=2)
Traceback (most recent call last):

  File "<ipython-input-2-9d003b56d13f>", line 1, in <module>
    model = DQN('MlpPolicy', env, learning_rate=1e-3, prioritized_replay=True, verbose=2)

NameError: name 'DQN' is not defined




pip show stable-baselines
Name: stable-baselines
Version: 2.10.1
Summary: A fork of OpenAI Baselines, implementations of reinforcement learning algorithms.
Home-page: https://github.com/hill-a/stable-baselines
Author: Ashley Hill
Author-email: ashley.hill@u-psud.fr
License: MIT
Location: /Users/name/anaconda3/lib/python3.7/site-packages
Requires: matplotlib, joblib, numpy, pandas, opencv-python, gym, cloudpickle, scipy
Required-by: 
Note: you may need to restart the kernel to use updated packages.

pip show tensorflow
Name: tensorflow
Version: 1.15.3
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/name/anaconda3/lib/python3.7/site-packages
Requires: google-pasta, wheel, tensorflow-estimator, absl-py, astor, termcolor, grpcio, numpy, protobuf, wrapt, keras-applications, six, opt-einsum, keras-preprocessing, gast, tensorboard
Required-by: 
Note: you may need to restart the kernel to use updated packages.

pip show gym
Name: gym
Version: 0.17.2
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Users/name/anaconda3/lib/python3.7/site-packages
Requires: pyglet, cloudpickle, numpy, scipy
Required-by: stable-baselines
Note: you may need to restart the kernel to use updated packages.

Any help would be much apprecuated - for why it is saying DQN is not defined.. when running the import from stable-baselines fine.

Thanks

**Comment by Miffyli** [comment]
It seems not all lines were executed (perhaps you are running jupyter notebooks? In that case you need to run all cells in order).

The code seems fine and should run correctly. Closing the issue as "no tech support".
