### ISSUE TITLE
Custom Policy

### ISSUE THREAD

**Issue by candygocandy** [hill-a/stable-baselines#1109]
For Custom Policy, I am wondering if you have implementation with resenet structure?

Specifically, I am looking to build an IMPALA_CNN (that involves with residual connection). However, I have no idea how to define that. Here is the IMPALA-CNN structure that I am talking about `https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/models.py#L28`

Is it possible to help me out?

**Comment by araffin** [comment]
Hello,

>However, I have no idea how to define that. 
>https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/models.py#L28


Well, impala cnn would have the same role as `nature_cnn` we are using in SB2, you should take a look at the doc/code and look for `cnn_extractor` in the policy file.

Anyway, I would also highly recommend to switch to Stable-Baselines3: https://github.com/DLR-RM/stable-baselines3

Take a look at "features_extractor" in the documentation: https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#sb3-policy

**Comment by candygocandy** [comment]
Thanks for the quick reply. Do you know what is the archecture for the default Cnnpolicy? (after the NatuerCNN, how layers / neurons for policy and value?)

**Comment by araffin** [comment]
>Do you know what is the archecture for the default Cnnpolicy?

best is to look at the code ;)

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/torch_layers.py#L62

So, after the Nature CNN, there is one fully-connected layer to reduce the dimension to 512, and then it directly a linear layer for the policy/value function heads.
