### ISSUE TITLE
[Question] How can I initialize weights of MLP policy by some customized values?

### ISSUE THREAD

**Issue by zrz961203** [hill-a/stable-baselines#1121]
My algorithms seem to be stuck in some local optimum, I wonder if it's possible to use some customized values to initialize MLP policy, for example, use some 0.1 for some layers. Thanks!

**Comment by Miffyli** [comment]
The easiest way is probably using [get_parameters](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.get_parameters) and [load_parameters](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.load_parameters) in the beginning to set the parameters to what you want.

PS: We recommend moving to [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) for better support and easier-to-modify code :)
