### ISSUE TITLE
LinearAnneal

### ISSUE THREAD

**Issue by JulioEstebanAsiainNeno** [hill-a/stable-baselines#1125]
Hey there! @araffin 
I've been trying to emulate the following paper: Distributed multi-robot collision avoidance via deep reinforcement learning for
navigation in complex scenarios, and it said they used the PPO LinearAnneal function to get the logstd. While checking multiple papers and this github, I haven't been able to find it. I saw on git that you were using LinearAnneal too from the OpenAi environments but I can't seem to find the function. Could you guide me in the correct way so I can find it and use it correctly?

Thanks
Julio

**Comment by araffin** [comment]
Hello,
Best for you is to switch to SB3 and use a callback, see related issues: https://github.com/DLR-RM/stable-baselines3/issues/231
