### ISSUE TITLE
evaluate_policy of MlpLstmPolicy with DummyVecEnv

### ISSUE THREAD

**Issue by LeZhengThu** [hill-a/stable-baselines#1129]
Hi @araffin @Miffyli , I'm working with MlpLstmPolicy with DummyVecEnv and want to evaluate the policy. However, there's an error: AssertionError: You must pass only one environment when using this function. Below is the code that replicates my error.

```
import gym
from stable_baselines import PPO2
from stable_baselines.common.evaluation import evaluate_policy
from stable_baselines.common.vec_env import DummyVecEnv


def make_env():
    def maker():
        env = gym.make('CartPole-v1')
        return env
    return maker

n_training_envs = 4
envs = DummyVecEnv([make_env() for i in range(n_training_envs)])
lstm_model = PPO2('MlpLstmPolicy', envs, nminibatches=n_training_envs)
lstm_model.learn(int(1000))
evaluate_policy(lstm_model, lstm_model.get_env())

```

**Comment by Miffyli** [comment]
As error states, you can only use one env for evaluation. You need to create a new DummyVecEnv that only contains one of your environments.

**Comment by LeZhengThu** [comment]
@Miffyli  I mean if there's any way to use multiple envs to accelerate the training? If understand correctly, the purpose of the vectorized env, like DummyVecEnv, is to stack multiple independent environments into a single environment and speed up the training process.

**Comment by Miffyli** [comment]
Unfortunately not. This is further constrained by LSTM policies, which require same number of envs for `predict` as they used during training. `evaluate_policy` automatically does this for you.

If you can live without LSTM policies, check out [SB3](https://github.com/DLR-RM/stable-baselines3/) where policies can be evaluated with multiple envs.

**Comment by LeZhengThu** [comment]
OK, that's fair. Thanks for the reply. I'll close this question.
