### ISSUE TITLE
How to set constant learning rate in PPO1?

### ISSUE THREAD

**Issue by nicehzj** [hill-a/stable-baselines#1131]
I checked the doc, but I still cannot find a way to set a constant learning rate in PPO1.

I tried a lot of ways, and the learning rate is always 1e-3.

Can anyone help me?

Thanks a lot

**Comment by Miffyli** [comment]
Did you mean setting a learning schedule? Because if learning rate is always 1e-3, it is being constant.

**Comment by araffin** [comment]
Closing as the answer is in the doc.
