### ISSUE TITLE
Prediction for same observation using same model

### ISSUE THREAD

**Issue by hugistaken** [hill-a/stable-baselines#1156]
Hi, 
I've been trying to understand how .predict generates a suggested action... for the same model and same input I get completely different outcomes. Is there a way to replicate a model's performance on a data set, or is there some inherent randomness that is occasionally giving me high accuracy for my model?

**Comment by Miffyli** [comment]
You need to pass `deterministic=True` as part of the `predict` call :). The default is that agent samples an action from a distribution, i.e. you will get different actions. 

Also we recommend moving to [stable-baselines3](https://github.com/DLR-RM/stable-baselines3).
