### ISSUE TITLE
Data normalization for a2c inputs?

### ISSUE THREAD

**Issue by hugistaken** [hill-a/stable-baselines#1157]
Hey, I've been experimenting with the A2C model, and I've noticed that the scaling of data plays a big role in the outcome produced. For example, I've passed the same data represented as decimals in the thousandths, and in the tenths, and gotten drastically different results. I was looking for some tips or intuitive explanations for best practices and what goes on behind the scenes, specifically what order of magnitude you've found works best and how to treat separate inputs of different orders of magnitude. Thank you. 
Edit: found good recourses in stable baselines docs.

**Comment by Miffyli** [comment]
Yup, as you noticed, docs have the most resources we have to offer :). Also we recommend using [stable-baselines3](https://github.com/DLR-RM/stable-baselines3), which has better docs and maintained code-base.

Closing as resolved.
