### ISSUE TITLE
Cannot install stable baselines 3

### ISSUE THREAD

**Issue by OishikGuha** [hill-a/stable-baselines#1160]
**Describe the bug**

So, I was watching a [course](https://www.youtube.com/watch?v=Mut_u40Sqz4) on reinforcement learning, and in the first part where the tutor installs the stable-baselines3 package, I get this error when doing the same:
The full error message is:
```
ERROR: Command errored out with exit status 1: 'd:\python\python38\python.exe' 'd:\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Administrator\AppData\Local\Temp\pip-build-env-s7uz5mve\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel requests tqdm click 'importlib-resources; python_version < '"'"'3.9'"'"'' Check the logs for full command output.
```
This is the command I used:
```
pip install stable_baselines3[extra]
```

**System Info**
Describe the characteristic of your environment:
 * Installing library: pip
 * GPU: Nvidia GTX 1060
 * Python version: 3.8
 * Tensorflow version: 2.8.0
 * Pip version: 20.2.3

**Comment by Miffyli** [comment]
Hey. This is stable-baselines repository, not stable-baselines3 :). Anywho, the command should be `pip install stable-baselines3[extra]` (`-` instead of `_`). If this works, please close the issue. Note that we do not offer extensive tech support in issues.

**Comment by OishikGuha** [comment]
@Miffyli thank you but that is giving me the same error.

**Comment by Miffyli** [comment]
Ah, can you share the full log of errors? I imagine it is related to this: https://github.com/DLR-RM/rl-baselines3-zoo/issues/232 

Try just installing `pip install stable-baselines3`. You will still get the main stable-baselines3 code and you can train agents.

**Comment by OishikGuha** [comment]
@Miffyli 
> Ah, can you share the full log of errors? I imagine it is related to this: https://github.com/DLR-RM/rl-baselines3-zoo/issues/232
I can't really find the logs but..

> Try just installing pip install stable-baselines3. You will still get the main stable-baselines3 code and you can train agents.
Thank you, this worked :)
