### ISSUE TITLE
Is there a simple way to modify tensorboard summaries while using model.learn? [question]

### ISSUE THREAD

**Issue by Ofer-Idan** [hill-a/stable-baselines#119]
I am training DDPG agents on different environments following the examples in the docs, and using the predefined DDPG class, MlpPolicy and the .train method. 
From going through the code, it seems that DDPG comes pre-built with a few scopes (adam_mpi, input_info etc.) that include some info (parameter noise stats, actor loss etc.) but not everything I would like to cover.

Is there a way to define and add summaries without forking the repo and delving into ddpg itself? 
For example, it would be super useful if we could add Q statistics to tensorboard while maintaining the simplicity of the training code

Thanks!

**Comment by araffin** [comment]
Hello,

>Is there a way to define and add summaries without forking the repo and delving into ddpg itself?

From what you described, you need to change the code but you don't necessarily need to fork the repo, for instance you can create a class CustomDDPG that inherits from stable_baselines DDPG class.
An example: https://github.com/araffin/learning-to-drive-in-a-day/blob/master/ddpg_with_vae.py

**Comment by araffin** [comment]
>Then again this could be implemented as a parameter for advanced users

I think we should keep the default tensorboard logging (maybe remove all the histogram to save memory), more advanced users are supposed to be able to hack the code, no?

I would like to keep the interface as simple as possible while providing a bit of flexibility (for me, choosing which tensor you want to log is too much).

**Comment by hill-a** [comment]
> more advanced users are supposed to be able to hack the code, no?

Well that is true, I don't think I would like to hack some code just so I can log specific details for example. So I'm not sure more more advanced users would either.

> I would like to keep the interface as simple as possible while providing a bit of flexibility 

Indeed, hence the question about notation. I'm not sure I can make any simpler/user-friendly.

**Comment by JoelNiklaus** [comment]
I would like to comment on this. My tensorboard log files are huge! Up to 100GB. So for me it would be very nice if there was an option to disable some logging. 

Do I understand that correctly that the only way to reduce the file size is to extend the algorithm class (PPO, DDPG) at the moment?

**Comment by araffin** [comment]
>Do I understand that correctly that the only way to reduce the file size is to extend the algorithm class (PPO, DDPG) at the moment?

For now yes, but I think @hill-a was working on this in the `enhancements`, I will try to work on this one if he doesn't have the time in the coming days.

> So the most memory heavy summaries are the histograms?

I'm not sure, there are also metadata that may takes space to (see comment [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L229), anyway I agree that there is too much tensorboard logging for the moment.

**Comment by JoelNiklaus** [comment]
Ok. Thank you very much. I am looking forward to it :)
