### ISSUE TITLE
.action_probability() with (obs, act) input?

### ISSUE THREAD

**Issue by sirspinach** [hill-a/stable-baselines#127]
For my project it would be handy to have a overloaded version of `.action_probability()` which returns the batch probability that the policy will choose batched actions `act` when seeing batched observations `obs`.

If I were to implement this would this be something that the maintainers think would be nice to have in the repo? (Also, any potential difficulties with this approach, especially with continuous action spaces?)

**Comment by araffin** [comment]
Hello,

>the batch probability that the policy will choose batched actions act when seeing batched observations obs.

Well, when using vectorized environments, you already have that:

```python
import numpy as np
from stable_baselines import PPO2

model = PPO2("MlpPolicy", "CartPole-v1")
# env is a dummy vec env
env = model.get_env()

obs = env.reset()
# Create a fake batch
n_batch = 16
batch_obs = np.concatenate([obs] * n_batch)
# outputs: (16, 2) (n_batch, n_actions)
print(model.action_probability(batch_obs).shape)
```

**Comment by hill-a** [comment]
Hey,

@araffin, I think @sirspinach mean the probablity of a known given action being taken for a known given observation: 
```python
act = [env.action_space.sample() for _ in range(128)]
obs = [env.observation_space.sample() for _ in range(128)]
p = model.action_probability(obs, act)
```
where p would be the probablity of the action being taken by the policy with that observation.
Or am I mistaken?
