### ISSUE TITLE
Flexible architecture for LSTM policies

### ISSUE THREAD

**Issue by erniejunior** [hill-a/stable-baselines#137]
The discussions in #91 yielded good new ideas to specify the architecture of FeedForwardPolicies and LSTMPolicies. So far, only the ideas for the FeedForwardPolicies were implemented. I propose to also implemente the ideas discuseed [here](https://github.com/hill-a/stable-baselines/issues/91#issuecomment-442442250). I plan to implement the 'alternative notation' without the possibility of non-shared LSTMs. At the same time I plan to solve issue #90.

**Comment by araffin** [comment]
closed by #139
