### ISSUE TITLE
Setting up custom environments

### ISSUE THREAD

**Issue by imankgoyal** [hill-a/stable-baselines#14]
Is there a way to set up a custom environment, so that one can use the framework for custom environments (apart from OpenAI-Gym/Mujoco) as well? Specifically, an example like https://rllab.readthedocs.io/en/latest/user/implement_env.html for the framework would be great.
Thanks!

**Comment by araffin** [comment]
Hi,

Thanks for your interest.
To use the algorithms on custom environments, they just need to follow the gym interface.
How to create a new gym env: https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym
Basically, you need to implement `reset()`, `step()` and `render()` methods. Optionnaly, you can register the env with gym, that will allow you to create the RL agent in one line: https://stable-baselines.readthedocs.io/en/master/guide/quickstart.html

In the test, we have an example with identity env, which is a custom env:
- defined here: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/identity_env.py
- how to use it: https://github.com/hill-a/stable-baselines/blob/master/tests/test_identity.py

That is a good question, I'll add it to the documentation ;)

**Comment by imankgoyal** [comment]
Thank you. This helps a lot!
