### ISSUE TITLE
[Question] checkpoint in PPO2

### ISSUE THREAD

**Issue by AloshkaD** [hill-a/stable-baselines#146]
Is there a reason why the dqn has checkpoint but not PPO2? I simply need to save before I reach the end of training to make sure if the PC is restarted I don't lose the training. This could be easily done with the dqn

**Comment by araffin** [comment]
Hello,
What you are looking for is called [callback](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training) in the documentation.

**Comment by AloshkaD** [comment]
Thanks! I saw that but I was thinking about passing it to ppo2 like in dqn and hence submit a PR.
