### ISSUE TITLE
model.predict() returns actions in range [-1,1] from model trained with range [0,1]

### ISSUE THREAD

**Issue by pstansell** [hill-a/stable-baselines#147]
**Description of the bug**

If a continuous action is specified in the range [0,1], rerunning with
a saved trained model returns actions in the range range [-1,1].

In particular, the function

`model.predict(obs, deterministic = True)`

returns actions in the range [-1,1] instead of the required range of
[0,1].

**Code Example**

On line 30 of

`gym/envs/classic_control/continuous_mountain_car.py`

replace

`self.min_action = -1.0`
  
by

`self.min_action = 0.`

On line 7 of the example PPO1 code give at

  https://stable-baselines.readthedocs.io/en/master/modules/ppo1.html

replace

`env = gym.make('CartPole-v1')`

by

`env = gym.make('MountainCarContinuous-v0')`

Running this code shows that during training the action is in the
range [0,1] as required, but during a rerun of the saved model the
actions are in the range [-1,1].

**System Info**

My environment:

* Installed by pip into virtual environment.
* Stable Baselines version 2.3.0
* Python version 3.5.2 is installed in the virtual environment.
* Tensorflow version 1.12.0.
* OpenAI Gym version 0.10.9.
* My OS is Ubuntu-16.04.
* No GPUs.

**Comment by araffin** [comment]
Hello,

I think the problem you described is already documented here: https://github.com/hill-a/stable-baselines/issues/104

Also related: https://github.com/hill-a/stable-baselines/issues/112

The thing is that the ouput range is [-inf, inf] because of the use of gaussian.

**Comment by pstansell** [comment]
Hello Araffin,

Thanks for your help.  In my case, using PPO1, it seems that clipping
the actions as shown below allows a trained model to be loaded and run
for my environment
```
actions, states = model.predict(obs, deterministic = True)
actions = np.clip(actions, env.action_space.low, env.action_space.high)
obs, rewards, done, info = env.step(actions)
```

**Comment by araffin** [comment]
ok, closing the issue then.

**Comment by pstansell** [comment]
Hi Antonin,

I'm quite new to Python and don't know the code well, but could the line

  actions = np.clip(actions, env.action_space.low, env.action_space.high)

not be added at the end of the predict() method to fix this problem
for future users?  If that's not a good solution then adding a comment
in the documentation would be helpful.

**Comment by araffin** [comment]
>not be added at the end of the predict() method to fix this problem for future users? 

The predict is meant to be independent of the environment.

>If that's not a good solution then adding a comment in the documentation would be helpful.

this is already documented [here](https://stable-baselines.readthedocs.io/en/master/modules/policies.html)

**Comment by pstansell** [comment]
I see, you are right, but I'm afraid that I didn't notice that warning
on the Policy Networks page of the documentation.  Even if I had read
it early on I would not have known how to avoid the problem without
an example.

Maybe it would be helpful for beginners if there were an example of the
Continuous Mountain Car environment on the PPO1 page of the
documentation.  Then it could be made really clear how to deal with
continuous actions spaces when using the predict method.
