### ISSUE TITLE
AssertionError: Error: the input policy for the DDPG model must be an instance of DDPGPolicy.

### ISSUE THREAD

**Issue by HareshMiriyala** [hill-a/stable-baselines#150]

**Comment by araffin** [comment]
Hello,
Please fill the issue template otherwise we cannot help you.

**Comment by Pawull** [comment]
I also get this message using the example at:
https://stable-baselines.readthedocs.io/en/master/modules/ddpg.html

`model = DDPG(MlpPolicy, env, verbose=1, param_noise=param_noise, action_noise=action_noise)
`

> Traceback (most recent call last):
>   File "/home/pawu/devel/rl-autopilot/lunar_lander/baselines/main.py", line 45, in <module>
>   File "/home/pawu/devel/rl-autopilot/lunar_lander/baselines/main.py", line 27, in main
>     
>   File "/home/pawu/devel/rl-autopilot/lunar_lander/baselines/main.py", line 18, in get_models
>     DDPG(MlpPolicy, env, actor_lr=LEARNING_RATE, critic_lr=LEARNING_RATE, gamma=GAMMA, verbose=1),
>   File "/usr/lib/python3.5/site-packages/stable_baselines/ddpg/ddpg.py", line 270, in __init__
>     self.setup_model()
>   File "/usr/lib/python3.5/site-packages/stable_baselines/ddpg/ddpg.py", line 277, in setup_model
>     assert issubclass(self.policy, DDPGPolicy), "Error: the input policy for the DDPG model must be " \
> AssertionError: Error: the input policy for the DDPG model must be an instance of DDPGPolicy.

**Comment by araffin** [comment]
@Pawull try replacing `MlpPolicy` (class) by `"MlpPolicy"` (string), if this works, you are not importing the right MlpPolicy (please double check the example in the doc).

**Comment by Pawull** [comment]
@araffin My bad, I indeed used the wrong policy while trying to use multiple different MlpPolicy implementations. Thanks.
