### ISSUE TITLE
Example code for PPO2 throws MPI failure

### ISSUE THREAD

**Issue by SerialIterator** [hill-a/stable-baselines#163]
**Describe the bug**
I installed stable baselines according to the docs for ubuntu. I copied the "Getting Started" code for running PPO2 on a CartPole environment and saved it to a file "tester.py". When I run it, it says "MPI_INIT failed for some reason". I have a conda environment for stable-baselines and I have removed and reinstalled stable-baselines and all dependencies. I uninstalled mpi4py and reinstalled but get the same error.

**Code example**

```python
import gym
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

output:
```
[hacky-box:15731] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 458
[hacky-box:15731] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 166
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value A system-required executable either could not be found or was not executable by this user (-126) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "A system-required executable either could not be found or was not executable by this user" (-126) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[hacky-box:15731] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**System Info**
Describe the characteristic of your environment:
 * Linux Mint Cinnamon 19 
 * Library was installed in Conda Environment python=3.6.5 using pip. apt-get to update and install 
    cmake, libopenmpi-dev, python3-dev and zlib1g-dev although they were already installed.
 * 2- nvidia GTX-1080ti GPU's. nvidia driver:390.77 cuda:9.2 cudann:7.2.1
 * Python version 3.6.5
 * Tensorflow version 1.12.0
 * mpi4py: 3.0.0

**Additional context**
After searching for a solution, there was an issue reported to openai baselines with the same error [here](https://github.com/openai/baselines/issues/573) although there was no solution just an explanation that mpi is used for PPO. I have used a Pytorch implementation of baselines PPO algo and it is able to parallelize the workers [repo](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr) so I don't think it is the mpi4py package. I feel like the conda env is using python 3.6.5 and ignoring the header files for python-dev version downloaded using apt-get although I'm not sure how to check for that yet.

**Comment by araffin** [comment]
Hello,
What command did you type to run the code?
PPO2 does not use MPI (that's PPO1 which parallelize using it).
Also I suspect your problem to be related to MPI, not Stable-Baselines (and the issue [here](https://github.com/openai/baselines/issues/573) mentioned the same Linux distribution...)

Did you try what was suggested [here](https://github.com/openai/baselines/issues/573#issuecomment-420473660) to check that MPI is working fine?

Note: I edited your comment to format it properly using markdown (please check the syntax for next time you post some code ;))

**Comment by araffin** [comment]
The last error you get is only related to gym, usually it is because you forgot to call `ènv.close()`. (see https://github.com/openai/gym/issues/893)

Closing this issue then (because not related to stable-baselines).

**Comment by YijiongLin** [comment]
Hello! @araffin 
Recently I tried to run the multiple thread environment, but it kept failing. And I proposed this issue in  [here](https://github.com/openai/baselines/issues/998). Could you please take a look? Any feedback is really appreciated!
