### ISSUE TITLE
[question] How is TimestepsSoFar computed?

### ISSUE THREAD

**Issue by antoine-galataud** [hill-a/stable-baselines#164]
Hi,

My stable-baselines version is 2.3. I'm trying to understand how TimestepsSoFar is computed for TRPO. In the logs after I start a training, first stats are as following:

```
----------------------------------
| EpLenMean       | 128          |
| EpRewMean       | -840         |
| EpThisIter      | 1            |
| EpisodesSoFar   | 1            |
| TimeElapsed     | 18.3         |
| TimestepsSoFar  | 128          |
| entloss         | 0.04307969   |
| entropy         | 4.307969     |
| ev_tdlam_before | -0.00229     |
| meankl          | 0.0095857065 |
| optimgain       | 0.1366807    |
| surrgain        | 0.09360102   |
----------------------------------
```

Then, second one:

```
---------------------------------
| EpLenMean       | 192         |
| EpRewMean       | -1.24e+03   |
| EpThisIter      | 1           |
| EpisodesSoFar   | 2           |
| TimeElapsed     | 23.9        |
| TimestepsSoFar  | 384         |
| entloss         | 0.04303209  |
| entropy         | 4.3032093   |
| ev_tdlam_before | 1.61e-06    |
| meankl          | 0.010002808 |
| optimgain       | 0.14815919  |
| surrgain        | 0.105127096 |
---------------------------------
``` 

3rd trace: 

```
---------------------------------
| EpLenMean       | 256         |
| EpRewMean       | -1.67e+03   |
| EpThisIter      | 1           |
| EpisodesSoFar   | 3           |
| TimeElapsed     | 29.6        |
| TimestepsSoFar  | 768         |
| entloss         | 0.042882647 |
| entropy         | 4.2882648   |
| ev_tdlam_before | 0           |
| meankl          | 0.010393932 |
| optimgain       | 0.16137204  |
| surrgain        | 0.118489385 |
---------------------------------
```

You can see that `TimestepsSoFar` seems to double every time although batch size is 128. The problem I have happens with a custom env (tried with CartPole, it seems to increment correctly). 

What could be the reason for that?

**Comment by araffin** [comment]
Hello,
do you use MPI to train it?

I think the two relevant lines in the code are:

https://github.com/hill-a/stable-baselines/blob/88a5c5d50a7f6ad1f44f6ef0feaa0647ed2f7298/stable_baselines/trpo_mpi/utils.py#L70

and

https://github.com/hill-a/stable-baselines/blob/88a5c5d50a7f6ad1f44f6ef0feaa0647ed2f7298/stable_baselines/trpo_mpi/trpo_mpi.py#L434

There may be a bug, because total_timesteps does not seem to be resetted... in `traj_segment_generator`
