### ISSUE TITLE
[Question] - How to render during training?

### ISSUE THREAD

**Issue by iandanforth** [hill-a/stable-baselines#167]
How would I run model.learn() but have the env render during training?

#### Why would you want to do this?

I'm developing a new MuJoCo model and I ran into instability in the simulation. This instability manifests as `MuJoCo Warning: Nan, Inf or huge value in QVEL at DOF 0. The simulation is unstable.` 

One method of trying to isolate why the simulation has become unstable is to watch the training process until the point where this occurs.

#### Are you blocked on this?

No. I can add in env.render() myself directly to ppo2.py but I'd love to know a better / less hacky way to do this.

**Comment by hill-a** [comment]
Hey,

The [callback function](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training) might work here:
```python
def callback(locals, _globals):
    locals["self"].env.render()
    return True

...

model.learn(int(1e4), callback=callback)
```

**Comment by araffin** [comment]
Yes, the callback function could be a solution, but for ppo2, it is called only after n_steps...

>No. I can add in env.render() myself directly to ppo2.py but I'd love to know a better / less hacky way to do this.

Well, that's just one line of code, and as this is only for debug purposes, I don't think that's a big deal, and I'm afraid I don't see any better solution.

**Comment by iandanforth** [comment]
Thanks both!
