### ISSUE TITLE
predict() selects random actions 

### ISSUE THREAD

**Issue by nagadomi** [hill-a/stable-baselines#17]
`trained_model.predict()` selects random actions for the same input. It is probably the expected behavior, but I need deterministic actions in some cases(I am using this library for algorithmic trading). For now I have implemented it with `action_probability()`, but it would be nice to have a method to return deterministic actions for test run.

**Comment by araffin** [comment]
Hi,
Yes, most algorithms have stochastic policies. Some (like DDPG) are stochastic during training but fully deterministic during testing. A workaround is what you have done with the action_probability.
That may be a good idea to add a `deterministic` keyword. What do you think @hill-a  ?

**Comment by hill-a** [comment]
That's a good point, I’ll add it to the TODO list of the current branch.

**Comment by araffin** [comment]
@nagadomi #16 was just merged with master. It adds the "deterministic" argument to the predict function ;)
We plan to release it soon on pypi, but you can install from source (see documentation "Bleeding-Edge version" https://stable-baselines.readthedocs.io/en/master/guide/install.html#bleeding-edge-version)

**Comment by nagadomi** [comment]
Thank you for your prompt attention to this issue. :+1:
