### ISSUE TITLE
Multiprocessing not working with TRPO

### ISSUE THREAD

**Issue by carlo-** [hill-a/stable-baselines#171]
Vectorized environments do not seem to be supported for TRPO anymore, despite what is currently stated in the [documentation](https://stable-baselines.readthedocs.io/en/master/modules/trpo.html#can-i-use).

When trying to train with a `SubprocVecEnv` I get this error:
> Error: the model requires a non vectorized environment or a single vectorized environment

because `requires_vec_env` is set to `False` in the initialization of TRPO:
```python
super(TRPO, self).__init__(policy=policy, env=env, verbose=verbose, requires_vec_env=False,
                           _init_setup_model=_init_setup_model, policy_kwargs=policy_kwargs)
```

I tried to change the source and set `requires_vec_env=True`, but now I get shape mismatch errors from Tensorflow. Is this a bug or is multiprocessing not supported for TRPO anymore? The bug can be reproduced with all environments as far as I have seen.

**Code example**
```python
def init_env(seed=0):
    def _init():
        env = gym.make('CartPole-v1')
        env.seed(seed)
        return env
    return _init

def main():
    n_workers = 8
    env = SubprocVecEnv([init_env(seed=42 + i) for i in range(n_workers)])
    model = TRPO(MlpPolicy, env)
    model.learn()
```

**System Info**
 * Ubuntu 16.04
 * Python 3.6.7
 * stable-baselines installed via pip
 * tensorflow 1.12.0
 * gym 0.10.9
 * mpi4py 3.0.0

**Comment by araffin** [comment]
Hello,
If you read the documentation carefully, it says `Multi processing: ✔️ (using MPI)`, that means vectorized env are not supported and you have to use MPI for multiprocessing (cf the commands shown above in the doc). Maybe we should make it clearer in the doc.
Feel free to open a PR to update the documentation ;)

**Comment by carlo-** [comment]
Oh I see. I'm not familiar with MPI so I must have missed that. Thank you!

**Comment by yjc765** [comment]
> Oh I see. I'm not familiar with MPI so I must have missed that. Thank you!

Could you use MPI for multiprocessing of TRPO?  Thanks!

**Comment by PierreExeter** [comment]
@yjc765 
You can execute this script example (trpo_multi.py) with MPI to use multiprocessing with TRPO as follows:

```python
import gym
from stable_baselines.common.policies import MlpPolicy
from stable_baselines import TRPO

env = gym.make('CartPole-v1')
model = TRPO(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
```

Execute with 8 processes:
```python
mpirun -np 8 python trpo_multi.py 
```

Hope this helps.
