### ISSUE TITLE
[Question] Tesorboard episode_reward vs ppo2.py ep_rewmean console output.

### ISSUE THREAD

**Issue by iandanforth** [hill-a/stable-baselines#175]
Hopefully a basic question. I would expect that `ep_rewmean` on stdout and `episode_reward` in tensorboard would be very similar (just given their names).

`ep_rewmean` (and other stats) look like this:

![image](https://user-images.githubusercontent.com/446062/51715680-98569780-1fee-11e9-9137-4a82c2872d78.png)

When I look at the `episode_reward` graph in tensorboard I see much lower numbers.

![image](https://user-images.githubusercontent.com/446062/51715648-7ceb8c80-1fee-11e9-84eb-846c5a95c334.png)

What is the relation between these two quantities?

**Comment by araffin** [comment]
(i did not mean to close the issue, was the result of a bad manipulation ^^`)

**Comment by iandanforth** [comment]
Thanks for the answer and sorry for the lack of context!

For posterity this was run with `train.py` from rl-baselines-zoo which I now see adds the [VecNormalize(env) wrapper](https://github.com/araffin/rl-baselines-zoo/blob/master/train.py#L126), thus this ticket would have been more appropriate in that repo.

**Comment by Pastafarianist** [comment]
While this issue exists, perhaps logging from OpenAI Baselines shouldn't be called legacy. Currently it is the only way to retrieve original reward, which is the only way to compare agent performance against other results.

**Comment by araffin** [comment]
>Currently it is the only way to retrieve original reward

What about the `Monitor` wrapper? This is the way to retrieve the original training reward.

**Comment by Pastafarianist** [comment]
It has no native integration with Tensorboard though, unless I am missing something.

**Comment by araffin** [comment]
with this solution (now added to the documentation), this is now possible to log additional values: #409

**Comment by noyan72** [comment]
Did I realize that by results_plotter.plot_results we can see the original reward that environment return?

 and isn't the episode-reward on the tensorboard valid?

**Comment by noyan72** [comment]
@araffin 
Did I realize that by results_plotter.plot_results we can see the original reward that environment return?

and isn't the episode-reward on the tensorboard valid?
