### ISSUE TITLE
[question] Updating a policy with externally generated experience data

### ISSUE THREAD

**Issue by antoine-galataud** [hill-a/stable-baselines#176]
Hi,

The use case would be the following:
- train a policy in a simulated environment
- deploy this policy, use it to predict actions based on collected observations
- store observations and actions in a storage layer (DB, ...)
- use collected data to update the policy on a regular basis

If I’m correct, this only makes sense with off-policy algorithms. 

I had a quick look into the code and the simplest way to do it would be to provide a custom Runner instance (where avalaible, checked ACER but not sure other algos use it).

Questions:
- where would it be really applicable? I guess there are a few limitations/constraints that prevent from doing this with some particular algos. 
- do you see a better way than using Runner abstraction?

Thanks!

**Comment by twkillian** [comment]
> I would rather directly access the replay buffer (as done [here](https://github.com/araffin/learning-to-drive-in-5-minutes/blob/master/teleop/teleop_client.py#L332)) and then use the `train_step` method to optimize the policy (you have an example [here](https://github.com/araffin/learning-to-drive-in-5-minutes/blob/master/algos/custom_sac.py#L23))

Thanks for this suggestion!
