### ISSUE TITLE
PPO2 using observation space Box and Discrete [question]

### ISSUE THREAD

**Issue by Coronon** [hill-a/stable-baselines#183]
So I'm trying to train an algorithm on a board game.
As observation space I would like to return the current positions of all pieces(Box) and the turn number(Discrete), as the game ends after a maximum of 60 turns. After trying Tuple and Dict space and both returning 'not implemented' I just don't know how to proceed. The only idea I came up with was using a MultiDiscrete with the first 100 fields being the game board(10x10) and the last one the current turn.

Now my question:
Is there any more elegant way of doing this?

**Comment by araffin** [comment]
Hello,

> would like to return the current positions of all pieces(Box) and the turn number(Discrete), as the game ends after a maximum of 60 turns.

I think the easiest solution is to use box for your observation space (concatenate the current positions of all pieces and the turn number). Here, you don't need to transform your turn number to a one-hot vector because you can compare different values (e.g. turn 10 is after turn 9, which after turn 5, ...). If your discrete observation was not comparable (e.g. each int represent an item), then you would have to create a one hot vector.

Also related: #107 #133

**Comment by Coronon** [comment]
Thanks for your very quick reply, but being german I dont understand you 100%.
What would the observation space definition look like? Right now without the turn I have:
`self.observation_space = spaces.Box(-17, 16, (10, 10), dtype=np.int8)`

**Comment by araffin** [comment]
You can flatten everything in one dim, so here you will have a vector of shape (100,) and then you add the turn number, you get a vector of shape (101,).
Note: you can define the limits (low/high) of the space using a numpy array too: https://github.com/openai/gym/blob/master/gym/spaces/box.py#L20

**Comment by Coronon** [comment]
Yes they are ints like 1, 2, 3, 4, 5... up to 16(inclusive) and the same down to -16. OK so Im going to use a multidiscrete then. But when I tried it once I came to the conclusion that I can't set a min, which is 0 by default. So should I just map -16 to like 20 and then -15 --> 21? Sry for all the questions, but I'm completely new to RL.

**Comment by araffin** [comment]
>So should I just map -16 to like 20 and then -15 --> 21?

I'm not sure to understand what you meant...
Anyway, if you want to have only positive ints starting at 0, you can do `pos + 15`, so your observations lies in [[0, 32]] (even though 16 will never appear).

**Comment by Coronon** [comment]
Yeah, id love to have negative ints but I dont know how to define that. Multi discrepte does not offer negative values, does it?

Btw. Thanks for your great help, Im feeling really welcomed by the community!

**Comment by araffin** [comment]
>Yeah, id love to have negative ints but I dont know how to define that. 

Internally, in your environment, you can have negative ints. However, from the algorithm point of view (what you give as input), it does change anything because you are using discrete observations.

>Btw. Thanks for your great help, Im feeling really welcomed by the community!

Your welcome ;)

**Comment by Missourl** [comment]
> You can flatten everything in one dim, so here you will have a vector of shape (100,) and then you add the turn number, you get a vector of shape (101,). Note: you can define the limits (low/high) of the space using a numpy array too: https://github.com/openai/gym/blob/master/gym/spaces/box.py#L20
> 
> EDIT: Why do you have `dtype=np.int8` ? you positions are also discretes ? If so, your multidiscrete solution is the right one ;)

Hello,

Please regarding this idea, how could you code the observation space such that you take 100 different samples from first interval, and 1 sample from second interval? 

Thank you
