### ISSUE TITLE
TypeError when using PPO2 and MultiDiscrete

### ISSUE THREAD

**Issue by nagadomi** [hill-a/stable-baselines#187]
**Describe the bug**

When using PPO2 and MultiDiscrete action space, the following error occurs.

```
  File "/home/ubuntu/.local/lib/python3.5/site-packages/stable_baselines/common/distributions.py", line 200, in proba_distribution_from_latent
    return self.proba_distribution_from_flat(pdparam), pdparam, q_values
  File "/home/ubuntu/.local/lib/python3.5/site-packages/stable_baselines/common/distributions.py", line 195, in proba_distribution_from_flat
    return MultiCategoricalProbabilityDistribution(self.n_vec, flat)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/stable_baselines/common/distributions.py", line 342, in __init__
    self.categoricals = list(map(CategoricalProbabilityDistribution, tf.split(flat, nvec, axis=-1)))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1337, in split
    value=value, size_splits=size_splits, axis=axis, num_split=num, name=name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8148, in split_v
    num_split=num_split, name=name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'size_splits' has DataType uint32 not in list of allowed values: int32, int64
```

**System Info**

gym >= 0.10.9

**Additional context**

The issue is due to OpenAI/gym change. https://github.com/openai/gym/pull/1249
`dtype` of `MultiDiscrete#nvec` has been changed from `np.int32` to `np.uint32`, but the tf function does not seem to allow uint32.

I have fixed the following lines on my local branch.
https://github.com/hill-a/stable-baselines/blob/cb0662ffb1f063e4823034916b12a0a7099f83d4/stable_baselines/common/distributions.py#L479-L480
```
return MultiCategoricalProbabilityDistributionType(ac_space.nvec.astype(np.int32))
```

**Comment by araffin** [comment]
Hello,
Thanks for reporting the issue.
OpenAI had also to fix it here: https://github.com/openai/baselines/commit/ab02fae71d8fa3260d8efe3eae861a4ed01fbd5d

Please open a PR so we can fix that ;) (and don't forget to read the contribution guide)

**Comment by nagadomi** [comment]
My intention is just a bug report.
I do not know the whole codebase, so if the above fix is correct, please merge it freely.

**Comment by josecegra** [comment]
I am trying to run a custom environment with a MultiDiscrete action space in google colab and I have the same problem. I clone the gym and stable-baselines repositories and install them with:

```
%pip uninstall gym
!git clone https://github.com/openai/gym.git 
%cd gym
%pip install -e .

%pip uninstall stable-baselines 
!git clone https://github.com/hill-a/stable-baselines 
%cd stable-baselines
%pip install -e .
```

If I run the following script

`class TestEnv(gym.Env):
  metadata = {'render.modes': ['human']}
  def __init__(self, N=10):
    super(TestEnv, self).__init__()
    self.N = N
    self.x = np.zeros((N,))
    self.current_step = 0
    self.action_space = spaces.MultiDiscrete([N**2])
    self.observation_space = spaces.Box(
        low=0, high=1000, shape=(N,), dtype=np.float16)
  def _next_observation(self):
    obs = self.x
    return obs
  
  def _take_action(self, action):
    pass
  
  def step(self, action):
    self._take_action(action)
    reward = 0
    if action == int(self.N/2):
      reward = 1
    self.current_step += 1
    done = self.current_step >= 1000
    obs = self._next_observation()
    return obs, reward, done, {}
  
  def reset(self):
    self.x = np.zeros((self.N,))
    self.current_step = 0
    return self._next_observation()
  
  def render(self, mode='human', close=False):
    print(self.x)
    
env = DummyVecEnv([lambda: TestEnv(N=100)])
model = PPO2(MlpPolicy, env, verbose=0)
print('Learning')
model.learn(total_timesteps=10000)`

I get the following error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-664e8495dff7> in <module>()
     14 env = DummyVecEnv([lambda: TestEnv(N=100)])
     15 
---> 16 model = PPO2(MlpPolicy, env, verbose=0)
     17 
     18 print('Learning')

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     58           "allowed values: %s" %
     59           (param_name, dtypes.as_dtype(dtype).name,
---> 60            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     61 
     62 

TypeError: Value passed to parameter 'size_splits' has DataType uint32 not in list of allowed values: int32, int64`

Is it possible that this issue has not been completely fixed? Thank you in advance!

**Comment by araffin** [comment]
Could you provide a link to your colab?
and give your gym version/tf version ?

I checked with gym v 0.12.5 and tf v1.8.0 (and stable baselines master version) and it works...

Note: since the fix, the type was changed again in https://github.com/openai/gym/commit/cc75b53590ae6d8359167a7b0acf090fe5e90e95

**Comment by josecegra** [comment]
Problem solved, I installed tensorflow and gym with
```
!pip install tensorflow==1.8.0
!pip install gym==0.12.5
```

and it runs. Thanks for the support and the great work :)
