### ISSUE TITLE
[question] location of the utility functions

### ISSUE THREAD

**Issue by junhyeokahn** [hill-a/stable-baselines#188]
Hello, Thanks for your efforts to maintain this repo!

I have a quick question about the locations of utility functions.

For example, ```linear``` in ```a2c/utils.py``` and ```traj_segment_generator``` in ```trpo_mpi/utils.py``` seem to be more generic utility function and more reasonable to be located in ```common/utils.py```.
Is there any intend you define utility functions in specific algorithm directory?

**Comment by araffin** [comment]
Hello,

That's a good remark. I would say it is defined there for legacy reason. 
For `traj_segment_generator`, it was even worse before, when it was duplicated in the `GAIL` folder.

In the same vein, there are a bunch of functions in `common` that are not used at all or that are duplicated. I think we should do some cleaning at some point. But for now, our focus is more on finishing the refactor for different algorithms (e.g. ACKTR for continuous actions).

**Comment by junhyeokahn** [comment]
Thanks! I am looking forward to see it!
