### ISSUE TITLE
The observation was mistaken for image.

### ISSUE THREAD

**Issue by mymusise** [hill-a/stable-baselines#189]
Hey, guys. `stable-baselines` is a great project, it helps me to build my agent fast. Thanks all for your contribution.

Recently, I got a problem when I was trading my custom environment with DQN:
```
InvalidArgumentError (see above for traceback): Tensor must be 4-D with last dim 1, 3, or 4, not [32,5,1]
	 [[node input_info/observation (defined at /home/mymusise/pro/money/venv/lib/python3.6/site-packages/stable_baselines/deepq/build_graph.py:438)  = ImageSummary[T=DT_FLOAT, bad_color=Tensor<type: uint8 shape: [4] values: 255 0 0...>, max_images=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_info/observation/tag, _arg_deepq/input/Ob_0_1)]]
```

My custom environment like this:
```
class MyEnv(GoalEnv):

    def __init__(self):
        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Box(low=-1, high=1,
                                            shape=(5,1),
                                            dtype=np.float32)
```
I found [here](https://github.com/hill-a/stable-baselines/blob/v2.4.0/stable_baselines/deepq/build_graph.py#L436) may be the problem.
And the input tensor of [`tf.summary.image`](https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/summary/image) must be 4-D.

So, it should be `len(obs_phs[0].shape) == 4` instand of `len(obs_phs[0].shape) == 3`?
And I think it's not a good way to check the observation is an image with checking the shape.

**Comment by araffin** [comment]
Hello,
I think the right definition of your space is `shape=(5,)`.

>So, it should be `len(obs_phs[0].shape) == 4` instand of `len(obs_phs[0].shape) == 3`?

I have to check that. We are refactoring it on the `enhancements` branch. I think `len(obs_ph[0]) == 3` but `len(obs_ph) == 4`.

**Comment by mymusise** [comment]
Thanks for your quick answer!
Yep,  but what if `shape=(5,3)` or any `shape=(, 1/3/4)`.  I think it may have the same problem.

**Comment by hill-a** [comment]
Hey,

Unless you are dealing with images, you shape should be `shape=(5,)`.

This is because the as the code detects whether the input is a vector if if `len(obs_phs[0].shape) == 1`, an image if `len(obs_phs[0].shape) == 3` and will crash otherwise.

If you are dealing with images, you shape should be `shape=(width, height, n_channels)'

for example, atari envs have this shape:
```
In [1]: from stable_baselines.common.cmd_util import make_atari_env
   ...: env = make_atari_env('PongNoFrameskip-v4', num_env=1, seed=0)
   ...: env.observation_space
   ...: 
Out[1]: Box(84, 84, 1)
```

**Comment by mymusise** [comment]
Thanks, guy!
