### ISSUE TITLE
[question] D4PG - mujoco implementation

### ISSUE THREAD

**Issue by Scitator** [hill-a/stable-baselines#191]
Hi,

Thanks for your RL framework, looks very promising. Currently I am interested in implementation of current RL algorithms. So, I wonder have you already done any experiments with mujoco environments? If so, are there any experiment configs available? For cheetah or humanoid, for example.

**Comment by araffin** [comment]
Hello,
We don't have any mujoco licence so we did only experiments using pybullet equivalents (that are similar but different).
You can find hyperparameters in the [rl baselines zoo](https://github.com/araffin/rl-baselines-zoo). If hyperparameters are not present for a given algo-env tuple, then it means we did not try yet or we did not find suitable hyperparams yet.

**Comment by Sohojoe** [comment]
@Scitator I've been reproducing MuJoCo style environments in Unity (see https://github.com/Sohojoe/MarathonEnvsBaselines)- I have them training against both OpenAI.Baselines and Stable.Baselines - I tried to keep as close to the OpenAI.Baselines hyperparams as possible.
