### ISSUE TITLE
[Feature Request] Selective Logging to TensorBoard - mainly image observations

### ISSUE THREAD

**Issue by Kuldr** [hill-a/stable-baselines#192]
Hi,

I am currently finding that long runs are using a lot of disk space and memory in the tensorboard logs.
Being able to selectively log what data I need in tensorboard would be helpful in reducing space used.
My current solution involves commenting out the relevant logging lines in the RL Algorithm code but this solution isn't elegant for others.

**Comment by araffin** [comment]
This high disk usage will be fixed when #185 is merged.
