### ISSUE TITLE
[questions] variable in the function

### ISSUE THREAD

**Issue by junhyeokahn** [hill-a/stable-baselines#195]
Hello,
I have a quick question.
The variable ```new``` in the function ```traj_segment_generator``` in ```trpo_mpi/utils.py``` has not been updated and, thus ```nextvpred``` always returns zero. Is it intended?
I just realized in the original [baseline](https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/ppo1/pposgd_simple.py#L37), ```nextvpred``` is correctly set.

**Comment by araffin** [comment]
Hello,
Thanks for your remark, this looks like a bug.
I'll take a look. @hill-a I think I'll push a fix on the release 2.4.1 branch soon.

**Comment by junhyeokahn** [comment]
Thanks for the reply :)

**Comment by araffin** [comment]
@junhyeokahn the fix is pushed (will be merged with master soon) and you are now credited in the changelog ;)
