### ISSUE TITLE
[feature request] running mean for observation

### ISSUE THREAD

**Issue by junhyeokahn** [hill-a/stable-baselines#204]
Hello,
I appreciate your effort to maintain this awesome repo.

I am wondering if you have a plan to implement updating running mean / std of observation as [this](https://github.com/Breakend/baselines/blob/50ffe01d254221db75cdb5c2ba0ab51a6da06b0a/baselines/ppo1/pposgd_simple.py#L174)

**Comment by araffin** [comment]
Hello,

Please [Read the documentation](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecnormalize) before posting an issue.

**Comment by junhyeokahn** [comment]
Sorry for hasty question and thanks!
