### ISSUE TITLE
[question] ram version of gym atari

### ISSUE THREAD

**Issue by Charelvanhoof** [hill-a/stable-baselines#205]
Hi Antonin,

Need a pointer to run something as simple as

```
env_id = 'MsPacman-ramNoFrameskip-v0' 
env = make_atari_env(env_id, num_env=4, seed=0)
env = VecFrameStack(env, n_stack=4)
model = PPO2(MlpLnLstmPolicy, env, verbose=0)
model.learn(total_timesteps=training_length)

```
but that did not work
I probably need to unpack the make_atari_env, so when I look under the hood I see

```
env = gym.make(env_id)
env = NoopResetEnv(env, noop_max=30)
env = MaxAndSkipEnv(env, skip=4)
env = wrap_deepmind(env, episode_life=True, clip_rewards=True, frame_stack=True)
env = DummyVecEnv([lambda: env])
```
but have not yet been able to get it to work, any pointers?
Thanks

**Comment by araffin** [comment]
Hello,

I recommend you to read [Atari preprocessing](https://danieltakeshi.github.io/2016/11/25/frame-skipping-and-preprocessing-for-deep-q-networks-on-atari-2600-games/).
Also, Atari Ram is quite different as the observation is not an image anymore (see [obs definition](https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py#L51), it is a vector of size 128) so you cannot use completely the same pre-processing.
