### ISSUE TITLE
[feature request] Dict spaces in VecEnv

### ISSUE THREAD

**Issue by AdamGleave** [hill-a/stable-baselines#208]
The `VecEnv` implementations, `DummyVecEnv` and `SubprocVecEnv`, currently only support array-like spaces (e.g. `Box` or `MultiDiscrete`). In particular, they do not support `Dict` spaces. This is useful for environments with multiple distinct types of observations, e.g. both image and raw observations, as well as for multi-agent environments (key-value pair for each agent). 

Although further work will be required to add support for `Dict` spaces to the RL algorithms themselves, it seems worth adding support to `VecEnv` before this as `VecEnv` may also be used by end-users with their own RL algorithms.

There is also a case for adding support for `Tuple` spaces, although I consider this lower priority since a `Dict` can handle any use case a `Tuple` can. If there is interest in adding support for `Tuple` I would be happy to work on this though.

**Comment by araffin** [comment]
closed by #207
