### ISSUE TITLE
[Bug] Unexpected Argument when using A2C predict function 

### ISSUE THREAD

**Issue by Kuldr** [hill-a/stable-baselines#209]
**Describe the bug**
```
When using a train model in to predict it throws an error with the following stack trace
  File "/.../stable_baselines/common/base_class.py", line 367, in predict
    actions, _, states, _ = self.step(observation, state, mask, deterministic=deterministic)
TypeError: step() got an unexpected keyword argument 'deterministic'
```

**Code example**
This happens when calling model.predict (only tried with an A2C model)

**Temporary Fix**
I have managed to fix this by changing line 367 in common/base_class.py
from `actions, _, states, _ = self.step(observation, state, mask, deterministic=deterministic)`
to `actions, _, states, _ = self.step(observation, state, mask)`

**Comment by hill-a** [comment]
Hey,

This seems odd, are you using a custom Policy class?

As the step function in the base policy for A2C ([`ActorCriticPolicy(BasePolicy)`](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L214)) does have the `deterministic` keyword argument

**Comment by araffin** [comment]
Hello,
as @hill-a pointed out, it seems that some information are missing to help you, please fill the template form completely (especially minimal code to reproduce).

Trying to reproduce your problem, the following code runs:

```python
from stable_baselines import A2C

model = A2C("MlpPolicy", "Pendulum-v0")
env = model.get_env()
obs = env.reset()
model.predict(obs)
model.predict(obs, deterministic=True)
```

In fact, this feature is tested several times by the CI (for instance [here](https://github.com/hill-a/stable-baselines/blob/master/tests/test_deterministic.py#L40)), so it seems you are doing something custom, right?

**Comment by Kuldr** [comment]
I am using a custom policy class, which is missing the `deterministic` Keyword argument as @hill-a mentioned.

By following the updated docs adding the argument to the step function in my custom policy has solved the issue.

Thanks for your help on this
