### ISSUE TITLE
PPO2 value function clipping seems to be flawed

### ISSUE THREAD

**Issue by erniejunior** [hill-a/stable-baselines#216]
The PPO2 implementation clips the value function, as documented. It does so with the same clip range parameter as the probability ratios of the policies. For the value function, the difference between old and new predicted return is clipped, not a ratio. This difference depends on the reward scaling of the environment that is used.

I think we should at least introduce a separate clipping parameter for the value function.

Another option would be to clip the ratio between the old and new reward prediction. This fundamentally changes the algorithm but might be less sensitive to reward scaling.

**Comment by araffin** [comment]
Nice catch. I definitely agree for a separate argument for clipping the value function.
The main problem with that technique, is that is not documented anywhere.

>Another option would be to clip the ratio between the old and new reward prediction.

This should be tested, yes.

**Comment by araffin** [comment]
After some, it seems very important to have the possibility to deactivate the clipping on the value function, or it have a different value.
I'll do a small PR in the coming days ;)

**Comment by araffin** [comment]
Related: http://gradientscience.org/policy_gradients_pt1/
