### ISSUE TITLE
[Question] excessively large volume of tensorboard event file - PPO2

### ISSUE THREAD

**Issue by jucho2725** [hill-a/stable-baselines#221]
**Describe the question**

Hi, I have a question regarding Tensorboard event file. To start, I'm quite new to RL and Tensorflow, so please bear with me. I'm making an agent operating on CarRacing-V0, and since I have experimented this, i haven't got any big issue about using Tensorboard. I changed the model from PPO1 to PPO2, and the reason being is that parameters in PPO1 was not clear enough for me to adapt. 

After I run the code, I got the error message like below and could find that the volume of the event file was over 17GB.  It was only 5k steps operated before stopped. For comparing with others, other event files are lower than 100MB, after the learning of 300k steps was finished(PPO1).

**Code example**

```
model = PPO2(policy=CnnPolicy, env=env, n_steps=256, nminibatches=128,
                 lam=0.95, gamma=0.997, noptepochs=8, ent_coef=0.01,
                 learning_rate=5e-4, cliprange= 0.2, verbose=0, tensorboard_log='graph/')

model.learn(total_timesteps=300000, callback=callback, tb_log_name="190304")
```

`OSError: [WinError 8] Not enough storage is available to process this command`
 

As far as I checked the code, I was not able to figure out what makes this happened. Could anyone help this situation?

**System Info**
 * Locally installed version "2.4.1a" using pip install -e. in Conda Environment
 * NO GPU
 * Python 3.6.8
 * Tensorflow version 1.10.0
 * Versions of any other relevant libraries N/A

Thanks in advance.

Best regards
Jin Uk, Cho.
SungKyunKwan University

**Comment by araffin** [comment]
Hello, 
Please fill the issue template completely.
I also recommend you to upgrade your stable-baselines version. (should be fixed since #185 )

**Comment by jucho2725** [comment]
Thanks for quick response. 

Hope I edited it correctly.
I will check the version first and describe any changes.
Thank you.

**Comment by araffin** [comment]
Ok, then please upgrade your version (current is 2.4.1 (without the alpha)), it will solve your problem.

To update:
- if installed locally, `git pull` in the stable-baselines folder
- with pip: `pip install stable-baselines --upgrade`

**Comment by jucho2725** [comment]
Updated to the new version
- Stable-baseline 2.4.1
- Tensorflow 1.12.0

Tensorboard event file was much smaller than the previous one(17GB -> 500MB).
Thanks for your answer, and contribution.

**Comment by araffin** [comment]
Problem solved then.
