### ISSUE TITLE
[Question] ppo2 implementation details

### ISSUE THREAD

**Issue by agrib** [hill-a/stable-baselines#222]
When using more than 1 env , does every worker have its own act policy or they take from one central act policy?
Why do we have different train and act model and collecting critic value again through train model ? 
Can it be done through act model only?

**Comment by araffin** [comment]
Hello,

>does every worker have its own act policy or they take from one central act policy?

The answer is in the [Runner](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L414): there is one central policy.

> Why do we have different train and act model and collecting critic value again through train model ?

The `act_model` is only used during testing. In fact, it seems that `self.value` is unused.
For the critic, it is the value from the `train_model` that is used (see [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L139))
