### ISSUE TITLE
ddpg learn eval/return and eval/Q should be mean?

### ISSUE THREAD

**Issue by keshaviyengar** [hill-a/stable-baselines#225]
In stable-baselines/ddpg/ddpg.py line 916 and 918 should the eval/return and eval/Q be np.mean to make scalar?
`# Evaluation statistics.`
`if self.eval_env is not None:`
`                        combined_stats['eval/return'] = eval_episode_rewards`
`                        combined_stats['eval/return_history'] = np.mean(eval_episode_rewards_history)`
`                        combined_stats['eval/Q'] = eval_qs`
`                        combined_stats['eval/episodes'] = len(eval_episode_rewards)`

**Comment by araffin** [comment]
Hello,
Could you elaborate a bit more?

**Comment by keshaviyengar** [comment]
- `eval_qs` is a numpy array from this [line](https://github.com/hill-a/stable-baselines/blob/a139bb77866f094388b4f7ce096a6ad3695c9b7a/stable_baselines/ddpg/ddpg.py#L886) and needs to be scalar to pass the `as_scalar` check [here](https://github.com/hill-a/stable-baselines/blob/a139bb77866f094388b4f7ce096a6ad3695c9b7a/stable_baselines/ddpg/ddpg.py#L921)
- same as `eval_episode_rewards`. It is a numpy array [here](https://github.com/hill-a/stable-baselines/blob/a139bb77866f094388b4f7ce096a6ad3695c9b7a/stable_baselines/ddpg/ddpg.py#L890)
- If the `eval_env` is None then there is no issues
- When `eval_env` is not None, the `as_scalar` function is not passed.

**Comment by keshaviyengar** [comment]
I have forked stable-baselines and made the changes [here](https://github.com/keshaviyengar/stable-baselines)

**Comment by araffin** [comment]
Ah ok, this is a bug then.
Please fill the issue template next time ;)

Code to reproduce the error:

```python
import gym
from stable_baselines import DDPG

eval_env = gym.make("Pendulum-v0")
model = DDPG("MlpPolicy", "Pendulum-v0", eval_env=eval_env, verbose=1)
model.learn(50000)
```

Feel free to submit a PR ;) (and don't forget to look at the CONTRIBUTING.md guide before)

**Comment by keshaviyengar** [comment]
Ah sorry just saw that issue template, I'll take a look at CONTRIBUTING.md and submit one correctly.
