### ISSUE TITLE
[Feature Proposal] Automatic Selection of Network Type

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#227]
For beginners, selecting the right policy depending on the environment requires a bit of knowledge (mostly looking at the code of the environment) and this could be simplified by detecting automatically if a CNN or a Mlp policy is needed.
In practice, this would translate by passing a `"auto"` value to the model.

Currently:
```python
from stable_baselines import PPO2

# Images -> CnnPolicy
model = PPO2("CnnPolicy", "BreakoutNoFrameskip-v4")

# Vector obs -> MlpPolicy
model = PPO2("MlpPolicy", "CartPole-v1")
```

Proposed feature:
```python
from stable_baselines import PPO2
# auto for both cases
model = PPO2("auto", "BreakoutNoFrameskip-v4")
model = PPO2("auto", "CartPole-v1")
```

Thing I'm not sure: what string to use? "auto", "autoPolicy", "autodetect"?

**Comment by hill-a** [comment]
Hey,

I like this idea, it will even prevent more advanced users when they mix up they environment observation space types (such as my self sometimes 😄), however I hate the idea of using strings like "auto" as keywords, as there are already good pythonic way of having default behaviour when no value (`None`) is given.

I would perefere to make it a code breaking 3.0 change, and pass policy to a keyword argument with `None` as default.

If you want to avoid breaking legacy code, we can either do this:
```python
def __init__(self, policy=None, env=None, *args, **kwargs):
    if env is None:
        raise ValueError("env must be defined")
```
or like numpy [arange](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html) and do this
```python
def __init__(self, arg1, args2=None, *args, **kwargs):
    if args2 is None:
        policy = None
        env = arg1
    else:
        policy = arg1
        env = arg2
```

**Comment by araffin** [comment]
>I would prefer to make it a code breaking 3.0 change, and pass policy to a keyword argument with None as default.

I see, I really like the second solution. But I don't understand why you say this is a breaking change as previous code will still work.

If I understand, with the second solution, you could do:
```
model = PPO2("CartPole-v1")
```
so cool =)! (next step is to infer the env automatically :p )

**Comment by hill-a** [comment]
I was just thinking how we went from this:
```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines.ppo2 import PPO2

env = DummyVecEnv([lambda: gym.make("CartPole-v1)])
model = PPO2(MlpPolicy, env).learn(10000)
```

to now in 2.4.1 + with the proposed change:
```python
from stable_baselines import PPO2

model = PPO2("CartPole-v1").learn(10000)
```
I'm 98% sure we can't reduce this anymore 😄 

On a more serious note, the second solution should be done like this:
```python
def __init__(self, *args, **kwargs):
    if not args:
        raise ValueError("Must at least define the environment")
    elif len(args) == 1:
        env = args[0]
        if not (hasattr(env, "step") and hasattr(env, "reset")):
             raise ValueError("If only one positional argument is given, it must be an gym.Env")
        policy = None
    elif len(args) == 2:
        env = args[1]
        if not (hasattr(env, "step") and hasattr(env, "reset")):
            raise ValueError("If only two positionals arguments are given, the second must be an gym.Env")
        policy = args[0]
        if not isinstance(policy, BasePolicy):
            raise ValueError("If only two positionals arguments are given, the first must be an {}".format(BasePolicy.__name__))
    else:
        raise ValueError("Only the Environement and the policy can be positional argument, (got {} positional arguments)".format(len(args)))
    
    ...
```
with type checking and all that, luckly for us I think this can be done in the base classe, and passed through with `*args` from the model `__init__` functions.

**Comment by araffin** [comment]
>If you prefer the second solution however, it should be done like this:

I feel like this can be simplified. I would also rather do something like:

```python
def __init__(self, policy, env=None, **kwargs):
    if env is not None:
        assert isinstance(env, gym.Env), "the 'env' argument must be a gym.Env"
        # Check on the policy are as in previous versions
    else:
        assert isinstance(policy, gym.Env), "When the 'env' argument not is given, the first argument must be a gym.Env"
        env = policy
        policy = None
    
    if policy is None:
        # TODO: autodetect
```

**Comment by hill-a** [comment]
Good remark, I need to remind my self "Easier to ask for forgiveness than permission" sometimes...

Looks good, just need to definie the minimum shape for `nature_cnn` and this should be almost done honestly.

**Comment by hill-a** [comment]
Playing around with the autodetect feature:

For the policy autodetect, `nature_cnn` requires a 36x36 image minimum. Should we autodetect on the low value, high values, and number of channels (`observation_space.shape[2]`) of the `observation_space`? or just detect if `len(observation_space.shape) == 3 and all(observation_space.shape[:2] >= 36)`?

**Comment by araffin** [comment]
I would go for the second solution (and add some info in the verbose mode).
Anyway, I think we need a check in all cases (or add a note in the documentation) about the minimal size for an image.

**Comment by hill-a** [comment]
> I would go for the second solution (and add some info in the verbose mode).

Alright then.

btw, the solution 
```python
def __init__(self, policy, env=None, **kwargs):
    if env is not None:
        assert isinstance(env, gym.Env), "the 'env' argument must be a gym.Env"
        # Check on the policy are as in previous versions
    else:
        assert isinstance(policy, gym.Env), "When the 'env' argument not is given, the first argument must be a gym.Env"
        env = policy
        policy = None
    
    if policy is None:
        # TODO: autodetect
```
does not work, as env is set to `None` when loading a model by default :/

**Comment by araffin** [comment]
>does not work, as env is set to None when loading a model by default :/

I see... a simple workaround would be to allow passing nothing, but to check when `learn()` is called.

**Comment by araffin** [comment]
After thinking again about that feature, this could be nice to have for the user but would obfuscate the code, the best way would be to have function overload... So I'm removing it from the roadmap for now.
