### ISSUE TITLE
Custom Environment with Discrete (Binary) Action Space Always Choosing 0

### ISSUE THREAD

**Issue by bglick13** [hill-a/stable-baselines#229]
**Describe the bug**
I am trying to implement a relatively simple custom environment with a Discrete (Binary) action space. However, as soon as I start the learning process I get the following error coming from the call to 

`tf.clip_by_global_norm(grads, self.max_grad_norm)`

in `self.setup_model()`

`InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[node loss/VerifyFinite/CheckNumerics (defined at c:\users\ben\documents\stable-baselines\stable_baselines\ppo2\ppo2.py:168) ]]
`

If I set `max_grad_norm=None`, then the learning process runs, but the loss immediately goes to NaN. For the record, this is the case for several RL algorithms (PP02, ACER, ACKTR) using an MlpLstmPolicy.

Could this be a problem with how I've defined by environment, or is this a known issue?

I'd appreciate any guidance.

UPDATE: Out of curiosity, I switched the action space to box, and the actions are nan at the start of learning

**Comment by Jyosua** [comment]
@bglick13 did you find a solution for this? I'm currently seeing the same thing with a custom environment and discrete action space.

**Comment by bglick13** [comment]
Hey @Jyosua, I'm not sure I ever did. I think I ended up using a different library. Sorry!

**Comment by araffin** [comment]
Related #358
