### ISSUE TITLE
DDPG saved model

### ISSUE THREAD

**Issue by y428lin** [hill-a/stable-baselines#232]
Hello,

The DDPG model.save might save wrong parameters. Below is my code:

model = DDPG(MlpPolicy, env, gamma=0.999, actor_lr=0.0001, critic_lr=0.0001, normalize_observations=True, memory_limit=int(1e6), batch_size=64, verbose=0, param_noise=None, action_noise=action_noise, tensorboard_log="/home/yuanlin/tensorboard_outputs/")

model.learn(total_timesteps=10000)
model.save("model_acc_action_noise")

Then I tried two cases. For the first case, I did not load the saved model and directly proceed to model. predict.

For the second case, I loaded the saved model and then used model.predict:
del model # remove to demonstrate saving and loading
model = DDPG.load("model_acc_action_noise")

The two cases gave me different results. What do you think?

Thank you.

**Comment by araffin** [comment]
Duplicated issue: #228 
Will be fixed in: #230
