### ISSUE TITLE
Windows: Pip install problem

### ISSUE THREAD

**Issue by Juphex** [hill-a/stable-baselines#233]
If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.  

**Describe the bug**
Hey,

I am just reading the stable-baselines docs and got problems installing it on Windows :(

What do you mean by, how does the command look like?:

**Code example**

> 2. Clone Stable-Baselines Github repo and replace this line gym[atari,classic_control]>=0.10.9 by this one
> gym[classic_control]>=0.10.9
> 3. Install Stable-Baselines from source, inside the folder, run pip install -e .

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...) -
 * GPU models and configuration -
 * Python version 3.7.1
 * Tensorflow version -
 * Versions of any other relevant libraries -

**Comment by araffin** [comment]
It seems we forgot to mention this was in [setup.py](https://github.com/hill-a/stable-baselines/blob/master/setup.py#L102)...
