### ISSUE TITLE
[Question] DDPG return normalization

### ISSUE THREAD

**Issue by y428lin** [hill-a/stable-baselines#234]
Hi,

I am trying to find a paper or document about normalizing the return for DDPG. I am not sure how the return normalization is done (formulas), where in the DDPG algorithm the normalized return is used, and how it potentially impacts the DDPG training performance. Would you please send any links to any helpful information if possible?

Thanks a lot.

**Comment by y428lin** [comment]
Hello,

It seems like pop art could be a good method for return normalization.

Previously, there was a bug on pop art, issue #101 . Has this been fixed in stable baselines?

I ran training using pop art, and it gave the following error:
in _setup_popart
    assert len(out_vars) == 2
AssertionError

Thank you.

**Comment by araffin** [comment]
> Has this been fixed in stable baselines?

Hello,
this will be fixed in #262 

> Would you please send any links to any helpful information if possible?

For reward normalization, I recommend you to read:
- https://github.com/openai/baselines/issues/629
- https://github.com/openai/baselines/issues/538
- http://joschu.net/docs/nuts-and-bolts.pdf

For that
