### ISSUE TITLE
[question] Episodic Rewards in A2C vs. PPO2 

### ISSUE THREAD

**Issue by rasoolfa** [hill-a/stable-baselines#235]
Hi,

Is there any reason that two different functions are used to report epsidoc rewards in [A2C](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/a2c/a2c.py#L234) and [PPO](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L339)? can 'episode_reward' be used in PPO too or "ep_rewmean" in A2C?

And to report  results, can either one be used?

Thanks

**Comment by araffin** [comment]
Hello,

One is used only to when tensorboard logging is activated ('episode reward'), the other one requires a Monitor wrapper (cf examples). The main difference is that "ep_rewmean" will always report the original reward even when normalization is applied but 'episode reward' does not require any extra wrapping.

>can 'episode_reward' be used in PPO too or "ep_rewmean" in A2C?

"ep_rewmean" will be added in #206 for A2C and "episode_reward" is already present in PPO2.


>And to report results, can either one be used?

This is only training/logging data and should not be used to report results (related to  #199 ).

**Comment by rasoolfa** [comment]
Thanks a lot. 

Not really, showing how a method progresses during training is valid thing to do in RL especially for metric like sample efficiency.
https://arxiv.org/pdf/1709.06009.pdf
> This is only training/logging data and should not be used to report results (related to #199 ).
