### ISSUE TITLE
Mean Episode Reward and Length showing NaN in PPO2 training.

### ISSUE THREAD

**Issue by batu** [hill-a/stable-baselines#24]
Hello,

First of all I would like to thank you for this is incredibly polished package. Seeing good documentation just makes me feel happy.

While training PPO2 on Pong-ram-v0 (and several other envs) I realized that the episode reward doesn't print correctly to the console.  It is seen as follows:
![screenshot from 2018-09-18 12-15-51](https://user-images.githubusercontent.com/6670976/45710834-a1b18e00-bb3c-11e8-8a3a-954d383c7ef2.png)

I tried looking into it but couldn't figure out why just yet. If you give me some pointers I would like to work on fixing it.

I am using python 3.6.5 on an Ubuntu 16.04.

**Comment by batu** [comment]
Thank you! This is definitely good enough to get me started. 

I will look into it when I have the time, should be within a weeks time.

**Comment by batu** [comment]
I managed to get the average reward over multiple environments, however I am having some difficulty getting the episode length.

From what I can tell, there is no easy way of getting the length of every episode? 

I worked on taking the difference between "true"s in the masks, however, for that to work I need to know what the maximum episode length (which I assume isn't available?) to handle the overflows which I think is different than n (The number of steps between the last "true" in mask[i] and the first "true" in mask[i+1] is another episode.) My abomination of an implementations currently seems to work if the length of the max_episode is less than 2 * n_steps. 

That being said, I am almost sure I am over-complicating things and there is just a nice variable for episode length, somewhere.

**Comment by araffin** [comment]
Looking at the code again, I found that there was an `EpisodeStats` class in a2c utils (https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/a2c/utils.py#L428) that apparently can do the job.
It is used in ACER only. @hill-a it seems that this class can be reused, no?

Otherwise, I recommend you taking a look at the new vec env monitor (only in openai baselines for now: https://github.com/openai/baselines/blob/master/baselines/common/vec_env/vec_monitor.py)

@batu looking at your code, using the max episode length won't work as some environments does not have limits.

**Comment by araffin** [comment]
@batu How are you doing?

**Comment by batu** [comment]
I have a semi-working implementation, however, it is definitely not clean enough. When my current work hump passes I will go back to it and when I stop making silly mistakes submit a PR

**Comment by rachlee93** [comment]
Hi, 

maybe I misunderstand the resolution of this, but for the life of me I still can't get the average episode length for an A2C model. Can someone clarify how I can see eplenmean? Or is it only for PPO2 models?

**Comment by araffin** [comment]
if you read the first answer, you need to use a Monitor wrapper, this will done automatically if you use the rl zoo.

**Comment by noyan72** [comment]
@hill-a 
How is the episode-reward  calculated in tenorsboard?  Is that calculated as same as you tell (you would just need to create a list of the episode rewards, accumulate said rewards, and return average rewards + average episode length)?
