### ISSUE TITLE
Training progress collapses after reloading (in colab)

### ISSUE THREAD

**Issue by Christoph-Schuhmann** [hill-a/stable-baselines#243]
I am trying to train a DQN agent on colab for Atari Breakout.

After 12 hours the kernel shuts down and when I reload it, the performance of the save model remains during inference, but quickly collapses when I continue to train it.

I have encountered the same issue with my own implementation of DQN Breakout and I believe that the problem is somehow related to not saving and reloading the opimizer parameters of Adam properly, ... but I haven't found a solution yet. ... Normally model. save should also save the optimizer weights and it should be no problem to continue the training ... But somehow I have this problem with stable baselines as well as with my own imlementation ... Could it be a bug keras? ... ???

**Comment by araffin** [comment]
Hello,

I see possible problems:
- I'm afraid we do not save the target network parameters properly (in that case, that is a bug)
- there is also the adam state as you pointed out, but a way to check that is to replace Adam with SGD, or to call train multiple times without re-loading the model
- I don't remember if the exploration status (when using epsilon greedy exploration) is saved...

**Comment by araffin** [comment]
Related #301

**Comment by araffin** [comment]
Fixed in SB3: https://github.com/DLR-RM/stable-baselines3/issues/435
