### ISSUE TITLE
[question] how to visualise nn hidden unit?

### ISSUE THREAD

**Issue by HDClark94** [hill-a/stable-baselines#247]
Hi,

Is there access through either the tensorboard support or calling common.policies classes the hidden units of the various neural network implementations?

Thanks

**Comment by araffin** [comment]
Hello,
What do you mean exactly by "visualizing"?
If you want to access the weights of the policy, I would recommend you to take a look at that issue: #223

**Comment by HDClark94** [comment]
Sorry for being vague, I'll try to explain a little more

From the example ACER code:

```
import gym

from stable_baselines.common.policies import MlpPolicy, MlpLstmPolicy, MlpLnLstmPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines import ACER

# multiprocess environment
n_cpu = 4
env = SubprocVecEnv([lambda: gym.make('CartPole-v1') for i in range(n_cpu)])

model = ACER(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
model.save("acer_cartpole")

del model # remove to demonstrate saving and loading

model = ACER.load("acer_cartpole")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

I'd like to store the activations from all hidden units in the neural network layers at each timestep in the ACER class so I can plot the activation after learning.

**Comment by HDClark94** [comment]
Hi, I'm a little confused what line of code you were referring to in your response to the question you referred to me. line 515 doesn't show weights, I guess the link is old relative to when SAC was updated.

**Comment by araffin** [comment]
>Hi, I'm a little confused what line of code you were referring to in your response to the question you referred to me. line 515 doesn't show weights, I guess the link is old relative to when SAC was updated.

Yes, your are right, I updated my link.

>I'd like to store the activations from all hidden units in the neural network layers at each timestep in the ACER class so I can plot the activation after learning.

It does not seem trivial what you want to do. You would need a custom version of stable baselines, where each activation has a name that you can retrieve with tensorboard or something else.

**Comment by HDClark94** [comment]
understood, thank you. I do like a challenge!
