### ISSUE TITLE
Step action gives all nan

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#257]
Given:
self.action_space = gym.spaces.Box(-1., 1., shape=(len(self.src.asset_names) + 1,), dtype=np.float32)
self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=((len(self.src.asset_names) + 1) * window_length * history.shape[-1],), dtype=np.float32)

With some observation spaces I get all action nan when stepping the env.
What could be the problem?

**Comment by araffin** [comment]
Hello @hn2 ,

Here you are again... without a filled issue template (especially minimal code to reproduce).

We already invested some time helping you in #239 and #242 (#246), where again lots of information were missing.
It seems again related to your gym env and not to stable baselines, so as stated by @hill-a , we do not do tech support.

Unless you can have a minimal code to reproduce that error and that may show a bug from stable_baselines and not your code, I will close this issue.

**Comment by hn2** [comment]
I am not sure where the bug is since sometimes it works (when tested with action and observation spaces have only 7 assets), however with 89 assets it doesn't (action always return all nan).

**Comment by hn2** [comment]
Can I send you the complete code privately?

**Comment by hill-a** [comment]
as @araffin said, issue template was not used. We cannot confirm this is a stable baselines issues.

There is no need to send your code, we do not do tech support.

To anwser your question of what it could be, try and use a normalisation wrapper to your environment (https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecnormalize), you may have some values that are exploding the gradient of the model. Or make sure your environment is not sending bad data to the model. Although NaNs are a typical issue in Neural networks:
 * https://stats.stackexchange.com/questions/258610/machine-learning-dealing-with-nan-values
 * https://stackoverflow.com/questions/33962226/common-causes-of-nans-during-training
 * https://www.quora.com/Why-do-l-get-NaN-values-when-l-train-my-neural-network-with-a-rectified-linear-unit

Locking conversation.
