### ISSUE TITLE
record_expert.py multie env and LSTM support [feature request]

### ISSUE THREAD

**Issue by XMaster96** [hill-a/stable-baselines#260]
I have realized that record_expert.py has no support for multiple envs and don't reset the hidden state when using an LSTM model (mask). When Training an LSTM model with multiple envs you also need the same number of envs for predictions. The easiest solution is to just use multiple envs and only use the data from the first one. I have already implemented this for myself, and could create a pull request at any time.

**Comment by araffin** [comment]
>I have realized that record_expert.py has no support for multiple envs and don't reset the hidden state when using an LSTM model (mask). 

yes, that's true, the script was only tested to handle feedforward policies.

>When Training an LSTM model with multiple envs you also need the same number of envs for predictions. 

I think we would be interested with a PR that adds support for the LSTM in `record_expert` and `pretrain`. For handling multiple envs, I'm not sure, it does not seem to be a trivial change.
Btw, where do you want to handle multiple envs? In `record_expert` and in `pretrain` or only in `pretrain()`?

Be sure to check `CONTRIBUTING.md` before ;)
