### ISSUE TITLE
PPO2 LSTM state update to initial_state after done

### ISSUE THREAD

**Issue by eastskykang** [hill-a/stable-baselines#263]
I am a little bit confused about the internal state of the LSTM. 

It seems initial_state is only used at the very beginning. However, shouldn't the internal state be updated to initial state when the mask = 1? (after done)

#161 suggest it should be updated like 

```
state = mask * initial_state + (1 - mask) * state
```

**Comment by XMaster96** [comment]
`Initial_state` returns a zero array for more than one env (if you use multiple envs). with `(1 - mask) * state` you multiplying `0` with the `state` of a single env to reset it back to zero. This happens without affecting the states of other evs.
