### ISSUE TITLE
Atari environments not training

### ISSUE THREAD

**Issue by skosch** [hill-a/stable-baselines#265]
I am trying to train Atari models using the [Colab notebook](https://colab.research.google.com/drive/14NwwEHwN4hdNgGzzySjxQhEVDff-zr7O) linked to in #43. The code is essentially identical to that in the official stable-baselines docs. I haven't touched the code at all.

The agent does not seem to train. I've tried Breakout as well as Pong, I've tried ACER as well as PPO2, I've tried training for a long time. Nothing seems to work. E.g. for Pong, `ep_reward` (or equivalent) stays consistently at about -20.9 :slightly_frowning_face: 

To verify that it really isn't working, I render some frames using
```python
import matplotlib.pyplot as plt
obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    plt.imshow(env.render(mode='rgb_array'))
    plt.grid(None)
    plt.show()
```
which confirms that the "trained" agent is behaving randomly.

Am I missing something? Have recent changes to the project and/or TF broken the example code? Is the notebook working for others?

**Comment by araffin** [comment]
Hello,

>The agent does not seem to train.

How long did you train it? And what is your setup (please fill the issue template ;))

Anyway, I would recommend you to use the [rl baselines zoo](https://github.com/araffin/rl-baselines-zoo) which makes it easier to train and test agents.
The code contains tested hyperparameters and the best practices for using stable-baselines ;)

Note: I'm currently running the notebook too to check ;)

**Comment by skosch** [comment]
Thanks so much Antonin! I'm trying out the zoo notebook right now.

**Comment by araffin** [comment]
The only known tuple of algorithm-env where we are aware there may be an issue is ACER on Breakout (see #103 ). However, it works for all other tested Atari games.

**Comment by araffin** [comment]
So, both with the colab notebook and rl zoo, it seems that A2C is training fine on Breakout...

current state of the colab notebook:
```
---------------------------------
| ep_len_mean        | 323      |
| ep_reward_mean     | 5.94     |
| explained_variance | 0.828    |
| fps                | 421      |
| nupdates           | 32800    |
| policy_entropy     | 1.27     |
| total_timesteps    | 2656800  |
| value_loss         | 0.0304   |
---------------------------------
```

The `ep_reward_mean` will be around 50 after 5e6 timesteps, and above 200 after 1e7 steps.

**Comment by skosch** [comment]
Thanks again. Perhaps I'm really not training long enough then – is 1e6 not enough to get at least *some* results on Pong? Are there some reference values for minimum timesteps?

**Comment by araffin** [comment]
> is 1e6 not enough to get at least some results on Pong?

Most of the time not.

>Are there some reference values for minimum timesteps?

at least 3e6 timesteps I would say.

**Comment by skosch** [comment]
I see. Sorry to bother you then – thanks for this wonderful framework and for your quick responses!
