### ISSUE TITLE
Expose self.sess for GAIL

### ISSUE THREAD

**Issue by kantneel** [hill-a/stable-baselines#267]
Unlike all of the other models, the GAIL class does not expose its attribute `self.sess`. Instead, one has to reach into the TRPO attribute and reference `self.trpo.sess`. This leads to displeasing code like:
```python 
if isinstance(model, GAIL):
    model.trpo.sess.close()
else:
    model.sess.close()
```
I propose we expose the attribute with the code below, similar to [this line](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/gail/model.py#L52)
```python
# In the GAIL constructor
self.sess = self.trpo.sess
```

**Comment by araffin** [comment]
Hi,
This is a good remark, but I think we should go further and use magic methods (`__get_attr__` and `__set_attr__`) to make `GAIL` just a wrapper around trpo.
For instance, that would allow to avoid overwritting `get_env()` and `set_env()`.

Don't hesitate to ask if what I wrote is a little too obscure ;)

**Comment by kantneel** [comment]
I agree. This suggestion is both more elegant and more comprehensive.
