### ISSUE TITLE
“async” is a reserved word in Python 3.7 and greater

### ISSUE THREAD

**Issue by cclauss** [hill-a/stable-baselines#27]
Using __async__ as a function parameter is a syntax error in Python >= 3.7.  Other modules like PyTouch and Cuda have shifted to using __non_blocking__ instead of __async__.

flake8 testing of https://github.com/hill-a/stable-baselines on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./stable_baselines/acktr/acktr_cont.py:83:68: E999 SyntaxError: invalid syntax
                               epsilon=1e-2, stats_decay=0.99, async=1, cold_iter=1,
                                                                   ^
./stable_baselines/acktr/value_functions.py:39:40: E999 SyntaxError: invalid syntax
                                   async=1, kfac_update=2, cold_iter=50,
                                       ^
./stable_baselines/acktr/acktr_disc.py:174:87: E999 SyntaxError: invalid syntax
                                                                stats_decay=0.99, async=1, cold_iter=10,
                                                                                      ^
./stable_baselines/acktr/kfac.py:15:74: E999 SyntaxError: invalid syntax
                 full_stats_init=False, cold_iter=100, cold_lr=None, async=False, async_stats=False, epsilon=1e-2,
                                                                         ^
4     E999 SyntaxError: invalid syntax
4
```

**Comment by araffin** [comment]
Hi,
Yes it is a known issue (see the roadmap in the _projects_).
Feel free to submit a PR (I would recommend renaming it `use_async`).

**Comment by cclauss** [comment]
__async__ in Python is now synonymous with asyncio.  My sense is that __use_async__ would be inappropriate unless it really means use asyncio.

**Comment by araffin** [comment]
@hill-a what is your opinion on that?

**Comment by cclauss** [comment]
__async___ was used to solve this upstream https://github.com/openai/baselines/pull/542

**Comment by geeksambhu** [comment]
Can I look into this issue? What are we replacing `async` with: `async_` or `non_blocking`?

**Comment by hill-a** [comment]
`async_` can work, but considering most of the issues are from ACKTR, the `async` means asynchronous eigen decomposition, might as well call it `async_eigen_decomp`.

**Comment by araffin** [comment]
+1 for `async_eigen_decomp` ;)

**Comment by araffin** [comment]
@geeksambhu do you still plan to submit a PR in order to solve this issue?

**Comment by araffin** [comment]
@geeksambhu Unless you already started, I plan to fix that issue tomorrow ;).
