### ISSUE TITLE
How to use Frameskip enviorments?

### ISSUE THREAD

**Issue by Christoph-Schuhmann** [hill-a/stable-baselines#272]
I successfully trained the NoFrameskip version of Breakout with the DQN algorithm, but when I tried now to train the standard gym version of Space Invaders (with the skipping of 2,3 or 4 frames), I got a error,  because the atari-wrapper has an assertion that only allows NoFrameskip enviorments.

Is there a way to train Frameskipping versions of Atari games with stable baselines? 
What do I need to do?

**Comment by araffin** [comment]
Hello,

>Is there a way to train Frameskipping versions of Atari games with stable baselines?

Well, I would say the solution is easy. You have to create your custom `make_env` function and use it.
See [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L277) and [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/cmd_util.py#L18).

However, I don't see the point of using frame-skip env, as it is done by that wrapper...

**Comment by sjtuytc** [comment]
then why do you make that assertion in "stable_baselines/common/atari_wrappers.py"?

**Comment by araffin** [comment]
>then why do you make that assertion in "stable_baselines/common/atari_wrappers.py"?

You mean that [line](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L285)?
Because the frame skipping is done the lines right after that (that's what I meant by "as it is done by that wrapper...").

**Comment by sjtuytc** [comment]
I see, thanks. Actually you're using your own frame skipping instead of the gym one.
