### ISSUE TITLE
Improve __getattr__ for VecEnvWrapper

### ISSUE THREAD

**Issue by kantneel** [hill-a/stable-baselines#274]
In more complicated experiments, a user may wish to wrap a VecEnv with multiple instances of `VecEnvWrapper` in a modular fashion. For example, we could have something like below:

```python
class RewardVecWrapper(VecEnvWrapper):
    def __init__(self, venv, reward_multiplier):
        super().__init__(venv)
        self._reward_multiplier = reward_multiplier

    def step_wait(self):
        obs, rewards, dones, infos = self.venv.step_wait()
        rewards *= self._reward_multiplier
        return obs, rewards, dones, infos

    def get_reward_multiplier(self):
        return self._reward_multiplier

class LoggingVecWrapper(VecEnvWrapper):
     def custom_log(self, infos):
           # stateful logging, saving to file in custom format, etc. 
           ...

     def step_wait(self):
         obs, rewards, dones, infos = self.venv.step_wait()
         self.custom_log(infos)
         return obs, rewards, dones, infos
```

The issue arises if I have a venv which has been wrapped with `RewardVecWrapper` and and I wish to call `get_reward_multiplier`. Depending on if I have wrapped it with `LoggingVecWrapper` (or any number of wrappers really), I would have to do some unappealing type-checking, something to the effect of 

```python
def get_arbitrarily_deep_reward_multiplier(wrapped_venv):
    reward_venv = wrapped_venv
    while True:
        if isinstance(reward_venv, RewardVecWrapper):
            return reward_venv.get_reward_multiplier()
        else:
            reward_venv = reward_venv.venv
```

I believe we can fix this by modifying `VecEnvWrapper.__getattr__` to the following: 
```python
# in class VecEnvWrapper
def __getattr__(self, name):
    # Edit: line below was originally "return self.venv.__getattr__(name)"
    return getattr(self.venv, name)
```

This way, as long as different VecEnvWrappers have unique names for attributes of interest, one can always find that attribute from a top-level call to `venv.__getattr__`.

**Comment by AdamGleave** [comment]
This seems useful even if you have just a single wrapper, if the `VecEnv` being wrapped has a custom method name, but definitely becomes more useful when there are many layers of `VecEnvWrapper`'s.

However, the resulting code does seem hard to reason about, and it would break a lot of code analysis tools (e.g. many IDEs probably wouldn't be able to jump to the function definition). Where possible it seems generally better to keep a reference to the original `VecEnvWrapper` and call that directly.

I think overall I'm in favour of this as there are use cases where this seems a cleaner approach, but I am worried this feature could be abused. @hill-a @araffin @erniejunior any perspective on this?

**Comment by kantneel** [comment]
`__getattr__` is called when the attribute is not found for that object. This is in contrast to `__getattribute__`, which is called every time an attribute reference is made.

**Comment by araffin** [comment]
@hill-a I would like to know your thought on that ;)

@kantneel thanks for the PR, as always, don't forget the changelog and the tests
+ I would add a warning in the docstring

**Comment by hill-a** [comment]
I'm mostly worried about trying to use a attribute that has the same name in two different nested wrappers, which would could cause some nice headaches if it is not noticed by the user. Maybe add some depth check to see if it exists, and warn if so (or maybe a flag to help? not sure). Solving this would be quite important in my opinion to avoid issues.

Other than that, this could be used to help solve issues with rolling normalization wrappers on `OffPolicyRLModel` that use experience replay. Not to mention how useful this is for analysing behaviours through environments methods if they are needed.

**Comment by AdamGleave** [comment]
I like the idea of  a warning. One option would be for `VecEnvWrapper` to do inspection on the environment it is wrapping and find all non-standard methods (i.e. not `step_wait`, `step_async`, etc). Keep these in some instance variable, and then propagate them up each time we wrap. Then issue a warning *when wrapping* if there are duplicate method names, and perhaps have `__getattr__` raise an error in that case.

**Comment by kantneel** [comment]
I'm not sure that doing these checks when wrapping is the best idea, since that may break existing codebases even though the users of the code don't actually call __getattr__ in a dangerous way. An example that comes to mind is if a user wishes to create a custom callback function for their custom wrappers and decides to use the same name for all of them e.g. "log_callback." I think doing a check for duplicate attribute names when calling __getattr__ on a particular name makes more sense.

**Comment by AdamGleave** [comment]
A warning wouldn't actually break code, but I appreciate the concern.
