### ISSUE TITLE
Possible Typo in A2C documentation

### ISSUE THREAD

**Issue by zamlz** [hill-a/stable-baselines#275]
**Describe the bug**
The following lines,
```
python -m stable_baselines.ppo2.run_atari
runs the algorithm for 40M frames = 10M timesteps on an Atari game. See help (-h) for more options.
python -m stable_baselines.ppo2.run_mujoco
runs the algorithm for 1M frames on a Mujoco environment.
```
Shouldn't that line be a2c instead of ppo2?

**Comment by araffin** [comment]
Hello,
I think this will be fixed in https://github.com/hill-a/stable-baselines/pull/269 , thanks for pointing out the issue.

**Comment by zamlz** [comment]
Sorry! I should have checked if a PR existed for it!
