### ISSUE TITLE
[feature request] GAIL ExpertDataset requires loading from file

### ISSUE THREAD

**Issue by AdamGleave** [hill-a/stable-baselines#281]
**Describe the bug**
Currently GAIL's `ExpertDataset` requires the dataset is loaded from a file. However, there are common use cases where the datasets already in memory, for example:
  - You have generated demonstrations (e.g. from a synthetic expert) in the same application as you wish to train GAIL. 
  - You have demonstrations in a different format to what GAIL `ExpertDataset` expects (which is quite a strange format IMO). You wish to convert your dataset to the format expected and then pass it to `ExpertDataset`.
Of course, you can work around this by saving the dataset to disk and loading it -- but that's a little perverse.

**Comment by araffin** [comment]
Hey,

I agree on that feature ;)

>which is quite a strange format IMO

what would be a better format? I'm interested in suggestions.

**Comment by AdamGleave** [comment]
> what would be a better format? I'm interested in suggestions.
The main thing I find awkward about the GAIL format is that it flattens all of the data, requiring this extra array `episode_starts` to recover episode boundaries. I tend to instead store the observations, actions, rewards, etc as a list of NumPy arrays, one for each episode. 

It can be helpful to flatten things for training purposes, e.g. to be able to sample random subsets of trajectories, but it's much easier to flatten than it is to unflatten. And the `ExpertDataset` code right now has to do some contortions to support e.g. `traj_limit_idx` which would be simple if not flattened.

However it's not a big deal -- I don't think we necessarily need to update the format, just give users a choice of using their own formats if it makes more sense in their applications.

**Comment by araffin** [comment]
>I tend to instead store the observations, actions, rewards, etc as a list of NumPy arrays, one for each episode.

But can you save those list in a numpy archive? I think that was my main motivation for this format, this allows to store episodes of different lengths, at the compromise of some transformations.

>However it's not a big deal -- I don't think we necessarily need to update the format, just give users a choice of using their own formats if it makes more sense in their applications.

ok

**Comment by AdamGleave** [comment]
> But can you save those list in a numpy archive? I think that was my main motivation for this format, this allows to store episodes of different lengths, at the compromise of some transformations.
I don't think NumPy supports this, seems like a good reason to use this format. You can get similar compression of nested data structures containing NumPy arrays using https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html but it's probably not worth introducing that dependency just for this use case.
