### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by patterntrade** [hill-a/stable-baselines#283]
Writing some quick n dirty code just to get the framework going. Yes, I know it could be much more elegant. Having a maddening error I can't seem to figure out.

```python
import gym
from gym import spaces
import numpy as np
from stable_baselines.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines.a2c.a2c import A2C
from stable_baselines.common.policies import CnnPolicy
class CustomEnv(gym.Env):
    metadata = {'render.modes': ['human']}

    def __init__(self, ob_sp,N_DISCRETE_ACTIONS):
        super(CustomEnv, self).__init__()
        self.action_space = spaces.Discrete(N_DISCRETE_ACTIONS)

        self.l=ob_sp["l"]
        self.h=ob_sp["h"]
        self.x=ob_sp["x"]
        self.y=ob_sp["y"]
        self.z=ob_sp["z"]
        self.dtype=ob_sp["dtype"]

        self.observation_space = spaces.Box(low=self.l, high=self.h, shape=(self.x,self.y,self.z), dtype=self.dtype)

    def step(self, action):
        self.obs,self.reward,self.done,self.comment=self.execute(action)
        self.steps+=1
        return self.obs, self.reward, self.done, {}
    
    def reset(self):
        self.steps=0
        self.done=False
        self.obs=self.random()
        return self.obs
    
    def render(self, mode='human', close=False):
        if mode == 'rgb_array':
            return self.obs
        elif mode == 'human':
            from gym.envs.classic_control import rendering
            if self.viewer is None:
                self.viewer = rendering.SimpleImageViewer()

            if self.obs.ndim<=3:obs=np.array(self.obs,dtype=self.dtype)

            else:obs=np.array(self.obs[:,:,:,0],dtype=self.dtype)
            self.viewer.imshow(obs)
            return self.viewer.isopen
        
    def random(self):
        self.obs=np.random.randint(self.l,self.h,size=(self.x,self.y,self.z),dtype=self.dtype)
        return self.obs

    def execute(self,action):
        self.random()
        self.reward=self.random()
        if self.steps>100: self.done=True
        return self.obs, self.reward, self.done, {}

print("program start")
#if __name__=="main":
print("Dummy run")
shape={}
shape["l"]=0
shape["h"]=255
shape["x"]=128
shape["y"]=64
shape["z"]=3
shape["dtype"]=np.uint8
N_DISCRETE_ACTIONS=2

env=DummyVecEnv([lambda: CustomEnv(shape,N_DISCRETE_ACTIONS)])
model= A2C(CnnPolicy,env).learn(total_timesteps=1000)
```

Getting this back:

> 
> Traceback (most recent call last):
>   File "/Users/kodiak/5th/custom_env.py", line 71, in <module>
>     model= A2C(CnnPolicy,env).learn(total_timesteps=1000)
>   File "/Users/kodiak/anaconda3/envs/tflow/lib/python3.6/site-packages/stable_baselines/a2c/a2c.py", line 236, in learn
>     obs, states, rewards, masks, actions, values, ep_infos, true_reward = runner.run()
>   File "/Users/kodiak/anaconda3/envs/tflow/lib/python3.6/site-packages/stable_baselines/a2c/a2c.py", line 330, in run
>     obs, rewards, dones, infos = self.env.step(clipped_actions)
>   File "/Users/kodiak/anaconda3/envs/tflow/lib/python3.6/site-packages/stable_baselines/common/vec_env/base_vec_env.py", line 94, in step
>     return self.step_wait()
>   File "/Users/kodiak/anaconda3/envs/tflow/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 36, in step_wait
>     self.envs[env_idx].step(self.actions[env_idx])
> ValueError: setting an array element with a sequence.
> 

I know the code hiccups because somewhere a non-scalar is being put into an array cell. But where?

Help would be most appreciated

:-)

**Comment by araffin** [comment]
Hello,

the problem comes from this line:

```python
self.reward=self.random()
```

the reward must be a scalar, not a ndarray that looks like an image ;)

**Comment by patterntrade** [comment]
Ah, yes, of course. Thank you so much. Kudos!
