### ISSUE TITLE
ACKTR Policies

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#29]
During the refactoring, it seems that old policy of ACKTR was abandoned in favor of `common.policies`. I think we should double check because this may affect performances.

**Comment by hill-a** [comment]
Hey,

I dont think this is an issue for discrete ACKTR, as it uses the a2c policies pre-refactoring (https://github.com/hill-a/stable-baselines/blob/v0.1.6/baselines/acktr/run_atari.py), and the a2c policies are the basis for the current refactored policies. 

However, you are right about the `GaussianMlpPolicy` (https://github.com/hill-a/stable-baselines/blob/v0.1.6/baselines/acktr/policies.py), which is used in continuous ACKTR. This needs to be taken into account when refactoring continuous ACKTR.
