### ISSUE TITLE
[question] Understanding observation_space

### ISSUE THREAD

**Issue by flipflop4** [hill-a/stable-baselines#291]
Firstly, thanks for such an amazing resource - it's been absolutely invaluable.

(How do I add a [question] and [custom gym env] label to this???)

I've been really struggling with what probably amounts to a rudimentary problem  and was wondering if anyone has the patience or inclination to help explain the correct use of observation_space in a custom environment. 

At each step I have a numpy array of dimensions (119,7) which I'd like to use as the observation. I'm currently trying to use the ACKTR model with MlpLnLstmPolicy.

With that in mind I've tried a number of ways to set a Box space, but have yet to manage to crack it. 

min_vals is an array taken from my 'master' dataframe, i.e., `min_vals = master.min(axis=0).values`
max_vals is an array `max_vals = master.max(axis=0).values`
observation is an array of shape (119,7) i.,e, `observation = master.space`

When I try to use: 
`self.observation_space = spaces.Box(low=min_vals, high=max_vals)`
I get "ValueError: could not broadcast input array from shape (119,7) into shape (7)"

Using: 
`self.observation_space = spaces.Box(low=min(min_vals), high=max(max_vals),shape =(119,7) , dtype = np.float32)`
I get "TypeError: Object of type 'int64' is not JSON serializable"

With:
`self.observation_space = spaces.Box(low=min_vals, high=max_vals,shape =(119,7) , dtype = np.float32)`
I get an AssertionError based on 'assert np.isscalar(low) and np.isscalar(high)'

I could go on but at this point my efforts devolved into just trying random sequences. I've tried to compare what I'm doing to a number of other envs and I'm clearly failing to grasp the observation_space concept so any help would be really appreciated.

**Comment by araffin** [comment]
Hello,

please use a 1D vector as input (so, in your case a 119 x 7 D vector), I don't think we support Box spaces which are not 1D (@hill-a , do we?)

The best way to learn about gym spaces is also to look at the [code of gym](https://github.com/openai/gym/blob/master/gym/spaces/box.py).

@hill-a I think we should also add that to the documentation, no? (not the first time someone has an error because of that).

**Comment by hill-a** [comment]
Indeed, ACKTR does not support Box spaces yet (https://stable-baselines.readthedocs.io/en/master/modules/acktr.html#can-i-use). I'm guessing this is the root of the cryptic error:

> Using:
self.observation_space = spaces.Box(low=min(min_vals), high=max(max_vals),shape =(119,7) , dtype = np.float32)
I get "TypeError: Object of type 'int64' is not JSON serializable"

as the observation_space is not compatible with ACKTR. Although I'm not sure this is the issue (maybe type problems with min_vals/max_vals?)

> When I try to use:
self.observation_space = spaces.Box(low=min_vals, high=max_vals)
I get "ValueError: could not broadcast input array from shape (119,7) into shape (7)"

here `min_vals` and `max_vals` are of shape (7), however you never told Box the shape of the input, hence Box assumes it is of the shape of the min/max arrays you entered

> With:
self.observation_space = spaces.Box(low=min_vals, high=max_vals,shape =(119,7) , dtype = np.float32)
I get an AssertionError based on 'assert np.isscalar(low) and np.isscalar(high)'

and here, when shape is defined, low and high must be scalars and not arrays (https://github.com/openai/gym/blob/master/gym/spaces/box.py#L24)


> @hill-a I think we should also add that to the documentation, no? (not the first time someone has an error because of that).

I'm not sure about the 1D issue, as we kinda support multi dimention observations with MLPs... (https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L436).
But fleshing out the custom env would be quite good imo.

**Comment by flipflop4** [comment]
@hill-a @araffin Thanks so much for your responses, I'll have a bit of time over the weekend to look at this and I'll report back on how I get on. Really appreciate the time you've taken to reply.

Just one observation --> https://stable-baselines.readthedocs.io/en/master/modules/acktr.html#can-i-use has a tick for Box under Observation. My action space is straight forward enough (Discrete(4)) although once I've worked out a simple (haha) env  I'll probably shift to a model which supports continuous action space.

**Comment by araffin** [comment]
@hill-a I think you confused observation space with action space for ACKTR.

@flipflop4 , the following code works, so you can maybe take inspiration of it ;):

```python
import numpy as np
import gym
from gym import spaces
from stable_baselines import ACKTR, PPO2
from stable_baselines.common.vec_env import DummyVecEnv


class CustomEnv(gym.Env):
    metadata = {'render.modes': ['human']}

    def __init__(self):
        super(CustomEnv, self).__init__()
        self.action_space = spaces.Discrete(4)
        self.observation_space = spaces.Box(-1, 1, shape=(119, 7), dtype=np.float32)
        # Alternatively, you can define your space like that:
        # highs = np.ones((119, 7), dtype=np.float32)
        # lows = -highs
        # self.observation_space = spaces.Box(lows, highs, dtype=np.float32)

    def step(self, action):
        obs = self.observation_space.sample()
        return obs, 0, False, {}
    
    def reset(self):
        return self.observation_space.sample()


env = DummyVecEnv([lambda: CustomEnv()])
model = ACKTR('MlpLstmPolicy', env, verbose=1).learn(10000)
```

**Comment by flipflop4** [comment]
@araffin I've just now managed to check this out, apologies for the delay.
 
Thanks so much for the help, if there's anything I can do to help contribute let me know. You guys are rocking it, keep up the good work.
