### ISSUE TITLE
[feature request] tqdm for training

### ISSUE THREAD

**Issue by Pastafarianist** [hill-a/stable-baselines#297]
It would be convenient to have `tqdm` wrapped around the main training loop — especially if it was `from tqdm.auto import tqdm`, as it autodetects whether it runs in a Jupyter notebook or in a terminal and uses either `stderr` or a widget.

**Comment by araffin** [comment]
Hello,
I think you can already implement that using a custom callback.
I m afraid this would require too much changes (and hide useful logs) if we make it the default.

**Comment by Pastafarianist** [comment]
It is a good idea to implement that using callback, thank you.

I've experimented a little and this seems to work:

```python
from tqdm.auto import tqdm

class TqdmCallback(object):
    def __init__(self):
        self.pbar = None
    
    def __call__(self, _locals, _globals):
        if self.pbar is None:
            self.pbar = tqdm(total=_locals['nupdates'])
            
        self.pbar.update(1)
        
        if _locals['update'] == _locals['nupdates'] - 1:
            self.pbar.close()
            self.pbar = None

        return True
```

One thought is that perhaps `stable-baselines` should accept multiple callbacks (Keras style), but that would be a topic for another issue.

**Comment by araffin** [comment]
Thank you for the snippet, in fact, that give me the idea of proposing "common" callback like chechpoint saving or model evaluation using an eval env.

**Comment by Pastafarianist** [comment]
Right, I was thinking of opening an issue about the removal of evals compared to `baselines` :)

**Comment by dniku** [comment]
For those finding this issue via search, here is a version that works with Stable Baselines 3:

```python
from tqdm.notebook import tqdm
from stable_baselines3.common.callbacks import BaseCallback

class TqdmCallback(BaseCallback):
    def __init__(self):
        super().__init__()
        self.progress_bar = None
    
    def _on_training_start(self):
        self.progress_bar = tqdm(total=self.locals['total_timesteps'])
    
    def _on_step(self):
        self.progress_bar.update(1)
        return True

    def _on_training_end(self):
        self.progress_bar.close()
        self.progress_bar = None
```

**Comment by araffin** [comment]
Thanks, it is also present in our tutorial on callbacks now: https://github.com/araffin/rl-tutorial-jnrr19#content
