### ISSUE TITLE
Training the same model after loading.

### ISSUE THREAD

**Issue by batu** [hill-a/stable-baselines#30]
Hello again, 

I was looking into continuing training after loading a model. Simply using 
`model.load("path-to-model")                 `
`model.learn(total_timesteps= 500000) `
`model.save("path-to-model")                `

However the training seems to reset as seen here:
![image](https://user-images.githubusercontent.com/6670976/45896756-f1d16000-bd89-11e8-9f6f-5f572e407d98.png)

I don't think learn is inherently resetting the parameters. Do you know why this might be the case?

Thank you!

**Comment by araffin** [comment]
Hello,

Can you provide us with a minimal code to reproduce the behavior?
I just tried with PPO2 on CartPole-v1, I did not see what you described :/ .

My example:
```python
from stable_baselines import PPO2

tensorboard_log = '/tmp/debug/'
model = PPO2('MlpPolicy', 'CartPole-v1', tensorboard_log=tensorboard_log)
# Get the env object
env = model.get_env()
# The mean reward starts from zero
model.learn(50000)
# After 50k steps, it reaches a mean reward > 200
model.save('/tmp/test_ppo')
# Delete the trained model
del model

model = PPO2.load('/tmp/test_ppo.pkl', env=env, tensorboard_log=tensorboard_log)
# the mean reward starts from about 200
model.learn(50000)
```

Btw, please use the issue template next time ;)

**Comment by batu** [comment]
User error...

Conceptually I was thinking that model.load() was operating on the model (in-place) and thus not assigning it to the model variable afterwards.

I apologize for the time lost!
