### ISSUE TITLE
Buggy Logic in trpo_mpi.utils.traj_segment_generator, 'ep_lens' key unreliable. 

### ISSUE THREAD

**Issue by GerardMaggiolino** [hill-a/stable-baselines#302]
The function will record improper episode lengths in the returned dictionary. 

The current episode length is recorded under 'current_it_len'. This is reset to zero even if the episode is not finished when yielding on line 89. 

When the episode finishes, 'current_it_len' is recorded in the dictionary's ep_lens list. This length could be significantly shorter than the actual episode length. 

The amount of time steps stored in 'total_timestep' as current_it_timesteps is correct; however, if using the ep_lens list, the length of the episode is shorter than it actually is. 

**Example:** 
Assume batch size (horizon) of 1200. Each episode lasts 500 time steps. 

First iteration:  'ep_lens' = [500, 500], as only two episodes were completed. 'total_timesteps' is correct at 1200. 

Second iteration: 'ep_lens' = [300, 500], as the episode from the last iteration completes, one more completes fully, and the next is ongoing on time step 400. 

Third iteration: 'ep_lens' = [100, 500, 500]. 

The corresponding reward in 'ep_rets' is correct for the entirety of the episodes, but the length of the episodes as found in 'ep_lens' list are significantly shorter than expected. 

I'm unsure what the episode lengths in 'ep_lens' are used for, but if they're used for some normalization based on the rewards, any of those calculations would be incorrect.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, looks like a legit bug.

>I'm unsure what the episode lengths in 'ep_lens' are used for

They are only used for logging (I have to double check), so that should be only a minor bug.

See here: https://github.com/hill-a/stable-baselines/blob/baa4aa5a3c3ffe4ef192b1d4b1c64e15c307c13f/stable_baselines/trpo_mpi/trpo_mpi.py#L464

**Comment by GerardMaggiolino** [comment]
I added a fix; apologies if it's minor enough of a bug to not warrant a PR. It looks like it affected logging in both TRPO and PPO1 modules, and the fix is only a few lines of change.

**Comment by araffin** [comment]
>if it's minor enough of a bug to not warrant a PR

Everything that can be improved is worth a PR ;) (and the small ones are easier to review)
