### ISSUE TITLE
[feature request] filter_size can be a array instead of one value

### ISSUE THREAD

**Issue by yutingsz** [hill-a/stable-baselines#317]
My conv filter is not a square matrix. Its height is 1 and weight is 3. 
In the conv function within the utils.py, the input parameter, filter_size, needs to be an array instead of a value. It is rather simple change.

**Comment by araffin** [comment]
Hello,
if it does not break anything, then yes, this should a good small improvement.

**Comment by yutingsz** [comment]
Thanks. Do you want to update the code? Or I am happy to do my contribution to this project as I am using your code everyday.

**Comment by araffin** [comment]
> Or I am happy to do my contribution to this project as I am using your code everyday.

Yes, please do a PR and don't forget to read the contribution guide completely ;)
