### ISSUE TITLE
From Multi Env Training to Single Env Production: PPO2 and LSTM[question]

### ISSUE THREAD

**Issue by kaidahousecat** [hill-a/stable-baselines#32]
First of all, great work! I got some good results from this library.

I trained the model on 10 paralles environments with SubprocVecEnv. Now in production I would like to use it with just one environment. When I try to load the model file, it states that its not possible with the LSTM-Policy to load the model with a different amount of environments.

Did I miss something?

**Comment by araffin** [comment]
Hello,

I don't think you missed anything, I think that is one of the current limitation of recurrent policies. Can you confirm @hill-a ?
