### ISSUE TITLE
How can I get the value of the policy? [question]

### ISSUE THREAD

**Issue by JoelNiklaus** [hill-a/stable-baselines#335]
Hi,

I want to build an architecture similar to AlphaZero. For this I need the output of the value head. I didn't see any application of this in the docs and couldn't figure it out by looking at the code: How can I get the value based on an observation?

Cheers,
Joel

**Comment by araffin** [comment]
Hello,
I think you should look at the policy class (for actor critics algos), here:
https://github.com/hill-a/stable-baselines/blob/a37f1ebd93708b045f10658b890af4e9e68e556d/stable_baselines/common/policies.py#L273
and here:
https://github.com/hill-a/stable-baselines/blob/a37f1ebd93708b045f10658b890af4e9e68e556d/stable_baselines/common/policies.py#L583

Also, it will depends on the algorithm, for instance for ppo2, you can directly call the value method:
https://github.com/hill-a/stable-baselines/blob/a37f1ebd93708b045f10658b890af4e9e68e556d/stable_baselines/ppo2/ppo2.py#L206

**Comment by JoelNiklaus** [comment]
Thank you very much. I tried it out:

```
policy = "MlpPolicy"
model = PPO2(policy, env, n_steps=hp.n_steps, gamma=hp.gamma, nminibatches=hp.nminibatches,
             learning_rate=hp.learning_rate, verbose=1,
             tensorboard_log=tensorboard_log_dir)

model.learn(total_timesteps=hp.total_timesteps, tb_log_name=log_name, callback=callback)

obs = env.reset()
action = **model.predict(obs)**[0]  # the prediction is a tuple with the next state as the second entry
print(**model.value(obs)**, file=sys.stderr)
obs, rewards, dones, info = env.step(action)
```

Passing the observation to the predict function everything works fine but passing it to the value function, I got the following problem:

Traceback (most recent call last):
  File "experiment.py", line 162, in <module>
    print(model.value(obs), file=sys.stderr)
  File "/Users/joelito/miniconda3/envs/project/lib/python3.7/site-packages/stable_baselines/common/policies.py", line 583, in value
    return self.sess.run(self.value_flat, {self.obs_ph: obs})
  File "/Users/joelito/miniconda3/envs/project/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/joelito/miniconda3/envs/project/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (48, 13) for Tensor 'input/Ob:0', which has shape '(?, 48, 13)'

Why does the value function expect a differently shaped tensor?

**Comment by araffin** [comment]
What happens is that you don't have all the magic that you have in the predict method:

https://github.com/hill-a/stable-baselines/blob/a37f1ebd93708b045f10658b890af4e9e68e556d/stable_baselines/common/base_class.py#L469-L473

so you need to reshape your observation to the correct shape yourself.

**Comment by JoelNiklaus** [comment]
Ah, I see. This works now:

`obs = np.array(obs)
  obs = obs.reshape((-1,) + env.observation_space.shape)
  value = model.value(obs)`

Thank you very much for the fast and helpful support!

**Comment by JoelNiklaus** [comment]
I receive values between -3 and 4. Can I know in what range to expect the value to be? Is it within the reward_range?

**Comment by araffin** [comment]
Well, the value estimates the expected return, which is a sum of discounted reward. If you know the bounds of the reward and the max number of timesteps, then you can bound the value too.

**Comment by JoelNiklaus** [comment]
Right. Thanks
