### ISSUE TITLE
[question]no ep_rewmean, eplenmean displayed, I don't know why

### ISSUE THREAD

**Issue by snowzjy** [hill-a/stable-baselines#339]
**Describe the bug**
when run my program,the fallowing displayed, but no ep_rewmean, eplenmean displayed, I don't know why
//-------------------------------------
| approxkl           | 0.0          |
| clipfrac           | 0.0          |
| explained_variance | -5.96e-07    |
| fps                | 49           |
| nupdates           | 77746        |
| policy_entropy     | 6.521396e-05 |
| policy_loss        | 0.0          |
| serial_timesteps   | 2487872      |
| time_elapsed       | 4.58e+04     |
| total_timesteps    | 1166190      |
| value_loss         | 278.51614    |
//-------------------------------------

**Code example**
model = PPO2(MlpLstmPolicy, train_env,n_steps=32, nminibatches=1,lam=0.95, gamma=0.99, noptepochs=15,
             vf_coef = 0.0001,ent_coef=0.0001,learning_rate=0.00005,cliprange=0.2,verbose=1,
            tensorboard_log="./tensorboard/")

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
pip
 * GPU models and configuration
gpu
 * Python version
3.6
 * Tensorflow version
1.13
 * Versions of any other relevant libraries

**Additional context**
the ep_rewmean also not displayed in tensorboard, I also want the ep_rewmean displayed in tensorboard. Could you know if there is any way?

**Comment by araffin** [comment]
Hello,

the questions are already answered here: 
https://github.com/hill-a/stable-baselines/issues/24 https://github.com/hill-a/stable-baselines/issues/175 and https://github.com/hill-a/stable-baselines/issues/294
Anyway, we should update the documentation to be clearer.
