### ISSUE TITLE
[question] Using PPO2 for problems outside of gym

### ISSUE THREAD

**Issue by Qaceless** [hill-a/stable-baselines#341]
I want to use PPO2 on an RL problem outside the gym environment. Is there an existing way to do this or do I have to manually go through PPO2.py to extract the integration with gym?

**Comment by araffin** [comment]
Hello,

I won't recommend using it outside a gym env, as the gym interface (which is quite simple) is all you need to define a RL problem. Also, it makes things easier to try out different approaches.

> Is there an existing way to do this or do I have to manually go through PPO2.py to extract the integration with gym?

The gym interface is the only assumption for the algorithms implemented in this repo, so you have to extract the integration, but usually, it is easier (and recommended) to wrap your problem in a gym env instead.

**Comment by Qaceless** [comment]
I'm tackling a problem based in a custom simulation environment so wrapping it in a gym env isn't an option. Right now I'm using a deep Q implementation which operates by training the nn in python, feeding it to the sim, running the sim based off the given nn, collecting the results, feeding them back into the python implementation, and cycling that process. I'm trying to swap out deep Q for PPO2.

Is there a way i can easily insert the use of gym between these steps? Otherwise, do you think it would make more sense for me to extract gym from here or try and code PPO2 from scratch?

**Comment by araffin** [comment]
I'm not sure to understand your problem, anyway, sounds more like a technical question, and as mentioned in several issues, we don't do personal tech support.

To give you an example of wrapping custom env (like a real robot using ROS), you can take a look at: https://github.com/araffin/robotics-rl-srl (where some bridge was implemented using sockets)

**Comment by Qaceless** [comment]
Ah okay I'll take a look, thanks for your help!
