### ISSUE TITLE
Multiprocessing and Frame-Stacking Best Practices? [question]

### ISSUE THREAD

**Issue by AI-Guru** [hill-a/stable-baselines#342]
Namaste!

I am very happy using stable baselines!

I would love to make use of both multiprocessing and frame-stacking. In code, what would be the best practice to combine SubprocVecEnv and VecFrameStack?

Thank you!

**Comment by araffin** [comment]
Hello,

>what would be the best practice to combine SubprocVecEnv and VecFrameStack?

Could you elaborate?

**Comment by AI-Guru** [comment]
With pleasure.

I have an environment that yields visual data as observations, very much like Atari.

I intend to use 4 stacked frames as input for the CnnPolicy.

I intend to train A2C. Using multiple environment instances on multiple CPUs.

Thus it would be great to set up stable baselines to yield 4 stacked frames per process.

How to do this in code?

**Comment by araffin** [comment]
For this, please read the documentation: https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html
and look at examples and the rl zoo ;): https://github.com/araffin/rl-baselines-zoo
and https://github.com/araffin/rl-baselines-zoo/blob/master/train.py#L189
