### ISSUE TITLE
Unexpected behavior in model after save / load to new variable 

### ISSUE THREAD

**Issue by greg234234** [hill-a/stable-baselines#345]
Hi all, in reference to saving / loading, and in the context of the deterministic fix test file, the steps are:

1. train the model, variable name: model
2. save the model
3. load the model, variable name: model2, as a copy
4. the predictions between model and model2 are not equal
5. ¯\\\_(⊙_ʖ⊙)_/¯

Is it custom to delete a model and reload it, then evaluate on new data?  I am confused about what information is different if both models are evaluating the same new observation for the first time.

**Code example**
Please view the publicly shared Colaboratory notebook here: https://colab.research.google.com/drive/1TmLBUypB-par8hW3IG_KkI45BtHCKvjp

**System Info**
   - tpu, gpu, cpu
   - python 3
   - tensorflow 1.13.1
   - pip ( clone of the deterministic-fix branch )

**Comment by araffin** [comment]
Hello,

It seems there is an indent error (a for loop seems to be missing) in the given colab.

Does your problem only occurs with ACER or also with PPO2/A2C?

**Comment by greg234234** [comment]
Hi @araffin , thanks for looking at it.

Yes, I took out the for loop because we're evaluating the two models linearly(?), model.predict(obs) and then model2.predict(obs).

Yes, I confirm it happens also with PPO2/A2C.

**Comment by araffin** [comment]
How do you expect that both model predictions will be the same with `deterministic=False`?

**Comment by greg234234** [comment]
Yes of course, that would be illogical.  tl;dr I'm closing the thread with my apologies and a full disclosure below of how such a silly thing could happen. 

For some reason, in an unrelated issue, deterministic=False passed the assertion tests in the commented tests blow, while deterministic=True was causing my own environment not to take any actions. Finally deterministic=False was mistakenly carried all the way to this thread. 

I had been experimenting with CartPole-v1 and my own environment in the determinism branch tests, where predictions from the both environmental observations were equal in the other two tests commented out below in that Colab notebook, however not for the experiment we were discussing in this thread.   Thank you again.
