### ISSUE TITLE
TD3 Implementation

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#347]
TD3 is a successor of DDPG (see [original implementation](https://github.com/sfujim/TD3)) that would be nice to have in the repo.

See also [Spinning Up](https://spinningup.openai.com/en/latest/algorithms/td3.html)

**Comment by doviettung96** [comment]
Absolutely. DDPG is not stable for difficult tasks in Roboschool. TD3 will probably help.

**Comment by araffin** [comment]
>DDPG is not stable for difficult tasks in Roboschool.

Usually, I would recommend SAC in that case. But yes, TD3 and SAC have different strengths/weaknesses, so would be good to have them both.

**Comment by doviettung96** [comment]
@araffin ,
Yeah. Basically, I would like to make a comparison for Roboschool HumanoidFlagrunHarder so I have to run DDPG even though it is not good for the task. Anyway, do we have any ways to speed up the off-policy algorithms? They are not using multiprocessing (multi workers) like on-policy methods. It is quite painful to collect millions of timesteps with just only 1 worker.

**Comment by araffin** [comment]
>They are not using multiprocessing (multi workers) like on-policy methods

There is for DDPG. (see HER-support branch on rl-baselines zoo).

**Comment by doviettung96** [comment]
I will try that. Can't wait to see the release of TD3. Thank you.

**Comment by doviettung96** [comment]
Good news. Finally, I could try TD3 using stable-baselines. Thank you.
