### ISSUE TITLE
[Feature Proposal] Callback collection

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#348]
It would be nice to have a collection of common callback like:
- class for chaining callback
- checkpoint callback (save every n calls)
- save best training model callback
- eval callback (with a test env) that can write the results in a file
- others?

see https://github.com/hill-a/stable-baselines/issues/297 for an example

**Comment by rusu24edward** [comment]
@araffin I've been attempting to design a checkpoint to save every n calls. This has required digging into the algorithms a bit. For the algorithms that callback at every iteration, I've been able to modify the [callback example]() to save every n steps. However, some algorithms (e.g. PPO) do not callback every step, so tracking them is a little different. PPO1 and TRPO have a `timesteps_so_far` variable that can be used for this. However, I'm still working out a way to do this for PPO2. Any thoughts?

**Comment by rusu24edward** [comment]
Did a little more digging and it looks like we can get "accurate" steps from `_locals['self'].num_timesteps`.

**Comment by MichaelRazum** [comment]
Hello,
I like this framework a lot. Just one remark on the callbacks. I think it's a great idea to have one file where all the common callbacks are stored. This is what I'm using so far:
````python
def save_after_n_steps(saving_freq, save_path):
    """
    #common/callbacks.py
    Callback calls model.save method every saving_freq steps
    """
    def save_after_n_steps(_locals, _globals):
        if (_locals['self'].num_timesteps % saving_freq == 0):
            _locals['self'].save(save_path)
    return save_after_n_steps
````
 What I don't like about the callbacks is that _locals, _globals are passed to the function. Something like BaseRLModel or some generic Classes would be more convenient from my perspective, at least as a first argument.
