### ISSUE TITLE
Trouble with custom policy

### ISSUE THREAD

**Issue by jdbrody** [hill-a/stable-baselines#350]
Hello,
I just pulled the latest version of the project and don't seem able to use a custom policy network  anymore.  I copied the example froom [https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html) into a file; this used to run fine but now I get:

> $ python ./custom_policy_example2.py 
> /usr/lib64/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> WARNING:tensorflow:From /usr/lib64/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From ./custom_policy_example2.py:18: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.flatten instead.
> WARNING:tensorflow:From ./custom_policy_example2.py:22: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dense instead.
> Traceback (most recent call last):
>   File "./custom_policy_example2.py", line 58, in <module>
>     model = A2C(CustomPolicy, env, verbose=1)
>   File "/home/justin/.local/lib64/python3.6/site-packages/stable_baselines-2.5.1-py3.6.egg/stable_baselines/a2c/a2c.py", line 86, in __init__
>     self.setup_model()
>   File "/home/justin/.local/lib64/python3.6/site-packages/stable_baselines-2.5.1-py3.6.egg/stable_baselines/a2c/a2c.py", line 113, in setup_model
>     n_batch_step, reuse=False, **self.policy_kwargs)
>   File "./custom_policy_example2.py", line 32, in __init__
>     self.pdtype.proba_distribution_from_latent(pi_latent, vf_latent, init_scale=0.01)
> AttributeError: can't set attribute
> 

The code is the last  example on the  referenced webpage   (following "
If your task requires even more granular control over the policy architecture, you can redefine the policy directly:")

For what it's worth, this used to work fine for me.

**System Info**
 * Library was installed in a virtual environment using `python setup.py install --user`
 * GPUs:  Titan 1080 Ti and a Titan X
 * Python version:   3.6
 * Tensorflow version:  1.13

**Comment by araffin** [comment]
Hello,

This is due to a recent breaking change in the base class, see https://github.com/hill-a/stable-baselines/pull/244

You need to replace `self.value_fn` by `self._value_fn`, `value_fn` is now a property.
The doc needs to be updated, feel free to submit a PR for that ;)

**Comment by jdbrody** [comment]
Many thanks for  the quick response!  Is there a similar issue with the line
`
self.proba_distribution, self.policy, self.q_value = \
                self.pdtype.proba_distribution_from_latent(pi_latent, vf_latent, init_scale=0.01)
`

It seems to be choking there (before it tries to set `self.value_fn`)

**Comment by araffin** [comment]
Yes, that is the same issue. There were made private, you have to prefix those variables with an underscore.

**Comment by jdbrody** [comment]
Thanks so much!  That fixed the constructor, but now the `step` function is unhappy that `self._value` is undefined.  

> AttributeError: 'CustomPolicy' object has no attribute '_value'

Is this an easy fix as well?

**Comment by jdbrody** [comment]
Replaced `self._value` with `self._value_flat`; this seemed to fix it.
