### ISSUE TITLE
[feature request] allow np.arrays as values to the logger

### ISSUE THREAD

**Issue by dwiel** [hill-a/stable-baselines#356]
In some cases it is helpful to log a vector to the kv logger. For example, I wanted to log mean action vector and a mean position vector.

I'm not sure how this should be handled by tensorflow logger, but for json and stdout  loggers there is an obvious formatting.

**Comment by araffin** [comment]
Hello,

>In some cases it is helpful to log a vector to the kv logger. 

If I understand well, this feature is only aim at custom version of stable-baselines? (installed from source and modified).

**Comment by dwiel** [comment]
It is useful also from custom environments. I am using it to log some additional details about the environment to help with debugging. They to need be reported at the same frequency and also benefit from the averaging.

**Comment by araffin** [comment]
>It is useful also from custom environments.

Ok, in that case I think that is a small but nice to have feature.
