### ISSUE TITLE
ubuntu 14: errors with Signal: Segmentation fault

### ISSUE THREAD

**Issue by Deastan** [hill-a/stable-baselines#357]
Hello everyone,
I am trying to do simple thing with different algos to learn more how to use to be sure everything works.
So I ran the small codes behind, and if I put a few numbers of timesteps (1000), it works when I have added `from pyglet.gl import *` but then, there is this segementation errors after the training part (I think when it opened render()). 
If I remove the pyglet, I have the errors in this topic https://github.com/openai/baselines/issues/235.  I run env.render() with only gym package and it works without any issue.

For instance, when I tried to run for 100'000 I get this error (with ppo2). I tried with DDPG and it was working and now, I also get this error.
Does someone thing it is a problem with the graphic card + tensorflow, or stable-baselines on ubuntu 14 ? Or maybe an other issue ? I don't have this error if I run only gym without stable_baselines...

I am really sorry to disturb you with this issue.

**Describe the bug**
I have the following error when I am trying to do increase the total_timesteps from 10000 to 100000:
```
[roboticlab14:06940] *** Process received signal ***
[roboticlab14:06940] Signal: Segmentation fault (11)
[roboticlab14:06940] Signal code: Invalid permissions (2)
[roboticlab14:06940] Failing at address: 0x845b60
[roboticlab14:06940] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7f5ec90e7330]
[roboticlab14:06940] [ 1] /usr/local/bin/python3() [0x845b60]
[roboticlab14:06940] *** End of error message ***
Segmentation fault (core dumped)
```

**Code example**
```python
import gym
from pyglet.gl import *
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=100000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

env.close()
print("End of script")`
```

**System Info**
Describe the characteristic of your environment:
pip and source for Gym
 * GPU models and configuration: RTX2070
 Python version: 3.6.8
Libraries:
stable-baselines                2.5.1      
tensorboard                     1.13.1     
tensorflow-estimator            1.13.0     
tensorflow-gpu                  1.13.1

**Comment by araffin** [comment]
Hello,

Unfortunately, this sounds related to your personal configuration.
And it is hard to debug if we cannot reproduce the bug :/ 

>Signal code: Invalid permissions

Are you root on that machine?

**Comment by araffin** [comment]
Maybe related: https://github.com/Microsoft/CNTK/issues/2054

"The problem was that OpenMPI was not compiled with CUDA support."

**Comment by Deastan** [comment]
@araffin  Yes I am root on this machine.
I will look at this two link soon. Thank you.
