### ISSUE TITLE
PPO2 - network diverges, outputs become NaNs

### ISSUE THREAD

**Issue by tesslerc** [hill-a/stable-baselines#36]
Installed via pip, running python3.6, TensorFlow 1.9

Environment is HalfCheetah-v2 (yet observed also in other environments).

`env = VecNormalize(env, norm_obs=True, norm_reward=False, clip_obs=10.)`
`model = PPO2(MlpPolicy, env, gamma=0.99, n_steps=2048, ent_coef=0.0, learning_rate=3e-4, max_grad_norm=0.5, lam=0.95, nminibatches=32, noptepochs=10, cliprange=0.2, vf_coef=1.0, verbose=2)`
`model.learn(total_timesteps=int(1e6))`

Also tried using the default parameters and same result.

**Comment by araffin** [comment]
Hi,
Thanks for reporting the bug. Do you have an environment that is not using Mujoco where you experience that? (We don't have Mujoco licence, so it would be easier for us to reproduce the bug on a free environment)

Did you tried in verbose mode and/or with tensorboard support to have additional logs of what can go wrong? (Maybe not only the output is becoming NaN)

**Comment by tesslerc** [comment]
Hey, sorry for the delayed response.
I'll be back in the office tomorrow and will test the fix.
Thanks!
