### ISSUE TITLE
Tensorboard "episode reward" plot shows only 1 entry while training A2C model

### ISSUE THREAD

**Issue by sheetalsh456** [hill-a/stable-baselines#360]
Hi,

I'm training an A2C model with the following code:

`model = A2C(policy='CustomLSTMPolicy', env=env, verbose=1, 
            tensorboard_log="./a2c_tensorboard/").learn(total_timesteps=100000)`

where env is my custom registered vectorized environment, which I created by registering my custom env with env_id=MyEnv-v0 and then creating a vectorized environment using the following code:

`from stable_baselines.common.vec_env import SubprocVecEnv`
`env_id = "MyEnv-v0"`
`num_cpu = 4`
`env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])`

CustomLSTMPolicy is my custom registered LSTM policy which I've registered with the following code:

`from stable_baselines.common.policies import register_policy`
`register_policy('CustomLSTMPolicy', CustomLSTMPolicy)`

When I ran it initially, I was getting an episode reward plot like:
![image](https://user-images.githubusercontent.com/12454534/59074542-acee4a80-8880-11e9-9f89-e374c9d53e0f.png)

I ran the same code multiple times and now my plots look like:
![image](https://user-images.githubusercontent.com/12454534/59074576-da3af880-8880-11e9-955b-536ecc326165.png)

The episode reward plot now has only 1 datapoint, in some 1000+ episode. I have made no changes in the code at all. Just ran it multiple times. 
Not sure why this is happening. 

Can someone please help me with this?

Thanks! :)

**Comment by LincolnZhen** [comment]
I have similiar problem with you. Did you fix it?
