### ISSUE TITLE
Proposing stable-gym forking OpenAI Gym and making it better

### ISSUE THREAD

**Issue by dragon28** [hill-a/stable-baselines#362]
Hello Stable-Baselines Developers,

I would like to propose stable-gym which forking OpenAI Gym and making it better just as you guys have done well with OpenAI Baselines.

Thanks
:)

**Comment by araffin** [comment]
Hello,
I'm quite curious by what you would like to change.
Also, compared to baselines, the management of OpenAI gym is less opaque (no internal version), they are quite open to PR to solve issues (I already did some).
So, I would first try ([as we did](https://stable-baselines.readthedocs.io/en/master/)) to open issues in their repo and propose PR before doing a separate fork.

**Comment by araffin** [comment]
Closing because not directly related to SB.
