### ISSUE TITLE
PPO1 vs PPO2

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#365]
When running ppo1 vs ppo2 on the same data, ppo2 converges whereas ppo1 does not.
I tried several times with custom policies also and ppo1 never converges.

**Comment by araffin** [comment]
Hello,
This is your [10th issue](https://github.com/hill-a/stable-baselines/issues/created_by/hn2) and you are still failing are giving all the required information.
As discussed with @hill-a , if you continue to not follow the contributing guidelines, you will be blocked.

So, I assume you are using them on a custom gym environment, and apparently not with the same hyper-parameters (especially the number of workers). In any case, see #359 (and documentation) , PPO2 is not the same as PPO1 which is closer to the original paper.
So, it does not seem to be surprising regarding all those differences.
