### ISSUE TITLE
[Question] Why does DDPG not allow Discrete action spaces?

### ISSUE THREAD

**Issue by cli0** [hill-a/stable-baselines#37]
Is there a particular reason why this is not possible or is it just an issue of the current implementation?
And does anyone know of a way to "bypass" (or adapt to) this restriction when your actions are a discrete set?

**Comment by mcapuccini** [comment]
@araffin say you have a huge discrete action space, wouldn't it make sense to apply DDPG in that case? With PG methods and Q-learning you have an output node for each discrete action, while with DDPG you end up with a single output node. Or would it be hard to have the head DPG network to output discrete vaules from a single node? What about discretising continuous actions?

**Comment by araffin** [comment]
> huge discrete action space

You have methods for that: https://arxiv.org/abs/1512.07679

>What about discretising continuous actions? 

it is possible (you can use a `gym.Wrapper` for that) but then you may have issues as the algorithm was not created for that purpose.

**Comment by mcapuccini** [comment]
Cool, I'll try out the Wolpentiger architecture. I may send you a PR if I get something to work.
