### ISSUE TITLE
 [question]Does multitread traning generate 1 or many models?

### ISSUE THREAD

**Issue by greg2paris** [hill-a/stable-baselines#370]
Hello, 
Thank you so much for this adaptation of reinforcement algo.
I tried to train a custom environment with ppo2 multitreading.
As I understand, their is many environement that are working in the same time.
But what I dont understand, is when I want to use the trained model on new data (test data),
What happen to the many environment I had trained?
Do they fusion together to make a new model?
Or do I have to make a multi environment to test my data, and I will get a different prediction for as many model I have trained?

Because now, I m training my model on 8 environement, but I test it on 1 single env and it still working without any error.

But I dont know if im just using one model to make the predictions or do I use the 8 models experiences?

**Code example**
```python
def make_env_02(rank, seed=0):
    def _init():
        env = OhlcvEnv(window_size=TIMESTEP,
                 data=train_data,
                 market_data=train_market_data,
                 train=True,
                 show_trade=False,
                 usd_balance=500,
                 trading_by_hours=trading_by_hours,
                 trading_starting_time=trading_starting_time,
                 trading_ending_time=trading_ending_time,
                 data_name=data_name,
                 take_profit_value='1.0',
                 stop_loss_value='1.0')
        #env.setDefaultMultiplier(0)
        #env.seed(seed + rank)
        env.seed(rank)
        return env
    set_global_seeds(seed)
    return _init

num_cpu = 8  # Number of processes to use
# Create the vectorized environment
env = SubprocVecEnv([make_env_02(i) for i in range(num_cpu)])

policy = "MlpPolicy"  
model = PPO2(policy, env, verbose=0)

steps_multiplicator = 1
timesteps = 10 + (environment_times_steps * num_cpu) * steps_multiplicator 
model.learn(total_timesteps=timesteps)

# test
test_environment_times_steps = test_data.shape[0]
obs = test_environment.reset()
for ii in range(test_environment_times_steps * num_cpu * 3):
    action, _states = model.predict(obs, deterministic=True)
    obs, rewards, dones, info = test_environment.step(action)

```

**System Info**
I use google colab with GPU
Last version of python
Last version of tensorflow

**Additional context**
Im a Newbe

**Comment by araffin** [comment]
Hello,

Good questions. 

>Because now, I m training my model on 8 environement, but I test it on 1 single env and it still working without any error.

The answer is [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L132) in the code ;)

So two models are created, one for training, one for "acting" (for the predict function, after training), but they share the same weights.

You can use as many envs you want for prediction.

> Or do I have to make a multi environment to test my data, and I will get a different prediction for as many model I have trained?

This is only required for LSTM policies.


> What happen to the many environment I had trained?

Also, the environments are used only for gathering data, only one model is used for training.

> I tried to train a custom environment with ppo2 multitreading.

Small detail: for now, only multiprocessing is available (because python does not support proper multi-threading).

**Comment by greg2paris** [comment]
Thank you for your fast and detailed answer.

> Also, the environments are used only for gathering data, only one model is used for training.

But the thing is that my environment is always the same, "time series", the only thing that changes is the seed number for eatch environment.
And I get different result for eatch environment during the training, so I was thinking mabe I train one different model by environment.
But as you explained, It actally train only 1 model but the difference is due to the seed + stochastic choice of the action at every time step?

Thanks for the question label, i didn't know how to do it.

**Comment by araffin** [comment]
> But as you explained, It actally train only 1 model but the difference is due to the seed + stochastic choice of the action at every time step?

You mean that the results are not deterministic?
In fact, this is already discussed in other issues: #145 
We plan to work on that issue for v2.7.0.

**Comment by greg2paris** [comment]
I use deterministic=True on the testing data and its working fine, but now i think i get it for the trainning model part, thank you so much for your explanation.
Have a great day
