### ISSUE TITLE
What pre-processing does the agent itself do for Atari?

### ISSUE THREAD

**Issue by p-christ** [hill-a/stable-baselines#371]
Hi,

Thanks for your great repository.

What pre-processing gets done behind the scenes by the agents when playing an Atari game like breakout?  I'm not talking about the pre-processing done by the env object but rather by the agent itself - can anyone point me in the right direction?

e.g. it seems that the env produces observations with pixel values 0-255 so i'm guessing the agent at least divides the pixel value by 255 to make the values in range 0-1?

**Comment by araffin** [comment]
Hello,

>so i'm guessing the agent at least divides the pixel value by 255 to make the values in range 0-1?

you are right. It is in the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html) in fact ;)

In the code, i already answered that question in that issue: https://github.com/hill-a/stable-baselines/issues/328

**Comment by p-christ** [comment]
Thanks a lot. I've added that change but am still unable to get it working for some reason. I've written a colab to show the issue below.  

Have you got any ideas why a PyTorch model with the exact same weights as the Baselines model isn't able to play the game properly?   e.g. are there other preprocessing steps that a baselines agent does internally besides normalising to 0-1? 

https://colab.research.google.com/drive/1-IIjA1oKUjg5eoctajpl06OoHzU-5-_9

**Comment by araffin** [comment]
As I wrote to you in https://github.com/araffin/rl-baselines-zoo/issues/31, please open an issue for that, this will easier for other to find it afterward ;)

**Comment by p-christ** [comment]
ok will do that now
