### ISSUE TITLE
[question] obs and new obs in DQN callback

### ISSUE THREAD

**Issue by joaoreisucl** [hill-a/stable-baselines#384]
Hi,

I noticed that the `obs` and `new_obs` entries of `locals()` call in the DQN callback done in `deepq/dqn.py:188`  are identical (apart from the first step after a reset), probably because of the `obs = new_obs` done at line `deepq/dqn.py:214`. Is this intentional for any reason?

Best,
Joao

**Comment by araffin** [comment]
Hello,

This is normal. We want to store transitions in the replay buffer. A transition is composed of:
- the observation at time t
- the action at time t
- the received reward
- the next/new observation, which is the observation at time t+1

Once stored, we need to keep track of the current observation for the next transition, hence the obs = new_obs.

**Comment by joaoreisucl** [comment]
It makes sense, thank you for your reply!
