### ISSUE TITLE
Bug computing the Generalized Advantage Estimation (TRPO, PPO1, GAIL)

### ISSUE THREAD

**Issue by miguelrass** [hill-a/stable-baselines#385]
In file:  stable-baselines/stable_baselines/trpo_mpi/utils.py 
In function: add_vtarg_and_adv(seg, gamma, lam)  

Lines 138-140:
```
138. nonterminal = 1 - new[step + 1]
139. delta = rew[step] + gamma * vpred[step + 1] * nonterminal - vpred[step]
140. gaelam[step] = lastgaelam = delta + gamma * lam * nonterminal * lastgaelam
```

The **nonterminal** variable is calculated like in the original code by OpenAI. However, it is based on **new[]**, which has the same name in the original code, but a different behavior, at least when called from **stable-baselines/stable_baselines/ppo1/pposgd_simple.py**.

Behavior of **new[]**
In the original code: set to 1 if this is the first step of an episode
In stable baselines: set to 1 if this is the last step of an episode

So, when computing the Generalized Advantage Estimation (at least when called from PPO1), there is a miscalculation for every episode transition in a given batch. The bug is either on the PPO1 side, or in file **trpo_mpi/utils.py**.

**Comment by araffin** [comment]
Hello,

Looking at the code, despite a change of name, it seems that the behavior of "dones" (the new name of "news") is the same as the original:

https://github.com/hill-a/stable-baselines/blob/c68385aaa4f1362cb74f93f9f3cd6616b0fa5d1d/stable_baselines/trpo_mpi/utils.py#L21

https://github.com/hill-a/stable-baselines/blob/c68385aaa4f1362cb74f93f9f3cd6616b0fa5d1d/stable_baselines/trpo_mpi/utils.py#L54

I agree however, we should rename it `episode_starts` to be clearer.

>at least when called from stable-baselines/stable_baselines/ppo1/pposgd_simple.py.

Which lines are you talking about?

**Comment by miguelrass** [comment]
Yes, the comments say one thing but the code does another. 
Here is the code from line 85 to 104 (stable-baselines/stable_baselines/trpo_mpi/utils.py): 

 ```
        i = step % horizon
        observations[i] = observation
        vpreds[i] = vpred[0]
        actions[i] = action[0]
        prev_actions[i] = prevac

        clipped_action = action
        # Clip the actions to avoid out of bound error
        if isinstance(env.action_space, gym.spaces.Box):
            clipped_action = np.clip(action, env.action_space.low, env.action_space.high)

        if gail:
            rew = reward_giver.get_reward(observation, clipped_action[0])
            observation, true_rew, done, _info = env.step(clipped_action[0])
        else:
            observation, rew, done, _info = env.step(clipped_action[0])
            true_rew = rew
        rews[i] = rew
        true_rews[i] = true_rew
        dones[i] = done
```

Starting with  `i = step % horizon` which defines the index. Then, you save the observations and actions for the current time step in lines 86 and 88, respectively. Then you clip the action and finally call `env.step()` in line 98 (if using Gail) or line 100 (otherwise). That function returns the flag `done` which is saved in line 104, in the same index as defined in line 85. So, in practice, the flag marks if this is the last step of an episode.

**Comment by araffin** [comment]
I see... seems like a legit bug then.
Feel free to submit a PR ;)

**Comment by miguelrass** [comment]
Sorry, I don't have time right now. I was hoping you could solve it. Otherwise, I can only do it in August.

**Comment by araffin** [comment]
I will push a fix soon.
Apparently the bug was introduces here: https://github.com/hill-a/stable-baselines/commit/0de65ed183832ecf0121358e7f4dec7ae1552beb
in an attempt to remove duplicate variable... (dones was used only for logging before)

**Comment by araffin** [comment]
@miguelrass btw, thanks for spotting the bug! (you have been credited in the changelog)
and I'm seeing significant improvements for TRPO on harder problem (like the bullets envs (mujoco like)).

**Comment by miguelrass** [comment]
Good to know! Thanks for the credit!
