### ISSUE TITLE
[Feature Request] Use opencv-python-headless

### ISSUE THREAD

**Issue by neighthan** [hill-a/stable-baselines#389]
Is there any reason that `opencv-python` is needed instead of just `opencv-python-headless`? If not, using the latter as a dependency instead makes things easier on headless machines (otherwise, you're missing things like `libSM.so`). If there is some `opencv-python` functionality that's being used, is there any reasonable way to check whether a machine is "headless" and change the dependency based on that?

**Comment by araffin** [comment]
Hello,

Do you know exactly which features exactly are not present in the headless version?

>makes things easier on headless machines

It removes only some dependencies, no? If you want a ready to use headless environment, you can take a look at the docker image ;)

>If there is some opencv-python functionality that's being used, 

Maybe the `cv2.imshow()` if it is part of it.
