### ISSUE TITLE
HER model don't learn again after load previously learned model.

### ISSUE THREAD

**Issue by kjacek** [hill-a/stable-baselines#394]
It seems HER model don't learn again after load previously learned model.

```
model = HER.load('her_bit_env', env=env)
model.learn(1000)
model.save("her_bit_env")
```

I got exactly the same effect after test.
Stable baselines v.2.6

**Comment by araffin** [comment]
Hello,

I tried to reproduce the described behavior but couldn't ...

```python
from stable_baselines import HER, DQN, SAC, DDPG
from stable_baselines.her import GoalSelectionStrategy, HERGoalEnvWrapper
from stable_baselines.common.bit_flipping_env import BitFlippingEnv

model_class = DQN  # works also with SAC and DDPG

N_BITS = 20

env = BitFlippingEnv(N_BITS, continuous=model_class in [DDPG, SAC], max_steps=N_BITS)


goal_selection_strategy = 'future' # equivalent to GoalSelectionStrategy.FUTURE

# Wrap the model
model = HER('MlpPolicy', env, model_class, n_sampled_goal=4, goal_selection_strategy=goal_selection_strategy,
                                                verbose=1)
# Train the model
# it reaches a success rate of ~30% (mean reward:-17)
model.learn(20000)

model.save("./her_bit_env")

# WARNING: you must pass an env
# or wrap your environment with HERGoalEnvWrapper to use the predict method
model = HER.load('./her_bit_env', env=env)

# train again
# this time it reaches 100% success rate (mean reward=-9)
model.learn(20000)
```

PS: Please provide a minimal **working** example next time (it was not enough to reproduce the behavior)

**Comment by kjacek** [comment]
Hello,
Works fine in my custom gym. 
I noticed  learning e.g 5 times * n steps  is not the same as once  5*n  steps. 
Second is better.

**Comment by araffin** [comment]
> I noticed learning e.g 5 times * n steps is not the same as once 5*n steps.

Can you elaborate on that? does not seems right.

**Comment by rlan** [comment]
@araffin In light of your comment in https://github.com/hill-a/stable-baselines/issues/301#issuecomment-489308597, does HER have a perfect recovery or no?

**Comment by araffin** [comment]
as it is using off-policy algorithms, it does not by default. the most important thing missing would be the replay buffer, that you can save easily by yourself.
