### ISSUE TITLE
[question]  How to return a custom variable from DummyVecEnv

### ISSUE THREAD

**Issue by maxmatical** [hill-a/stable-baselines#398]
I have a custom environment where I want to return some intermediate variables from states, such as raw input values before performing preprocessing. Is there a way to do this? I tried to create a function to return values such as `def _return_values(self)` but when I try to run `CustomEnv._return_values()` I get `AttributeError: 'DummyVecEnv' object has no attribute '_return_values'`

**Comment by araffin** [comment]
Hello,
The answer is in the documentation, this is called `env_method`.

**Comment by maxmatical** [comment]
can you explain how to use `env_method`? I tried to do `test_env.env_method(_return_values)` but I get an error saying `NameError: name '_return_values' is not defined
`

**Comment by araffin** [comment]
It seems the base class is not in the documentation... I will add that in #392.
The method signature:

```python
def env_method(self, method_name, *method_args, indices=None, **method_kwargs):
        """
        Call instance methods of vectorized environments.

        :param method_name: (str) The name of the environment method to invoke.
        :param indices: (list,int) Indices of envs whose method to call
        :param method_args: (tuple) Any positional arguments to provide in the call
        :param method_kwargs: (dict) Any keyword arguments to provide in the call
        :return: (list) List of items returned by the environment's method call
        """
        pass
```

`method_name` must be a string.

**Comment by maxmatical** [comment]
Fantastic, that works, thank you so much!

**Comment by missBanerjee** [comment]
I have a custom environment named 'CumstomEnv' where I wrote a custom function def _start(self), but when I tried to do test_env.env_method(CustomEnv._start(test_env),indices=None) , it is giving me an error 'DummyVecEnv' object has no attribute 'dataset' . The function _start() is accessing the variable dataset . Can you please help.

**Comment by hanyang1986** [comment]
> Fantastic, that works, thank you so much!

Hi Max , could you explain more explicitly how you have solved the problem.

Many thanks
