### ISSUE TITLE
[feature request] Get last observation in trajectory with vecenv

### ISSUE THREAD

**Issue by qxcv** [hill-a/stable-baselines#400]
At present, the stable-baselines vecenv implementations drop the last observation in each trajectory (i.e the one for which `.step()` returns `done=True`) & replaces it with an initial observation produced by `.reset()`. For instance, in `DummyVecEnv`, the end of a trajectory is handled [as follows](https://github.com/hill-a/stable-baselines/blob/0e940c791e5f625c07fb4ffa9e042aeb0288caf3/stable_baselines/common/vec_env/dummy_vec_env.py#L39-L43):

```python
obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] =\
    self.envs[env_idx].step(self.actions[env_idx])
if self.buf_dones[env_idx]: 
    # drops observation for which `.step()` reported `done=True`
    obs = self.envs[env_idx].reset()
self._save_obs(env_idx, obs)
```

This seems like a reasonable design choice for many RL algorithms, but there are also combinations of environment & algorithm for which having all `(s,a,s')` transitions—including the last one—is useful. For example, [GAIL-from-observations](http://www.ifaamas.org/Proceedings/aamas2019/pdfs/p2229.pdf) recovers an imitation policy by learning a reward function of the form `r(s,s')` on (state, next state) tuples that scores how "demonstrator-like" a trajectory is. If the last state in each trajectory is very informative (e.g perhaps the final screen in an arcade game says "you lost!" or "you won!"), then the imitation learning algorithm will find it much easier to learn an accurate reward function if it has access to the final `(s,a,s')` transition.

There are a few ways of giving users access to the last state in each rollout. One minimally-invasive way would be to add it to `buf_infos` under a descriptive name like `"done_new_obs"` whenever the episode terminates. Does this seem like a reasonable change?

**Comment by AdamGleave** [comment]
:+1: on this issue -- it's a real problem when collecting data for imitation learning algorithms. In environments where the ground truth is a sparse reward, it makes it impossible for the model to accurately capture the reward.

I have a mild concern with modifying the `infos` dict, since consumers may not be expecting a new key. An alternative would be to add some property, `obs_before_reset`, and then samplers can if desired query this for environments with a `done` flag.

**Comment by araffin** [comment]
Modifying the infos dict is not usually a problem, as users should only look for certain keys, and adding more infos should not break things. As an example, some gym wrappers (like the Monitor wrapper) add some (undocumented) keys to the info dict.

However, for the name, I'm not sure what to choose:
- `done_new_obs` is a bit confusing for me
- `obs_before_reset` seems ok even though I'm not completely sure
- `last_observation` would be also confusing
- `episode_end_observation` ? seems also odd

**Comment by AdamGleave** [comment]
Ah yes, I forgot that behavior of `Monitor`, probably OK for us to add keys then.

For the name, how about `terminal_observation`?

**Comment by araffin** [comment]
+1 for the name ;)
