### ISSUE TITLE
test action space not clipping in Colab

### ISSUE THREAD

**Issue by SOGorman35** [hill-a/stable-baselines#402]
I installed 2.6.0 in Colab, and nothing else other than the additional dependencies that came along with it.  Basically, when training a model with continuous action space, it stays within the boundaries (which are 0-1), but once I get to testing, it doesn't clip the actions.  I can't comment on whether the same issue occurs with observation space since my observations are pre-scaled.  I tried this with both PPO2 and A2C models.

Switching from colab to my personal computer, with the exact same script, and the clipping issue goes away.  Just wondering if this is a bug, or if there is something else I should be installing in addition to 2.6.0 on Colab.

**Comment by araffin** [comment]
Hello,
Could you share the colab link and fill up the issue template ?

**Comment by araffin** [comment]
I suspect that stable-baselines was not properly upgraded on colab.
Could you check the version using:
```python
import stable_baselines as sb
print(sb.__version__)
```

**Comment by SOGorman35** [comment]
yeah, looks like brain fade on my part.  Version was out of date.
