### ISSUE TITLE
[question] For MlpLstmPolicy, does state get saved when model is saved/loaded?

### ISSUE THREAD

**Issue by maxmatical** [hill-a/stable-baselines#405]
If I trained an agent on some task, evaluated it on a custom test environment, but I want to preserve the state of the LSTM (say `h_t`) and test it on a separate environment that continues from the previous test environment, so I would want the LSTM to maintain `h_t` and continue to `h_t+1` in the next step. If I save and load the model, will it keep the state `h_t`?

**Comment by araffin** [comment]
Hello,
What you are looking for is already in the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#recurrent-policies) ;)

**Comment by maxmatical** [comment]
Hi,

I've read through the documentation, but it does not seem to address the state of the policy after saving/loading.

From what I've read, it seems like the policy stores the latest state unless we specifically specify `state = None`, so if that's the case, the hidden state `h_t` should be preserved when saving and loading the model. Is this correct? Thank you.

**Comment by araffin** [comment]
I don't think it is, because it is not part of the weights. When calling `get_parameters_list()` (on PPO2 with lstm policy), here is what I get:
```
[<tf.Variable 'model/pi_fc0/w:0' shape=(4, 64) dtype=float32_ref>,
 <tf.Variable 'model/pi_fc0/b:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'model/pi_fc1/w:0' shape=(64, 64) dtype=float32_ref>,
 <tf.Variable 'model/pi_fc1/b:0' shape=(64,) dtype=float32_ref>,
 <tf.Variable 'model/lstm1/wx:0' shape=(64, 1024) dtype=float32_ref>,
 <tf.Variable 'model/lstm1/wh:0' shape=(256, 1024) dtype=float32_ref>,
 <tf.Variable 'model/lstm1/b:0' shape=(1024,) dtype=float32_ref>,
 <tf.Variable 'model/vf/w:0' shape=(256, 1) dtype=float32_ref>,
 <tf.Variable 'model/vf/b:0' shape=(1,) dtype=float32_ref>,
 <tf.Variable 'model/pi/w:0' shape=(256, 2) dtype=float32_ref>,
 <tf.Variable 'model/pi/b:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'model/q/w:0' shape=(256, 2) dtype=float32_ref>,
 <tf.Variable 'model/q/b:0' shape=(2,) dtype=float32_ref>]
```

`wh` is present but no hidden state.

As shown in the documentation, you should in your case save the state and pass it when reloading the model.

**Comment by maxmatical** [comment]
I can't seem to find where in the documentation does it show an example of saving state and passing it when loading the model, can you provide and example please? Thank you.

**Comment by araffin** [comment]
The documentation shows how to get and pass the state, which is just numpy array, so you can use `np.save` and `np.load` in that case.

**Comment by maxmatical** [comment]
I see, so I can manually save and load the state. Thanks for the clarification.

**Comment by rachlee93** [comment]
I understand how we can save/load the state when we're running the `model.predict` but if we're just saving and loading the model from checkpoints and callbacks, how can we extract and pass in the state?

**Comment by Miffyli** [comment]
Those are accessible through callbacks, e.g. [see this list of variables available for PPO2](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#callbacks-accessible-variables), where `mb_states` is the one storing hidden state of networks. However I am not sure why you'd want to store hidden state, as it only will work with that specific version of policy with that specific history of steps taken in the environment.
