### ISSUE TITLE
Cnn/CnnLstm/CnnLnLstmPolicy Example for Not Image Input 

### ISSUE THREAD

**Issue by Charles808** [hill-a/stable-baselines#408]
Hi, I just wondering if there is any example using Cnn-related policy ?

I read some other example from several references, but only able to find the example using the pre-built environment or with image as the input.

I'm fully aware that CNN usually used for images-related.

But, I need it for experimenting in Stock Trading.

I wonder, if there any example for Cnn-related policy in custom environment with stock price as the input. Not images.

Thank you

**Comment by araffin** [comment]
Hello,
I assume you are talking about 1D convolutions?
In the examples, the CNNPolicy uses 2D convolutions, so only suitable for images. Usually MlpPolicies are fine for 1D feature vector.

You can find an example of custom 1D convolution here: https://github.com/RGring/drl_local_planner_ros_stable_baselines/blob/master/rl_agent/src/rl_agent/common_custom_policies.py

**Comment by Charles808** [comment]
Indeed, 

Thank you for the references. I greatly appricated it !
