### ISSUE TITLE
[question] Tensorboard from callback as per documentation?

### ISSUE THREAD

**Issue by jamessergeant** [hill-a/stable-baselines#409]
The [documentation](https://stable-baselines.readthedocs.io/en/master/guide/examples.html?highlight=callback#using-callback-monitoring-training) states:

> You can define a custom callback function that will be called inside the agent. This could be useful when you want to monitor training, for instance display live learning curves in Tensorboard (or in Visdom) or save the best agent. If your callback returns False, training is aborted early.

I'm unable to determine how exactly to log to tensorboard from the callback, is anyone able to provide or point to an example?

**Comment by araffin** [comment]
Hello,
Good point.
Here is a simple example on how to log both additional tensor or arbitrary scalar value:

```python
import tensorflow as tf
import numpy as np

from stable_baselines import SAC

model = SAC("MlpPolicy", "Pendulum-v0", tensorboard_log="/tmp/sac/", verbose=1)
# Define a new property to avoid global variable
model.is_tb_set = False


def callback(locals_, globals_):
    self_ = locals_['self']
    # Log additional tensor
    if not self_.is_tb_set:
        with self_.graph.as_default():
            tf.summary.scalar('value_target', tf.reduce_mean(self_.value_target))
            self_.summary = tf.summary.merge_all()
        self_.is_tb_set = True
    # Log scalar value (here a random variable)
    value = np.random.random()
    summary = tf.Summary(value=[tf.Summary.Value(tag='random_value', simple_value=value)])
    locals_['writer'].add_summary(summary, self_.num_timesteps)
    return True


model.learn(50000, callback=callback)
```

**Comment by jamessergeant** [comment]
@araffin Thank you! Very much appreciated. It's a bit obvious now that I have your example, just hadn't had the time to dig through the code. An example of this might be useful to add to the documentation, but I will leave up to you maintainers :)

**Comment by araffin** [comment]
>An example of this might be useful to add to the documentation

Good point, I wil try to do that in the next PR.
