### ISSUE TITLE
Installation failed with error code 1:

### ISSUE THREAD

**Issue by saltypeanuts** [hill-a/stable-baselines#415]
Running WSL, Debian
`
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ivbxwoxi/mpi4py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-osw3rycg-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-ivbxwoxi/mpi4py`

Tried to update python per:

https://github.com/hill-a/stable-baselines/issues/99

`sudo apt install -u python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.`

**Comment by araffin** [comment]
Hello,
Please fill in the issue template.

The problem seems to be related to mpi4py, not stable-baselines ...
