### ISSUE TITLE
[question] HER import error

### ISSUE THREAD

**Issue by gandhiy** [hill-a/stable-baselines#416]
**Describe the bug**
I can't import HER but I can use other models/components of stable-baselines

**Code example**
```python
from stable_baselines import HER

```

```bash
WARNING:tensorflow:From /anaconda3/envs/unity/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.

Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HER'
```

**System Info**
Describe the characteristic of your environment:
 * pip install stable-baselines
 * Python 3.7
 * Tensorflow version 1.7.1

**Additional context**
I've been using other models (DDPG, DQN, PPO1/2, etc...) for training a unique environment and they all work fine, but I can't even import HER to use with DDPG. Has anyone else run into this error?

**Comment by araffin** [comment]
Hello,

HER is present only since v2.6.0.

Please upgrade you stable-baselines version:
```
pip install --upgrade stable-baselines
```

You can check the version (that should be included next time you open an issue) using:
```python
import stable_baselines as sb
print(sb.__version__)
```

**Comment by gandhiy** [comment]
I completely forgot to check my stable-baselines version. That was the issue. 

Thank you.
