### ISSUE TITLE
Error on from stable_baselines import PPO2

### ISSUE THREAD

**Issue by crilazar** [hill-a/stable-baselines#420]
**Describe the bug**
I came across PPO2 from stable_baseline and I wanted to give it a try. I installed stable_baselines using pip. I copied the example: Train a PPO agent on CartPole-v1 using 4 processes.

Executing line by line the example code, the following line gives me an error.

from stable_baselines import PPO2

**Code example**
import gym
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

**System Info**
Describe the characteristic of your environment:
 * the library was installed using Anaconda powershell prompt with "pip install stable_baselines"
 * GPU models and configuration;  no GPU available
 * Python version; Python 3.6.8 :: Anaconda custom (64-bit)
 * Tensorflow version:  1.13.1
 * Versions of any other relevant libraries

**Additional context**
from stable_baselines import PPO2

Error message printout:

from stable_baselines import A2C
Traceback (most recent call last):

  File "<ipython-input-14-ca71b5ca1bbe>", line 1, in <module>
    from stable_baselines import A2C

  File "C:\Users\crila\Anaconda3\lib\site-packages\stable_baselines\__init__.py", line 4, in <module>
    from stable_baselines.ddpg import DDPG

  File "C:\Users\crila\Anaconda3\lib\site-packages\stable_baselines\ddpg\__init__.py", line 1, in <module>
    from stable_baselines.ddpg.ddpg import DDPG

  File "C:\Users\crila\Anaconda3\lib\site-packages\stable_baselines\ddpg\ddpg.py", line 17, in <module>
    from stable_baselines.common.mpi_adam import MpiAdam

  File "C:\Users\crila\Anaconda3\lib\site-packages\stable_baselines\common\mpi_adam.py", line 5, in <module>
    import stable_baselines.common.tf_util as tf_utils

AttributeError: module 'stable_baselines' has no attribute 'common'

**Comment by araffin** [comment]
Hello,
Please fill in the issue template.

**Comment by crilazar** [comment]
I filled in the template.

**Comment by araffin** [comment]
You forgot to mention you were using windows.
Please follow the instructions in the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/install.html), I suspect you are missing some dependencies (especially mpi).

PS: Please use code blocks for code example (cf the issue template for how to use them)

**Comment by crilazar** [comment]
Many thanks. It works now.

**Comment by Karlheinzniebuhr** [comment]
> Many thanks. It works now.

did you just install MPI? I installed it but still getting the import error for PPO2
