### ISSUE TITLE
Error in `python': munmap_chunk(): invalid pointer: 0x00007f42ff355ee4

### ISSUE THREAD

**Issue by sheetalsh456** [hill-a/stable-baselines#421]
Hi,

I'm trying to install stable-baselines with the command:

`pip install stable-baselines`

This installs the version 2.6.0. But when I import it in my code as:

`from stable_baselines.common.policies import ActorCriticPolicy`

it gives me the following error:

     *** Error in `python': munmap_chunk(): invalid pointer: 0x00007f42ff355ee4 ***
     *** Process received signal ***
     Signal: Aborted (6)
     Signal code:  (-6)

The same installation has been working for me for the past 2 months, and this issue crept in only the day before yesterday. 

If needed, these are the python libraries that I'm installing before stable-baselines.

    numpy
    scipy
    matplotlib
    pandas
    requests
    cmake
    py-make
    atari-py
    Pillow
    gym
    tensorflow-gpu==1.5
    keras==2.1
    opencv-python
    OpenMPI
    mpi4py
  
Also, all these installations are being done in a python 3.6 conda environment. 

I'm not sure why this is happening all of a sudden. Can someone please look into this?

Any suggestions will be appreciated. 

Thank you! :)

**Comment by araffin** [comment]
Hello,
Could you please fill in the issue template completely? (notable os version, tf version and full traceback)
