### ISSUE TITLE
DDPG and SAC for discrete action space.

### ISSUE THREAD

**Issue by soloist96** [hill-a/stable-baselines#422]
[question] Is there any reason why DDPG and SAC don't have the implementation for discrete action space?  And will appreciate it there are any suggestions for applying the DDPG with continuous action space on the discrete one. Thanks!

**Comment by araffin** [comment]
Hello,
For DDPG, you can already find an answer here: https://github.com/hill-a/stable-baselines/issues/37
For SAC, the implementation with discrete actions is not trivial and it was developed to be used on robots, so with continuous actions. Those are the main reason. Meanwhile, if you want to work with discrete actions, you have plenty of other algorithms that can do that (ACER, PPO, DQN, A2C, ACKTR, ...).

**Comment by cosmir17** [comment]
It was more than a year ago. Any news on this topic recently @araffin ?
It would be nice if SAC can take discrete action space input.

**Comment by araffin** [comment]
We have an issue about that in Stable-Baselines3 repo: https://github.com/DLR-RM/stable-baselines3/issues/157

But I would favor QR-DQN first in the contrib repo.

**Comment by cosmir17** [comment]
Thank you for letting me know @araffin
