### ISSUE TITLE
[Question] Does loading a model only load the weights, or the hyperparameters as well?

### ISSUE THREAD

**Issue by maxmatical** [hill-a/stable-baselines#432]
I'm trying to save and load a model multiple times to train on Colab, and I just want to make sure that when I call model.load, I'm using the same hyperparameters as well.

**Comment by araffin** [comment]
Hello,
It does also load the hyperparameters.
However, I recommend you to check this issue: #301 

You can do a quick check doing:

```python
from stable_baselines import SAC

model = SAC('MlpPolicy', 'Pendulum-v0', buffer_size=123)
model.save('sac_test')

loaded_model = SAC.load('sac_test')
assert loaded_model.buffer_size == 123
```
