### ISSUE TITLE
Convert the model into TF or ONNX

### ISSUE THREAD

**Issue by ChengYen-Tang** [hill-a/stable-baselines#434]
I want to run the model in other languages. Is there any way to convert the model into TF or ONNX? 
Thank

**Comment by Miffyli** [comment]
There is no pre-built system for converting models to other formats directly, but you can use [`get_parameters`](https://stable-baselines.readthedocs.io/en/master/modules/a2c.html#stable_baselines.a2c.A2C.get_parameters) function to get model's parameters as a dictionary that maps variable names to numpy arrays containing the parameters. You have to create model architecture manually in your target framework and also make sure everything works exactly as in the stable-baselines code.

**Comment by ChengYen-Tang** [comment]
Thank you for answering my question.
