### ISSUE TITLE
1d cnn

### ISSUE THREAD

**Issue by chhung3** [hill-a/stable-baselines#436]
Will in the future the project support 1d cnn? I read from the Tensorflow Utils that only 2d is supported now.

Thanks for the work of the project btw. It highly facilitate our development so far ^^.

**Comment by Miffyli** [comment]
You can create custom policies (i.e. networks) from ground up according to your needs, including using 1D convolutions. [See this documentation page for how to do it](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html).

**Comment by araffin** [comment]
Hello,

as @Miffyli pointing out, you can use custom policies, this question was already answered here in fact ;):
https://github.com/hill-a/stable-baselines/issues/408 (there is a link to an example too)
