### ISSUE TITLE
What is the default network architecture for MlpLnLstmPolicy?

### ISSUE THREAD

**Issue by ktattan** [hill-a/stable-baselines#438]
I'm trying to create a [custom policy network](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html#examples), but I can't find the default architecture for an [MlpLnLstmPolicy](https://stable-baselines.readthedocs.io/en/master/modules/policies.html#stable_baselines.common.policies.MlpLnLstmPolicy) to benchmark against. The only thing I see is that MlpLnLstm has a shared LSTM network of default size 256, but I don't know the sizes and number of layers within the Value and Policy networks.

It would also be good to know if there are any activations or dropouts between layers (if applicable).

Thank you

**Comment by Miffyli** [comment]
Indeed it is not apparent directly what is default architecture, but you can find the essentials in [LstmPolicy's init](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L377):

Two layers of 64 units with tanh-activations, followed by the LSTM layer of 256 units. This is then split into value and policy functions. If you use CNN version, it use the network from Nature DQN paper ([code here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L15)) with ReLU activations.

**Comment by Hoiy** [comment]
which parameters determine the number of recurrent steps?

**Comment by Miffyli** [comment]
@Hoiy See #759 (answer: `n_steps`)
