### ISSUE TITLE
[Question] Is the objective to maximize general rewards or discounted rewards?

### ISSUE THREAD

**Issue by soloist96** [hill-a/stable-baselines#441]
This may be a general question for RL algorithms. Are they trying to optimize the episode rewards without discount or the discounted reward? When I use tensorboard to visualize the results, I found that the episode reward (without discount) goes up gradually but the discounted rewards can drop a bit. Thank you!

**Comment by Miffyli** [comment]
You can optimize for either-or, depending on the situation, but you more commonly see optimizing the discounted returns (including this repository). See e.g. [Spinning Up RL tutorial](https://spinningup.openai.com/en/latest/spinningup/rl_intro.html) for more info.

**Comment by soloist96** [comment]
@Miffyli  Thank you for the reply. Yes, my understanding is that we are optimizing the  discounted returns. However, when I try to run the PPO2 with discount factor 0.99, my episode reward goes to 60 in the end while my discounted reward is only 20. There're only 20 steps in the environment, meaning if I discount all the rewards, the least I should get for the discounted reward is 60*0.99^20 ~ 49. Could you explain the inconsistency I get from the results? Thank you.

**Comment by araffin** [comment]
i think the discounted reward uses the value function (cf code), which usually overestimates the value of a state, so that sounds normal.

**Comment by Miffyli** [comment]
If you start tracing back from [PPO2 code where tensorboard logs these](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L215), you will end up to part where returns are calculated via [GAE computations](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L500). I do not know if this should end up to standard returns in the end, it could causing this discrepancy (would be fun to dig deeper, but currently taking days off from bigger headaches).

**Comment by araffin** [comment]
as @miffyli wrote, you can optimize for one or the other (setting gamma to one). In practice, most algorithms use the discounted return. SAC have a slightly different objective: it tries to maximize the entropy in addition to the discounted return.
