### ISSUE TITLE
[question] Error in DummyVecEnv

### ISSUE THREAD

**Issue by kosmylo** [hill-a/stable-baselines#443]
**Describe the bug**
I have created a custom environment and I want to train it with PPO. As I am trying to run it I get the following error: 

```bash

  File "c:\users\com\documents\github\stable-baselines\stable_baselines\common\vec_env\dummy_vec_env.py", line 69, in _save_obs
    self.buf_obs[key][env_idx] = obs

ValueError: could not convert string to float: :

```

**Code example**

```python
import gym
from LVEnv import *

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

#gym.envs.register(id='LVEnv-v0', entry_point='LVEnv:LVEnv', max_episode_steps=1440)
# The algorithms require a vectorized environment to run
env = gym.make("LVEnv-v0")
env = DummyVecEnv([lambda: env])
model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=20000)
obs = env.reset()

for i in range(2000):
  action, _states = model.predict(obs)
  obs, rewards, done, info = env.step(action)
  env.render()

```

**System Info**
 * The library was installed via docker and conda

**Comment by araffin** [comment]
hello,
please fill the issue template.

**Comment by kosmylo** [comment]
> hello,
> please fill the issue template.

Done! Sorry for the omission.

**Comment by araffin** [comment]
hello,
it seems that the issue comes from your environment, please double check the type and shape of each variable returned. what is your observation space?

**Comment by kosmylo** [comment]
> hello,
> it seems that the issue comes from your environment, please double check the type and shape of each variable returned. what is your observation space?

In general my environment corresponds to power network with some houses and I want to use a battery to learn to charge and discharge in the right moments. 

```python
def __init__(self):
        super(LVEnv, self).__init__()

        self.action_space = spaces.Box(
            low = -25.0, high = +25.0, shape=(1, ), dtype = np.float32)

        self.observation_space = spaces.Box(low = np.array([0.0, 0.0, 0.0, 0.0, 0.0]), high = np.array([1.0, 27.34, 1.0, 239, 3.3]), dtype = np.float32)
```

I have to mention that by replacing DummyVecEnv with SubprocVecEnv I do not really get a mistake and the algorithm runs, but I do not know if I can use some callbacks to see if the training goes on or if it sticks somewhere else.
