### ISSUE TITLE
[question] Enforcing history into the observation space

### ISSUE THREAD

**Issue by kosmylo** [hill-a/stable-baselines#457]
Is it possible somehow to enforce the past observations by augmenting the observations space in the current time step? Let's say keeping in the memory the observations from the last 4 time steps.

**Comment by araffin** [comment]
Hello,
Answer is in the documentation, it is called `VecFrameStack`.

**Comment by kosmylo** [comment]
Thanks for the answer. Since this is a wrapper and returns what the step function actually returns it has to be executed when I instantiate my environment like the following:

`env = gym.make("custom_env-v0")`
`env = DummyVecEnv([lambda: env])`
`env = VecFrameStack(env, 12)`

or in my custom_env?

**Comment by kosmylo** [comment]
Thanks!

**Comment by kosmylo** [comment]
By using `VecFrameStack` do I have to do any other modification in the policy that I use in order to activate looking back in the history? With the rewards does something similar hold?

**Comment by araffin** [comment]
>do I have to do any other modification in the policy that I use in order to activate looking back in the history?

VecFrameStack is a wrapper and modify only the environment, you don't need to modify the policy.
If you want to modify the input space, then you need to learn more about them.
We recently created a tutorial that cover that topic: https://github.com/araffin/rl-tutorial-jnrr19
