### ISSUE TITLE
[Question] Policy-ratio in PPO2

### ISSUE THREAD

**Issue by kazadwache** [hill-a/stable-baselines#458]
Hi, I have a question to understand your implementatoin of PPO2: While debugging through the implementation  I noticed that in the first execution of ppo2.py:_train_step the ratio of the old and new policy is unequal to 1.  (To make the value observable I have added it to the output of session.run) 
Shouldn't the ratio equal 1 in the first training step because the policy hasn't been updated yet?

**Comment by araffin** [comment]
Hello,

You are right the ratio should be one.
I also debugged it and most of the time, there is no problem, in some trial, I think it is because of numerical precision, you get a number very close to one (e.g. 0.99999994) but not equal to it.

You can do a sanity check using:
```python
from stable_baselines import PPO2

PPO2("MlpPolicy", "CartPole-v1", learning_rate=0.0).learn(500)
```
