### ISSUE TITLE
[Question] Continue Learning with different action space

### ISSUE THREAD

**Issue by Eastonboy99** [hill-a/stable-baselines#459]
Hello,

I am just starting out with reinforcement learning so pardon me if this is a simple or dumb question. I trained a model to play FZero on the SNES for about 8 hours. I now want to take what that model learning and increase the action space. Is this possible? I thought I could since I'm not taking anything away, just adding, but stable-baselines says I need to have the same action space in the environment for the model to use it

**Comment by Miffyli** [comment]
Matching action spaces are checked under the hood for sanity to avoid more obscure error messages. You could load up the trained model without an environment and use it to predict actions, which you then modify by hand to remove the actions you do not want to be included.
