### ISSUE TITLE
[Question] Reset to a Pickled Snapshot instead of the Initial State

### ISSUE THREAD

**Issue by batu** [hill-a/stable-baselines#46]
Hello, 

I am trying to extend stable-baselines to allow resetting to arbitrary "snapshot points" instead of the start  to increase exploratory capabilities of an agent.

I wanted to ask you the best way to go about doing this. Here is my current approach:

I created a SnapshotVecEnv inheriting from VecEnv. In addition to everything in the DummyVecEnv (I hope to multi thread it at some point) it has several additional functions mostly based on this [PR](https://github.com/openai/gym/pull/575):

```
save_snapshot(self):
    # use pickle to return a snapshot of the whole environment 
    # This will be called, for now, at random points within training.
    # I plan on keeping the saved snapshots within the SnapshotVecEnv per environment.

load_snapshot(self, snapshot):
   # set the current environment to the loaded snapshot
   # This will be called whenever the environment resets.
```

The main question I have is about the way the resetting is handled. Couldn't seem to figure out just yet. If you have time can you give me an overview of it? 

Also, I would be glad if you could point any possible flaws you see.

Thank you very much.

**Comment by araffin** [comment]
Hi,

>I am trying to extend stable-baselines to allow resetting to arbitrary "snapshot points" instead of the start >to increase exploratory capabilities of an agent.

I'm not sure to see the use case of this. It looks like resetting at a particular checkpoint instead of starting from the beginning? Maybe in Atari games like montezuma revenge, it could be useful, right?

>The main question I have is about the way the resetting is handled. Couldn't seem to figure out just yet

Could you elaborate on that?

**Comment by batu** [comment]
Yes, that is the idea. To ensure that the agent is more efficiently exploring a "novel frontier" instead of treading similar ground. 

I am not familiar with multithreaded programming and I couldn't figure out where the "resetting" was handled. (I was looking into the runner class, not the environment.) 

Currently creating a vectorized_snapshot environment that allows users to set snapshot routines. Let me know if that type of functionality is something you might be interested in supporting in the future

**Comment by aswin-raghavan** [comment]
Why was this issue closed?
