### ISSUE TITLE
No module named 'stable_baselines.sac/td3' when using Colab

### ISSUE THREAD

**Issue by maxmatical** [hill-a/stable-baselines#464]
On Colab, when I try to import `MlpPolicy` from either TD3 or SAC

```
!pip install stable-baselines

from stable_baselines.sac.policies import MlpPolicy as SAC_MlpPolicy
from stable_baselines.td3.policies import MlpPolicy as TD3_MlpPolicy

```
 I end up with the following error

```
ModuleNotFoundError: No module named 'stable_baselines.sac'

```

However I do not get the same issue with `from stable_baselines.common.policies import MlpPolicy` and have no issues importing the MlpPolicy from sac.policies on my own computer (MacOS)

**Comment by araffin** [comment]
Hello,
Please upgrade stable-baselines, or install the latest version:
```
!pip install stable-baselines --upgrade
```

```
!pip install stable-baselines==2.7.0
```

**Comment by Danilo-Araujo-Silva** [comment]
It looks like the most recent version of "stable-baselines[mpi]" is somehow broken.

I fixed using:

```
!pip install stable-baselines[mpi]
!pip install stable-baselines --upgrade
```

**Comment by araffin** [comment]
>It looks like the most recent version of "stable-baselines[mpi]" is somehow broken.

what do you mean?

**Comment by Danilo-Araujo-Silva** [comment]
> > It looks like the most recent version of "stable-baselines[mpi]" is somehow broken.
> 
> what do you mean?

So, I don't really know how to explain, but I was trying to use a project that was using stable baselines as a dependency on Colab. The project wasn't working until I did the mentioned above. If I remember properly, I was receiving an error like "ModuleNotFoundError: No module named 'stable_baselines.sac'". I was able to fix it installing the mpi and then calling the upgrade in the other one (but the second dependency was not being used directly in the project, actually).

**Comment by ameenpv** [comment]
> It looks like the most recent version of "stable-baselines[mpi]" is somehow broken.

Its true. I have the same error stating: "ModuleNotFoundError".

> I fixed using:
> 
> ```
> !pip install stable-baselines[mpi]
> !pip install stable-baselines --upgrade
> ```

Not for me. Any other workarounds?

**Comment by araffin** [comment]
Hello,
I just tried the [getting started notebook](https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/master/stable_baselines_getting_started.ipynb) from the documentation and it worked as expected...
