### ISSUE TITLE
[question] Adding replay buffer to DDPG and TD error question

### ISSUE THREAD

**Issue by r7vme** [hill-a/stable-baselines#47]
Hello. I want to add prioritization to replay buffer (similar to one in [deepq](https://github.com/hill-a/stable-baselines/blob/cc083d7eeb2f2431da590005519bce276a8aa29a/stable_baselines/deepq/replay_buffer.py#L70)).

As far as i can see i can extend exitising `Memory` class. Seems quite straight forward.

The second thing that i want to do is to compute priorities based on TD error (like [here](https://github.com/hill-a/stable-baselines/blob/cc083d7eeb2f2431da590005519bce276a8aa29a/stable_baselines/deepq/dqn.py#L230)). Unfortunately i see no explicit TD error definition in [ddpg](https://github.com/hill-a/stable-baselines/blob/cc083d7eeb2f2431da590005519bce276a8aa29a/stable_baselines/ddpg/ddpg.py).

Can you please point me out how i can get TD error for DDPG?

Thanks

**Comment by araffin** [comment]
Hello,

For the td error, I think the definition is the same (r_t + \gamma * V(s_{t+1} - V(s_t)), see [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/deepq/build_graph.py#L408) for DQN, and [1](https://github.com/hill-a/stable-baselines/blob/cc083d7eeb2f2431da590005519bce276a8aa29a/stable_baselines/ddpg/ddpg.py#L355), [2](https://github.com/hill-a/stable-baselines/blob/cc083d7eeb2f2431da590005519bce276a8aa29a/stable_baselines/ddpg/ddpg.py#L449) for DDPG (even though the td error is less clear in DDPG implementation).

As a side note, @hill-a was working on merging the two replay buffer implementations (DQN and DDPG).

**Comment by r7vme** [comment]
@araffin thanks for the answer, it would definitely help if i'll go with prioritization. I had some success even w/o prioritization. So closing the issue.
