### ISSUE TITLE
PPO2 exploration of the action space

### ISSUE THREAD

**Issue by jviquerat** [hill-a/stable-baselines#473]
Hi,

I am trying to set up an optimization problem using PPO2 by using ***one-step episodes***, as was successfully done in this preprint https://arxiv.org/abs/1908.09885 (using tensorforce). The problem I am considering here with stable-baselines is different than that of the paper. Long story short, the goal is to find the optimal position of an object in a 2D space.

I set up a custom environment, and I ask the agent to provide me with a new position at every episode, after what a FEM computation is required to compute the reward. My action space is [0,1]^2, which I then transform into a ring [r_min,r_max]x[theta_min,theta_max]. I should note that I am using ```SubprocVecEnv``` with 64 parallel envs, and that I am updating the network after every 64 runs (so if I am not wrong, ```n_steps=1```). 

I am monitoring the actions taken by the agent and plotting them in 2D. What I noticed is that the agent spends most of its actions hitting points on the [x,0] and [0,y] lines, as shown in this figure (this is the transformed action space, ie the ring I was talking about earlier) : 

<img width="636" alt="Capture d’écran 2019-09-13 à 09 38 02" src="https://user-images.githubusercontent.com/44053700/64845357-3fce1c00-d60a-11e9-9e4a-8c2593f2dea8.png">
 
I observe the same behavior wether I provide systematically the same initial state in ```reset``` or I call ```self.action_space.sample()``` to obtain a different initial state at each ```reset```.

My question is : Is that a standard behavior ? I would expect more variability, but I may be wrong.

**Comment by araffin** [comment]
Hello,

> using PPO2 by using one-step episodes

You problem seems more suited for black box optimization (a good start would be CMA-ES).

>My action space is [0,1]^2, which I then transform into a ring [r_min,r_max]x[theta_min,theta_max].

to be sure, the agent acts in the first space?

>I should note that I am using SubprocVecEnv with 64 parallel envs

Is there a reason of using that much environments?

>What I noticed is that the agent spends most of its actions hitting points on the [x,0] and [0,y] lines, as shown in this figure

To sum it up, you agent outputs an action of dimension two that lies in [0, 1] (radius) x [0, 1] (angle) and then you convert it to the unnormalized values?

I think you can find your answer to your question in [this thread](https://twitter.com/araffin2/status/1111983313676312576) and in the [documentation](https://stable-baselines.readthedocs.io/en/master/modules/policies.html)

In short: because the actions are sampled from a gaussian (initially centered at 0 with std 1),  it will saturate during exploration (by sampling negative values).
So you have two solutions:
- make the action space symmetric ([-1, 1])
- use an algorithm that can handle properly those limits (like SAC, TD3 or DDPG) (they also required symmetric action spaces but are better at handling limits)

**Comment by jviquerat** [comment]
> Hello,
> 
> > using PPO2 by using one-step episodes
> 
> You problem seems more suited for black box optimization (a good start would be CMA-ES).

Indeed, but this is a first toy problem to set things up before moving to (much) more degrees of freedom. In general, we are considering problems that could be solved either by formulating it as a control problem, or as an optimization problem. This is why we started to explore one-step episodes.

> 
> > My action space is [0,1]^2, which I then transform into a ring [r_min,r_max]x[theta_min,theta_max].
> 
> to be sure, the agent acts in the first space?

Yes

> 
> > I should note that I am using SubprocVecEnv with 64 parallel envs
> 
> Is there a reason of using that much environments?

The reward is the result of a finite element computation, which can, in general, be computationally expensive, although it is not systematically profitable to run this FEM computation in parallel (small problem, long physical time to compute). Using parallel environments allows me to save a lot of time.

> 
> > What I noticed is that the agent spends most of its actions hitting points on the [x,0] and [0,y] lines, as shown in this figure
> 
> To sum it up, you agent outputs an action of dimension two that lies in [0, 1] (radius) x [0, 1] (angle) and then you convert it to the unnormalized values?

Yes

> 
> I think you can find your answer to your question in [this thread](https://twitter.com/araffin2/status/1111983313676312576) and in the [documentation](https://stable-baselines.readthedocs.io/en/master/modules/policies.html)
> 
> In short: because the actions are sampled from a gaussian (initially centered at 0 with std 1), it will saturate during exploration (by sampling negative values).
> So you have two solutions:
> 
> * make the action space symmetric ([-1, 1])
> * use an algorithm that can handle properly those limits (like SAC, TD3 or DDPG) (they also required symmetric action spaces but are better at handling limits)

Indeed, this is precisely the answer I was looking for. I will go for the first option. 
I have another question, but will open a specific issue for it.
