### ISSUE TITLE
[question] How to use a trained agent in a production setting using a custom environment?

### ISSUE THREAD

**Issue by maxmatical** [hill-a/stable-baselines#477]
For example, if I created a custom environment for tic-tac-toe and trained an agent on it. How do I actually use the trained agent in a live setting? My current workflow is:

1. Load the custom environment with the current observation
2. `obs = env.reset()`
3. Get an action from `model.predict(obs)` optionally include `state = state` for recurrent policies
4. Manually perform the action, and observe the next step and save the latest state ( so there would not be a `env.step()` since there's no further observations)
5. Create a new environment with the latest observation and repeat this process

Is there a better way to actually use the agent to perform a task without continuously redefining a new environment? 

Optionally, is there a way to incorporate online learning into this process? Such that I can calculate a reward and use that to train the agent for additional steps based on the live feedback?

**Comment by Miffyli** [comment]
I do not quite understand the "create a new environment". If your environment follows Gym API, you can do the following (works for recurrent policies too):

```python
env = env.make("your_env_here")
agent = PPO2.load(path_to_model)
state = None
done = False
obs = env.reset()

# Play some limited number of steps
for i in range(1000):
    action, state = agent.predict(obs, state=state, mask=done)
    obs, reward, done, info = env.step(action)
    if done: 
        # Game over, reset env
        # and agent's hidden state
        state = None
        obs = env.reset()
```

Online learning: Also discussed in #466 , stable-baselines does not support individual update steps  and there are no plans on including it. However in your case you could try using `learn` function to achieve this, like so:

1) Load/initialize agent, create your tic-tac-toe environment
2) Start agent learning with `learn()`
3) Every call to environment's `step`, the environment executes agent's action **and then asks human (or other) player for their action, and executes that**.

This way the other players are "part of the environment" on which the agent learns. [This self-play environment](https://github.com/Miffyli/ToriLLE/blob/master/experiments/stable_baselines_experiments/competitive_env.py) uses same approach. Note how `player2` actions are done in `step` and `reset` functions.

**Comment by maxmatical** [comment]
The issue I'm encountering is that after the agent is trained, I want to be able to use it in a live setting (so it would take in new observations from the real world), then perform based on what it observes.

in the tic-tac-toe example, after an agent takes an action, there would be no more observations until it receives some sort of live feedback (say a real player makes a move). So I can't necessarily use a for loop because in the `env.step(action)` step, there would be no more observations

**Comment by Miffyli** [comment]
Do you mean the game would end prematurely / the other player (human) never makes their move? In that case you can encode the this behavior in the `step` function of your game: If no action from human player is received in N seconds, return some dummy observations and `done=True` to tell game is over. 

From the agent's point-of-view it does not matter if the underlying environment takes long time to respond, as long you keep feeding observations/states/masks in the correct order and reset them accordingly.

**Comment by maxmatical** [comment]
I mean more in a sense that the environment has no more observations until I make a move. For example

1. Agent makes a move
2. I make a move
3. Here the environment needs to be updated with my move as a new observation
4. Now I can do the `env.step(action)` 

What I'm missing is pt 3. It needs some way of integrating real world observations into the agent before making a step.

>as long you keep feeding observations/states/masks in the correct order and reset them accordingly.
This is what I'm trying to do. My current process is to re-create the environment just with that 1 new observation/state, then reset the environment and let the agent make 1 action. I'm wondering is that a better way to continuously feed the environment new observations that aren't generated automatically

**Comment by Miffyli** [comment]
I think asking for the player 2's (human) action inside the step function would work fine. I do not see why the environment could not exist/stay alive while we wait for human's action

For example:
```python
def step(self, action):
    # Do agent's action
    self.game.make_turn(action)
    if self.game.is_over:
        # If game is over, return already with correct reward
        ....
    # Request human for action. `get_player2_action`
    # returns with human's action once it is available
    human_action = get_player2_action()
    self.game.make_turn(action)
    if self.game.is_over:
        # Check if game is over again
        ....
    return self.game.state, 0, False, {}

**Comment by maxmatical** [comment]
A problem I'm applying this to in a production setting is a scheduling problem. So all the observations are in the from of a dataframe. In a production setting, if I were to deploy this agent to production, it would:
- only see 1 observation corresponding to the latest state (1 row in the dataframe)
- the agent takes an action
- then wait for the next row of the dataframe to be populated (as a result of the agent's actions and other external factors)

Would creating a function that takes the new row in the dataframe, then adding that as the latest observation (similar to what you described) be the right approach? Is there any code examples that I can reference?

Since I am continuously adding new observations, do I need to reset the observations at all? Looking at the answer from this comment https://github.com/hill-a/stable-baselines/issues/378#issuecomment-503519101

>Also, dont forget that your reset() also gets the latest observation and returns it.

**Comment by Miffyli** [comment]
Ah alright, so the final environment is different from tic-tac-toe. I can not give you right answers here on what would work best as this is the "research" part of RL: You have to try out things yourself and see what works best, unless you find references for this (I do not know any).

On resetting: It depends on what your environment is like. I recommend reading on "trajectories" and "terminal states", e.g. [from Spinning Up tutorials](https://spinningup.openai.com/en/latest/spinningup/rl_intro.html).
