### ISSUE TITLE
Error using exported PPO2 graph: Matrix size-incompatible

### ISSUE THREAD

**Issue by aumfer** [hill-a/stable-baselines#478]
I've trained up a model using `stable_baselines.PPO2` with `MlpPolicy`, exported it using `tf.saved_model.simple_save`, and imported it using `TF_LoadSessionFromSavedModel`.

Everything seems fine when I load the model

> 2019-09-17 20:34:06.797657: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2019-09-17 20:34:06.897365: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 163246 microseconds.

But then when I attempt to run a prediction I receive this error

> Matrix size-incompatible: In[0]: [6144,1], In[1]: [6144,64]
         [[{{node model/vf_fc0/MatMul}}]]

I thought maybe I was using the wrong input/output tensor, but after poking around the code a bunch and trying some other random ones, I don't think that's it. My input tensor should be size [6144,1]

Any ideas?

**Comment by aumfer** [comment]
`tf.saved_model.simple_save` export is based off on the code discussed https://github.com/hill-a/stable-baselines/issues/474 and https://github.com/hill-a/stable-baselines/issues/329

**Comment by Miffyli** [comment]
Do you happen to be using `MlpPolicy` with inputs of 6144 elements? Judging by the error you are feeding in one sample but the model is compiled for 64, resulting in invalid matmul. Try padding your input with zeros so that it has 64 samples. If this works, the action for your real sample should be the first element in the resulting array.

I assume either `simple_save` or `TF_LoadSessionFromSavedModel` sets the batch-dimension to a fixed number rather than a dynamic one like used in stable-baselines (which allows prediction on single sample and training on multiple samples).

**Comment by aumfer** [comment]
Strange...that gives me 

> Matrix size-incompatible: In[0]: [6144,64], In[1]: [6144,64]
	 [[{{node model/pi_fc0/MatMul}}]]

The weird thing is that `model/pi_fc0` is not the input or output node. Not sure where it is in the graph, as I haven't gotten Tensorboard/etc up and running.

**Comment by araffin** [comment]
hello,
could you provide a minimal code to reproduce the error? (as mentioned in the issue template)
best would be a colab notebook

**Comment by aumfer** [comment]
@Miffyli 's idea of padding out the input from [1,X] to [64,X] got it so that I can at least run the saved model. I'm not sure what I should send in there though. The results are nothing like what I get with the `.learn` or `.predict` functions. Is there some sort of preprocessing I should be doing to the input?

I will try to setup a notebook that loads the `simple_save` model and attempts to predict on it.

**Comment by aumfer** [comment]
I'm going to go ahead and close this, as it doesn't look to be an issue with stable-baselines.

Thanks for your help.
