### ISSUE TITLE
Bug when learning DQN agent

### ISSUE THREAD

**Issue by cli0** [hill-a/stable-baselines#48]
**Describe the bug**
I am trying to run the DQN agent on a custom made environment (which follows the OpenAI template). The environment does not represent pictures and the state has dimension (1,8) while the number of potential actions is 4. I am following this example template https://colab.research.google.com/drive/1L_IMo6v0a0ALK8nefZm6PqPSy0vZIWBT in my code. The only thing different between this code and mine is just the environment I chose and I am using DQN instead of DDPG(i have adapted the configurations accordingly). Namely:

`model = DQN(policy=MlpPolicy, env=env, verbose=1, tensorboard_log="/tmp/gym/logs").learn(total_timesteps=200000, callback=callback)`
`
When I run the program I get this error:

```
InvalidArgumentError (see above for traceback): Tensor must be 4-D with last dim 1, 3, or 4, not [32,1,8]
	 [[{{node input_info/observation}} = ImageSummary[T=DT_FLOAT, bad_color=Tensor<type: uint8 shape: [4] values: 255 0 0...>, max_images=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_info/observation/tag, _arg_deepq/input/Ob_0_1)]]
```

The same happens even when I create a simple custom policy such as this:

```
class CustomPolicy(FeedForwardPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomPolicy, self).__init__(*args, **kwargs,
                                           layers=[32, 32, 32],
                                           feature_extraction="mlp")
```

Why does this happen and how can I fix it? Does the whole library operate under an implicit assumption the environment/input is always going to be images?

**Comment by araffin** [comment]
Hello,
Are you using DQN policies? (cf [documentation](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html)):
"The DQN model does not support stable_baselines.common.policies, as a result it must use its own policy models"

Can you replace `policy=MlpPolicy` by `policy="MlpPolicy"`, this ensure that the correct policy is used.

Can you provide a simple example of what you did (with the import also) ?

**Comment by cli0** [comment]
Thanks for the quick reply. My gym spaces are:

```
        self.action_space = spaces.Discrete(self.k)
        self.observation_space = spaces.Box(-1,1,shape=(1,2*self.k+2))
```

I also used deepq policies and not common policies. The following is my code in its entirety:

```
import os, gym
import numpy as np
import matplotlib.pyplot as plt

from stable_baselines import deepq, DQN
from stable_baselines.deepq.policies import MlpPolicy, LnMlpPolicy, register_policy, FeedForwardPolicy
from stable_baselines.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines.bench import Monitor
from stable_baselines.results_plotter import load_results, ts2xy

best_mean_reward, n_steps = -np.inf, 0

def callback(_locals, _globals):
  """
  Callback called at each step (for DQN an others) or after n steps (see ACER or PPO2)
  :param _locals: (dict)
  :param _globals: (dict)
  """
  global n_steps, best_mean_reward
  # Print stats every 1000 calls
  if (n_steps + 1) % 1000 == 0:
      # Evaluate policy performance
      x, y = ts2xy(load_results(log_dir), 'timesteps')
      if len(x) > 0:
          mean_reward = np.mean(y[-100:])
          print(x[-1], 'timesteps')
          print("Best mean reward: {:.2f} - Last mean reward per episode: {:.2f}".format(best_mean_reward, mean_reward))

          # New best model, you could save the agent here
          if mean_reward > best_mean_reward:
              best_mean_reward = mean_reward
              # Example for saving best model
              print("Saving new best model")
              _locals['self'].save(log_dir + 'best_model.pkl')
  n_steps += 1
  return False


# Create log dir
log_dir = "/tmp/gym/"
os.makedirs(log_dir, exist_ok=True)

# Create and wrap the environment
gym.envs.register("myenv-v1", entry_point="gym_env.envs:MyEnv")
env = gym.make('myenv-v1')
env = Monitor(env, log_dir, allow_early_resets=True)
env = DummyVecEnv([lambda: env])

model = DQN(policy="MlpPolicy", env=env, verbose=1, tensorboard_log="/tmp/gym/myenv_logs").learn(total_timesteps=200000, callback=callback)
```

> The library should work on any type of features. MlpPolicies are made for anything that is not images.

That was my take away too but somehow I get this error that references images.

**Comment by cli0** [comment]
Hi, your suggestion got rid of the error message, thank you. However, where exactly do you mean using flatten? The MlpPolicy defines the network, and the output is flattened already. Or do you flatten the observation_space?

Now, running the file does not cause errors anymore but it still does not work. I do not get any of the printed statements in callback() on the screen, the monitor file is created but remains empty, and there is no best_model.pkl stored anywhere in /tmp/gym/ .

**Comment by araffin** [comment]
After looking at the code, I think your error comes from that line: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/deepq/build_graph.py#L435
It is a quick check made to distinguish images from other type of features. Passing a shape (1, 8) instead of (8,) may cause the problem.

>However, where exactly do you mean using flatten?

I mean that before, you were supposed to pass numpy ndarrays of shape (1, 8), to reshape them to (8,), you just need to call `.flatten()` on those arrays.

**Comment by araffin** [comment]
I just tried your code, replacing `myenv-v1` by `CartPole-v1`, and everything works on my side. What version of stable-baselines are you using ?

**Comment by cli0** [comment]
I am using version 2.1.0 installed with pip3 (pip threw an error). I also tested the code with Cartpole and it works fine, so apparently my environment is the problem I guess. Do you have any ideas/suggestions what might be going wrong? So what line or could be wrong with the env? The routine throws no errors whatsoever, it "runs" for about 5-10 minutes and ends normally but nothing appears on the screen or is stored in /tmp/gym/.

**Comment by araffin** [comment]
>so apparently my environment is the problem I guess.

I think too... Well try with a random agent first, check inputs, outputs, ... It is hard to tell you what's wrong without having the code (but I have no time for debugging something not related to stable-baselines).

>nothing appears on the screen

That is not normal, because you set verbose=1

**Comment by cli0** [comment]
I discovered where it is going wrong more or less. In the callback function, when the method ts2xy is called, it returns an empty list `[]`. And that's because the monitor.csv file is empty. It gets created everytime, but it is never populated. Have I done something wrong in the Monitor definition part of the code? I tried setting another path in my home directory where write rights should not be a problem and the same thing happens. Monitor always looks like this:

```
#{"t_start": 1538828078.5114834, "env_id": "myenv-v1"}
r,l,t
```

**Comment by araffin** [comment]
>Have I done something wrong in the Monitor definition part of the code? 

If your code is working with Cartpole but not with your env, I would focus on your custom environment. Do you have episodes?

**Comment by araffin** [comment]
closing this issue because not directly related to stable-baselines (the issue seems to come for the custom env).
