### ISSUE TITLE
LSTM state interpretation [question]

### ISSUE THREAD

**Issue by rporotti** [hill-a/stable-baselines#482]
Hi,
I wanted to know what exactly is the `state` returned from calling [predict](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.predict), since I don't get it from the documentation.
Calling `predict()` with no environment, given the same `obs` as input, outputs different numbers each time.
Can you please clarify this to me?

**Comment by Miffyli** [comment]
If you use default policies (e.g. `CnnLstmPolicy`, `MlpLstmPolicy`), then `states` are the hidden states of the LSTM layer in the policy (the `self.snew` part [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L427), with LSTM implementation [here](https://github.com/hill-a/stable-baselines/blob/4929e54449d0b01b7c1d3841a0b66ccabc7f7bff/stable_baselines/a2c/utils.py#L195)). 

If `state=None` when using prediction, [the state is initialized to zeros](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L352).

**Comment by rporotti** [comment]
Ok, thank you very much. I will take a look into it.
