### ISSUE TITLE
Image difference input

### ISSUE THREAD

**Issue by maystroh** [hill-a/stable-baselines#484]
Thanks for your effort in this library. 

I just wanted to ask if you plan to support a frame difference between current and previous frames as input to the CNN policies in addition to the stacking frame already implemented... recent papers discuss the success of such input to improve the performance of a RL agent. (here is one reference: https://arxiv.org/abs/1901.03162)   

Thanks again for your help.

**Comment by Miffyli** [comment]
This wouldn't be part of stable-baselines, rather part of OpenAI Gym interface and Wrappers, like the [frame stacking](https://github.com/openai/gym/blob/master/gym/wrappers/frame_stack.py) one you mentioned. In the wrapper you keep track of the previous image, subtract the current one and return the difference as an observation.

**Comment by maystroh** [comment]
Thanks.
