### ISSUE TITLE
the environment passed is not a vectorized environment, however PPO2 requires it

### ISSUE THREAD

**Issue by HareshMiriyala** [hill-a/stable-baselines#487]
**Describe the bug**
Unable to set_env in PPO2. The error thrown is " the environment passed is not a vectorized environment. However, PPO2 requires it", but the environment is vectorized !

**Code example**
```
env = gym.make('InvertedPendulum-v2')
    model = PPO2.load(
                'models/initial_policy_invpendulum.pkl',
                env=env,
                verbose=1)

    env = SubprocVecEnv([lambda: gym.make('InvertedPendulum-v2')])
    model.set_env(env)

    model.learn(total_timesteps=100000, reset_num_timesteps=False)

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
from source 
 * GPU models and configuration
RTX 2060 
* Python version
3.6.8

**Comment by LinuxIsCool** [comment]
Why closed? I'm having the same issue.

**Comment by Miffyli** [comment]
If your code is same as above, then the env is not vectorized in the `load` step. Set `env=None` in `load`, or change `env` to be VecEnv at the very beginning.
