### ISSUE TITLE
Depth/opticalFlow/object segmentation images as visual observation

### ISSUE THREAD

**Issue by maystroh** [hill-a/stable-baselines#493]
For visual observation, the code supports rendered image(s) from single camera, but there is no direct way to get the depth maps. I'm wondering if it is done or not? 
I already did an environment that can generate depth/opticalFlow/object segmentation images along with RGB image... something similar to this [project ](https://bitbucket.org/Unity-Technologies/ml-imagesynthesis/src/master/  )but not still not sure how can I use these images to train an agent using `stable-baselines`.. I'm looking for hints/tips that can help me understand more what are the things that should be modified in `stable-baselines` to stack multiple images of different type.

Thanks in advance.

**Comment by araffin** [comment]
Hello,
you should take a look at custom policies in the documentation (and at some issues in GitHub)
Don't forget to deactivate the automatic normalization.

**Comment by maystroh** [comment]
Thanks @araffin, you mean by the automatic normalization the scaling part in `observation_input` in `a2c/utils.py`?

```
if (scale and  not np.any(np.isinf(ob_space.low)) and not np.any(np.isinf(ob_space.high)) and np.any((ob_space.high - ob_space.low) != 0)):
            # equivalent to processed_observations / 255.0 when bounds are set to [255, 0]
            processed_observations = ((processed_observations - ob_space.low) / (ob_space.high - ob_space.low))
```

**Comment by araffin** [comment]
Yes, it is called 'scale' in the constructor.
