### ISSUE TITLE
Observation and Reward pre-processing before inputing to learning agent

### ISSUE THREAD

**Issue by v-i-s-h** [hill-a/stable-baselines#497]
Is there a method to do observation/reward pre-processing before these quantities are 'seen' by the learning agent?
Let `o` be the observation and `r` be the reward. I'm looking for a way to make `_o = func1(o)` and `_r = func2(r)` and the learning agent will be trained based on `(_o, _r)`.

I'm unable to find such a functionality in docs.

**Comment by Miffyli** [comment]
This is part of environments and not stable-baselines. Take a look at [Gym Wrappers](https://github.com/openai/gym/tree/master/gym/wrappers).

**Comment by v-i-s-h** [comment]
@Miffyli Thanks a lot. This is exactly what I was looking for. :)
