### ISSUE TITLE
Documentation on what stable-baselines is/hopes to be

### ISSUE THREAD

**Issue by rodonn** [hill-a/stable-baselines#5]
I love some of the edits and cleaning up of the openai/baselines code that you guys have done.

Do you hope to get these edits merged back into the main baselines code, or do you think this project will continue to persist as a separate fork?

If you are planning on remaining separate, you might want to update the README e.g. so that it doesn't include the instructions for installing from https://github.com/openai/baselines.git

**Comment by araffin** [comment]
Hi,
We just published a medium article on stable baselines: https://medium.com/@araffin/stable-baselines-a-fork-of-openai-baselines-reinforcement-learning-made-easy-df87c4b2fc82

at the same time, the package is now available on pypi, so you can just do (after installing apt-get dependencies):
```
pip install stable-baselines
```

**Comment by araffin** [comment]
Closing this issue as the fork has now a separate python package.

**Comment by araffin** [comment]
Linking this issue to the PR https://github.com/openai/baselines/pull/481 where discussions have begun.
