### ISSUE TITLE
can't close VecEnv's render

### ISSUE THREAD

**Issue by junhuang-ifast** [hill-a/stable-baselines#510]
I'm trying to run this sample code (in jupyter notebook) from the examples about vectorized environments. 

```
import gym
import numpy as np

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines.common import set_global_seeds
from stable_baselines import ACKTR

def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_global_seeds(seed)
    return _init

env_id = "CartPole-v1"
num_cpu = 4  # Number of processes to use
# Create the vectorized environment
env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])

model = ACKTR(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)

obs = env.reset()
for _ in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
env.close()
```

Note: I've added the env.close() at the end to close the renders. This closes the individual env renders but not the render from VecEnv. Then when I manually close the window, it crashes my jupyter notebook.

**Comment by junhuang-ifast** [comment]
I solved issue using [this](https://github.com/hill-a/stable-baselines/issues/166#issuecomment-502350843), where my test env was DummyVecEnv (while maintaining my train env as SubprocVecEnv)

I was wondering does having train/test env as two different vectorized env create any reproducibility/prediction issues?

**Comment by araffin** [comment]
Hello,
did you try outside a notebook?

**Comment by junhuang-ifast** [comment]
I have not. Im assuming it works outside a notebook. I'll update once I get to it thanks.

**Comment by araffin** [comment]
After checking this is apparently normal, because we are using opencv for rendering.

if you want to close the render window, you just need to do:
```python
import cv2
cv2.destroyAllWindows()
```

You need to know that you cannot render it again afterward (that's why the window is not closed when calling `env.close()`).

**Comment by junhuang-ifast** [comment]
this works thanks
