### ISSUE TITLE
For recurrent policies, the number of environments run in parallel should be a multiple of nminibatches

### ISSUE THREAD

**Issue by junhuang-ifast** [hill-a/stable-baselines#511]
I'm looking at this recurrent example 

```
from stable_baselines import PPO2

# For recurrent policies, with PPO2, the number of environments run in parallel
# should be a multiple of nminibatches.
model = PPO2('MlpLstmPolicy', 'CartPole-v1', nminibatches=3, verbose=0)
model.learn(1000)

# Retrieve the env
env = model.get_env()

obs = env.reset()
# Passing state=None to the predict function means
# it is the initial state
state = None
# When using VecEnv, done is a vector
done = [False for _ in range(env.num_envs)]
for _ in range(500):
    # We need to pass the previous state and a mask for recurrent policies
    # to reset lstm state when a new episode begin
    action, state = model.predict(obs, state=state, mask=done)
    obs, reward , done, _ = env.step(action)
    # Note: with VecEnv, env.reset() is automatically called

    # Show the env
    env.render()
env.close()
```

and is having this issue when i set nminibatches greater than 1:

> For recurrent policies, the number of environments run in parallel should be a multiple of nminibatches.

If I run this `model.get_env().num_envs`, I can see that PPO2 creates 1 env by default (which I **assume** is the _number of environments run in parallel_)

Mathematically, 1 is a factor of every number and so should be compatible with every number of nminibatches?

**Comment by araffin** [comment]
Hello,
it says a multiple, not a factor.

**Comment by junhuang-ifast** [comment]
@araffin hmm Im guessing multiple here means something different than my understanding. Would you mind elaborating in what scenario for LSTM policies I am able to set nminibatches>1 ?

**Comment by araffin** [comment]
From wikipedia (https://en.m.wikipedia.org/wiki/Multiple_(mathematics)):
"for the quantities a and b, we say that b is a multiple of a if b = na for some integer n"

so here, n envs must be of the form
n_envs = n x 3

**Comment by junhuang-ifast** [comment]
ok I see where you're coming from. thanks.
