### ISSUE TITLE
[question] Exporting trained agent into c/c++ code

### ISSUE THREAD

**Issue by AlessandroZavoli** [hill-a/stable-baselines#513]
Is it possible to export a trained agent/model into a C/C++ code?

**Comment by Miffyli** [comment]
There is no premade tool for that, but you can look at the docs [on exporting models](https://stable-baselines.readthedocs.io/en/master/guide/export.html) to find some guidance on how it has been done for different target platforms.

**Comment by araffin** [comment]
@hill-a has some experience on that too.

**Comment by AlessandroZavoli** [comment]
I was thinking about just exporting the weights and rebuild the network as a sequence of basic operations. Would it be possible for a simple sequential, dense network?

**Comment by araffin** [comment]
>Would it be possible for a simple sequential, dense network?

Totally, you can even use the C++ api of pytorch/tensorflow for that.
Btw, if you succeed and open source your code, please make a PR to document that ;)
