### ISSUE TITLE
[question] Using custom environments

### ISSUE THREAD

**Issue by vedantbhatia** [hill-a/stable-baselines#514]
Hi,

I've created a custom gym environment for my problem, and it has a Discrete action space and a MultiDiscrete observation space. 

I keep running into this error, regardless of the algorithm I try:
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Input must be scalar but has rank 1 for 'deepq/input/one_hot' (op: 'OneHot') with input shapes: [?,1], [2], [], [] and with computed input tensors: input[1] = <1 2>."

I've cross-checked my usage of the gym spaces from the official environments, but it's possible I've missed something. The exact shapes are:
"

        self.observation_space = spaces.MultiDiscrete([(1, 2), (1, 7), (1, 9)])
        self.action_space = spaces.Discrete(9)

"

If this looks familiar/trivial, could you please point me in the right direction? Thanks!

**Comment by araffin** [comment]
Hello,

`ndarrays` are currently not supported for MultiDiscrete space (cf PR #152).

A solution for your problem is to use:
```python
self.observation_space = spaces.MultiDiscrete((2, 7, 9))
```
which is equivalent but works with stable-baselines.

**Comment by vedantbhatia** [comment]
> Hello,
> 
> `ndarrays` are currently not supported for MultiDiscrete space (cf PR #152).
> 
> A solution for your problem is to use:
> 
> ```python
> self.observation_space = spaces.MultiDiscrete((2, 7, 9))
> ```
> 
> which is equivalent but works with stable-baselines.

Thanks a lot, this worked!
