### ISSUE TITLE
[Question] Vectorized vs. MPI

### ISSUE THREAD

**Issue by keshaviyengar** [hill-a/stable-baselines#516]
* I have a question regarding the differences between the vectorized environment using the DummyVecEnv wrapper versus a multiprocessing version with MPI.
* I have a custom environment running with DDPG and HER and comparing MPI results with number of processes being 10 and a DummyVecEnv of the same environment with the VecEnv performing worse
* Is it to be expected to have similar results between vectorized and MPI training?

**Comment by araffin** [comment]
Hello,

>I have a custom environment running with DDPG and HER 

So, I assume you have a custom version of DDPG. Current version only support one env.
With VecEnv, it is the data collection that is multiprocessed. With MPI, the workers also perform update in parallel (this comes from OpenAI code so I don't know the details).

There may be also a bug with VecEnv and the current implementation of replay buffer, make sure to pass copy of arrays to the replay buffer (otherwise they may be changed by reference).

>don't have the results

I would assume VecEnv performance is worse?

**Comment by keshaviyengar** [comment]
> I assume you have a custom version of DDPG. Current version only support one env.
I have made some changes but nothing related to the vectorization. I was able to run a vectorized version, possibly incorrectly then if it is not supported. I will update the question with a code sample.

> I would assume VecEnv performance is worse?
Sorry for the poor grammar, I've updated the question to be more clear.

**Comment by keshaviyengar** [comment]
> I assume you have a custom version of DDPG. Current version only support one env.

I was able to create multiple environments with rl-baselines-zoo with the her.yml hyperparameter file for my custom environment. If it is not supported, possibly an warning message for her should be added as well when the environment is created in train.py.

**Comment by araffin** [comment]
>I was able to create multiple environments with rl-baselines-zoo with the her.yml hyperparameter file for my custom environment.

This is just a misleading print in the `train.py` (cf line 199), when using DDPG, it skips the creation of a VecEnv. However, if you try yourself, this will raise an error.

I would appreciate a PR for that (until I find some time to do it properly (I have to double check for the copy too)).

**Comment by keshaviyengar** [comment]
> I would appreciate a PR for that (until I find some time to do it properly (I have to double check for the copy too)).

I'll look into making a PR over in rl-baselines-zoo.
