### ISSUE TITLE
Tensorboard plotting in PPO2 is broken

### ISSUE THREAD

**Issue by drozzy** [hill-a/stable-baselines#518]
When I use tensorboard for PPO2 training, the reward plot is really messed up:

![Screen Shot 2019-10-23 at 11 35 21 AM](https://user-images.githubusercontent.com/140710/67409950-4ea0da80-f589-11e9-87c2-cfca7fb6d2d9.png)

**Comment by Miffyli** [comment]
Can you share a minimal code to reproduce this?

**Comment by araffin** [comment]
Duplicate of #143
