### ISSUE TITLE
When I ran the "Getting started" example I have the following error: "ModuleNotFoundError: No module named 'tensorflow.contrib'."

### ISSUE THREAD

**Issue by Roberto7766** [hill-a/stable-baselines#520]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.

**Describe the bug**

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)
for both code and stack traces.

```python
from stable_baselines import ...

```

```bash
Traceback (most recent call last): File ...

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
 * GPU models and configuration
 * Python version
 * Tensorflow version
 * Versions of any other relevant libraries

**Additional context**

**Comment by Roberto7766** [comment]
Hi,
after installing stable-baseline I tried the simple example:
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

But the result is:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-15de0e5fcc1b> in <module>
      4 from stable_baselines.common.policies import MlpPolicy
      5 from stable_baselines.common.vec_env import DummyVecEnv
----> 6 from stable_baselines import PPO2
      7 
      8 env = gym.make('CartPole-v1')

~/anaconda3/lib/python3.7/site-packages/stable_baselines/__init__.py in <module>
      2 from stable_baselines.acer import ACER
      3 from stable_baselines.acktr import ACKTR
----> 4 from stable_baselines.deepq import DQN
      5 from stable_baselines.her import HER
      6 from stable_baselines.ppo2 import PPO2

~/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/__init__.py in <module>
----> 1 from stable_baselines.deepq.policies import MlpPolicy, CnnPolicy, LnMlpPolicy, LnCnnPolicy
      2 from stable_baselines.deepq.build_graph import build_act, build_train  # noqa
      3 from stable_baselines.deepq.dqn import DQN
      4 from stable_baselines.deepq.replay_buffer import ReplayBuffer, PrioritizedReplayBuffer  # noqa
      5 

~/anaconda3/lib/python3.7/site-packages/stable_baselines/deepq/policies.py in <module>
      1 import tensorflow as tf
----> 2 import tensorflow.contrib.layers as tf_layers
      3 import numpy as np
      4 from gym.spaces import Discrete
      5 

ModuleNotFoundError: No module named 'tensorflow.contrib'

Any suggestion?

**Comment by Miffyli** [comment]
Check your tensorflow version. Stable-baselines supports Tensorflow versions 1.8.0 to 1.14.0.

**Comment by araffin** [comment]
Hello,
Please fill up the issue template next time. As @miffyli pointed out, you must be using tf2 which is currently not supported

**Comment by araffin** [comment]
Duplicate of #498
