### ISSUE TITLE
[question] PPO2 agent takes only one action after training

### ISSUE THREAD

**Issue by quoctuams** [hill-a/stable-baselines#522]
Hi guys,

Recently I built myself a custom gym environment, which is some kind of 2-player card game.
A random agent when facing the computer component (which I coded some very basic rules) wins about 20% of the time.
 
The agent that I trained using PPO2 algorithm after 500k steps improved the winning rate to about 55%. However when I test the agent in render mode, I notice that it only take 1 action repeatedly. 

Is it because the agent did not explore enough so it converged to a local maxima?
Is there anyway I can improve it? Maybe bigger model? More training steps? Would really appreciate if someone can shed a light on this.

This is my code:
```
import gym

from stable_baselines.common.policies import CnnPolicy
from stable_baselines.common.vec_env import DummyVecEnv, VecFrameStack
from stable_baselines.common.atari_wrappers import MaxAndSkipEnv
from stable_baselines import PPO2

env = gym.make('CR-v0')
env = MaxAndSkipEnv(env, skip=20) # I chose frame skip = 20 for faster training and also I think the difference between two states 20 frames apart is already very very small.
env = DummyVecEnv([lambda: env])
env = VecFrameStack(env, n_stack=2)

model = PPO2(CnnPolicy, env, gamma=0.995, verbose=1)
model.learn(total_timesteps=500000)
model.save("ppo2_cnn_cr_tune1")

del model

model = PPO2.load("ppo2_cnn_cr_tune1.zip")

obs = env.reset()
a_win = 0 # the agent
b_win = 0 # the computer component
for ep in range(20):
    ep_reward = 0
    count = 0
    for _ in range(3600*10):
        if count % 20 == 0:
            action, _states = model.predict(obs)
        else:
            action = 0
        obs, rewards, dones, info = env.step(action)
        ep_reward += rewards
        env.render()
        if dones:
            if rewards > 0:
            	a_win += 1
            elif rewards < 0:
            	b_win += 1
            print("Game", ep,". A won:", a_win, ". B won:", b_win, ". Reward:", ep_reward)
            env.reset()
            break

env.close()
```

Thank you.

**Comment by Miffyli** [comment]
At a quick glimpse:
* Why are you using frameskip with a card game? If frame-skip is 20, then it is going to repeat a single action over 20 steps before choosing another action. Try removing frame-skip wrapper.
* If that does not help, try playing around with `ent_coef` parameter to PPO2

**Comment by quoctuams** [comment]
Thank you for replying @Miffyli . 
Although it's a card game, the players activate the card to put some units on the map and the unit will follow certain predefined path and interactions. It's like a mini version of the mobile game Clash royale if you know it.
So maybe card game is the bad way to describe it on my part, more like RTS with very slow gameplay. That's why I think the observations with less than 20 frames apart are not different that much, thus the agent only need to make a decision maybe 3 times a second and can still achieve very good result.
Still, removing frame-skip will not hur. I will definitely try that and play around with the ent_coef as well. Will let you know the result. Thanks again :D
