### ISSUE TITLE
Tensorboard: No dashboards are active for the current dataset 

### ISSUE THREAD

**Issue by bektaskemal** [hill-a/stable-baselines#527]
I am trying to use tensorboard as described in the documentation. So, I added the tensorboard_log in the model definition. 
`model = DQN(CustomPolicy, env,verbose=1, tensorboard_log="./dqn_tensorboard/")`

However, tensorboard gives the error in the title and the logs in the terminal are as below:

> TensorBoard 1.14.0 at http://isl-k:6006/ (Press CTRL+C to quit)
I1028 16:32:13.820125 140303899174656 _internal.py:122] ::ffff:127.0.0.1 - - [28/Oct/2019 16:32:13] "GET / HTTP/1.1" 200 -

Am I missing something? What can be the cause of this problem?

Edit: I am running the script from a virtualenv.

**Comment by araffin** [comment]
Hello,
Please fill up the issue template completely.
