### ISSUE TITLE
Different results every time I train a PPO agent

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#532]
Hi, I am training an agent using PPO2 algorithm with a custom environment, I am running the training process for 200000 timesteps and saving the model. I train the agent again for 200000 timesteps with same set of hyperparameters, everything same and save the model. Now, if test both the models, actions taken by both the models are different. Why is it so even after running for 200000 timesteps. I hope this is not a bug.

**Comment by Miffyli** [comment]
Hard to say without more information, but generally reinforcement learning agents are like this: Different runs may result to completely different policies (with different performance), even if you train them "enough". This is why learning curves in papers are usually an average over many repetitions.

**Comment by venkatesh-chinni** [comment]
What could be the reason -  Different runs may result to completely different policies (with different performance), even if you train them "enough"?

**Comment by Miffyli** [comment]
The randomness of the environments, the starting policies and all the chaos than ensues. [I recommend reading this paper for more information on the gripes of reinforcement learning experiments](https://arxiv.org/abs/1709.06560).

**Comment by araffin** [comment]
Hello,
Yes, results depending on the random seed is unfortunately a known issue in RL (see [blog post](https://openlab-flowers.inria.fr/t/how-many-random-seeds-should-i-use-statistical-power-analysis-in-deep-reinforcement-learning-experiments/457) by @ccolas ).
As it does not seem to be particularly related to stable baselines, I will then close this issue.
