### ISSUE TITLE
assert self.n_batch % self.nminibatches == 0  AssertionError

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#537]
Hi I am trying to do a hyper parameter tuning by changing some of the default parameters of PPO2 algorithm. I have tried with some combinations already. 
My model
```
model = PPO2(MlpPolicy,env,gamma=0.99, n_steps=132, ent_coef=0.01,
             learning_rate=2.5e-2, vf_coef=0.5, max_grad_norm=0.5, lam=0.9,
             nminibatches=4, noptepochs=4, cliprange=0.1, cliprange_vf=None,
             verbose=1, tensorboard_log="./ppo_ahu_tensorboard/", _init_setup_model=True,
             policy_kwargs=None, full_tensorboard_log=False)

```
When I try to change the values of nminibatches and noptepochs, I always end up getting an error.
One such case, I tried with 
```
model = PPO2(MlpPolicy,env,gamma=0.8, n_steps=132, ent_coef=0.01,
             learning_rate=2.5e-2, vf_coef=0.5, max_grad_norm=0.5, lam=0.9,
             nminibatches=8, noptepochs=8, cliprange=0.1, cliprange_vf=None,
             verbose=1, tensorboard_log="./ppo_ahu_tensorboard/", _init_setup_model=True,
             policy_kwargs=None, full_tensorboard_log=False)

```
 and I get an error
```
assert self.n_batch % self.nminibatches == 0 AssertionError
```

What could be the reason? 
Thanks

**Comment by araffin** [comment]
Hello,

From PPO2 code:

```python
self.n_batch = self.n_envs * self.n_steps
```

Because you will divide for each update `n_batch` steps into `nminibatches`, `nminibatches` must be a factor of `n_batch`, otherwise you will not use some steps.
I agree we need to add a comment with the assert, I would appreciate if you could do a PR that solves that issue ;)
