### ISSUE TITLE
[Bug] Unable to pretrain a model with dataset twice

### ISSUE THREAD

**Issue by HareshKarnan** [hill-a/stable-baselines#538]
**Describe the bug**

ValueError: Variable pretrain/model/pi_fc0/w/Adam/ already exists , disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:
File "/usr/local/lib/python3.6/dist-packages/stable_baselines/common/base_class.py", line 266, in pretrain
    optim_op = optimizer.minimize(loss, var_list=self.params)

**Code example**

```
model.pretrain(dataset, n_epochs=10)
# some code that changes values in the dataset
model.pretrain(dataset, n_epochs=10)
```

**Comment by araffin** [comment]
Hello,

Thanks for reporting the issue, looks like a bug (I could reproduce it).
I don't have the time now to fix it, so we would appreciate if you could submit a PR that solves this issue ;)

**Comment by E666GT** [comment]
Any update about this?

**Comment by araffin** [comment]
>Any update about this?

So, unless someone does a PR to solve this, it is not going to be solved.
However, you can use SB2 + the imitation repo (TF release)
or SB3 + the imitation repo (master version): https://github.com/HumanCompatibleAI/imitation

**Comment by lorepieri8** [comment]
The problem is still there:

`ValueError: Variable pretrain/model/pi_fc0/w/Adam/ already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? `

**Comment by Miffyli** [comment]
@lorepieri8 

Double-check that you have installed the newest version of stable-baselines (preferably with `pip install git+https://github.com/hill-a/stable-baselines`)
