### ISSUE TITLE
[feature request] Problem when using Tuple Observation Space and Custom Policy

### ISSUE THREAD

**Issue by basso95** [hill-a/stable-baselines#541]
**Describe the bug**
I'm trying to define a custom policy that uses a tuple observation space composed of two Box spaces: `self.observation_space = spaces.Tuple((spaces.Box(...),
                                               spaces.Box(...))`. The first Box space is the initial input of the network, while the second one enters at a latter stage in the network. The algorithm I'm using is PPO2. Here are the main points where I'm encountering some problems: 
- inside common/runners.py, class AbstractEnvRunner `self.obs = np.zeros((n_env,) + env.observation_space.shape, dtype=env.observation_space.dtype.name); 
        self.obs[:] = env.reset()` Here we can't store tuples this way, so I could manually set the shape of the Tuple inside the custom environment and  do `self.obs = env.reset()` removing the [:] operator
- same thing inside ppo2/ppo2.py, method Runner.run(): it is not possible to assign mb_obs
- the previous two problems could be overcome with little modification of the code, however I think that the main problem comes inside the PPO2._train_step() method: here when we pass `td_map` as a feed dict to sess.run(), we must pass observation as a single placeholder, and there is no option to override it in the same way as when defining the step, proba_step and value methods of a custom policy (see example at https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html)

The only workaround I found for my specific problem is to stack the two boxes together, filling the unused spaces with zero, and then subsetting it inside the custom policy to go back to the two original needed placeholders. However, I think it might be useful for everyone to have more freedom when defining custom environments and policies, without touching the library source code.

In my opinion, if observations are only elaborated by the custom actor and critic network, there should be a more flexible way in defining the placeholders passed as feed dictionaries for tensorflow session.run. I think this is a crucial step in moving beyond simple fully connected architectures and default ones in this library.

**Comment by Miffyli** [comment]
This has been discussed multiple times, mainly in #133 . Long story short: Full support for Tuple/Dict requires major changes all around the codebase. Same goes for giving "easy access" to placeholders and such. Better support is planned for TF2/PyTorch version, though. Please share your comments on #133 so we do not have fragments of this discussions all around :). 

Closed as duplicate.

**Comment by basso95** [comment]
Got it! Thanks
