### ISSUE TITLE
Documentation - unable to add the information displayed in the terminal (default logging) to tensor board for plotting

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#543]
Hi, The documentation says

All the information displayed in the terminal (default logging) can be also logged in tensorboard. For that, you need to define several environment variables:
```
# formats are comma-separated, but for tensorboard you only need the last one
# stdout -> terminal
export OPENAI_LOG_FORMAT='stdout,log,csv,tensorboard'
export OPENAI_LOGDIR=path/to/tensorboard/data
```
This part is bit unclear, where should I set/run or execute the above two line

I am clear with the below part
and to configure the logger using:
```
from stable_baselines.logger import configure

configure()
```

And this part generally I do in ananconda promt
Then start tensorboard with:
```
tensorboard --logdir=$OPENAI_LOGDIR

```
Thank you

**Comment by araffin** [comment]
Hello,

The first command are [bash](https://github.com/Idnan/bash-guide#saving-your-environment-variables) commands and should be run in the terminal where you start your script.

**Comment by venkatesh-chinni** [comment]
I doubt if export commands work for windows

**Comment by venkatesh-chinni** [comment]
I tried with `set` but tensorboard says no scalar data

**Comment by araffin** [comment]
the fact that you are using windows explains a lot... maybe take a look at [that answer](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt/79614), I cannot help you much.

**Comment by venkatesh-chinni** [comment]
tried with that, still getting an error ->
```
tensorboard: error: unrecognized arguments: effect\ppo_tensorboard_09_11_logs
```  

Anything that you can help?

**Comment by araffin** [comment]
>Anything that you can help?

This is a tensorboard error, please look at tensorboard doc for windows.

**Comment by venkatesh-chinni** [comment]
```
SETX OPENAI_LOG_FORMAT "stdout,log,csv,tensorboard"
SETX OPENAI_LOGDIR "C:\path\to\tensorboard\data"
tensorboard --logdir=%OPENAI_LOGDIR%
```

worked in windows. You can close the issue

**Comment by araffin** [comment]
>How do I retrieve the data displayed on the terminal? Maybe in some .csv format. I didn't understand the guide.

what is not clear in https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html#legacy-integration?

>I don't understand these graphs, is there an explanation of what they display? I can only go by intuition.

Unfortunately, you need to understand the paper and look at the code for those ones (please take a look at spinning up guide, link is in the resource section).

>actor_loss and critic_loss

what is not clear here?

>episode_reward

Episodic reward (but it is known to be buggy, see different issues, solved in SB3)

>param_noise_stddev 

You need to read this paper: https://arxiv.org/abs/1706.01905

"rewards" is usually the sum of discounted rewards.

> Is there an explanation of what the logger displays in the terminal while training?

not yet, this is missing in the documentation.

**Comment by nndei** [comment]
Dear @araffin, 

Thank you for the reply.

I have not understood if I can retrieve a .csv file containing the data shown in the terminal during the training process after finishing the training. Also, since the export commands are bash commands, where does `from stable_baselines.logger import configure` and `configure()` go? Can I make this work in zoo?

For the other questions, thank you very much for providing info, I will surely read what you suggested in order to better grasp what is displayed.

Best regards
