### ISSUE TITLE
Pretrain VecEnv: mismatch shape between dataset and input tensor

### ISSUE THREAD

**Issue by quoctuams** [hill-a/stable-baselines#546]
**Describe the bug**
I record myself playing a game and obtain a dataset (.npz) with the following structure:
actions (12582, 1)
obs (12582, 64, 36, 6)
rewards (12582,)
episode_returns (2,)
episode_starts (12582,)
Total trajectories: 1
Total transitions: 12580

When I feed this dataset to pretrain using PPO2 model using below command:
```
dataset = ExpertDataset(expert_path='dummy_cr_demo.npz',
                        traj_limitation=1, batch_size=32)
model = PPO2('CnnPolicy', env, gamma=0.99, n_steps=128, verbose=1, tensorboard_log="./tensorboard/")
model.pretrain(dataset, n_epochs=1000)
```

, there is an error message about wrong shape of the input.

```
Pretraining with Behavior Cloning...
Traceback (most recent call last):
  File "/Users/tunguyen/Desktop/deep_learning/clash_royale/agent_learning/pretrain_human_demo.py", line 68, in <module>
    model.pretrain(dataset, n_epochs=1000)
  File "/Users/tunguyen/miniconda3/envs/rl-baseline/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 282, in pretrain
    train_loss_, _ = self.sess.run([loss, optim_op], feed_dict)
  File "/Users/tunguyen/miniconda3/envs/rl-baseline/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Users/tunguyen/miniconda3/envs/rl-baseline/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 13824) for Tensor 'input/Ob:0', which has shape '(?, 64, 36, 6)'
```
Shape (32, 13824) is batchsize of 32 * (64x36x6) I think.
Any help is appreciated :(

**System Info**
Describe the characteristic of your environment:
 * Python version: 3.7.3
 * Tensorflow version: 1.14.0
 * Versions of any other relevant libraries: stable-baselines 2.8.0; numpy 1.17.3

**Comment by araffin** [comment]
Hello,
Your input looks like an image, why are you using a mlp ?

**Comment by quoctuams** [comment]
Hi, the environment's observation space is a Box. I tried CnnPolicy first but the error still happened. That's why I tried MlpPolicy as shown in the documentation just to see if that changes anything. Sorry my example should have been CnnPolicy. 
Do you know why this happened and is there anything I should do?

**Comment by araffin** [comment]
> Do you know why this happened and is there anything I should do?

You are using an uncommon shape (6 channels is not really standard), normally, with images, you store only path to them in the npz archive and the dataloader will use opencv to load them. If you don't, I'm afraid the channels get flatten at some point. You may need to write a custom dataloader (cf `gaill/dataset/`).

**Comment by quoctuams** [comment]
Thanks a lot araffin, I think I have figured out the flatten part you mentioned. I will write a custom dataloader then. Great work guys!
