### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Roberto7766** [hill-a/stable-baselines#548]
When I run the following code the memory continuously grows till the kernel runs out of memory.

___________________________________________________________________________________________________

import os, inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(os.path.dirname(currentdir))
os.sys.path.insert(0, parentdir)
import gym
from pybullet_envs.bullet.kukaCamGymEnv import KukaCamGymEnv
import pybullet as p
import time
import pybullet_data
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.deepq.policies import MlpPolicy
from stable_baselines import DQN
import datetime

cid = p.connect(p.SHARED_MEMORY)
if (cid < 0):
  p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
p.resetSimulation()

def main():
  env = KukaCamGymEnv(renders=False, isDiscrete=True)
  model = DQN(MlpPolicy, env, verbose=2,tensorboard_log="./tensorboard/", learning_rate=0.001, full_tensorboard_log=True)
  model.learn(total_timesteps=10000000)
  obs = env.reset()

  while True:
      action, _states = model.predict(obs)
      obs, rewards, dones, info = env.step(action)
      print(rewards, dones)
      env.render()

if __name__ == '__main__':
  main()

___________________________________________________________________________________________________

 Libraries installed with pip
 GPU: GTX1060 6GB
 Python: 3.7.4
 Tensorflow: 1.14.0

NOTES: pybullet installed, tensorboard running

**Comment by araffin** [comment]
Hello,
That's totally normal, DQN uses a replay buffer and it seems that the input is an image. If you know the dimensions (and the buffer size), then you can compute in advance how many RAM you need.
So, you have two solutions : downsample the input with a wrapper or reduce the buffer size.

**Comment by Miffyli** [comment]
A note for a future PR: I have used lz4 compression with replay memory before and for uint8 images it can at least halve the amount of memory required with ~5% slowdown from compression/decompression. It would be rather trivial addition to `replay_buffer`, but with the caveat that lz4 might not be always supported (need to check this). This could be an optional feature that is enabled if lz4 is detected. I remember seeing this being used in some other RL library but now I can not seem to find it.

**Comment by araffin** [comment]
You have lz4 compression in this PR: https://github.com/openai/gym/pull/1485

**Comment by Roberto7766** [comment]
Ok thanks. I reduced buffer dimension and now it works!
