### ISSUE TITLE
[question] Memory leak due to line 466 in ppo2.py

### ISSUE THREAD

**Issue by jingxixu** [hill-a/stable-baselines#550]
**Describe the bug**
I am using PPO2 with the observation being a sequence of images and joint values. However the memory keeps growing due to line 466 `mb_obs.append(self.obs.copy())` in the file `ppo2.py`. Is the `copy()` here really necessary? Without it there is no memory issue. I have provided the code chuck from `ppo2.py` in the following section.

**Code example**
```python
        for _ in range(self.n_steps):
            actions, values, self.states, neglogpacs = self.model.step(self.obs, self.states, self.dones)
            mb_obs.append(self.obs.copy())
            mb_actions.append(actions)
            mb_values.append(values)
            mb_neglogpacs.append(neglogpacs)
            mb_dones.append(self.dones)
            clipped_actions = actions
            # Clip the actions to avoid out of bound error
            if isinstance(self.env.action_space, gym.spaces.Box):
                clipped_actions = np.clip(actions, self.env.action_space.low, self.env.action_space.high)
            self.obs[:], rewards, self.dones, infos = self.env.step(clipped_actions)
            for info in infos:
                maybe_ep_info = info.get('episode')
                if maybe_ep_info is not None:
                    ep_infos.append(maybe_ep_info)
            mb_rewards.append(rewards)
```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...) pip
 * GPU models and configuration GeoForce 1080Ti
 * Python version 3.7.4
 * Tensorflow version 1.14.0
 * Versions of any other relevant libraries

**Comment by Miffyli** [comment]
Without the `copy` (i.e. if the line is only `mb_obs.append(self.obs)`) all the elements in `mb_obs` would refer to same observation, which would be the final one. True, memory usage does not grow, but only because you are really only storing the last sample.

**Comment by jingxixu** [comment]
Thanks! Also, is it possible for you to explain what is the difference between `act_model` and `train_model` in `ppo2.py`? I have copied the code below. Many thanks!

```python
act_model = self.policy(self.sess, self.observation_space, self.action_space, self.n_envs, 1, n_batch_step, reuse=False, **self.policy_kwargs)
with tf.variable_scope("train_model", reuse=True, custom_getter=tf_util.outer_scope_getter("train_model")):
    train_model = self.policy(self.sess, self.observation_space, self.action_space,
                                              self.n_envs // self.nminibatches, self.n_steps, n_batch_train,
                                              reuse=True, **self.policy_kwargs)
```

**Comment by araffin** [comment]
You have already an answer here: #314 an dthere: https://github.com/hill-a/stable-baselines/issues/222

**Comment by araffin** [comment]
@jingxixu out of curiosity, what is your numpy version?
(there are possibly related issues #182 #642 )

**Comment by denyHell** [comment]
@jingxixu Hi, I am curious how did you track down which line caused the memory leak...
