### ISSUE TITLE
How to print the action probabilities during training of a PPO2 Agent

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#554]
Hi I am training an agent with PPO2 algorithm. i am facing a problem that agent is always taking the same action. So I want to print the action probabilities of my policy network to check why agent is always taking the same action. Can you help me with that?

**Comment by araffin** [comment]
Hello,

Answer is in the [documentation](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.action_probability).
Related to https://github.com/hill-a/stable-baselines/issues/553
