### ISSUE TITLE
[question] Tensorboard callback during testing/predicting?

### ISSUE THREAD

**Issue by stefanbschneider** [hill-a/stable-baselines#560]
I see that it's easy to pass tensorboard callbacks to the `model.train()` function. Is there any way to do something similar when testing the model after training, i.e., using the `model.predict()` call? For me, tensorboard is a convenient way to also see how the agent is doing during testing.

I just saw that `predict()` does not seem to accept callbacks directly. So I guess this is not possible? What's the best practice then?

**Comment by Miffyli** [comment]
`predict` only returns a single action for a single observation, it does not evaluate the agent on the environment. No code for that exists yet, but #508 will add `evaluate_policy` for easier evaluation of the agents. Meanwhile you have to write the evaluation loop yourself (see [examples](https://stable-baselines.readthedocs.io/en/master/guide/examples.html) for hints).

**Comment by stefanbschneider** [comment]
I saw the manual evaluation loop in the examples, which is where I saw the `predict` call. I was just wondering if there is a way to include tensorboard callbacks in this evaluation loop?

Thanks for your pointer to https://github.com/hill-a/stable-baselines/pull/508 though. It seems like `evaluate_policy` will accept tensorboard callbacks and solve my question. Hopefully, you'll be able to merge the PR soon :)

**Comment by araffin** [comment]
As @Miffyli mentioned, `model.predict()` is quite different from `model.learn()` as it only does one thing. Compared to keras predict method, this only take a batch of observation as input (not a generator), most of the evaluation code must be written by the user for now (this will normally change in the future with evaluation callback #348  and PR #508).

**Comment by benediktkreis** [comment]
Hi @araffin,

When I'm trying to use [evaluate_policy](https://stable-baselines3.readthedocs.io/en/master/common/evaluation.html#stable_baselines3.common.evaluation.evaluate_policy) with a [TensorboardCallback](https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html#logging-more-values)  or even an empty [Custom Callback](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#custom-callback), I'm getting a `TypeError: 'TensorboardCallback' object is not callable`. What am I doing wrong? My goal is to write same  environment values to a Tensorboard log during the evaluation of my model.

My code looks like:
`
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10, deterministic=True, callback=TensorboardCallback())`

**Comment by technocrat13** [comment]
I am facing the same issue @benediktkreis, I am trying to evaluate my agent on the same environment with the same TensoboardCallback for all the logging used during testing. I also do not find a way to assign a `tb_log_name` so I doubt `evaluate_policy` is what I am looking for


I wish there was a way to switch off training in SB3 and run the same training loop again
