### ISSUE TITLE
Add Typing to Stable Baselines

### ISSUE THREAD

**Issue by AdamGleave** [hill-a/stable-baselines#561]
I'm wondering if it's worth us starting to use Python [type annotations](https://docs.python.org/3/library/typing.html) as in [PEP 484](https://www.python.org/dev/peps/pep-0484/) et al? We can introduce these gradually, and type checkers can still catch some classes of bug even without annotations.

Right now we already specify the types of most functions in the docstring, so I don't think it would be much extra work to specify these formally using type hints.

Concretely we'd need to add type checking to Travis, document it and make sure the current code type checks. I tried running `pytype` against Stable Baselines quickly and there were a few errors (I think mostly false positives) but probably wouldn't take long to fix or suppress them.

@hill-a @araffin @erniejunior @Miffyli curious on your thoughts on this, if there's demand I can probably make a PR for this (though may take me a while).

**Comment by araffin** [comment]
Hello,

I'm totally for this feature (in fact , it was already present in the roadmap under an obscure note saying "type everything")

For checking, I don't know much what is available, I've seen "mypy" several time in the past (that's what pytorch uses I think).

**Comment by Miffyli** [comment]
I also vote yes on this feature. As mentioned, this should be rather straight-forward with the typing being in the docstrings already.

My only gripe with these is the readability: Looks like with complex/more varying parameters the typing hints get long and cumbersome to read in code (note: Based on few random libraries I have seen online). On a quick overview over PIP 484 there does not seem to be comments on how to keep things clean/readable. Could this be done by e.g. putting (almost) every parameter on its own line, or would be this be against PIP8 / other style guides?

**Comment by AdamGleave** [comment]
> I'm totally for this feature (in fact , it was already present in the roadmap under an obscure note saying "type everything")

Ah nice, I missed this!

> For checking, I don't know much what is available, I've seen "mypy" several time in the past (that's what pytorch uses I think).

I'm most familiar with [pytype](https://github.com/google/pytype). It seems to be particularly easy to drop in to existing projects and gradually add typing (which makes sense, given this is what Google had to do).

I tried [mypy](https://mypy.readthedocs.io/) but found it a bit fiddly with third-party libraries: it wants you to provide type stubs if the library isn't typed. However, you can just use `--ignore-missing-imports` to workaround this.

[pyre](https://pyre-check.org/) came out recently and looks interesting. Seems more featureful than the others, e.g. it has an incremental mode to type check in real time. When I tried it recently it seemed to also struggle with third-party libraries that are untyped, though.

> My only gripe with these is the readability: Looks like with complex/more varying parameters the typing hints get long and cumbersome to read in code (note: Based on few random libraries I have seen online).

I've tended to be putting each parameter on a new line for complex functions. I believe this is PEP8 compliant (at least `flake8` does not complain, and `black` auto-formats in this style).

Type hints *do* get cumbersome for some complex types. For example, we'll probably have `Union[Env, VecEnv, str]` in some places. It's always possible to just not add a type hint if it's too awkward, though :) And type variables can help manage the complexity.
