### ISSUE TITLE
Any example of single agent for multiple environments using VecEnvs?

### ISSUE THREAD

**Issue by urvishp80** [hill-a/stable-baselines#562]
I have a question regarding raining a single agent for multiple environments. I read the docs and was able to find that using `VecEnv` I can stack multiple environments to train single agent. But, there is no such example in the doc related to it. Is there any example of it? Thanks in advance. 

If there is no such example then can I submit one with good documentation for learning purposes?

**Comment by araffin** [comment]
Hello,

You did not search [much](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#multiprocessing-unleashing-the-power-of-vectorized-environments), did you?

More complete tutorial: https://github.com/araffin/rl-tutorial-jnrr19 (will be added in #536 )

**Comment by urvishp80** [comment]
I looked at the documentation and found that example of cart-pole but could not understand it as I am new to RL. I have a very basic knowledge at this moment. Closing the issues. Thanks for the help.
