### ISSUE TITLE
[question] How to create 1 deterministic agent during traning multiple agent?

### ISSUE THREAD

**Issue by greg2paris** [hill-a/stable-baselines#569]
Hello,
I am currently traning 4 agents in a same custom environement.
I would like to make one of them a deterministic agent that will use the current policy.
So I will know how the agent will really perform without any exploration durring the testing phase.
How can I make this happen?

This is the current code im using:
`
# multiprocess environment
    def make_env(rank, seed=0):
        def _init():
            env = Env(agent_number=rank)
            return env

        # set_global_seeds(seed)
        return _init
Env = SubprocVecEnv([make_env(i) for i in range(4)])
`

**Comment by araffin** [comment]
Hello,
what you are looking for is the `predict` method (cf doc), it should be used outside the training loop or with a callback (cf tutorial : https://github.com/araffin/rl-tutorial-jnrr19)

**Comment by greg2paris** [comment]
Mabe i wasn't clear about what I am trying to do.
I want to have 3 agents that are learning and exploring, while another agent will only use the current deterministic policy.
So I actually can see the trained agent in action.
My environement is continuous tast so I dont go back to the starting point again and again. So I need to do the predict in real time with the trainning.
The predict method you are talking about is only avalable outside training.
And the callback method is only avalable when the network is updating his policy.
So I need a way to use determinist policy for 1 of the 4 agent.

**Comment by araffin** [comment]
> So I need a way to use determinist policy for 1 of the 4 agent.

You mean you want also to collect samples with this deterministic policy?
Then you need to define a custom class that derives from Stable-Baselines one.
