### ISSUE TITLE
Fork means unsearchable on github

### ISSUE THREAD

**Issue by pathway** [hill-a/stable-baselines#57]
Trying to search the codebase on github returns "Sorry, forked repositories are not currently searchable"

I think you can maintain openai/baselines as a remote, yet not have this repo marked as a "fork" in github, to allow for search.

For now I just grep my clone of your repo in bash.  But this repo is clearly substantial enough to be a first-class repo in github, and apparently forks are not treated as first class repos by github.

**Comment by araffin** [comment]
Hi,
We thought about that at some point with @hill-a, 
the main problem now is that if we change repo uri, we will lost most of the people that starred/followed/forked this repo. But, I'm also interested by @hill-a 's point of view, he may have changed his mind.

>For now I just grep my clone of your repo in bash.

Yep, I basically do "search in folder" with my editor.

**Comment by araffin** [comment]
Related: https://github.com/openai/baselines/pull/481

**Comment by araffin** [comment]
Hello,
as a compromise, I created a mirror here: https://github.com/Stable-Baselines-Team/stable-baselines
That allows to search in the repo (and be visible in github search) while keeping the main repo development here (issue, pull requests, stars, ...)

**Comment by Pastafarianist** [comment]
You can ask Github support to detach the repo from the original one. However, I'm not sure that detaching would be a good idea as there is already the issue of credibility (OpenAI Baselines is _the_ standard, while forks receive less trust), and detaching the repo will break a connection to the Baselines and thus will impact credibility.

**Comment by araffin** [comment]
I guess we can now close this issue with Stable-Baselines3 having its separate repo: https://github.com/DLR-RM/stable-baselines3
