### ISSUE TITLE
main process hangs when finished when using subprocenv 

### ISSUE THREAD

**Issue by jbulow** [hill-a/stable-baselines#570]
**Describe the bug**

The cartpole example on [https://stable-baselines.readthedocs.io/en/master/guide/examples.html](https://stable-baselines.readthedocs.io/en/master/guide/examples.html) hangs when finished.

**Code example**

See cartpole example on https://stable-baselines.readthedocs.io/en/master/guide/examples.html

**System Info**

Running in venv populated using pip:

stable-baselines                  2.9.0a0  (installed from master branch 2019-11-18)

Running on CPU (no GPU present)

 * Python version

3.7.5

 * Tensorflow version
tensorflow                        1.15.0

 * Versions of any other relevant libraries

gym                               0.15.4
numpy                             1.17.4    

**Additional context**

All examples using SubprocVenEnv hangs on exit, not only the cartpole example

**Comment by araffin** [comment]
Hello,
what is your os? do you have mpi installed?
try to use `start_method='fork'` on linux
Otherwise, you can use a DummyVecEnv, it is usually faster.

**Comment by jbulow** [comment]
start_method='fork' solves the problem.

I have mpi installed. Using ubuntu 18.04

**Comment by araffin** [comment]
>I have mpi installed. Using ubuntu 18.04

I have the same issue on my laptop, but is does not seem related to SB.

**Comment by jbulow** [comment]
Just tried out DummyVecEnv and achived quite good performance. 

It seems that a combination of SubprocVecEvn and DummyVecEnv could be really performant for simple simulators. I.e start a SubprocVecEnv with a number of DummyVecEnv:s.
