### ISSUE TITLE
Warmup actions in SAC are not normalized before being put in the buffer

### ISSUE THREAD

**Issue by Antymon** [hill-a/stable-baselines#573]
**Describe the bug**
SAC's replay buffer is meant to store actions limited to tanh-codomain, but warmup actions are sampled from Gym's Box and put directly in the buffer.

**Comment by araffin** [comment]
Hello,

Good remark, this bug must be present in TD3 too (although as most gym env have boundaries in [-1, 1] this was an issue only for custom env).
I would appreciate if you could open a PR that solves that issue ;)

**Comment by araffin** [comment]
A good way to do so would be to add those methods to the base class:

```python
    def _scale_action(self, action):
        """
        Rescale the action from [low, high] to [-1, 1]
        (no need for symmetric action space)

        :param action: (np.ndarray)
        :return: (np.ndarray)
        """
        low, high = self.action_space.low, self.action_space.high
        return 2.0 * ((action - low) / (high - low)) - 1.0

    def _unscale_action(self, scaled_action):
        """
        Rescale the action from [-1, 1] to [low, high]
        (no need for symmetric action space)

        :param action: (np.ndarray)
        :return: (np.ndarray)
        """
        low, high = self.action_space.low, self.action_space.high
        return low + (0.5 * (scaled_action + 1.0) * (high - low))
```

**Comment by Antymon** [comment]
Hi, seems you know perfectly what needs to be done... so you still want me to do a PR?

**Comment by araffin** [comment]
>so you still want me to do a PR?

Please yes, I don't have the same to do it completely and properly (currently working on others PR).

**Comment by Antymon** [comment]
I will do one tomorrow.
