### ISSUE TITLE
[bug] HER not working in environments that have max_step = 1

### ISSUE THREAD

**Issue by renan-cunha** [hill-a/stable-baselines#578]
**Describe the bug**
HER is not working with environments that have a max step equal to 1. For example, on a modified version of BitFlipping where the agent can make only one action. The desired goal never changes on the "compute_reward()" method. I think it should use the achieved_goal sometimes as the desired one so it can compute a good reward and the agent can learn something. The behavior is ok with the default version of BitFlipping

[desired goal used](https://i.ibb.co/tpTVcdr/Screenshot-from-2019-11-23-18-12-40.png)

**Code example**
[code to run](https://gist.github.com/renan-cunha/894f142e339115746d833f8b5a0f9e55) 

Modified part of BitFlipping, the 'step' method always returns True as the 'done' variable
```python
    def step(self, action):
        if self.continuous:
            self.state[action > 0] = 1 - self.state[action > 0]
        else:
            self.state[action] = 1 - self.state[action]
        obs = self._get_obs()
        reward = self.compute_reward(obs['achieved_goal'], obs['desired_goal'], None)
        done = reward == 0
        self.current_step += 1
        # Episode terminate when we reached the goal or the max number of steps
        info = {'is_success': done}
        done = done or self.current_step >= self.max_steps
        return obs, reward, True, info
```

**System Info**
Describe the characteristic of your environment:
 * lib installed by pip
 * using CPU
 * python 3.6.8
 * tensorflow 1.14.1
 * gym 0.15.4
 * stable baselines 2.7.0

**Comment by araffin** [comment]
Hello,
Thanks for reporting the issue. After looking more closely, I think this is normal for the `future` strategy.
As mentioned in the code:

https://github.com/hill-a/stable-baselines/blob/4fada47f1b71b7548c935b1f01c6fb04199b3d54/stable_baselines/her/replay_buffer.py#L155-L158

However, using the `final` strategy, it samples different goal but does not seem to learn much...
