### ISSUE TITLE
[doc] load_results loads all files matching an undocumented pattern and not just a single file as stated in the documentation 

### ISSUE THREAD

**Issue by jbulow** [hill-a/stable-baselines#582]
**Describe the bug**

load_results loads all results ending with 'monitor.csv' (and json files) and not just a single file as the documentation states.

**Code example**
Erroneous comment [here](https://github.com/hill-a/stable-baselines/blob/e315ebecbfd26225522a2e63a6bbd440c1df7f01/stable_baselines/bench/monitor.py#L163)

**System Info**
N/A

**Comment by araffin** [comment]
Hello,
thanks for the issue. We would appreciate a PR that fixes this issue ;)
