### ISSUE TITLE
GAIL (PPO2 version)

### ISSUE THREAD

**Issue by rohitrango** [hill-a/stable-baselines#592]
PPO2 is generally more stable and gives better results than TRPO. However, there is no version of GAIL with PPO. Could we have this feature in the repo? ( I was trying to dabble around with a PPO-GAIL anyway)

Thanks

**Comment by araffin** [comment]
Hello,
We are now focusing on the migration to tf2 (cf #366 ) so I would avoid adding new algorithms now.
We plan (cf  #576 ) to drop GAIL support but you should still be able to use it thanks to [this repo](https://github.com/HumanCompatibleAI/imitation) also maintained by @AdamGleave and depends on Stable Baselines.
Btw, @AdamGleave what algorithms are supported with GAIL? (maybe PPO is already supported)

**Comment by AdamGleave** [comment]
[imitation](https://github.com/HumanCompatibleAI/imitation) uses PPO by default in its GAIL (and AIRL) implementation. But the RL algorithm is configurable by specifying a different `model_class` [here](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/util/util.py#L73). We've not tested with non-PPO, but other algorithms should work OK.

**Comment by araffin** [comment]
Good to know, closing this issue then.
