### ISSUE TITLE
Small error in custom environment documentation

### ISSUE THREAD

**Issue by justinkterry** [hill-a/stable-baselines#596]
Your custom gym environment documentation doesn't quite agree with open ai's:

[Yours](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html) has closing the render be an argument to render: 

`def render(self, mode='human', close=False):`

[Theirs](https://github.com/openai/gym/blob/master/docs/creating-environments.md) (which you link to as well) has close be it's own method, and that form is reflected in other libraries as well.

I'll submit a PR for this provided I'm not somehow crazy and you tell me where the documentation is.

**Comment by araffin** [comment]
Hello,
Thanks for spotting that mistake, in fact they changed their API but we forgot to change that example, feel free to submit a PR that solves this issue ;)

**Comment by justinkterry** [comment]
Which file is the documentation in?

**Comment by araffin** [comment]
Here it is: https://github.com/hill-a/stable-baselines/blob/master/docs/guide/custom_env.rst
