### ISSUE TITLE
Continuing training on a previous trained model

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#599]
Hi, I have trained an agent using PPO2 for 10000 steps and saved the model . I feel that the model can be improved by letting it train for more episodes. So I want to load this model and continue training on the loaded model which is already trained for 10000 steps. I have gone through the documentation but could find anything related to this. Is a feature available currently in stable baselines for this?

**Comment by araffin** [comment]
Please read the documentation more carefully ;)
You have an example of what you are looking for here: https://stable-baselines.readthedocs.io/en/master/guide/examples.html abd here: https://stable-baselines.readthedocs.io/en/master/guide/examples.html#continual-learning

**Comment by venkatesh-chinni** [comment]
I am training a model and saving it 
```
model = PPO2(CustomPolicy,env,gamma=1, n_steps=132, ent_coef=0.01,
             learning_rate=2.5e-4, vf_coef=0.5, max_grad_norm=0.5, lam=0.95,
             nminibatches=4, noptepochs=4, cliprange=0.2, cliprange_vf=None,
             verbose=0, tensorboard_log="./03_12_2019_logs/", _init_setup_model=True,
             policy_kwargs=None, full_tensorboard_log=False)

model.learn(total_timesteps=10000,callback=None, seed=None,
            log_interval=1, tb_log_name="Logs", reset_num_timesteps=True)

model.save("agent_03_12_2019")

```

So now if I wish to continue with the training on the same environment as earlier, I am supposed to load the model and continue with the training. Say like
```
model = PPO2.load("agent_03_12_2019")
model.learn(total_timesteps=10000,callback=None, seed=None,
            log_interval=1, tb_log_name="Logs", reset_num_timesteps=True)
```

So will this continue the training ?

**Comment by venkatesh-chinni** [comment]
okay, i need to use `model.set_env(env)` before model.leran. Thanks.

But I one thing I found missing is , when I trained my model for first time I have integrated it with tensorbaord, now when I do the continual training, the tensorboard graphs are not updated for the new timesteps. Am I missing something ?

**Comment by araffin** [comment]
>the tensorboard graphs are not updated for the new timesteps

again please read the doc about tensorboard integration, we cover that issue.

**Comment by matthew-hsr** [comment]
@araffin 

Thanks a lot for your answer!

I must be missing something though - reading the code, I don't see how `set_env` makes it learn continuously. It seems like `set_env` in `base_class.py` only changes `self.envs` and `self.env`, and reading the code for `Runner` and `learn` (in particular ppo2.py), I can't find the code that makes it learn continuously instead of starting fresh.

Could you elaborate on which part of the code makes it learn continuously?

Thanks in advance!

**Comment by venkatesh-chinni** [comment]
I have tried with 

```
model = PPO2(CustomPolicy,env,gamma=1, n_steps=132, ent_coef=0.01,
             learning_rate=2.5e-4, vf_coef=0.5, max_grad_norm=0.5, lam=0.95,
             nminibatches=4, noptepochs=4, cliprange=0.2, cliprange_vf=None,
             verbose=0, tensorboard_log="./03_12_2019_logs/", _init_setup_model=True,
             policy_kwargs=None, full_tensorboard_log=False)

model.learn(total_timesteps=10000,callback=None, seed=None,
            log_interval=1, tb_log_name="Logs", reset_num_timesteps=False)

model.save("agent_03_12_2019")
```

```
model = PPO2.load("agent_03_12_2019")

n_cpu = 8
env = DummyVecEnv([lambda: AHUenv() for i in range(n_cpu)])
model.set_env(env)


model.learn(total_timesteps=2000000,callback=None, seed=None,
            log_interval=1, tb_log_name="VAV 27_12_logs", reset_num_timesteps=False)

model.save("agent_03_12_2019_continued_training_1")
```

With this the continual training is happening but the tensor board graphs are being updated. I have manually changed the `reset_num_timesteps` to False. but still the tensorboard graphs are not updated.

**Comment by cevans3098** [comment]
I'm working on some similar code, but I am am having issues with TensorBoard throwing an exception:

```
  File "C:\Anaconda3\envs\envTF1\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 442, in __init__
    super().__init__(env=env, model=model, n_steps=n_steps)
  File "C:\Anaconda3\envs\envTF1\lib\site-packages\stable_baselines\common\runners.py", line 19, in __init__
    self.obs[:] = env.reset()
  File "C:\Anaconda3\envs\envTF1\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 111, in reset
    remote.send(('reset', None))
  File "C:\Anaconda3\envs\envTF1\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Anaconda3\envs\envTF1\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
```

 a sampling of my code is shown below:

```python
    env = SubprocVecEnv(env_list)

    model = PPO2(policy ='CustomPolicy', env = env, verbose = 1, 
                 vf_coef = VF_COEFF,
                 noptepochs = EPOCHS,
                 ent_coef = ENT_COEFF,
                 learning_rate = LEARNING_RATE,
                 tensorboard_log = tensorboard_log_location,
                 n_steps = NSTEPS,
                 nminibatches = MINIBATCHES)

    model.save(results_folder + run_name)

    # Training the model
    for i in range(number_training_steps):
        logname = run_name + '_' + str(i)
        model.learn(total_timesteps = int((total_timesteps/number_training_steps)),
                    reset_num_timesteps = False,
                    tb_log_name = logname)
        
        env.close()
        
        path = results_folder + logname
        model.save(path)


        if i < number_training_steps:
            env = SubprocVecEnv(env_list)
            model.load(load_path=path, env=env)
```
The the first training will complete, but when the model attempts to execute the learn method on the second iteration, the BrokenPipeError: [WinError 232] The pipe is being closed is thrown.

Not sure what this error means or how to resolve the problem.  pointing me towards documentation or pointing out coding mistakes would be appreciated

**Comment by yjc765** [comment]
> I have tried with
> 
> ```
> model = PPO2(CustomPolicy,env,gamma=1, n_steps=132, ent_coef=0.01,
>              learning_rate=2.5e-4, vf_coef=0.5, max_grad_norm=0.5, lam=0.95,
>              nminibatches=4, noptepochs=4, cliprange=0.2, cliprange_vf=None,
>              verbose=0, tensorboard_log="./03_12_2019_logs/", _init_setup_model=True,
>              policy_kwargs=None, full_tensorboard_log=False)
> 
> model.learn(total_timesteps=10000,callback=None, seed=None,
>             log_interval=1, tb_log_name="Logs", reset_num_timesteps=False)
> 
> model.save("agent_03_12_2019")
> ```
> 
> ```
> model = PPO2.load("agent_03_12_2019")
> 
> n_cpu = 8
> env = DummyVecEnv([lambda: AHUenv() for i in range(n_cpu)])
> model.set_env(env)
> 
> 
> model.learn(total_timesteps=2000000,callback=None, seed=None,
>             log_interval=1, tb_log_name="Logs", reset_num_timesteps=False)
> 
> model.save("agent_03_12_2019_continued_training_1")
> ```
> 
> With this the continual training is happening but the tensor board graphs are being updated. I have manually changed the `reset_num_timesteps` to False. but still the tensorboard graphs are not updated.

Hello, have you solved the problem that the tensorboard is not updated? Thanks!

**Comment by jtromans** [comment]
@araffin I note that you mentioned:
"EDIT: you may need to set `num_timesteps` manually to continue properly the graphs"

Where do you set this parameter? Obviously it is not an argument to the PPO learn.

**Comment by SheilaGLZ** [comment]
I could solve the tensorboard problem. When loading the model, set `tensorboard_log` too:
`model = PPO2.load(model_path, tensorboard_log="some_name")`
After that I could see my logs again

**Comment by anguyenbus** [comment]
Hi,

my case is: if have a changing environment like a RNN network, and the reinforcment learning agent is to control whether I should mask the input. (inout - input*mask) and mask is [0,1] discrete.

So what I did is that I train RNN for some epochs, and RNN is the observation of agent. 

Agent will then train by model.learn(5000), RNN is in infernce mode when model is trained

Then I go back and train RNN with model.predict(deterministic= True) for predicting the mask.

I am not sure if the model will sample from the updated RNN environment?

**Comment by Damuna** [comment]
To sum up (I'm stupid so it took me a while to put everything together), the working code is something like this:

```
#Model (if no model is saved)
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=logdir)		#Multi-layer perceptron

#continue training (Path to the last saved model)
model_path = f"models/1660556760/5000"
log_path = f"logs/PPO/1660556760/5000"
model = PPO.load(model_path, tensorboard_log=log_path)
model.set_env(env)''
```
Comment the second part the first time you run the code, and the first one the other times.

**Comment by LucaRosafalco** [comment]
I tried with

ppo_mlp = ppo2.PPO2("MlpPolicy",env,gamma=Gamma,verbose=1,n_steps=nSteps,nminibatches=nBatch,
                                      learning_rate=learningRate,tensorboard_log=logDir,
                                      policy_kwargs=dict(act_fun=tf.nn.tanh,net_arch=[dict(pi=[64],vf=[64])]))

ppo_mlp = ppo2.PPO2.load(model_path, tensorboard_log=log_path)        
if __name__=="__main__":
    env = SubprocVecEnv([lambda: gym.make('Resonator1D-v2')])            
    ppo_mlp.set_env(env)
    # Training   
    ppo_mlp.learn(total_timesteps=totalTimeSteps, log_interval=1, callback=callback, reset_num_timesteps=False)
    ppo_mlp.save(folder_out_weights)

but I got
ValueError: Cannot feed value of shape (10, 10) for Tensor 'loss/advs_ph:0', which has shape '(?,)'

What am I doing wrong? Thanks!

**Comment by milliyang** [comment]
> > the tensorboard graphs are not updated for the new timesteps
> 
> again please read the doc about tensorboard integration, we cover that issue.
> 
> EDIT: you may need to set `num_timesteps` manually to continue properly the graphs

you are just not listening

**Comment by trueToastedCode** [comment]
make sure to use `reset_num_timesteps=False` when learning with previously saved model
