### ISSUE TITLE
Action not clipped for A2C

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#6]
Using A2C with continuous actions (ex; LunarLanderContinuous-v2), actions are not clipped, leading to out of bound error.

**Comment by hill-a** [comment]
This is due to ```stable_baselines.common.distributions.DiagGaussianProbabilityDistribution``` not taking into account the actions space bounds, when using a ```gym.spaces.Box``` action space.

**Comment by hill-a** [comment]
fixed a9e79ea

**Comment by araffin** [comment]
It seems that this problem is solved here (in the env instead of the agent): https://github.com/openai/gym/pull/1060
