### ISSUE TITLE
[feature request] parallel replay buffer for DQN

### ISSUE THREAD

**Issue by flodorner** [hill-a/stable-baselines#604]
When training small models with low dimensional state spaces, the replay buffer seems to be a bottleneck in DQN. Sampling and updating the buffer for multiple indexes can somewhat easily be vectorized using numpy and can lead to significant speedups of these functions for large batch sizes.  
I have implemented the improvement [here](https://github.com/flodorner/stable-baselines) and wanted to create this issue before starting my pull request, in order to get feedback.

**Comment by araffin** [comment]
Related to #324 and #452
