### ISSUE TITLE
[feature-request] TVT: Temporal Value Transport

### ISSUE THREAD

**Issue by eunomiadev** [hill-a/stable-baselines#605]
Optimizing Agent Behavior over Long Time Scales by Transporting Value looks promising.
Reference [TVT DeepMind Research](https://github.com/deepmind/deepmind-research/tree/master/tvt)

**Comment by araffin** [comment]
Hello,

Could you elaborate a bit?

You should know that we are for now focusing on the migration to TF 2.0, so we will avoid adding experimental/new features for now.
We also prefer to wait a bit (and see what stays) before implementing the latest RL method available.

**Comment by araffin** [comment]
Closing as no additional motivation was added.
