### ISSUE TITLE
Compatibility with MultiDiscrete spaces as observation_space

### ISSUE THREAD

**Issue by GBanlik** [hill-a/stable-baselines#61]
Using a space_observation of type MultiDiscrete throws an error on PPO (also tested with ACKTR) use. The error is no present if a Discrete type observation_space is used.
For a very basic test environment the broken env uses:
`self.observation_space = spaces.MultiDiscrete([[0, 12], [0, 250]])`
With returned observation:

```
 def _get_obs(self):
 return np.array([self.variable1,  self.variable2])
```

Whereas for testing purposes, which works, a Discrete environment:
`self.observation_space = spaces.Discrete(3000)`
With returned observation:
```
def _get_obs(self):
return np.array([self.variable1])
```

When using a MultIDiscrete type observation_space, the thrown error is then:
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-c542a1080f7d>", line 1, in <module>
>     runfile('C:/Users/MainUser/Desktop/untitled0.py', wdir='C:/Users/X/Desktop')
> 
>   File "D:\Programs\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
>     execfile(filename, namespace)
> 
>   File "D:\Programs\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/MainUser/Desktop/untitled0.py", line 44, in <module>
>     env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run
> 
>   File "D:\Programs\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 35, in __init__
>     self.buf_obs = {k: np.zeros((self.num_envs,) + tuple(shapes[k]), dtype=dtypes[k]) for k in self.keys}
> 
>   File "D:\Programs\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 35, in <dictcomp>
>     self.buf_obs = {k: np.zeros((self.num_envs,) + tuple(shapes[k]), dtype=dtypes[k]) for k in self.keys}
> 
> TypeError: 'tuple' object cannot be interpreted as an integer

As for the code which originates said problem, it was simply retrieved from the examples page (the random agent, meaning, evaluate function works fine for both cases, the problem is in directly using the models) to ensure the problem wasn't in my code:
```
def evaluate(model, num_steps=1000):
  """
  Evaluate a RL agent
  :param model: (BaseRLModel object) the RL Agent
  :param num_steps: (int) number of timesteps to evaluate it
  :return: (float) Mean reward for the last 100 episodes
  """
  episode_rewards = [0.0]
  obs = env.reset()
  for i in range(num_steps):
      # _states are only useful when using LSTM policies
      action, _states = model.predict(obs)
      # here, action, rewards and dones are arrays
      # because we are using vectorized env
      obs, rewards, dones, info = env.step(action)
      
      # Stats
      episode_rewards[-1] += rewards[0]
      if dones[0]:
          obs = env.reset()
          episode_rewards.append(0.0)
  # Compute mean reward for the last 100 episodes
  mean_100ep_reward = round(np.mean(episode_rewards[-100:]), 1)
  print("Mean reward:", mean_100ep_reward, "Num episodes:", len(episode_rewards))
  
  return mean_100ep_reward

env = gym.make('Test-v0')
# vectorized environments allow to easily multiprocess training
# we demonstrate its usefulness in the next examples
env = DummyVecEnv([lambda: env])  # The algorithms require a vectorized environment to run

model = ACKTR(MlpPolicy, env, verbose=0)

# Random Agent, before training
mean_reward_before_train = evaluate(model, num_steps=10000)

# Train the agent for 10000 steps
model.learn(total_timesteps=10000)

# Evaluate the trained agent
mean_reward = evaluate(model, num_steps=10000)

```

**Comment by araffin** [comment]
Hello,
Thanks for reporting the issue.
Could you please follow the issue template and provide a minimal yet complete code to reproduce the error?

**Comment by araffin** [comment]
Hello,
Thanks for the update.
I suspect your issue is related to this one: https://github.com/openai/gym/issues/1191
What is your gym version?

**Comment by araffin** [comment]
Are you sure you are using `0.10.5`? Did you install it with pip? 
On my computer, the following code raises an error (with this gym version):
```python
spaces.MultiDiscrete([[0, 12], [0, 250]])
```
`AssertionError: nvec should be a 1d array (or list) of ints`

What you want to do is:
```python
spaces.MultiDiscrete([12, 250])
```
no ? (12 and 250 discrete actions)

**Comment by GBanlik** [comment]
That's strange, yes I installed it via Pip and it is definitely `0.10.5`.
I never got an error, it is how the `Hands‑On Intelligent Agents with OpenAI Gym` book defines the space is to be used, but, I have changed it to your recommendation (although I'm working with an observation space, not an action space but I take it its the same), and the problem persists, exactly as before.

**Comment by araffin** [comment]
>I never got an error

I created a colab notebook so you can reproduce the error (with gym 0.10.5): https://colab.research.google.com/drive/1KDWriJMxBv8rtqjvGEu6Qz9bzZvtKt-B

With the latest version of gym (0.10.8), there is no error but the shape is changed (and that causes the error in the vec env): https://colab.research.google.com/drive/1oDOxpECm5mU-joHy_lnLwPGBQkgTaHCh

>I have changed it to your recommendation

If you don't have any error with your original, then my recommendation won't work anyway.

**Comment by GBanlik** [comment]
Ah I see.

Should I then use an older gym version before the shape is changed?

**Comment by araffin** [comment]
Yes,
I would recommend using 0.10.5 (with my recommendation for declaring the space).
I am waiting for OpenAI answer. If breaking things (i.e. no backward compatibility) is what they wanted, we will have to patch stable-baselines, otherwise, we will wait for a fix from gym.

**Comment by GBanlik** [comment]
You are right.

All fixed up, thank you for your help. Hopefully they will fix their end soon enough.
Now to get SubprocEnv working, which seems to not work. I'll run some more testing and open a new issue if needed.

Once again, thank you.
