### ISSUE TITLE
[question] Multi-core with DQN

### ISSUE THREAD

**Issue by matthew-hsr** [hill-a/stable-baselines#612]
I understand that Multi Processing for DQN is not supported - but does having a non-zero batch size mean multi-cores are utilized?

Correct me if I'm wrong, shouldn't at least the forward propagation and backward propagation be possible to be parallelized? 

Thanks in advance!

**Comment by araffin** [comment]
Hello,

Multiprocessing in the doc is only about the environment (you can only have one env with DQN), for training or inference (predicting an action), it uses the GPU if possible or multiple cores if supported. But this comes from tensorflow, not stable baselines.

**Comment by matthew-hsr** [comment]
Thanks araffin! By default Tensorflow uses all available CPU cores right? How may I confirm that's the setting on my machine?

**Comment by araffin** [comment]
>Tensorflow uses all available CPU cores right?

It depends on your installation, but this is no more related to stable baselines. We have keyword for controlling the cpu used when creating a tf session (cf doc).
Closing this issue.
