### ISSUE TITLE
[Question] Schedule for the environment or "curriculum"

### ISSUE THREAD

**Issue by charles-blouin** [hill-a/stable-baselines#617]
Hello there,

What would be the cleanest way to send a schedule to the environment's reset function? Many [papers ](https://arxiv.org/pdf/1901.08652.pdf) implement a varying difficulty setting over the training period. This is especially useful in robotics where initially, the goal is only to find a working solution, and later in the training, the goal is to reduce the energy used by the policy.

Thanks a lot for the great code!

**Comment by charles-blouin** [comment]
There does not seem to be any simple clean way to do this. Unfortunately, Open AI gym does not define a difficulty setting in the reset function. This means that SubprocVecEnv would have to be modified (or a new derived class defined), and each algorithm would need to call the new SubprocVecEnc.

A workaround is to use the callback function of the learn method to write the progress to a file, and use that progress to modify the environment by reading the file at each reset.

Closed for now.

**Comment by araffin** [comment]
>What would be the cleanest way to send a schedule to the environment's reset function? 
>Unfortunately, Open AI gym does not define a difficulty setting in the reset function.

Hello,

if your schedule only depends on the time, then you can have a counter inside the environment.
If it depends on the performance of the agent, then you call a custom method (cf doc) from the agent from time to time (or monitor the performance inside the environment).

**Comment by charles-blouin** [comment]
Thank you, those are good ideas!
