### ISSUE TITLE
BUG: cannot import name 'make_vec_env' in PPO2 Example

### ISSUE THREAD

**Issue by cevans3098** [hill-a/stable-baselines#620]
**Describe the bug**
I'm just starting to run through the examples in stable-baselines and was able to get the initial code examples working in the getting started section of the documentation without issue.  I am currently trying to run the [PPO2 code example](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#example), but I am running into an issue and receive the following Exception: 

_**cannot import name 'make_vec_env'**_

**Code**
The following code is a direct copy from the documentation and is currently failing

```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2

# multiprocess environment
env = make_vec_env('CartPole-v1', n_envs=4)

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
model.save("ppo2_cartpole")

del model # remove to demonstrate saving and loading

model = PPO2.load("ppo2_cartpole")

# Enjoy trained agent
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

```

```bash
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "F:\anaconda3\envs\envTensorflow\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "F:\anaconda3\envs\envTensorflow\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\anaconda3\envs\envTensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Craig\source\repos\Stable_Baseline_testing\PPO2_Example.py", line 5, in <module>
    from stable_baselines.common import make_vec_env
ImportError: cannot import name 'make_vec_env'

```
**System Info**
* Python 3.6
* Tensorflow-GPU 1.14
* stable-baseline 2.8.0

**Comment by surbhi1944** [comment]
Rather using following:

from stable_baselines.common import make_vec_env
env = make_vec_env('CartPole-v1', n_envs=4)

You can use the below code for vectorization:

from stable_baselines.common.vec_env import DummyVecEnv, VecNormalize
env = gym.make('Walker2d-v2')
env = DummyVecEnv([lambda: env])
env = VecNormalize(env, norm_obs=True, norm_reward=False,clip_obs=10.)

**Comment by araffin** [comment]
>stable-baseline 2.8.0

The `make_vec_env` helper was introduced after this version, and is currently only available on master.
You have three solutions:
- Install stable-baselines from source (cf doc)
- Wait a bit (the version 2.9.0 will be released on pip soon, before the end of december)
- Copy the code snippet from master into your code

**Comment by cevans3098** [comment]
@araffin thank you.  I figured this was the case after investigating futher over the weekend.  Thank you for verifying.  I was able to get everything working properly once I copied the code into my own.

Thank again for the response.
