### ISSUE TITLE
Unable to import 

### ISSUE THREAD

**Issue by surbhi1944** [hill-a/stable-baselines#621]
Packages installed in python3.7:
![pip3 7](https://user-images.githubusercontent.com/51375621/70890905-2626e100-200c-11ea-8614-8f4a59935be2.PNG)

But unable to import 
![issue](https://user-images.githubusercontent.com/51375621/70890943-3474fd00-200c-11ea-80ec-6cf87a86edec.PNG)

**Comment by araffin** [comment]
Hello,
please fill up the issue template completely

**Comment by surbhi1944** [comment]
Thankyou for reply.
Issue solved
