### ISSUE TITLE
Unable to use GPU:

### ISSUE THREAD

**Issue by surbhi1944** [hill-a/stable-baselines#623]
I have gpu in my system but code is running only cpu even i set gpu
# Specify which GPU(s) to use
    os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # Or 2, 3, etc. other than 0

# On CPU/GPU placement
    config = tf.compat.v1.ConfigProto(allow_soft_placement=True, log_device_placement=True)
    config.gpu_options.allow_growth = True
    tf.compat.v1.Session(config=config

When i print: 
print("######Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')),tf.config.experimental.list_physical_devices('GPU'))
output is: [] 0

**Comment by araffin** [comment]
Hello,
This seems to be a tensorflow issue, not an issue with stable-baselines.

**Comment by surbhi1944** [comment]
Thakyou..

**Comment by surbhi1944** [comment]
Thankyou...
