### ISSUE TITLE
The output of the making a gif example is wrong.

### ISSUE THREAD

**Issue by KuKuXia** [hill-a/stable-baselines#625]
Hi,

**Describe the bug**
In the document of making a gif example. I found a bug and here is the code copied from the document.

```python
import imageio
import numpy as np

from stable_baselines import A2C

model = A2C("MlpPolicy", "LunarLander-v2").learn(100000)

images = []
obs = model.env.reset()
img = model.env.render(mode='rgb_array')
for i in range(350):
    images.append(img)
    action, _ = model.predict(obs)
    obs, _, _ ,_ = model.env.step(action)
    img = model.env.render(mode='rgb_array')

imageio.mimsave('lander_a2c.gif', [np.array(img[0]) for i, img in enumerate(images) if i%2 == 0], fps=29)
```
In the final line of the code, using img[0] cannot make a right GIF, and I think the enumerate operation is the key to this problem.

Details of the variables:
images: 350 * 400 * 600 * 3
img: 400 * 600 * 3
img[0]: 3

I've made a pr [link](https://github.com/hill-a/stable-baselines/pull/624)

**System Info**
Describe the characteristic of your environment:
 * Install the library using pip
 * GPU: titan xp
 * Python 3.5.6
 * TensorFlow-gpu=1.14.0

**Comment by araffin** [comment]
Hello,

Nice catch.

This is a confirmed bug. I would have expected the `VecEnv` to return a list of images, but this is not the case. Btw, the render method seems to be broker with `DummyVecEnv` for  `num_envs>1`.

**Comment by KuKuXia** [comment]
Hi,
Yup, I got it. This bug is hard to find until I run the code many times. I'm working on reading the document and run every code on my local PC. I'll keep updating if I find a new bug. Last, This repo is really awesome.
