### ISSUE TITLE
the weird result of using callable expert in GAIL

### ISSUE THREAD

**Issue by HeegerGao** [hill-a/stable-baselines#627]
I use a simple expert policy(always return 0) to test how to use a callable expert function in GAIL. But I find the cartpole can end up very perfect even though the expert is so stupid. I don't know why. You can copy these 30 lines and run it in your computer to see what happens:
```python
import gym
from stable_baselines import GAIL
from stable_baselines.gail import ExpertDataset, generate_expert_traj

env = gym.make('CartPole-v1')
def dummy_expert(_obs):
    #callable expert
    return 0

generate_expert_traj(dummy_expert, 'expert_cartpole',env, n_timesteps=0, n_episodes=100)
# Load the expert dataset
dataset = ExpertDataset(expert_path='expert_cartpole.npz', traj_limitation=-1, verbose=1)
model = GAIL('MlpPolicy', env, dataset, verbose=1)
model.learn(total_timesteps=1000)
model.save("gail_cartpole")
del model # remove to demonstrate saving and loading

model = GAIL.load("gail_cartpole")
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
    if dones:
        env.reset()

**Comment by araffin** [comment]
Hello,

Interesting... it may comes from the fact that the episode terminates when the cartpole falls down, so to maximize its long term reward (act like the expert), it needs to balance the pole as long as possible.

**Comment by HeegerGao** [comment]
> Hello,
> 
> Interesting... it may come from the fact that the episode terminates when the cartpole falls down, so to maximize its long term reward (act like the expert), it needs to balance the pole as long as possible.

Thanks for your reply! Maybe it is because that cartpole is too simple, because even if I change the training timestep to only 1, it still learns quite good. It is really interesting.(lol)

Be the way, the reason why I ask this question is that I just want to make sure there isn't bug in your code. Now I think this issue is not from your code. It's from the algorithm itself.

**Comment by araffin** [comment]
>Be the way, the reason why I ask this question is that I just want to make sure there isn't bug in your code. Now I think this issue is not from your code. It's from the algorithm itself.

`GAIL` should work (I tested it on several problems) but I would recommend you to use the implementation from https://github.com/HumanCompatibleAI/imitation (by @AdamGleave  et al., based on stable baselines) because they are actively working on it.

**Comment by AdamGleave** [comment]
Yeah this sounds like the episode termination bias described in [Kostrikov et al](https://openreview.net/forum?id=Hk4fpoA5Km). If you want to test that you could make a cartpole variant with fixed horizon and see if GAIL still learns from a bad expert (I'd expect it not to).
