### ISSUE TITLE
Cannot run default implementation of GAIL

### ISSUE THREAD

**Issue by flaurida** [hill-a/stable-baselines#63]
Hi all, 

Thanks so much for putting this together, I'm very excited about it!

I am trying to run the default implementation of GAIL, but it is throwing an error about the input policy being the wrong type as shown below. Note that I already downloaded the default expert data for the deterministic Hopper expert, and that it is logging out the return stats on the data.

```assert issubclass(self.policy, ActorCriticPolicy), "Error: the input policy for the TRPO model must be " \
AssertionError: Error: the input policy for the TRPO model must be an instance of common.policies.ActorCriticPolicy.```

How to reproduce:
In command line: `python -m stable_baselines.gail.run_mujoco`

Please let me know if I'm missing something, thanks again!

**Comment by araffin** [comment]
Hi, 
Thanks for reporting the bug. @hill-a, it seems that we forgot to refactor GAIL policies.
It's hard for us to debug GAIL for now, as we don't have a mujoco licence...
Feel free to submit a PR if you solve the issue ;)

To guide you a bit:
take a look at `common.policies.py`, you will need to tweak `gail.mlp_policy.py` a bit so it follows the structure of the base class.
Don't hesitate to ask if you have any additional questions ;)

**Comment by krishpop** [comment]
Hi! I'm currently taking a look into this issue, will let you know if I can figure out the cause! I think it might actually be related the trpo_mpi.setup_model method, (as the saved models are loaded from a .npz file), and I reckon that these saved models are not consistent with the current class definition

**Comment by araffin** [comment]
Hi @krishpop ,

Thank you for working on that!

>Is the general design pattern for these scripts is not using the `policy_fn`?

I'm not sure to understand what you mean...

**Comment by krishpop** [comment]
It seems in much of the original baselines code, and in some of the code in stable-baselines, there is a usage of a lambda argument called `policy_fn` that generates a policy of a particular type when called. However, it seems the usage of `policy_fn` is being phased out in stable-baselines, after looking into the trpo_mpi implementation, as well as the `BaseRLModel`, it seems now that there is a policy registry used to organize the different policies.

**Comment by araffin** [comment]
Ok, now I understand what you mean ;)
So, yes this behavior was removed in favor of passing either string (if the policy is registered) or class.

**Comment by krishpop** [comment]
Yes, thanks for clarifying. I will try fixing that, test, and send a PR soon

**Comment by araffin** [comment]
@flaurida @krishpop I started working on updating GAIL (branch [gail-test](https://github.com/hill-a/stable-baselines/tree/gail-test). I'm also adapting it to make it work with other environments (not only mujoco ones) and check at the same time the performance.
