### ISSUE TITLE
[Question] Continuous action space not being searched well

### ISSUE THREAD

**Issue by rusu24edward** [hill-a/stable-baselines#637]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

I would like to understand more about continuous action space. I have a custom environment with an action space that range from about -2000 to 2000. When I train with PPO2, I notice that most of the chosen actions are around 0 and rarely go up as high as +-2, let alone +-2000. This seems a little strange since my environment supports action values far from zero.

How can the agent explore the action space if the actions are so limited?

Is it better to normalize the action space of my custom environment to be around 0?

I can discretize my action space and use a discrete space, but this seems to defeat the purpose of having agents that can learn in a continuous space.

I did not include example code since my question is fairly general, but I am happy to provide if it needed.

**System Info**
 * Installed with pip3
 * No gpus
 * Python 3.7
 * TF 1.14

**Comment by araffin** [comment]
Hello,
the answer is in the documentation : https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment
(and there is a related issue here: #473 )

**Comment by cisprague** [comment]
It would be convenient to have a wrapper that normalises user-defined environements.

**Comment by araffin** [comment]
>It would be convenient to have a wrapper that normalises user-defined environments.

This is more a gym-related issue. Anyway, we have some documentation about that and an `env_checker` now (cf doc).
