### ISSUE TITLE
[bug] memory increases throughout run with ppo2

### ISSUE THREAD

**Issue by titusquah** [hill-a/stable-baselines#642]
**Describe the bug**
This is similar to a previous issue: "Increasing memory usage throughout run time #182". 
The memory usage keeps increasing and causes slow performance and system instability for long runs. 
My current version of numpy is 1.17.1 and I tried to downgrading the numpy version to 1.16.1 but that did not fix the memory increase.
**Code example**

```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2

# multiprocess environment
env = make_vec_env('CartPole-v1', n_envs=4)

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=1000000)
model.save("ppo2_cartpole")

```
![Figure_1](https://user-images.githubusercontent.com/46580668/71699133-695ab100-2d7b-11ea-842f-21e062825b52.png)

**System Info**

Describe the characteristic of your environment:
Windows 10 
 * Describe how the library was installed (pip, docker, source, ...)
Installed from source
Tensorflow installed from conda
 * GPU models and configuration
Not using GPU
 * Python version
3.7.4
 * Tensorflow version
1.14.0
 * Versions of any other relevant libraries
numpy: 1.17.1

**Comment by Miffyli** [comment]
I was not able to replicate the issue (Windows 10, Python 3.7.2, Numpy 1.17.1 or 1.18.0, Tensorflow 1.14.0 no GPU). The memory usage (according to task manager) hovered around 225MB and stayed there throughout the whole run. In the light of the related issue you could try upgrading Numpy to 1.18 to see what happens.

**Comment by titusquah** [comment]
It was one of the other packages installed in my pip environment so creating a new environment and testing it there fixed it. 
I will move over to Linux as well. 
Thank you for your help!
