### ISSUE TITLE
Feature request: Add training information to tensorboard scalars

### ISSUE THREAD

**Issue by phemmer** [hill-a/stable-baselines#643]
I think it would be a good change to add the training information metrics that are output to the logger (when `verbose>=1`) to tensorboard as well.

I've occasionally run into issues where looking at a snapshot of the values (the log output to the console) hasn't been obviously problematic, but looking at the values over time has made an issue apparent.
Currently I'm copying the code that generates the logger values out of the model and into my own custom callback where I write to tensorboard. But I would like to leave that code in the model and not have to duplicate it.

Making the change is likely trivial, as it would just involve taking the values from `loger.getkvs()`. But I wanted to solicit feedback before creating a PR, as there's a few ways to go about it, and don't want to waste the time if there's no chance it'd get merged.

My thought on implementation would be to make `logger.dumpkvs()` accept an optional parameter for a `TensorboardWriter`, and when present, would dump the values there in addition to the console.
However this does mean that the tensorboard output would be linked to setting `verbose>=1`. If someone wants to output to tensorboard, but not console, it wouldn't be possible. An alternative could be a separate method on `logger` specifically for dumping to tensorboard, but not sure how the model parameters should look to toggle that behavior.

**Comment by araffin** [comment]
Hello,

have you read the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html#legacy-integration) ?

**Comment by phemmer** [comment]
Yes, I called that out in the issue description:

> Currently I'm copying the code that generates the logger values out of the model and into my own custom callback where I write to tensorboard. But I would like to leave that code in the model and not have to duplicate it.

**Comment by araffin** [comment]
>Currently I'm copying the code that generates the logger values 

Why are you doing that where you can enable logging the values with tensorboard with
```
# formats are comma-separated, but for tensorboard you only need the last one
# stdout -> terminal
export OPENAI_LOG_FORMAT='stdout,log,csv,tensorboard'
export OPENAI_LOGDIR=path/to/tensorboard/data
```
which avoid using callbacks?

**Comment by phemmer** [comment]
I apologize then, as I misunderstood that section of the documentation, and thought it was saying something else. That solution isn't great (it creates a seaparate run in tensorboard instead of being part of the same run, and it creates a ton of top-level tags, instead of putting them all under logger, which would be cleaner IMHO). But as the functionality obviously exists, it does not need to be added, and I'll close the issue.

**Comment by araffin** [comment]
>That solution isn't great 

yes, I know, that's why it is the *legacy* integration, I agree on the fact it could be better (hence the *enhancement* tag). Another thing to add to the list of v3 ( #576 and #366 ).
