### ISSUE TITLE
[suggestion] Remove `gym[mujoco,atari,classic_control,robotics]` from setup.py

### ISSUE THREAD

**Issue by zafarali** [hill-a/stable-baselines#65]
Keeping `gym[mujoco,atari,classic_control,robotics]` in the setup.py script causes it to install a lot of unnecessary things some of which may not be available. For example in the colab, i was unable to install mujoco. Letting the user explicitly decide what to include might be a good way to maintain a lightweight install.

Thanks!

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.  

**Describe the bug**

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
 * GPU models and configuration
 * Python version
 * Tensorflow version
 * Versions of any other relevant libraries

**Additional context**

**Comment by araffin** [comment]
Hello,
Thanks for reporting this issue, I'm on it ;) (see https://github.com/hill-a/stable-baselines/pull/64)
Will be fix soon (with a new release of stable-baselines)
