### ISSUE TITLE
Problems with docker image after change #565 No module named 'stable_baselines.common'

### ISSUE THREAD

**Issue by sikora507** [hill-a/stable-baselines#650]
I noticed that some time ago, exactly at Nov 21, 2019, there was a change in documentation by @AdamGleave 
The change in file `docs/guide/install.rst` was from line:
`docker pull araffin/stable-baselines`
to line
`docker pull stablebaselines/stable-baselines`

I see that on docker hub, there are now 2 images, but I can't get `stablebaselines/stable-baselines` to work.

When I do `docker pull stablebaselines/stable-baselines`
Then I run `docker run -it stablebaselines/stable-baselines`
Then inside the container i run `root@e138a33e5fca:/# pip install stable-baselines`
Then I run python `root@e138a33e5fca:/# python`

And when I try to include something from stable_baselines like this line taken straight from the documentation: `>>> from stable_baselines.common.policies import MlpPolicy`
I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'stable_baselines.common'
```

This is not the issue with old image `docker pull araffin/stable-baselines` and I can run examples from the documentation. But I guess we are using `docker pull stablebaselines/stable-baselines` now which I think is not working.
With the new image, I cannot include anything from stable_baselines.

Please help.

**Comment by araffin** [comment]
Hello,
the docker image does not have Stable Baselines installed.
as written in the docs:
"
If you are looking for docker images with stable-baselines already installed in it, we recommend using images from RL Baselines Zoo.

Otherwise, the following images contained all the dependencies for stable-baselines but not the stable-baselines package itself. They are made for development."

**Comment by sikora507** [comment]
Yes i saw this. That's why I'm doing `pip install stable-baselines` after using this image. It worked for `araffin/stable-baselines` but something is not right with the new one.

Even on [baselines zoo](https://github.com/araffin/rl-baselines-zoo/blob/master/docker/Dockerfile) the dockerfile is installing stable-baselines through pip on line 45 in dockerfile:
`pip install stable-baselines[mpi,tests]==2.9.0 && \`

Here's my example dockerfile I created for hosting flask web api in python using stable-baselines from old image:
```
FROM araffin/stable-baselines

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN \
    pip install stable-baselines
RUN \
    pip install flask
RUN \
    pip install -U ptvsd

ENV PATH=~/.local/bin:$PATH

COPY . /root/code
WORKDIR /root/code

ENTRYPOINT [ "python", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5010", "--no-debugger", "--no-reload"]
```
After changing from "affin" to "stablebaselines" it won't work (python imports won't find the modules). I can't figure out what the problem is.
I looked at RL Baselines Zoo for a moment, but there you need to build your docker images first so I thought it cannot be that complicated and created my own dockerfile instead. But I'll give it a try.
