### ISSUE TITLE
[question] HER and desired/achieved goal sampling

### ISSUE THREAD

**Issue by edwinlima** [hill-a/stable-baselines#651]
I would like to know how you guys sample the desired and achieved goals during testing of a HER agent. I can create the desired and achieved goals during training in my environment but during testing/playing when I only have access to the observation space (current state), what would be the values of the desired and achieved goals, do you sample them randomly?  Thanks in advance

**Comment by araffin** [comment]
Hello,
I'm not sure to understand your question.

>during testing/playing when I only have access to the observation space (current state)

Why don't you have access to the desired goal? Because that's the whole point of HER, achieving desired goals...
