### ISSUE TITLE
Question: model/lstm1 node has 0 inputs - PPO2 with MlpLnLstmPolicy

### ISSUE THREAD

**Issue by signalprime** [hill-a/stable-baselines#656]
**Bug description**
Tensorboard reports the LSTM node, located at model/lstm1 has 0 inputs, when reviewing the graph of PPO2 with MlpLnLstmPolicy.  

Screenshots:
![image](https://user-images.githubusercontent.com/15487280/72643765-6942df80-393d-11ea-8923-1949caec6fd7.png)
 
**Code example**
```python
import gym

from stable_baselines.common.policies import MlpLnLstmPolicy 
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env = gym.make('CartPole-v1')

model = PPO2(MlpLnLstmPolicy, env, verbose=1, nminibatches=1, tensorboard_log="/logdir/")
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

env.close()
```

**System Info**
 * installed via pip+git
 * Python 3.6
 * Tensorflow version 1.14.0

**Comment by araffin** [comment]
Hello,

I think you should take a look at the train model, this is the one used for training.
It is defined here: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L132
https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/policies.py#L415

I think the one you are looking at is the one used for inference, but then there may be an issue there.
