### ISSUE TITLE
Scale Training to multiple Machines

### ISSUE THREAD

**Issue by avolution** [hill-a/stable-baselines#657]
Hey Guys,

I want to scale the training of my models to multiple machines.

Is that possible with the current codebase(e.g. in python multiprocessing) or do I have to create a special env for that? 

My Ideas:
Cause we have that structure:
Step -> calc on every worker -> step ->  calc on every worker -> step -> ...

I would use Kubernetes to create a cluster provides worker nodes for example with a socket endpoint for communication with the main training process.

The question is whether is this is not to expensive on effort for inter machine communication so its not worth to use multiple machines.

Let's discuss
----

**Comment by araffin** [comment]
Hello,

Some algorithms (cf doc, PPO1, DDPG and TRPO) support MPI, so they can be easily training on multiple machine.
For the rest, among the one that support multiprocessing (i.e. `VecEnv`), you will need to create a custom `VecEnv` I think (cf code for how it works currently with multiprocessing).
But before trying multiple machine, I would first try with a `DummyVecEnv`, that usually yields the best performances (cf [tutorial](https://github.com/araffin/rl-tutorial-jnrr19))
