### ISSUE TITLE
[question] Usage without Gym

### ISSUE THREAD

**Issue by MentalGear** [hill-a/stable-baselines#658]
My simulator doesn't support the gym env at the moment. Is it also possible to use the stable baselines without a gym environment. For example by passing values directly as command line arguments ?

**Comment by Miffyli** [comment]
Simply put, no. The agent-environment interaction is defined (and limited to) what is specified in Gym. However creating a Gym wrapper around your environment should not be too difficult. The main required parts are the `step`, `reset` and `close` functions as well as `observation_space` and `action_space` class variables. See e.g. [this blog post](https://towardsdatascience.com/creating-a-custom-openai-gym-environment-for-stock-trading-be532be3910e) for more information.

**Comment by araffin** [comment]
You have also a section in the documentation and a colab notebook: https://github.com/araffin/rl-tutorial-jnrr19

**Comment by GF-Huang** [comment]
It sounds like stable-baselines are more for experiments than real projects, am I understanding that right? 
If I understand correctly, is SB3 also geared towards experiments rather than real projects?

**Comment by Miffyli** [comment]
@GF-Huang More or less: the core maintainers are from academia, so there is focus on research. People do use SB3 for practical projects, too (see SB3 docs "Projects").
