### ISSUE TITLE
Multiprocessing with HER+DDPG and MuJoCo env 

### ISSUE THREAD

**Issue by MariusHebecker** [hill-a/stable-baselines#659]
Hi Everyone. I'm wondering what's the best way to use multiprocessing with HER+DDPG and a MuJoCo environment as vectorized subprocess environments seem to be not supported. What's the recommended way of using MPI? 
Thanks in advance!

**Comment by araffin** [comment]
Hello,

You can find an answer in the documentation and here: https://github.com/hill-a/stable-baselines/issues/424
