### ISSUE TITLE
Loaded model from file does not consider its action space continuous: error when running in `LunarLanderContinuous-v2` environment

### ISSUE THREAD

**Issue by lukasmericle** [hill-a/stable-baselines#66]
I train a model with PPO2 on the `LunarLanderContinuous-v2` environment, then save it to a file.

Then I load the file, just like in the example, and run it again with the same environment to render the process, again just like in the example.

But an error occurs which indicates that the loaded/inferred model has as an attribute `self.continuous=False` or similar.

The equivalent process works just fine without error if `env_name='LunarLander-v2'`.

**MWE of bug:**
```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2

env_name = 'LunarLanderContinuous-v2'
policy = MlpPolicy
rl_alg = PPO2
rl_name = 'ppo2'

env = gym.make(env_name)
env = DummyVecEnv([lambda:env])

model = rl_alg.load(rl_name+"_"+env_name)

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

Stack trace:
```python
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Loading a model without an environment, this model cannot be trained until it has a valid environment.

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-e900d1547adb> in <module>()
     12 while True:
     13     action, _states = model.predict(obs)
---> 14     obs, rewards, dones, info = env.step(action)
     15     env.render()

/usr/local/lib/python3.5/dist-packages/stable_baselines/common/vec_env/base_vec_env.py in step(self, actions)
     92         """
     93         self.step_async(actions)
---> 94         return self.step_wait()
     95 
     96     def get_images(self):

/usr/local/lib/python3.5/dist-packages/stable_baselines/common/vec_env/dummy_vec_env.py in step_wait(self)
     45         for env_idx in range(self.num_envs):
     46             obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] =\
---> 47                 self.envs[env_idx].step(self.actions[env_idx])
     48             if self.buf_dones[env_idx]:
     49                 obs = self.envs[env_idx].reset()

/usr/local/lib/python3.5/dist-packages/gym/wrappers/time_limit.py in step(self, action)
     29     def step(self, action):
     30         assert self._episode_started_at is not None, "Cannot call env.step() before calling reset()"
---> 31         observation, reward, done, info = self.env.step(action)
     32         self._elapsed_steps += 1
     33 

/usr/local/lib/python3.5/dist-packages/gym/envs/box2d/lunar_lander.py in step(self, action)
    236 
    237     def step(self, action):
--> 238         assert self.action_space.contains(action), "%r (%s) invalid " % (action,type(action))
    239 
    240         # Engines

AssertionError: array([0.87050533, 1.862139  ], dtype=float32) (<class 'numpy.ndarray'>) invalid
```

**System Info**
Model was trained/saved on Python 3.6 and loaded on Python 3.5
Library was installed via `pip install stable-baselines`
Trained on GPU, loaded and run on CPU only
All packages are up-to-date except I must run Tensorflow 1.5.0

**Additional context**
The model was trained and saved on a Google Compute Engine instance and run locally on an old Thinkpad laptop.

**Comment by araffin** [comment]
Hello,
The problem is that you don't clip the action. Cf Documentation:
https://stable-baselines.readthedocs.io/en/master/modules/policies.html

>For all algorithms (except DDPG), continuous actions are only clipped during training (to avoid out of bound error). However, you have to manually clip the action when using the predict() method.


An easy solution to your problem is to upgrade your gym version, as they added clipping in LunarLanderContinuous recently ;) (see commit https://github.com/openai/gym/commit/d1146303b070a463e9e81086a0aeff7a2c909311#diff-41ce3ee7821ddd711130ac102a355dec)

(I assume your gym version is <= 0.10.5)

**Comment by lukasmericle** [comment]
Great, thanks for the detailed answer! For some reason, it seemed like installing `stable-baselines` from pip encouraged `gym 0.10.5` as a dependency. Upgrading `gym` resolved the issue.

**Comment by araffin** [comment]
The thing is that gym broke backward compatility with their new version for Multidiscrete action space, making stable baselines tests fails. That s why version 0.10.5 is the one recommended (but in your case, that does not matter)
