### ISSUE TITLE
Bug in check_env for high dimensional action space in custom environment

### ISSUE THREAD

**Issue by juliuskittler** [hill-a/stable-baselines#660]
**Describe the bug**

It seems like there is an bug in one of the test cases for `check_env`. The test case is supposed to give a warning. However, due to the code line `(np.abs(action_space.low) != np.abs(action_space.high)`, the test case has a `ValueError` when the action spice is high dimensional. The condition cannot properly be checked as implied by `The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. 

**Code example**

In your desired directory and environment:

`git clone https://github.com/notadamking/Stock-Trading-Environment.git`
`cd Stock-Trading-Environment`
`jupyter notebook`

Then, in the jupyter notebook:
```from env.StockTradingEnv import StockTradingEnv
from stable_baselines.common.env_checker import check_env
import pandas as pd
df = pd.read_csv('./data/AAPL.csv')
df = df.sort_values('Date')
env = StockTradingEnv(df)
check_env(env)```


Then the error is:

Then, in the jupyter notebook:
```ValueError                                Traceback (most recent call last)
<ipython-input-6-58967ee300b6> in <module>
      2 df = df.sort_values('Date')
      3 env = StockTradingEnv(df)
----> 4 check_env(env)

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\stable_baselines\common\env_checker.py in check_env(env, warn, skip_render_check)
    206         # Check for the action space, it may lead to hard-to-debug issues
    207         if (isinstance(action_space, spaces.Box) and
--> 208                 (np.abs(action_space.low) != np.abs(action_space.high)
    209                  or np.abs(action_space.low) > 1 or np.abs(action_space.high) > 1)):
    210             warnings.warn("We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**System Info**

Describe the characteristic of your environment:
error occured in Windows and in WSL

 * Describe how the library was installed (pip, docker, source, ...)
pip install stable-baselines

 * GPU models and configuration
no GPU used for this

 * Python version
3.7.5

 * Tensorflow version
2.0.0 (but the error also occured with older version)

**Comment by juliuskittler** [comment]
The issue is in line 208 of this file on the current version/commit of stable baselines (today is 24.01.2020): https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/env_checker.py

**Comment by Miffyli** [comment]
Good catch! Looks like `test_envs.py` does not test for action spaces with more than one continuous action, so that needs to be fixed as well. We would appreciate a PR that fixes this issue and adds missing tests :)
