### ISSUE TITLE
docs for 2.9.0 have not been released

### ISSUE THREAD

**Issue by Visgean** [hill-a/stable-baselines#662]
Hi the version in pip is 2.9.0 however read the docs does not contain this build:

![image](https://user-images.githubusercontent.com/193832/73118516-242a3900-3f4d-11ea-89cc-d1b14b9a9e3b.png)

**Comment by araffin** [comment]
Hello,

Nice catch, the master version was quite close to it but now I added the v2.9.0 ;) : https://stable-baselines.readthedocs.io/en/v2.9.0/ (the process is manual unfortunately)

**Comment by Visgean** [comment]
Thanks, you might have been affected by the github change of webhooks: https://docs.readthedocs.io/en/stable/webhooks.html#my-project-isn-t-automatically-building
