### ISSUE TITLE
[feature request] DummyVecEnv render for n_env > 1

### ISSUE THREAD

**Issue by shwang** [hill-a/stable-baselines#663]
`render` for DummyVecEnv is a no-op for n_env > 1 because it will always throw a warning without even attempting to render: https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/dummy_vec_env.py#L67.

I think that `DummyVecEnv`'s super() call is expecting `VecEnv.render()` to actually perform a render rather than printing a warning and doing nothing. Basically `DummyVecEnv` is expecting the OpenAI Baselines implementation for `VecEnv.render`:

https://github.com/openai/baselines/blob/9ee399f5b20cd70ac0a871927a6cf043b478193f/baselines/common/vec_env/vec_env.py#L110-L119

**Comment by araffin** [comment]
Hello,
Thanks for pointing out, this feature was definitely missing (in fact `seed()` is also missing too).
