### ISSUE TITLE
dqn.DQN methods lack parameter documentation

### ISSUE THREAD

**Issue by blthayer** [hill-a/stable-baselines#668]
[enhancement] [documentation]

Hello, and thank you for putting this repository together! I'm refactoring my code to use stable-baselines instead of baselines, as I appreciate your additional testing and documentation.

I'm using DQN, and noticed that only the DQN class initialization parameters are documented within the class docstring. None of the class methods (e.g. `learn`, `predict`, `action_probability`) have parameter documentation. 

This caused a hitch for me migrating over from baselines: the `callback` in the `learn` method uses the opposite conventions of baselines (`False` to stop training, `True` to continue, whereas it's the opposite in baselines).

Thank you!

**Comment by Miffyli** [comment]
This documentation is given in the root of all algorithms, [`BaseRLModel`](https://github.com/hill-a/stable-baselines/blob/4fada47f1b71b7548c935b1f01c6fb04199b3d54/stable_baselines/common/base_class.py#L351), which is inherited by all algorithms, which is then [reflected in the docs](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html#stable_baselines.deepq.DQN.learn). 

I do agree, though: just by looking at the code this is not apparent you have to take extra steps to see the docs. However I do not know good way to fix this.

**Comment by blthayer** [comment]
@Miffyli - Thanks for your prompt reply, and documentation link! 

Since the documentation is present both on readthedocs as well as when using an IDE such as PyCharm (using `ctrl` + `Q` to get quick documentation gives me the parameter documentation for `DQN.learn`), I think this is a non-issue. Thanks for pointing me in the right direction, and thanks again for putting this repository together!
