### ISSUE TITLE
MlpPolicy is the only working policy for my custom environment

### ISSUE THREAD

**Issue by ppanteliadis** [hill-a/stable-baselines#671]
I tried making a custom Environment which I'm succeeding in training using `DQN `and `A2C `using the respective `MlpPolicy`.

```
env = FXTradingEnvironment(spot_rates, client_amounts, client_actions)
env = Monitor(env, filename=f'{log_dir}/FXTrading.log', allow_early_resets=True)
# The algorithms require a vectorized environment to run
env = DummyVecEnv([lambda: env])

model_dqn_mlp = DQN(MlpPolicy, env, verbose=0, tensorboard_log="./tmp/dqn_FX_tensorboard/")
model_dqn_cnn = DQN(CnnPolicy, env, verbose=0, tensorboard_log="./tmp/dqn_FX_tensorboard/")
```

And I get the following error:
```
model_dqn_cnn = DQN(CnnPolicy, env, verbose=0, tensorboard_log="./tmp/a2c_FX_tensorboard/")
Traceback (most recent call last):

  File "<ipython-input-69-cc2f20ccec35>", line 1, in <module>
    model_dqn_cnn = DQN(CnnPolicy, env, verbose=0, tensorboard_log="./tmp/a2c_FX_tensorboard/")

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\dqn.py", line 105, in __init__
    self.setup_model()

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\dqn.py", line 143, in setup_model
    double_q=self.double_q

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\build_graph.py", line 367, in build_train
    act_f, obs_phs = build_act(q_func, ob_space, ac_space, stochastic_ph, update_eps_ph, sess)

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\build_graph.py", line 141, in build_act
    policy = q_func(sess, ob_space, ac_space, 1, 1, None)

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\policies.py", line 176, in __init__
    layer_norm=False, **_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\deepq\policies.py", line 106, in __init__
    extracted_features = cnn_extractor(self.processed_obs, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\common\policies.py", line 24, in nature_cnn
    layer_1 = activ(conv(scaled_images, 'c1', n_filters=32, filter_size=8, stride=4, init_scale=np.sqrt(2), **kwargs))

  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines\a2c\utils.py", line 133, in conv
    n_input = input_tensor.get_shape()[channel_ax].value

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py", line 870, in __getitem__
    return self._dims[key]

IndexError: list index out of range
```

Am I doing something wrong? Did I miss something from the docs?

**Comment by araffin** [comment]
Hellon
Did you try the `check_env` wrapper? What is your observation space?

I assume the observation space is a 1D vector, in that case `CnnPolicy` does not make sense (cf doc) or you will need a custom CnnPolicy (cf #436 and https://github.com/hill-a/stable-baselines/issues/456 )

**Comment by ppanteliadis** [comment]
Obs space is a (2,5) vector.

My environment is defined as 
```
class FXTradingEnvironment(gym.Env):
    """A RL FX trading environment made for use with gym-enabled algorithms"""
    metadata = {'render.modes': ['human']}
```

But the check_env is returning:
`AssertionError: You environment must inherit from gym.Env class  cf https://github.com/openai/gym/blob/master/gym/core.py`

**Comment by ppanteliadis** [comment]
@araffin Apparently, using the Monitor class, changes the class type of the environment.

**Comment by araffin** [comment]
>But the check_env is returning

Please make it run with it before continuing, looking at the code of the env checker will also give you some answers ;)

https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/common/env_checker.html#check_env

https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/env_checker.py

**Comment by MentalGear** [comment]
@ppanteliadis I have the same issue with "You environment must inherit from gym.Env class cf " error. Would you mind telling us how and if you have fixed this bug ?

**Comment by araffin** [comment]
>Would you mind telling us how and if you have fixed this bug ?

Your environment must derive from `gym.Env` class, this is not a bug. Here, the environment is implemented in c++ so this is a corner case.

**Comment by MentalGear** [comment]
Actually, found the issue for  "You environment must inherit from gym.Env class cf " error.
I used check_env after a the Monitor env wrapper. Check_env must be used right after init the env and before other env augmentations.
Maybe the error message could be cleared up a bit to help future users quicker identify the issue, by returning: " You**r** environment must inherit **directly** from gym.Env class cf  Wrappers must be added after checking."
