### ISSUE TITLE
Seeding for vecotorized environments in BaseRLModel is broken

### ISSUE THREAD

**Issue by NeoExtended** [hill-a/stable-baselines#675]
In Line 184 of [base_class.py](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/base_class.py) the environments are initialized with the seed in the form of:
`                for idx in range(self.env.num_envs):
                    self.env.env_method("seed", seed + idx)`

but it should be 

`                for idx in range(self.env.num_envs):
                    self.env.env_method("seed", seed + idx, indices=idx)`

or else we just initialize all the environments over and over with a new seed, but all envs still have the same.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue.
A even better fix would be to implement seed() method for the BaseVecEnv.
We would appreciate a PR that solves that issue ;)

**Comment by NeoExtended** [comment]
I created the pull request. I dont have that much experience with git, but i hope i followed your template. The changes work for me. 
Btw I noticed some maybe unwanted behaviour with the new env.render() method comming from some previous change to the master branch: The current code requires the mode parameter which may break some code and the tutorials.
