### ISSUE TITLE
Is it possible to specify the name of the Tensorboard folder to be created?

### ISSUE THREAD

**Issue by ppanteliadis** [hill-a/stable-baselines#689]
Now, when I do

```
LOG_PATH='logs'
mymodel = A2C(MlpPolicy, env, verbose=0, tensorboard_log=LOG_PATH)
```

This will generate a A2C_1 folder in the logs directory.

Would it be possible to control the name of the A2C folder?

**Comment by araffin** [comment]
Hello,

The answer is in the documentation ;) (take a look at the `learn()` method)
