### ISSUE TITLE
Loading models from orginal baselines

### ISSUE THREAD

**Issue by MatPoliquin** [hill-a/stable-baselines#690]
I have a bunch saved models trained with the latest original baselines with TF 1.14
Provided I specify the exact same policy network of course, what is the easiest way to load these parameters (model.load() doesn't seem to have options for that). Are there helper functions for conversion?

**Comment by araffin** [comment]
Hello,

You should take a look at the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters), especially the `load_parameters()` method.

**Comment by MatPoliquin** [comment]
Yes but the format is different, it would need to be converted before beeing used by model.load_parameters(), so I was wondering if there was already some helper functions for it before I spend time writing one.

**Comment by Miffyli** [comment]
There is no helper function for this in stable-baselines, but coming up with a crude one should not be super-difficult. You need to figure out how to open models [baselines saves](https://github.com/openai/baselines/blob/master/baselines/common/tf_util.py#L322), map the variable names from there to ones used in stable_baselines (see e.g. `get_parameters()` parameters method), update such dictionary with the ndarrays from baselines and finally use `load_parameters()` to load those parameters.

**Comment by araffin** [comment]
I'm afraid this won't be possible to have a generic helper, but adding a link to your code would be good ;)

**Comment by MatPoliquin** [comment]
alright, thanks for the answers
