### ISSUE TITLE
[feature request] Option to pass reset parameters to runners/algorithms

### ISSUE THREAD

**Issue by Solliet** [hill-a/stable-baselines#691]
# Motivation

## Usecase 1:

Some environments can be customized by passing in parameters in the reset function. This is often done in environments with very expensive initialization such as unity games. An alternative option to passing arguments to the reset is to register environments using `gym.register`. This however just pushes the problem down the line. The environment I am currently working on has  5 initialization parameters of 2.3 options (on average), this puts it at 2.3**5 (or roughly 64) combinations, thus I will need to create and register 64 environment ids, this just pushes the problem to creating a mechanism to make IDs, but at 5 parameters, you are looking at ids 40 characters long. 

## Usecase 2:

Some environments get progressively harder, thus an agent needs to spend more time in the more difficult 'levels'. Without the option to alter the reset parameters, any scheduling mechanism will need to be baked into the environment itself which doesn't make a lot of sense. In addition, if we simply let the agent progress naturally, it is likely that it will spend more time in easier levels and in consequence, never learn to solve the more difficult problems.

This problem can be solved by evaluating the agent and supplying new reset parameters such that the agent spends more time in the harder parts. The new reset parameters can be provided using a callback.

# Proposition

The proposition is to allow passing a dictionary in the learn or the algorithm function for reset environments. An extension would be passing a callable that returns the parameters.

## Example scenario

To start the environment, i use `common.make_vec` and I pass in the string id of the environment:

file: `myenv/__init__.py`
```python
register(
    id="MyEnvId-v0",
    entry_point="myenv:Env"
)
```

In training file:

```python
import myenv
import stable_baselines as sb

env = sb.common.make_vec_env('MyEnvId-v0', 8)
# init ...

def reset_params():
    return {'myparam1':'foo'}

model.learn(...., reset_params = reset_params)
```

### Changes introduced:

- Every agent will need a parameter that needs to be taken into account when resetting
- Runners will have to be adjusted

### Alternatively
- Wrapper around `reset`

**Comment by araffin** [comment]
Hello,

I think you already have the ability to do what you want, and it will be even easier with the new callbacks (see PR #644 )

>this just pushes the problem to creating a mechanism to make IDs, but at 5 parameters, you are looking at ids 40 characters long.

Do you know about passing `kwargs` to the `gym.make` ? (see https://github.com/openai/gym/blob/master/gym/envs/registration.py#L141)
This is a recent feature from gym, this allow to avoid having too much ids.

>Some environments get progressively harder, thus an agent needs to spend more time in the more difficult 'levels'. 

Why can't you just call a method from the environment like `env.change_level(level_id)`? 
iit is possible to that both with normal env and `VecEnv`, and would be trivial to call with a callback

old style:
```python
def callback(locals_, globals):
    locals_['self'].env.change_level(level_id)
    # for a vec_env: locals_['self'].env.env_method('change_level', level_id)
```
new style (coming soon), in combination with a `EvalCallback` (cf pull request):

```python
...
    def _on_rollout_env(self):
        self.training_env.change_level(level_id)
        # for a vec_env: self.training_env.env_method('change_level', level_id)
```

To provide that method (in case it does not exist), a simple wrapper would do the job.

**Comment by Solliet** [comment]
Hi,

> Do you know about passing kwargs to the gym.make ? (see https://github.com/openai/gym/blob/master/gym/envs/registration.py#L141)
> This is a recent feature from gym, this allow to avoid having too many ids.

Yes I am aware, but this requires creating new environments. Is that correct? The problem here is that creating a new environment takes around 4-5 seconds which is roughly 3-4 episodes.

>Why can't you just call a method from the environment like env.change_level(level_id)?
iit is possible to that both with normal env and VecEnv, and would be trivial to call with a callback

To change the level I'd need to reset the environment. But I suppose I can sort of 'queue' the change until it resets.

I think the callback is sufficient. Thanks for the help! Feel free to close this.

**Comment by araffin** [comment]
> but this requires creating new environments. Is that correct?

yes

> But I suppose I can sort of 'queue' the change until it resets.

exact, you should use the wrapper to queue the change, something like:

```python

class MyWrapper(gym.Wrapper):
    def __init__(env):
        super(MyWrapper, self).__init__(env)
       self.level_id = 0
    def reset(self):
        return self.env.reset(level_id=self.level_id)
    def change_level(self, level_id):
        self.level_id = level_id
