### ISSUE TITLE
How to enable multicore support under Windows10?

### ISSUE THREAD

**Issue by Chris273672** [hill-a/stable-baselines#700]
First thanks for the great work people put into baselines. Really amazing project! My question:
The env trains fine, but it nevr uses more than one core (Win10) rather then 4:

    env = make_vec_env(TestEnv, n_envs=4, seed=0)
    model = ACER(MlpPolicy, env, verbose=0)
    model.learn(total_timesteps=250000)

This starts 4 environments, but all run on the same core.  Anything I am missing?

**Comment by araffin** [comment]
Hello,
I recommend to read the doc on [VecEnv](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html) and [make_vec_env](https://stable-baselines.readthedocs.io/en/master/common/cmd_utils.html#stable_baselines.common.cmd_util.make_vec_env) ;)

Hint: you wil have to use the `vec_env_cls` argument.

**Comment by Chris273672** [comment]
Thanks! That solved it.
