### ISSUE TITLE
[question] PPO2 minibatches with custom envs

### ISSUE THREAD

**Issue by ggenesum** [hill-a/stable-baselines#701]
Hello, 
I'dd like to use PPO2 on a custom gym environment I made. 
However, I have to set nminibatch to 1:
"For recurrent policies, with PPO2, the number of environments run in parallel
should be a multiple of nminibatches".
Is there a way to edit n_envs for my custom env ?
Thanks

**Comment by Miffyli** [comment]
Please read the documentation, especially [this example](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#recurrent-policies).

**Comment by ggenesum** [comment]
I found the solution, I just had to create a vector of envs.
Thanks for your help
