### ISSUE TITLE
Callback function for prediction

### ISSUE THREAD

**Issue by juliuskittler** [hill-a/stable-baselines#706]
This is a suggestion for a feature:

**Issue**

 It seems like currently, the callback function only works for `model.learn`. 

**Suggestion**

However, it would be great to use the exact same callback function for `model.predict` (possibly with a different log path). It's really helpful to compare the same metrics tracked with the callback function during traing when evaluating the model as well.

Or am I mistaken here and there is a way to use the callback function also during `model.predict`? Thanks a lot in advance.

**Comment by araffin** [comment]
Hello,

I'm not sure to get your point... `model.predict()` is a stand-alone method whereas `model.learn()` handle the all training loop and hide a lot of thing (and that's why callback are useful for that one).

That being said, better callbacks are coming (including a built-in collection of common callback) soon in #644

**Comment by juliuskittler** [comment]
Okay, I have a custom callback function that also writes variables from the environment to a monitor.csv at the end of every episode (for instance rewards but lots of other things as well). Of course, I can extract all this information myself in a different function during evaluation (from `env` when using `model.predict`) but I was hoping that there is a way to simply use the callback in the same way during `model.predict`.  

Looking forward to the better callback functions that you announced.

**Comment by araffin** [comment]
>, I have a custom callback function that also writes variables from the environment to a monitor.csv at the end of every episode

It sounds that you need more a `gym.Wrapper` than a callback in that case.
