### ISSUE TITLE
Should achieved_goal and desired_goal also be part of the observation?

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#708]
When using HER, the `observation_space` should consist of `observation`, `achieved_goal` and `desired_goal`.

My question is, should `achieved_goal` and `desired_goal` also be part of the `observation`?

I was taking a look at [OpenAI's Fetch environment](https://github.com/openai/gym/blob/639264c545329638a513d3c241e52ef792f56379/gym/envs/robotics/fetch_env.py#L108-L121), and it looks to me like the `achieved_goal` is indeed part of the `observation`, but the ` desired_goal` is not. Why is that?

**Comment by araffin** [comment]
Hello,

This question should be on the gym repo.

>Why is that?

`achieved_goal` is always deduced from the current observation where  `desired_goal` is what you want to achieved. They are all passed (cf the code you linked) to the agent.

**Comment by araffin** [comment]
Closing this in favor of https://github.com/openai/gym/issues/1826
