### ISSUE TITLE
[Question] Is my environment feasible for teaching an agent how to react to opponent moves?

### ISSUE THREAD

**Issue by mikefoufoutos** [hill-a/stable-baselines#713]
In my setup, I want to make an agent find a good policy for buying and selling in the exchange market.

To that end, I made 3 auxillary files. 

One is the spot rates of the given Exchange rate of interest, one is the client actions (Buy, Sell, Do nothing) and the other the amounts the clients used in this setup. 

Every row in the data represents a day. and every column a second in the day.
So the spot rate[i,j] corresponds to the client action and amount of the ith day and jth second.

I want my agent to respond to client actions. 
So if the client performs a buy, it makes sense for my agent to make the same amount as sell in order to reduce his exposure or break the amount in lower chunks over time.

Basically, the clients are disrupting the agent every time.

So I made a function 
```
def _client_action(self):
   spot = spots[i,j]
   amount = amounts[i,j]
   action = actions[i,j]
   
   # Disrupt the agent's variables with this function
   transaction(spot, amount,action)

def _agent_action(self, action):
   spot = spots[i,j]
   transaction(spot, action[0], action[1])

def step(self, action):
   _client_action()
   agent_action()

   reward = ...
   obs = self._next_obs()

   return obs, reward, done, {}
```

Is this environment feasible? 
I started this with the Alpha Go paradigm in mind

I want my system to react when an action is taken against him. 
But all I think it's doing at the time is making random moves. I'm using A2C with MlpPolicy.

Then the testing code below should be adjusted.
I will provide new spot, c_amount, c_action data or feed them one at a time, and the agent should output what to do (Buy X, Sell X, Do nothing).

```
obs = env.reset()
        for i in range(0, len(client_amounts.index)):
            for j in range(0, len(client_amounts.columns)):
                c_amount = client_amounts.iloc[i,j]
                c_action = client_actions.iloc[i,j]

                action, _states = model.predict(obs)
                obs, rewards, dones, info = env.step(action)
                env.render()
```

**Comment by Miffyli** [comment]
Sorry to put this so bluntly, but this is not place for asking generic ML/RL questions. These issues are specifically for issues related to stable-baselines (bugs, enhancements, etc). You should try asking your question on Stackoverflow or [/r/reinforcementlearning](https://www.reddit.com/r/reinforcementlearning/).

But in short: RL agents are bad in "game-theory" setups with other agents trying to out-smart you. Among many others things, the agents are [very easy to fool](https://arxiv.org/abs/1905.10615).

**Comment by araffin** [comment]
Closing this issue for the reasons mentioned by @Miffyli
