### ISSUE TITLE
[Question] newest version of stable baselines with pip

### ISSUE THREAD

**Issue by xTaeko** [hill-a/stable-baselines#715]
Hello,
I use the "make_vec_env" Method to create my own environment as a VecEnv. I noticed that in Monitor.py, which is used there, the Method "close()" is fixed in the git Repo. 
But if i install stable baselines with pip the "close()" method is not working, because of the missing super in 
`

        super(Monitor, self).close()
        if self.file_handler is not None:
            self.file_handler.close()
`

Do I have to install it in a different way or anything to get the fixed version with pip?

**Comment by araffin** [comment]
Hello,
this answer is in the documentation ;)

**Comment by xTaeko** [comment]
Thank you for answering quickly, but I only see that this problem is fixed in Pre-Release. I'm not sure how to get this Pre-Release with pip, or can I just download this repo to get it? 
Sorry, if I just not seeing it in the documentations.

**Comment by Miffyli** [comment]
You can do [this](https://stable-baselines.readthedocs.io/en/master/guide/install.html#bleeding-edge-version), or even `pip install git+https://github.com/hill-a/stable-baselines` might work.

**Comment by xTaeko** [comment]
Thank you very much for this answer :)
