### ISSUE TITLE
Increasing memory usage during training with DQN

### ISSUE THREAD

**Issue by RobSumner** [hill-a/stable-baselines#716]
Describe the bug:
Memory usage increases linearly during training when using DQN. When training with a large number of timesteps this can cause OOM. I originally noticed this when training on a custom env using DQN, but have since replicated using Cartpole environment. 

Code:

```python
import gym
from stable_baselines import DQN
from stable_baselines.deepq.policies import MlpPolicy

env = gym.make('CartPole-v1')
model = DQN(MlpPolicy, env, gamma=0.997, buffer_size=2500, batch_size=256, exploration_fraction=0.12952,
            target_network_update_freq=500, prioritized_replay=False, verbose=0)
model.learn(total_timesteps=7500)
```

Memory use plot (made using mprof run):
![mem_use](https://user-images.githubusercontent.com/30184137/75634065-32314080-5c02-11ea-8e56-994b22aec1a5.png)

I would have expected the plot to plateau once the replay buffer was full (at 2500 steps), but the memory use continues to increase past this point. 

System Info:
Describe the characteristic of your environment:
Linux, Ubuntu 18.04
Stable baselines version 2.9.0 without MPI (installed using conda) .
Python version 3.7.6
Tensorflow version 1.14
numpy version 1.18.1

**Comment by Miffyli** [comment]
Hmm, I have had multi-day DQN runs in the past with no leaking issues like this (and currently running one for a third day). I will try to replicate this once I have a machine available.

**Comment by Miffyli** [comment]
I did not observe the same behavior on my machine with the given code (plots below from mprof). Ubuntu 18.04, Python 3.6.9 (not conda), Tensorflow 1.14.0, Numpy 1.18.1, stable baselines 2.9.0. Smells like the reason is in one of the underlying libraries (or maybe even Python version).

With GPU: 
![image](https://user-images.githubusercontent.com/1633800/75874585-b3632000-5e1a-11ea-8fef-835154d070b9.png)

Without GPU: 
![image](https://user-images.githubusercontent.com/1633800/75874659-e2799180-5e1a-11ea-86ee-f29548405620.png)

**Comment by RobSumner** [comment]
Thanks - I'll experiment with different libraries and try to isolate the problem.

**Comment by RobSumner** [comment]
I have now replicated the non-leaking behaviour (for python 3.6.9 and 3.7.6) by changing the setup process for my virtual environment.

![setup_5](https://user-images.githubusercontent.com/30184137/76080822-ade31280-5f9f-11ea-9344-ba507dede935.png)

I found that installing Tensorflow using Pip rather than Conda will fix the issue, although I haven't been able to find the exact package difference that caused the problem. 

For reference (or anyone else having the same issue) the commands I used was:
```
conda create --name env python=3.7.6
conda activate env
python -m pip install --upgrade pip setuptools wheel
pip install stable-baselines[mpi]
pip install tensorflow==1.14
```

**Comment by araffin** [comment]
Closing this one as it does not seem to be related to stable baselines.

**Comment by danieldugas** [comment]
For the record:

I'm also observing this with the following environment (installed through pip):
Ubuntu 18.04
tensorflow 1.13.2
numpy 1.19.5
stable-baselines 2.10.0

![memleak](https://user-images.githubusercontent.com/1926730/110921982-767c1400-831f-11eb-9a18-2e7fd1d2ec58.png)
