### ISSUE TITLE
pip stable_baselines has no callbacks.py!

### ISSUE THREAD

**Issue by AkhilSinghRana** [hill-a/stable-baselines#719]
[Question]:
Why is there no callbacks.py in the pip version of stable_baselines, Version:2.9.0

The file exists in the github code base though! Do I have to build the package from github source to get callbacks, functionality? Anyone faces the same issue?

**Comment by Miffyli** [comment]
Yes... New callbacks are not included in the current Pypi version (2.9.0), only in the github. You can install github version with simple `pip install git+https://github.com/fact-project/shifthelper`.

**Comment by araffin** [comment]
Would be a duplicate of #715

**Comment by AkhilSinghRana** [comment]
> Yes, new callbacks are not included in the current PyPi version (2.9.0), only in the github. You can install github version with simple `pip install git+https://github.com/fact-project/shifthelper`.

I think the link is not correct though!

**Comment by Miffyli** [comment]
@AkhilSinghRana Wups, my bad ^^. This is what you get for copy/pasting stuff from Stackoverflow.
