### ISSUE TITLE
Can't import callbacks

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#721]
When I try to import the callbacks I get the error `ModuleNotFoundError: No module named 'stable_baselines.common.callbacks'`.

I'm using the most recent release of stable-baselines:

```bash
> pip freeze | grep stable-baselines
stable-baselines==2.9.0
```

**Comment by Miffyli** [comment]
Closing as a duplicate of #719 

tl;dr: Version with callbacks is not on PyPi. Install from github.

**Comment by araffin** [comment]
@Miffyli I think we either need to default the doc on the latest release or write a warning
anyway, I plan to finish #200 this week end so we can do a pip release afterward.
