### ISSUE TITLE
Step is wrong for td3 tensorboard logging

### ISSUE THREAD

**Issue by bycn** [hill-a/stable-baselines#727]
https://github.com/bycn/stable-baselines/commit/ff37ffd5de31eafa9620ba1593fc6753fd36a5ab

**Comment by araffin** [comment]
Hello,
can you please detail a bit more the issue?

**Comment by bycn** [comment]
Sure. The tensorboard is logging summary scalars for every gradient step, but it is passing step instead of step + gradient_step to the train_step function. This results in logging multiple scalars to the main train_step, so the graph will have multiple values / x value

**Comment by araffin** [comment]
well, it seems that `step + grad_step` would be also wrong as for the next step, you can have the same value. The correct fix would be to average the value during one update (i.e. average the values for `grad_steps` gradient steps)

**Comment by araffin** [comment]
Fixed in SB3: https://github.com/DLR-RM/stable-baselines3
