### ISSUE TITLE
Gym dependency should be updated to at least 0.11.+

### ISSUE THREAD

**Issue by AndriiNeverov** [hill-a/stable-baselines#730]
**Describe the bug**

https://github.com/hill-a/stable-baselines/pull/492/files#diff-ae2c195deca83463a62c483e4d45b6f7R160 introduced self.env.action_space.seed(seed), however https://github.com/hill-a/stable-baselines/blob/master/setup.py#L120 still has 'gym[atari,classic_control]>=0.10.9'.

Space#seed doesn't exist in https://github.com/openai/gym/blob/0.10.11/gym/core.py#L195. It was introduced in https://github.com/openai/gym/blob/0.11.0/gym/spaces/space.py#L20.

**Comment by araffin** [comment]
Hello,
nice catch, we would appreciate a PR that solves this issue ;)
