### ISSUE TITLE
[Question] Feature importance to speed up training?

### ISSUE THREAD

**Issue by jarlva** [hill-a/stable-baselines#731]
My observation training dataset has many columns ( > 300). It's reasonable to assume that not all of them are important and some are more important than others. Finding which ones will greatly reduce training and optimization cycles. 
For example: say I train using all columns a simplified problem. Then, analyzing tensorboard and/or saved model data (or another way) to find which columns were actually used most by TF to train and further optimize.

Anyone knows how?

Using TF1.15.

**Comment by araffin** [comment]
Hello,

It seems that the best way would be to train different models with different features (e.g. one with everything, one with only the first 50%, ...) and compare their score.

**Comment by jarlva** [comment]
It could take a long time with over 300 columns. There must be another way.

**Comment by jarlva** [comment]
I found the following PCA article: https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html

**Comment by araffin** [comment]
PCA is a classic technique for [dimension reduction](https://scikit-learn.org/stable/modules/unsupervised_reduction.html) but it has nothing special with RL. You could even pre-train an autoencoder as in [this project](https://towardsdatascience.com/learning-to-drive-smoothly-in-minutes-450a7cdb35f4?gi=ff7d2b3e8bae) to reduce the dimension.
