### ISSUE TITLE
DDPG normalize_observations

### ISSUE THREAD

**Issue by y428lin** [hill-a/stable-baselines#736]
Hi,

I am using Stable Baselines DDPG for my research. I have a question about selecting "normalize_observations". "normalize_observations" performs running average and standard deviation for normalization during training. When we load a saved model for testing, would it load the last normalization statistics (from training)?

Ideally, it would be better if the running average and standard deviation would continue from training to testing, right? Is there a way that we can save the last normalization statistics from training and use it for testing?

I would appreciate your help at your earliest convenience.
Thank you.

**Comment by araffin** [comment]
>When we load a saved model for testing, would it load the last normalization statistics (from training)?

yes, because it is in the tensorflow graph. For other algorithms, you have to use `VecNormalize` and save it separately (cf doc). It is done automatically in the rl zoo.

>would continue from training to testing, right? 

it should be frozen for testing

**Comment by y428lin** [comment]
Thank you for the reminder.
So the last normalization statistics from training is saved and loaded for testing in Stable Baselines DDPG. But you also suggested the last training statistics should be frozen for testing. It seems contradictory?

If it is frozen for testing, how do we pick the initial mean and standard deviation values for initial testing?

**Comment by araffin** [comment]
>But you also suggested the last training statistics should be frozen for testing. It seems contradictory?
>If it is frozen for testing, how do we pick the initial mean and standard deviation values for initial testing?

It is frozen for testing but as in any normalization, you use the statistics from training.
in the case of DDPG, as long as you don't call `.learn()` another time, the stats are frozen (from training). For `VecNormalize`, you should pass `training=False` (cf rl zoo).
