### ISSUE TITLE
Can't load model when using HER + SAC

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#740]
When loading a model using HER + SAC I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model = HER.load('test.zip', env = env)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/her/her.py", line 148, in load
    data, _ = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 652, in _load_from_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/save_util.py", line 120, in json_to_data
    base64.b64decode(serialization.encode())
ModuleNotFoundError: No module named 'numpy.random._pickle'
```

```bash
> pip freeze | grep -E 'numpy|stable'
numpy==1.17.3
stable-baselines==2.10.0a0
```

**Comment by Miffyli** [comment]
Could you provide a minimal code to reproduce this whole setup (i.e. code that creates a model, saves it and then tries to load it)?

**Comment by tirafesi** [comment]
I actually can't, when saving and loading the model on my pc it seems to always work fine.

I'm thinking, when I got this error, the model was saved on a remote computer. I then copied the model to my local computer and when loading it got the error. So maybe it's because of a mismatch between the numpy versions?

```bash
local:~$ pip freeze | grep -E 'numpy|stable'
numpy==1.17.3
stable-baselines==2.10.0a0
```

```bash
remote:~$ pip freeze | grep -E 'numpy|stable'
numpy==1.18.1
stable-baselines==2.10.0a0
```

**Comment by tirafesi** [comment]
Yes, that was definitely it. Updated my local version of numpy to match the one on the remote computer fixed the issue.

**Comment by erwincoumansepic** [comment]
I ran into the same problem.
Is there any way to make this save/load model independent of the numpy version?

**Comment by Miffyli** [comment]
@erwincoumansepic 

If you are not able to load the full model, you can still try `load_parameters` function to load the network weights of that saved model. You need to create model similar to one stored in the model file manually, though.
