### ISSUE TITLE
Multi Discrete for DQN

### ISSUE THREAD

**Issue by H-Park** [hill-a/stable-baselines#742]
Is this feature in the roadmap? Is it wanted? I know DQN is pretty unique in that it doesn't rely on common/policies as it has its own policy class, so implementing such a feature is a little harder without relying on common/distributions.py

**Comment by araffin** [comment]
Hello,

>Is this feature in the roadmap? Is it wanted? 

This feature is not on the roadmap. Btw, as mentioned in #576 and #733 we are now focusing on the V3 so we avoid adding new features to the current v2, it would be mostly bug fixes and usability improvements.
It would be wanted if there was a big demand as for `Dict` spaces (see #133 ) but DQN is also not designed to handle those type of actions, which mean this would make it more complicated if we implement it.
Anyway, you can always convert a `MultiDiscrete` action space to `Discrete` (even though it will increase the action space dimension).
