### ISSUE TITLE
[feature request] Environment Wrappers should take arguments on reset and pass them to the environment

### ISSUE THREAD

**Issue by Solliet** [hill-a/stable-baselines#749]
## Issue
Some environments accept arguments in their reset functions, if we wrap an environment in a `VecEnv`, we don't have direct access to the underlying environment, but we can always call `env_method`. This however, prohibits us from wrapping the custom environment with certain wrappers, e.g. `FrameStack` since it overrides the `reset` method.

Example issue:

```python
env = make_vec_env(
    "CustomEnv-v0", 1, wrapper_class=partial(wrap_deepmind, frame_stack=True))
model = PPO2(CnnLstmPolicy, env, verbose=1, nminibatches=1, n_steps=32).learn(10000)


obs = env.env_method('reset', realtime=True)
# Fails because frame_stack doesn't take in arguments
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
```

## Proposal

Allow variadic and keyword  (or only keyword) arguments in the `reset` method of all non vectorized wrappers. This already exists in certain wrappers like `FireResetEnv`, thus adding it will make everything more consistent. I can implement this right away.

**Comment by araffin** [comment]
Hello,
If you are using `Framestack` then you should use `VecFrameStack` with `VecEnv`.
Also, having keywords in the `reset()` is not in the default gym api, so I would avoid supporting such feature.

This issue was also already discussed in https://github.com/hill-a/stable-baselines/issues/691, where you create a `gym.Wrapper` (different from a `VecEnvWrapper`) that you can change from outside using callback (cf the new callback in the doc, they are much easier to use).
Note that calling `env_method` and `set_attr` should solve most of your issues.

**Comment by Solliet** [comment]
Hello,
Yes it does solve them, however, in many `gym` wrappers `**kwargs` are used.
For example, the method definition of `Wrapper.reset` is:

```python
def reset(self, **kwargs):
    return self.env.reset(**kwargs)
```

**Comment by araffin** [comment]
Fair enough. What do you think about that @Miffyli @AdamGleave ?

**Comment by araffin** [comment]
After thinking more about that issue, I think this is a valid and simple request, please go ahead and do the PR ;)

**Comment by Miffyli** [comment]
I agree this could be an useful feature. Indeed default Gym API does not provide arguments for the `reset`, but there are cases where it would be very useful (e.g. Changing settings of Unity Obstacle Tower between resets).

**Comment by AdamGleave** [comment]
Seems harmless enough. My main concern is possible inconsistencies. If our wrappers pass-through arguments to `reset` but Gym wrappers do not this will be quite confusing to users.

**Comment by araffin** [comment]
>If our wrappers pass-through arguments to reset but Gym wrappers do not this will be quite confusing to users.

as mentioned by @Solliet (and not documented by OpenAI, again...), the base class `gym.Wrapper` passes those arguments. Our `Monitor` wrapper has it and some wrapper for Atari.
However, we should keep the `VecEnvWrapper` as it.

**Comment by AdamGleave** [comment]
> as mentioned by @Solliet (and not documented by OpenAI, again...), the base class `gym.Wrapper` passes those arguments. Our `Monitor` wrapper has it and some wrapper for Atari.

OK, in that case I'm fine making this change.
