### ISSUE TITLE
Atari Performance for PPO2

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#75]
**Describe the bug**
PPO2 have bad performance on Atari games. For example, it does not converge on pong.

**Code example**
Using https://github.com/araffin/rl-baselines-zoo:
```
python train.py --algo ppo2 --env PongNoFrameskip-v4
```

**System Info**
Describe the characteristic of your environment:
 * Stable-Baselines v2.1.2
 * GPU 
 * Python 3.6
 * Tensorflow 1.8

**Comment by araffin** [comment]
The explained variance is never good, it may comes from the value function...

**Comment by SungyunPark** [comment]
I got really bad performance too but you did close your issue by yourself can I ask you the reason?

**Comment by araffin** [comment]
Hello,
can you be more precise? (cf issue template)
the issue was fixed in #76 and the performance was tested with the rl zoo.

**Comment by SungyunPark** [comment]
Okay I think the version I have for PPO2 is more recent one than fixed one. According to file stable_baseline/__init__.py, version is "2.10.0a0". And then I trained ppo2 in Pong environment with 4 environments(num_env=4) but I did not apply VecFrameStack(env, n_stack=4). The total time step I set was 10000000 steps and I posted the picture of tensorboard.
![Screenshot from 2020-01-15 17-30-41](https://user-images.githubusercontent.com/46016058/72418140-9e282880-37bd-11ea-8277-8b492e17feee.png)

**Comment by araffin** [comment]
>but I did not apply VecFrameStack(env, n_stack=4)

Please use the rl zoo and the hyperparameters from the rl zoo, otherwise I cannot warranty the results. And please read the [doc](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html) ;)
