### ISSUE TITLE
[question] Why are observation and achieved_goal the same in bit flipping env?

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#750]
In the observation dictionary returned from the bit flipping env, `observation` and `achieved_goal` are the same:

https://github.com/hill-a/stable-baselines/blob/3069a0e859afd23879def492b8c57896a6c45faa/stable_baselines/common/bit_flipping_env.py#L70-L80

Aren't all of the dictionary elements `{observation, achieved_goal, desired_goal}` fed to the neural network as input? Since `observation` and `achieved_goal` are the same, isn't the neural network being fed the same input twice? Wouldn't it be better for `observation` to be an empty list then?

Or do the neural network inputs consist only of `observation` and `desired_goal`?

**Comment by araffin** [comment]
Hello,

Because it is a `GoalEnv`, we must output those three. The `achieved_goal` can always be deduced from the `observation`. Here, it is a special case where the two are equal, and yes the network is fed twice the same input.

**Comment by tirafesi** [comment]
> The achieved_goal can always be deduced from the observation

do you mean that the `achieved_goal` should always be a part of `observation`?

Say i'm optimizing a robotic arm to move an object. Which of the following would be the correct observation dictionary?

**a)**
```python3
{
    'observation': arm_joints,
    'achieved_goal': object_pos,
    'desired_goal': goal_pos
}
```

**b)**
```python3
{
    'observation': arm_joints + object_pos,
    'achieved_goal': object_pos,
    'desired_goal': goal_pos
}
```

**Comment by araffin** [comment]
>do you mean that the achieved_goal should always be a part of observation?

No always part but that you can at least deduced it from the observation.

a) would be correct if the object is always at the same place
b) would be better in my opinion

Anyway, as mentioned in #745 , the current implementation also gives `achieved_goal` to the agent.

**Comment by tirafesi** [comment]
> Anyway, as mentioned in #745 , the current implementation also gives achieved_goal to the agent.

Exactly, so why is a) only correct when the object is always at the same place? Since `achieved_goal` is fed to the agent, it doesn't matter if the object is always at the same place or not, right?

**Comment by araffin** [comment]
I'm closing this issue as the initial question was answered.

>Exactly, so why is a) only correct when the object is always at the same place?

for the reason I mentioned before. It is more for correctness (e.g. if you use another implementation of HER). In practice, with the current version of SB, it does not matter.
