### ISSUE TITLE
[question] HER and prioritized experience replay

### ISSUE THREAD

**Issue by johannes-dornheim** [hill-a/stable-baselines#751]
Hi

in the stable-baselines implementation, HER does not support prioritized replay buffer.  In the HER Paper they state that: "Prioritized experience replay (....) is orthogonal to our work and both approaches can be easily combined". So my question is: Are there 'deeper reasons' for the lack of support or is it just a currently missing feature?

Best Regards,
Johannes

**Comment by Miffyli** [comment]
I believe there are no bigger reasons to lack of support, other than lack of implementation. It would require coming up with prioritizes for the samples in the buffer, and then updating the `replay_buffer.py` in HER. I am not too familiar with HER to know how easy of a feat this would be. On the first glance it does not sound as straight-forward as with DQNs.

**Comment by RyanRizzo96** [comment]
Actually, PER has been shown not to improve performance over HER. 

Prioritised Sequence Experienec Replay (PSER) outperforms PER but has not been imlpemented with HER.

However, Energy Based Prioritisations (EBP) significantly improves over HER and PER. I have put my name forward to imlpement this in the new PyTorch version.

**Comment by Miffyli** [comment]
Ok, thanks for the info! Indeed any such new features would be things for the PyTorch version :).

**Comment by araffin** [comment]
I added it to possible features for  Stable-Baselines3 1.1+ in https://github.com/DLR-RM/stable-baselines3/issues/1
