### ISSUE TITLE
SubprocVecEnv inside if __name__ == "__main__": does not terminate after execution

### ISSUE THREAD

**Issue by AvisekNaug** [hill-a/stable-baselines#752]
The code snippet is taken from [here](https://github.com/hill-a/stable-baselines/issues/40#issuecomment-426287371) and modified based on documentation for SubprocVecEnv to start inside a `if __name__ ==  "__main__":` as suggested [here](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#subprocvecenv). 

The program works fine with the expected behavior. The SubprocVecEnv closes correctly and the "Done" output is obtained. But doesn't seem to terminate after execution. Currently, Ctrl+C is used to exit the program. 

Any idea why it happens and solution to the problem?
 
System Info

1. Ubuntu 18.04
2. Installed stable-baselines with pip
3. GPU: Single Nvidia RTX 2080 Super
4. Python 3.6.9
5. tensorflow-gpu 1.14.0 (from pip)
6. gym 0.16.0  (from pip)
7. 
8. CUDA Version: 10.0

```python
import os
import math
import sys
from collections import defaultdict

import gym
from gym import error, spaces, utils

from gym.utils import seeding

import numpy as np
from scipy import stats
from sklearn.preprocessing import StandardScaler
    
class BaselEnv(gym.Env):

    def __init__(self):
        super(BaselEnv, self).__init__()
        print("Env initialized")
        # state space
        self.action_space = spaces.Discrete(3000)
        #self.observation_space = spaces.Box(low=np.array([0, 0, 0]), high=np.array([250, 11, 7]), dtype=int)
        self.observation_space = spaces.Box(low=np.array([0, 0]), high=np.array([11, 250]), dtype=np.float32)
        self.viewer = None
        self.steps_beyond_done = None
        self.seed()
        
        self.observation = self.reset()
        
    def step(self, action):
        assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
        reward = 0
        done = False
        return self._get_obs(), reward, done, self._get_obs()
    
    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]
    
    def reset(self):
        return self._get_obs()
    
    def _get_obs(self):
        return np.array([1.0, 2.0])


from stable_baselines.common.vec_env import SubprocVecEnv
from multiprocessing import freeze_support
def make_env(seed):
    def _init():
        env = BaselEnv()
        env.seed(seed)
        return env
    return _init

if __name__ ==  "__main__":
    
    n_envs = 2

    env = SubprocVecEnv([make_env(i) for i in range(n_envs)])
    obs = env.reset()

    for i in range(10):
        print(i)
        action = [env.action_space.sample() for _ in range(n_envs)]
        obs, reward, done, info = env.step(action)

    # Lines added by me
    env.close()
    print("Done!")
```

**Comment by araffin** [comment]
Hello,

I assume you have also MPI installed?
I've got the same issue on my laptop with a similar config. As a workaround, you can use `start_method="fork"` which should work (this is not the default because it causes travis to crash as it is not thread safe).

**Comment by AvisekNaug** [comment]
Well I used this snippet just to reproduce the problem with something simple and self contained. I have been using `PPO2` to do solve for an environment and leveraging `SubprocVecEnv` for that purpose. The lines of interest in my code that you can easily understand is [here](https://github.com/AvisekNaug/CDC2020/blob/master/rl_source/env_test.py#L77) in my research work code.

 
> EDIT: you should use `make_vec_env` which makes things easier and default to `DummyVecEnv` which is usually faster.

I have been using it as you might see in the `env_test.py` file. I have tested the same script with `DumyVecEnv` and did not have this issue.

**Comment by zacharyyamaoka** [comment]
@AvisekNaug Have you found a way to get the environment to to close? I am having a similar issue. Thanks

**Comment by AvisekNaug** [comment]
No, I haven't.

**Comment by araffin** [comment]
Should be fixed in SB3: https://github.com/DLR-RM/stable-baselines3
