### ISSUE TITLE
[question] PPO2 Training & Playback Performance 

### ISSUE THREAD

**Issue by IsidoraR** [hill-a/stable-baselines#765]
For PPO2, if the episode reward and the discounted rewards have both plateaued, can I assume that the policy has converged to the optimal policy? I've run a few training sessions where it seemed like the agent learned a good policy and the rewards had also plateaued, but when I play back the saved models from those training sessions, the agent performs significantly worse..

**Comment by araffin** [comment]
Hello,

Please fill up the issue template completely.
