### ISSUE TITLE
[Question] DQN vs Open AI Baseline's Rainbow agent

### ISSUE THREAD

**Issue by wilkinsmicawber** [hill-a/stable-baselines#77]
The rainbow agent by default experienced the best base result in sonic for the OpenAI team by a large margin, if you exclude the ridiculously resource intensive parallel PPO training:

https://arxiv.org/pdf/1804.03720.pdf

 Is the DQN agent provided by stable-baselines the rainbow model?

**Comment by araffin** [comment]
Hello,

>Is the DQN agent provided by stable-baselines the rainbow model?

The DQN agent is not the rainbow model, however it integrates:
- dueling DQN
- prioritized experience replay
- parameter noise (from OpenAI)

So the following are missing:
- n-step Bellman updates
- distributional RL

If you want an implementation of Rainbow, I recommend you to check Dopamine repo ;)

https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/rainbow_agent.py
