### ISSUE TITLE
[Question] When using MlpLnLstmPolicy, ask about custom action in prediction.

### ISSUE THREAD

**Issue by jongwon-park** [hill-a/stable-baselines#770]
I successfully train the model with MlpLnLstmPolicy. and I also predict using the model.
I want to perform a custum action at a specific step, is this possible in lstm?

**As in the code below**

```python
def predict():
    env = make_vec_env(HarmonyEnv, n_envs=8*4*2)
    model = PPO2.load('best_model.pkl', env=env)
    observation = env.reset()
    done = [False]
    action = None
    reward = None
    info = None

    reasons = []
    state = None
    step = 0
    while not np.all(done):
        if step == 10:
            action = 1
        else :
            action, state = model.predict(observation, state=state)
        observation, r, done, info = env.step(action)
        reasons.append(info)
        reward =+ r

```

**Comment by Miffyli** [comment]
Programming-wise, there is nothing stopping you from executing an action like that. _However_, as you noted, LSTM might not be happy with this as the hidden state does not include the effect of this. _If_ agent was trained with similar setup (10th step is `action=1`), then it could be fine, as agent should have learned this dynamic. If not, then all bets are off. Stable-baselines does not have support for this kind of execution, and I do not know how this could be done. I suggest you ask on other channels, as these issues are for stable-baselines problems (Reddit /r/reinforcementlearning or Stackoverflow).

**Comment by jongwon-park** [comment]
Thanks for your quick answer.
I will try to ask on other channels.
