### ISSUE TITLE
Question about SAC implementation

### ISSUE THREAD

**Issue by surbhi1944** [hill-a/stable-baselines#771]
Respected sir,
I want to know,  qf1_pi and qf2_pi are used to find  min_qf_pi in sac. How the parameters of qf1_pi and qf2_pi models of sac.py are updated?
As I did not find any loss function for these and also not any smoothening for parameter updation.

Thanks

**Comment by araffin** [comment]
Hello,
We are using the second version of SAC, where a value function and two q-value functions are present. The `min_qf_pi` is only used to update the value function  (cf `v_backup`).
`qf1_pi` is used to update the actor parameters, not the q-value in an update similar to [DDPG](https://spinningup.openai.com/en/latest/algorithms/ddpg.html).

> As I did not find any loss function for these and also not any smoothening for parameter updation.

The soft update is only done for the target networks (here the value target).

In the 3rd version of SAC, the value function is replaced by two target q-networks and the update is slightly different (it will be the case in the v3 of stable-baselines).

**Comment by surbhi1944** [comment]
Thankyou sir,

V-function in SAC is used to update the Q-backup and as per the below equation of Soft Actor Critic:
![image](https://user-images.githubusercontent.com/51375621/77751962-ab2e8700-704c-11ea-97fc-0171689b2d83.png)
![image](https://user-images.githubusercontent.com/51375621/77752824-50962a80-704e-11ea-8db3-2f13748a9b0f.png)

The backup of v_function should use the min of qf1 and qf2 for v_function as the parameters of these qf1 (θ1) and qf2 (θ2) are getting updated.
![image](https://user-images.githubusercontent.com/51375621/77744941-70265680-7040-11ea-860c-43916206e8c1.png)

Similarly in Softlearning version of SAC, the Q-backup uses 
![image](https://user-images.githubusercontent.com/51375621/77748079-c944b900-7045-11ea-89b0-776877b5c734.png) that are also getting updated using below second equation

![image](https://user-images.githubusercontent.com/51375621/77748475-715a8200-7046-11ea-8e30-2e92070620ca.png)
![image](https://user-images.githubusercontent.com/51375621/77748815-fe9dd680-7046-11ea-93de-7a69b68ec543.png)

But in the sac.py code v_backup uses min of qf1_pi and qf2_pi whose parameters are not getting updated. Hence it neither uses 
![image](https://user-images.githubusercontent.com/51375621/77749616-538e1c80-7048-11ea-985d-a8cd697a2558.png) nor ![image](https://user-images.githubusercontent.com/51375621/77749538-32c5c700-7048-11ea-8e12-9fc6aadb1427.png)
and uses something  
![image](https://user-images.githubusercontent.com/51375621/77752592-db2a5a00-704d-11ea-9926-a300a97007e3.png) whose parameters ![image](https://user-images.githubusercontent.com/51375621/77752518-b0400600-704d-11ea-8055-eadd907978e3.png) are not getting updated hence will act as some random values of parameters rather than learned parameters. 

Pleases correct me if I am wrong.

Thanks

**Comment by araffin** [comment]
There is an important detail missing in your equation, which is how do you select the actions.
I have to check again, but our implementation follows what is explained in the [spinning up](https://spinningup.openai.com/en/latest/algorithms/sac.html) guide (here the distribution used to sample the action is explicit)

**Comment by araffin** [comment]
To answer you, cost function per cost function.
I'm using the [arxiv paper](https://arxiv.org/abs/1801.01290) v2 as a reference.

The cost function of the value uses actions according to the policy and the update is described here:
https://github.com/hill-a/stable-baselines/blob/950c2a5bf95a9fa908be26fd5db11aa60cfa2b2a/stable_baselines/sac/sac.py#L249-L250

here, only the parameters of the value function are updated (note the `stop_gradient()`, `min_qf_pi` is only there to act as a "target value" (it is a regression), it is the min of the current q-values for the next state, following the current policy.

The cost function for the policy is like for DDPG, but with an entropy term:
https://github.com/hill-a/stable-baselines/blob/950c2a5bf95a9fa908be26fd5db11aa60cfa2b2a/stable_baselines/sac/sac.py#L237

Here, we only update the actor parameters, even though we use the gradient from the q-value following the current policy.

Finally, for the q-values, you use actions from the replay buffer and the value target for the regression:
https://github.com/hill-a/stable-baselines/blob/950c2a5bf95a9fa908be26fd5db11aa60cfa2b2a/stable_baselines/sac/sac.py#L216-L225

The only target network is for the value function and the soft update is defined here:
https://github.com/hill-a/stable-baselines/blob/950c2a5bf95a9fa908be26fd5db11aa60cfa2b2a/stable_baselines/sac/sac.py#L263-L275

**Comment by surbhi1944** [comment]
![image](https://user-images.githubusercontent.com/51375621/77763188-b25f9000-7060-11ea-9727-b483bc90e15b.png)
but sir min_qf_pi is  the min of the current q-values for the current state as per the equation and the code rather than next state as qf_pi are processing current state not the next state.
![image](https://user-images.githubusercontent.com/51375621/77763510-31ed5f00-7061-11ea-8e58-d76d37805015.png).

" the parameters of the q-values (that are used in qf1_pi) are getting updated"
 Lines 224, 225, 250, 252, 259-275 , 280 are updating only qf1, qf2, v-function (vf) , target_v-function,  but not qf2_pi and qf1_pi.
Where qf2_pi and qf1_pi are updated?

Thanks

**Comment by araffin** [comment]
>but sir min_qf_pi is the min of the current q-values for the current state

oups, mistake from my side, they are q-values values for the current state following the current policy

> Where qf2_pi and qf1_pi are updated?

they share the parameters with qf1/qf2 and also depends on the actor, so there are updated when qf1/qf2 are updated (and also when the actor is updated).

**Comment by surbhi1944** [comment]
Thank you....
