### ISSUE TITLE
Could not render SAC pendulum example given in Documentation

### ISSUE THREAD

**Issue by sprakashdash** [hill-a/stable-baselines#772]
I have tried Pendulum-v0 animation to run in different codes but the code of stable_baselines docs of SAC only shows me the first frame of pendulum render screen and does not animate throughout.

Here is the code in which I can see the animation:
```
import gym
env = gym.make('Pendulum-v0')
env.reset()

for i in range(1000):
    env.step(env.action_space.sample())
    env.render()
```

Here is the docs code of SAC I found and the animation freezes:
```
import gym
import numpy as np

from stable_baselines.sac.policies import MlpPolicy
from stable_baselines import SAC

env = gym.make('Pendulum-v0')

model = SAC(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=100000, log_interval=10)
model.save("sac_pendulum")

model = SAC.load("sac_pendulum")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```
This code runs but the render screen freezes in the first frame:
![image](https://user-images.githubusercontent.com/39633034/77840227-a11e9c80-71a2-11ea-8af7-dc6cec8caaba.png)

**System Info**
 Stable Baselines[mpi] Installed from pip
Ubuntu 16.04
 Nvidia  GeForce 940m
 Python version - 3.7.6
 Tensorflow version - 1.15.0 (GPU version)
 Using IPython in terminal

**Comment by sprakashdash** [comment]
Well, I found a workaround:
I think using Vectorized Environment by Stable Baselines resolves the issue.
So to edit the above code:
```
import gym
from stable_baselines.sac.policies import MlpPolicy
from stable_baselines import SAC
from stable_baselines.common import make_vec_env

env = make_vec_env('Pendulum-v0')

model = SAC(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=100000, log_interval=10)
model.save("sac_pendulum")

model = SAC.load("sac_pendulum")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

**Comment by araffin** [comment]
Hello,
did you try rendering before training?
what you may interpret as freezing would be the result of training (keeping the pendulum up).

For the first code, you also forgot to reset the env after each episode. Vecenvs does it automatically.

**Comment by sprakashdash** [comment]
> I have tried Pendulum-v0 animation to run in different codes but the code of stable_baselines docs of SAC only shows me the first frame of pendulum render screen and does not animate throughout.
> 
> Here is the code in which I can see the animation:
> 
> ```
> import gym
> env = gym.make('Pendulum-v0')
> env.reset()
> 
> for i in range(1000):
>     env.step(env.action_space.sample())
>     env.render()
> ```
> 
> Here is the docs code of SAC I found and the animation freezes:
> 
> ```
> import gym
> import numpy as np
> 
> from stable_baselines.sac.policies import MlpPolicy
> from stable_baselines import SAC
> 
> env = gym.make('Pendulum-v0')
> 
> model = SAC(MlpPolicy, env, verbose=1)
> model.learn(total_timesteps=100000, log_interval=10)
> model.save("sac_pendulum")
> 
> model = SAC.load("sac_pendulum")
> 
> obs = env.reset()
> while True:
>     action, _states = model.predict(obs)
>     obs, rewards, dones, info = env.step(action)
>     env.render()
> ```
> 
> This code runs but the render screen freezes in the first frame:
> ![image](https://user-images.githubusercontent.com/39633034/77840227-a11e9c80-71a2-11ea-8af7-dc6cec8caaba.png)
> 
> **System Info**
> Stable Baselines[mpi] Installed from pip
> Ubuntu 16.04
> Nvidia GeForce 940m
> Python version - 3.7.6
> Tensorflow version - 1.15.0 (GPU version)
> Using IPython in terminal

I this code I believe `env.render()` is called inside the loop. And first I trained the model and then I executed that loop.

**Comment by sprakashdash** [comment]
> Hello,
> did you try rendering before training?
> what you may interpret as freezing would be the result of training (keeping the pendulum up).
> 
> For the first code, you also forgot to reset the env after each episode. Vecenvs does it automatically.

In this code, I believe `env.render()` is called inside the loop. And first I trained the model and then I executed that loop.

**Comment by araffin** [comment]
What I meant, this should work:

```python

import gym
import numpy as np

from stable_baselines import SAC

env = gym.make('Pendulum-v0')

model = SAC('MlpPolicy', env, verbose=1)

# Render before training for 500 steps
obs = env.reset()
for _ in range(500):
    action, _states = model.predict(obs)
    obs, reward, done, info = env.step(action)
    env.render()
    # reset the env at the end of an episode
    if done:
        obs = env.reset()

# Train
model.learn(total_timesteps=20000, log_interval=10)
model.save("sac_pendulum")

model = SAC.load("sac_pendulum")

# Render after training
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, reward, done, info = env.step(action)
    env.render()
    # reset the env at the end of an episode
    if done:
        obs = env.reset()

**Comment by sprakashdash** [comment]
Thanks a lot, it worked!
