### ISSUE TITLE
Broken pipe with ppo2 multiprocessing and custom environment 

### ISSUE THREAD

**Issue by drose188** [hill-a/stable-baselines#774]
When trying vectorized custom environment it works with ppo1, ppo2 and sac with one env:

 self.norm_obs = True, 
 self.norm_reward = True 
 self.clip_obs = 10.
 self.clip_reward = 10.

self.env = DummyVecEnv([lambda: self.env])
self.env = VecNormalize(self.env, self.norm_obs, self.norm_reward, self.clip_obs, self.clip_reward)

When trying to add to the above multiprocessing with ppo2:

def _make_env(self, seed, p_env):
        def _init():
            env = p_env
            env.seed(seed)
            return env
        return _init

v_env = SubprocVecEnv([self._make_env(self.env, i) for i in range(2)])

It fails with error message: 

anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

**Comment by Miffyli** [comment]
Can you provide the full code you used, as well as the library versions and OS you used?

You might also want to take look at the tips here: https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html
