### ISSUE TITLE
[Question] What is the meaning of LSTM number of cells in custom policy network 

### ISSUE THREAD

**Issue by AlessandroZavoli** [hill-a/stable-baselines#775]
Dear all,

I'm trying to use an Lstm custom policy, according to the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html). With respect to this example code, 

```
class CustomLSTMPolicy(LstmPolicy):
    def __init__(self, sess, ob_space, ac_space, n_env, n_steps, n_batch, n_lstm=64, reuse=False, **_kwargs):
        super().__init__(sess, ob_space, ac_space, n_env, n_steps, n_batch, n_lstm, reuse,
                         net_arch=[8, 'lstm', dict(vf=[5], pi=[10])],
                         layer_norm=True, feature_extraction="mlp", **_kwargs)
```
i do not understand what the number of cells "n_lstm=64" means. 
Does it refer to 

1. the number of time-steps the net is unrolled?
2. the size of the hidden state?
3. something else? 

In the above example, what is the number of weight parameters for the LSTM and how do you calculate it?

Best regards
Alessandro Zavoli

**Comment by Miffyli** [comment]
Answer is [here](https://stable-baselines.readthedocs.io/en/master/modules/policies.html#stable_baselines.common.policies.LstmPolicy): It refers to the size of the hidden state.

**Comment by AlessandroZavoli** [comment]
Thanks.
Should I expect that increasing `n_lstm` gives me a better ability to correlate observations over time? Or  will it only "improve" the representation of the supposed hidden Markov Decision Process?
Sorry if the question is dumb

**Comment by Miffyli** [comment]
It is a fair question, albeit offtopic from stable-baselines issues. You have better chance of getting help on e.g. StackOverflow or reddit /r/reinforcementlearning.

But to quickly answer your question: You probably will not see a huge difference by increasing that size. I would keep it in 64-256 range. Even [state-of-the-art results](https://arxiv.org/abs/1802.01561) only use 256.
