### ISSUE TITLE
Question on VecNormalize

### ISSUE THREAD

**Issue by y428lin** [hill-a/stable-baselines#779]
Hi,
I trained with TD3 using VecNormalize:

env0 = DummyVecEnv([lambda: gym.make("merging-v0")])
env = VecNormalize(env0, norm_obs=True, norm_reward=False)
model = TD3(MlpPolicy, env,......)
model.learn(total_timesteps=int(1e6)) 
model.save("saved_model")
env.save('saved_env.pkl')

Now I would like to do testing:

env0 = DummyVecEnv([lambda: gym.make("merging-v0")])
env = VecNormalize.load('saved_env.pkl',env0)

model = TD3.load("saved_model")
model.set_env(env)

Is the testing code right? I saw other people who did not use the saved_env.pkl in the testing code. Instead, they simply created the env as: env = VecNormalize(env0, norm_obs=True, norm_reward=False).

My understanding is that the saved_env.pkl has the normalization statistics from training. Thus, we need to use the saved_env.pkl, right? But how do we pass "training=False" when using saved_env.pkl to freeze the running normalization during testing?

**Comment by Miffyli** [comment]
This version here is correct. As for passing the training: You can manually simply set `env.training = False` after loading, and it will disable updating the stats.

Documentation could include an example of loading the vecnormalize as well, along with its example of [saving them](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#mujoco-normalizing-input-features).

**Comment by araffin** [comment]
>My understanding is that the saved_env.pkl has the normalization statistics from training. Thus, we need to use the saved_env.pkl, right? But how do we pass "training=False" when using saved_env.pkl to freeze the running normalization during testing?

yes, you should do `training=False` when loading and we pass `norm_reward=False` because you don't need to normalize reward for testing and you want to have the original reward magnitude for evaluating your agent.

Anyway, best is always to take a look at the rl zoo, where you have the best practices for using stable-baselines.

I also agree with @Miffyli , we should update the doc to include an example.

PS: please use code formatting (cf issue template) next time

**Comment by y428lin** [comment]
Thank you. I have a follow-up question during testing. I loaded the environment as
env = VecNormalize.load('saved_env.pkl',env0)

For testing, I used
obs, rewards, done, info = env.step(action)

When an episode finished with done=True, the environment reset automatically initiated without me adding the code env.reset(). Is there a way to stop the automatic environment reset?

**Comment by Miffyli** [comment]
That is a feature of vectorized environments, where environments are reset immediately after terminal state,  so you can keep calling `step`. There is no immediate work-around for this. One thing you could do is to use the [observation/reward](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/vec_normalize.py#L31) statistics from `VecNormalize` along with vector-less environment manually.

**Comment by y428lin** [comment]
I would like to obtain the environment state when the episode terminates. It seems that, in vectorized environments, the state at termination is overridden by the initial reset state of a new episode since environments are reset immediately?

**Comment by araffin** [comment]
Please read the documentation about VecEnv carefully, you will find your answer ;)
