### ISSUE TITLE
[question] Custom workflow for stepping the environment

### ISSUE THREAD

**Issue by Achin17** [hill-a/stable-baselines#785]
I want to use the action computed by the SAC policy to use in an optimization process which would then be used to step the environment. I am planning to use ROS services to get this done as my optimization routine is in C++. I went through the documentation to see how this can be achieved using stable baselines but couldn't find anything relevant.
Is there any example you can refer me to? Or just pin point me to main files or the methods I would have to change to get this accomplished. Any help would be greatly appreciated.

**Comment by araffin** [comment]
Hello,
Is [that](https://github.com/araffin/robotics-rl-srl/tree/master/real_robots) what you are looking for?

In short: everything happens in the environment, and there is a ros bridge because we are using python 2 and 3.

**Comment by Achin17** [comment]
That certainly helps.Thanks!
