### ISSUE TITLE
[Question]Time-varying exploration rate.

### ISSUE THREAD

**Issue by WeiJieQiang** [hill-a/stable-baselines#788]
How to add time-varying exploration rate, say linearly decaying from exploration_max to exploration_min, in stable-baselines?

**Comment by Miffyli** [comment]
The answers are in [docs](https://stable-baselines.readthedocs.io/en/master/). This varies algorithm to algorithm. DQN has linearly decaying exploration by default, for example.

**Comment by WeiJieQiang** [comment]
Can we do this with DDPG or TD3?

**Comment by Miffyli** [comment]
As per documentation, this is not supported with those algorithms.

This would be a good enhancement for future versions (v3), where all parameters like this would go through the "constant or schedule" treatment, being a function of fraction-of-training-done.

**Comment by araffin** [comment]
>Can we do this with DDPG or TD3?

You can create a noise object that derives from the base ActionNoise class and implements that (there is an example in the zoo).

**Comment by WeiJieQiang** [comment]
Alright, thanks @Miffyli @araffin ! 

One question about customising policy network. Can the policy network in DDPG or TD3 be customised differently, for example actor network uses 1d cnn, and critic network uses mlp. I saw one example about [1d cnn](https://github.com/RGring/drl_local_planner_ros_stable_baselines/blob/master/rl_agent/src/rl_agent/common_custom_policies.py), but I guess the use of `cnn_extractor=` sets the cnn network to be the same for both actor and critic. Is there an example to setup different networks?

**Comment by Miffyli** [comment]
If you use `cnn_extractor`, then yes, it will use same extractor for both heads.

To have two completely different networks, you need to make a [custom policy](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html).

**Comment by araffin** [comment]
As the original question was answered, I will close this issue.
