### ISSUE TITLE
[Question] Adam updates diverges for DDPG

### ISSUE THREAD

**Issue by Adnanemiri** [hill-a/stable-baselines#789]
After few iterations I get the following error:

![issue](https://user-images.githubusercontent.com/19372190/78784757-d2b31700-799d-11ea-9ec6-3bba33774403.PNG)

Any suggestions why the exponential moving average of some squared gradients are 0 ?

**Comment by bl4ckrid3r** [comment]
I am encountring the same issue, even with altering epsilon from `mpi_adam.py` I still get the same issue.

**Comment by araffin** [comment]
Hello,
Please fill in the issue template completely.

**Comment by Adnanemiri** [comment]
After using VecCheckNan, it appears that my custom env returns NaN values for some actions, hence the error.

![image](https://user-images.githubusercontent.com/19372190/78889356-6dbdf680-7a5b-11ea-837f-1a5457ab1620.png)


Thanks.

**Comment by bl4ckrid3r** [comment]
That was my same issue too .

**Comment by araffin** [comment]
@Adnanemiri @bl4ckrid3r good to hear, as you are apparently from the same company, you don't need to double every message ;) (and the issue is also here for a good reason)
