### ISSUE TITLE
observations are identical in SubprocVecEnv after .reset()

### ISSUE THREAD

**Issue by mattroos** [hill-a/stable-baselines#79]
Thanks for this great RL tool!

I've created a custom environment and vectorized it with SubprocVecEnv.  When I call env.reset(), all observations in the vector of returned observations are identical, which I did not expect.  Yet, when I do the same thing with one of the atari environments, this is not the case--i.e., it has different video frames from breakout.  Should I be able to have unique environment states/observations upon calling reset()?  How can this be implemented?

**Comment by araffin** [comment]
Hello,

I recommend you checking the example in the documentation: https://stable-baselines.readthedocs.io/en/master/guide/examples.html#multiprocessing-unleashing-the-power-of-vectorized-environments
The environments need to be seeded with a different random seed for each process, otherwise, you will get the same observation for all processes.

You don't have that problem with atari, because `make_atari_env` does that for you, see  https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/cmd_util.py#L18

```python
def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_global_seeds(seed)
    return _init

env_id = "CartPole-v1"
num_cpu = 4  # Number of processes to use
# Create the vectorized environment
env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])

```

**Comment by mattroos** [comment]
Thanks, @araffin!  Is it necessary to register a custom environment with gym in order to achieve this?  I've been working from this example [https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html). I thought I could just add a seed argument like this
```
env = DummyVecEnv([lambda: CustomEnv(arg1, ..., seed) for seed in range(num_cpu)])
```
and set the seed in ```MyEnv.__init__()```, via ```numpy.random.seed(seed)```
but that not result in unique observations.

**Comment by araffin** [comment]
Well, with a custom env, if you don't want to register it, the only line that you have to replace is the `env = gym.make(env_id)`.
Your solution works but is not really following the gym interface.

**Comment by mattroos** [comment]
Thanks!
