### ISSUE TITLE
HER problem with replay_buffer when using SAC, TD3 or DDPG as model classes

### ISSUE THREAD

**Issue by edwinlima** [hill-a/stable-baselines#790]
Hi guys,

I'm trying to use HER with TD3, DDPG and SAC but I'm getting into an infinite loop apparently. When I use HER with DQN it works fine, the resampling from the replay_buffer works, but with those other guys it doesn't. I just create a  model as follows:

```Python
model_class=TD3
goal_selection_strategy = 'final'
model = HER('MlpPolicy', train_env, model_class, n_sampled_goal=4, goal_selection_strategy=goal_selection_strategy,
                verbose=1)
# 
model.learn(total_timesteps=episode_sz)

```
The training starts and at the end of every episode the method replay_buffer.add from the class  HindsightExperienceReplayWrapper is called as follows:
```python
        self.episode_transitions.append((obs_t, action, reward, obs_tp1, done))
        if done:
            # Add transitions (and imagined ones) to buffer only when an episode is over
            self._store_episode()
            # Reset episode buffer
            self.episode_transitions = []

```

Inside the _store_episode method a call to self.replay_buffer.add is made but, instead of calling the ReplayBuffer.add method, it calls again self.replay_buffer.add from the same class. In td3.py the replay_buffer is instantiated under setup_model method as follows:
```python
self.replay_buffer = ReplayBuffer(self.buffer_size)
```
And under the learn method (file td3.py) it is wrapped with a the replay_wrapper from HER as follows:
```python
        if replay_wrapper is not None:
            self.replay_buffer = replay_wrapper(self.replay_buffer)

```
As you could see on the sequence of errors below it jumps into an infinite loop because it calls the replay_buffer.add method recursively over and over again. I think this is a bug, it should call the replay_buffer.add method from the ReplayBuffer class as it does when i use DQN as model class and the one from the HindsightExperienceReplayWrapper class, which is why it goes into a loop. 

My environment:
 * GPU models and configuration: nvidia 1080 ti 11gb
 * Python version: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
 * Tensorflow version: 1.13.1
 * Stable baselines: latest version, just pulled from github.

I hope now it's more clear. 

Thanks.

``` Bash  
File "G:/GitHub/criptocurrencies/DDPG/main.py", line 113, in <module>
    model.learn(total_timesteps=episode_sz)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\her.py", line 113, in learn
    replay_wrapper=self.replay_wrapper)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\td3\td3.py", line 351, in learn
    self.replay_buffer.add(obs_, action, reward_, new_obs_, float(done))

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 78, in add
    self._store_episode()

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 154, in _store_episode
    self.replay_buffer.add(obs_t, action, reward, obs_tp1, done)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 78, in add
    self._store_episode()

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 154, in _store_episode
    self.replay_buffer.add(obs_t, action, reward, obs_tp1, done)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 78, in add
    self._store_episode()

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 154, in _store_episode
    self.replay_buffer.add(obs_t, action, reward, obs_tp1, done)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 78, in add
    self._store_episode()

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 154, in _store_episode
    self.replay_buffer.add(obs_t, action, reward, obs_tp1, done)

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 78, in add
    self._store_episode()

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\replay_buffer.py", line 182, in _store_episode
    obs, next_obs = map(self.env.convert_dict_to_obs, (obs_dict, next_obs_dict))

  File "c:\users\eigenaar\documents\github\stable-baselines\stable_baselines\her\utils.py", line 74, in convert_dict_to_obs
    return np.concatenate([obs_dict[key] for key in KEY_ORDER])
```

**Comment by araffin** [comment]
Hello,
please use code blocks as showed on the issue template.
I assume you have discrete actions? (because you use dqn) in that case, using ddpg/td3/sac does not make sense (cf doc).

**Comment by edwinlima** [comment]
I have used discrete actions with HER-DQN but I need to move to continuous actions, which actually works but not in combination with HER due to the problem explained above.

**Comment by edwinlima** [comment]
By now what I've done is this: I've modified the file replay_buffer.py which implements the HER wrapper HindsightExperienceReplayWrapper  by adding those two lines:

```python
        self.buffer_size = 50000
        self.replay_buffer = ReplayBuffer(self.buffer_size)#replay_buffer
```
That prevents that when the replay_buffer.add method within the class HindsightExperienceReplayWrapper  is called the ReplayBuffer add method is called, not the HindsightExperienceReplayWrapper.add one, which is what is causing the problem. Perhaps that gives less flexibility, not sure about the consequences but at least now it's training.

Best

**Comment by araffin** [comment]
Please fill the issue template completely, a lot of information are missing... not sure to understand you issue.

**Comment by edwinlima** [comment]
I've just updated the original post, let me know if that is enough, thanks.

**Comment by araffin** [comment]
It's better but please the give the complete traceback (it is truncated).
An the environment is missing so I cannot the error...

>Inside the _store_episode method a call to self.replay_buffer.add is made but, instead of calling the ReplayBuffer.add method,

Where exactly? (what you are describing seems normal to me)
Did you try with an environment that were not your own? Did you use the `env_checker()` (cf issue template)?

We have [unit tests](https://github.com/hill-a/stable-baselines/blob/master/tests/test_her.py) for HER, so if there was an infinite loop, I would have expected the tests to fail...
and SAC + HER was successfully trained in the rl zoo on FetchPush env...
