### ISSUE TITLE
[Question] VecEnv implementation reasoning

### ISSUE THREAD

**Issue by bycn** [hill-a/stable-baselines#793]
Hi,
It seems that for vectorized environments, the design for this library (and others) is to sample as following: if n = # environments, one sample is stored as a (n x obs_size) tuple into the replay buffer, and the model consumes the n-tuple. Why is it done this way, as opposed to storing the n-tuple as n separate tuples, and having the model consume one obs at a time? Thanks!

Bryan

**Comment by araffin** [comment]
Hello,

>Why is it done this way, as opposed to storing the n-tuple as n separate tuples, and having the model consume one obs at a time?

Why would you do it the other way?

(btw, it also support dicts but at the end, the behavior is the same)

**Comment by bycn** [comment]
The other way would allow you to test your model on 1 observation

**Comment by araffin** [comment]
>The other way would allow you to test your model on 1 observation easily.

You have the `predict()` method for that (cf doc).
The `VecEnv` is useful for making the training faster.
