### ISSUE TITLE
[HER] replay buffer should store info dictionary

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#794]
From GoalEnv 's `compute_reward` [documentation](https://github.com/openai/gym/blob/master/gym/core.py#L175):

> Compute the step reward. This externalizes the reward function and makes
        it dependent on an a desired goal and the one that was achieved. **If you wish to include
        additional rewards that are independent of the goal, you can include the necessary values
        to derive it in info and compute it accordingly**

However, the replay buffer does not store info and always calls `compute_reward` with `None` in its place:

https://github.com/hill-a/stable-baselines/blob/815628e8d4ce2b17b6c3fbeb184ea198326a1331/stable_baselines/her/replay_buffer.py#L176

This makes it impossible to compute rewards that depend on extra information.

**Comment by araffin** [comment]
Hello,

>This makes it impossible to compute rewards that depend on extra information.

Do you have a concrete example of such environment?

**Comment by tirafesi** [comment]
For example, if using `VecNormalize` (with a wrapper built around it, to make it compatible with `GoalEnv`).

Say `achieved_goal` is the current position of an object, and `desired_goal` is the desired position of the object. If both of these observations are normalized, then it's difficult to compute the reward since you don't know their original values. In such a case, it would make sense to pass the non-normalized observations in `info` and compute the reward from those instead.

**Comment by araffin** [comment]
>If both of these observations are normalized, then it's difficult to compute the reward since you don't know their original values. 

In that example, the trick (and that what is done since v2.10) is to store unnormalized observations/goals and normalize them only when sampling the buffer.
Note that `VecNormalize` + HER is currently not supported for legacy reasons (DQN/DDPG use a normal env, no `VecEnv`), in v3, it will work (`VecEnv` will be used by all algorithms, no need for additional transforms using `_UnVecWrapper()`)

**Comment by tirafesi** [comment]
> and normalize them only when sampling the buffer.

Even if that's the case, when calling `compute_reward(achieved_goal, desired_goal, info)` then the observations are already normalized, correct? Which means you'd still need a way to let the function know the non-normalized values to correctly compute the reward - thus my suggestion of passing them on `info`.

**Comment by araffin** [comment]
> then the observations are already normalized, correct?

they are not, `compute_reward()` is used before storing samples in the buffer (when creating imagined transitions).

**Comment by tirafesi** [comment]
I don't think I'm making my point clear. Currently, VecNormalize is not supported for HER. This means that if I want to use it, I need to build a wrapper around it. So, the `step` function of my environment will look something like:

```python3
def step(self, action):
	obss, rewards, dones, infos = self._normalized_env.step(action)
	
	# only 1 env
	raw_obs = obss[0]
	reward = rewards[0]
	done = dones[0]
	info = infos[0]

	# lets say the last 4 values of raw_obs correspond to achieved_goal and desired_goal
	obs = {
		"observation": raw_obs[: -4],
		"achieved_goal": raw_obs[-4: -2],
		"desired_goal": raw_obs[-2:]
	}

	# get unnormalized goals in order to properly compute the reward
	unnormalized_obs = self._normalized_env.get_original_obs()[0]
	info = {
		"unnormalized_achieved_goal": unnormalized_obs[-4:-2],
		"unnormalized_desired_goal": unnormalized_obs[-2:]
	}
	
	reward = self.compute_reward(obs["achieved_goal"], obs["desired_goal"], info)

	return obs, reward, done, info
```

This works fine for the current step. The problem is that since the `info` dictionary is not saved in the replay buffer, when `compute_reward` is called later on, the reward will not be able to be computed, since `info` is always `None`.

**Comment by araffin** [comment]
>I don't think I'm making my point clear. Currently, VecNormalize is not supported for HER. This means that if I want to use it, I need to build a wrapper around 

Actually, I would prefer to fix the internals properly (makes `VecEnv` the default for DQN/DDPG/SAC and TD3) rather than patching HER. However, I have no time for that (focusing on v3 right now, the open source process has started, it should be out in the next two months hopefully). 

Anyway, in that case, I would be ok with a PR that fixes this issue (I asked a concrete example because I wanted to be sure it was something that people may actually use).
If I understand well, only the replay wrapper need to be modified to store the infos of one episode, no?

**Comment by tirafesi** [comment]
> If I understand well, only the replay wrapper need to be modified to store the infos of one episode, no?

The replay buffer would have to receive the info and store it alongside the episode transitions:

https://github.com/hill-a/stable-baselines/blob/815628e8d4ce2b17b6c3fbeb184ea198326a1331/stable_baselines/her/replay_buffer.py#L63

But then every algorithm that can be used with HER would also have to be changed to provide the replay buffer with the info dictionary. For example, in SAC, you'd have to pass the info here:

https://github.com/hill-a/stable-baselines/blob/815628e8d4ce2b17b6c3fbeb184ea198326a1331/stable_baselines/sac/sac.py#L430

Which is probably gonna break the code when using the other replay buffers that don't expect to receive an extra argument.

**Comment by araffin** [comment]
```python
if isinstance(self.replay_buffer, HindsightExperienceReplayWrapper):
    self.replay_buffer.add_info(info)
```
should do the trick, no ?

**Comment by tirafesi** [comment]
hm yes, I think so. I'll see about making a PR at the start of next week then.

**Comment by tirafesi** [comment]
Could you please take a look at my [fork](https://github.com/tirafesi/stable-baselines)?

I added the `info` argument to the `HindsightExperienceReplayWrapper.add` function and updated the rest of HER and SAC accordingly. However, I keep getting this error:

 ```
File "/home/tirafesi/Documents/stable-baselines/stable_baselines/her/her.py", line 113, in learn
    replay_wrapper=self.replay_wrapper)
  File "/home/tirafesi/Documents/stable-baselines/stable_baselines/sac/sac.py", line 432, in learn
    self.replay_buffer.add(obs_, action, reward_, new_obs_, float(done), info)
  File "/home/tirafesi/Documents/stable-baselines/stable_baselines/her/replay_buffer.py", line 79, in add
    self._store_episode()
  File "/home/tirafesi/Documents/stable-baselines/stable_baselines/her/replay_buffer.py", line 154, in _store_episode
    self.replay_buffer.add(obs_t, action, reward, obs_tp1, done, info)
TypeError: add() takes 6 positional arguments but 7 were given
```

It looks as if the program isn't calling the `add` function I changed, but I can't seem to figure out why.

**Comment by araffin** [comment]
>function and updated the rest of HER and SAC accordingly. However, I keep getting this error:

Why didn't you do as mentioned? so keeping the api the same and adding a method `add_info()`?

**Comment by tirafesi** [comment]
Since `HindsightExperienceReplayWrapper` isn't a subclass of anything, changing it's behavior shouldn't affect other parts of the code. And between adding a new method or adding an argument to an existing one, I figured the latter would be cleaner - especially since both alternatives would change the algorithms in the same way: by checking `isinstance(self.replay_buffer, HindsightExperienceReplayWrapper)`.

What I don't understand is why SAC isn't calling the `add` method I changed.

**Comment by araffin** [comment]
>What I don't understand is why SAC isn't calling the add method I changed.

You should not change line 154, neither 184

**Comment by tirafesi** [comment]
> You should not change line 154, neither line 184

Ah, of course!

> you can even do cleaner by passing **kwargs

Not sure what you mean by that, but I think the current implementation should be good enough? [Here](https://github.com/hill-a/stable-baselines/pull/802) is the PR.
