### ISSUE TITLE
Custom policy for Graph Convolutional network [feature request] 

### ISSUE THREAD

**Issue by Ujwal2910** [hill-a/stable-baselines#797]
[feature request]. 
Is there any support for adding Graph based networks or Attention based networks in the Custom policy section?
I have been trying to add a Graph based policy for a multi agent scenario. Help would be appreciated.

**Comment by araffin** [comment]
Hello,
As you mention in your request, this is a custom policy, so unless it is widely used, we won't implement it in the basecode.
You can take a look at [this repo](https://github.com/dniku/rl-attention) for a starting point.

**Comment by Ujwal2910** [comment]
This seems good and implementable. I will try defining the Attention network as a custom policy is stable baseline framework and will update it learning works well. 
I am working on a multi agent framework where I want to use Graph Cnn network to project the multiple state space definition of multiple agents as a graph. Then use an Attention mechanism to lay specific emphasis on certain parts of the simulation.
My area of motivation have been these two papers :
1) https://arxiv.org/abs/1910.08809
2) https://z0ngqing.github.io/paper/preprint-jiechuan18.pdf

If you could suggest some places where i could look for integrating similar network in the stable baseline agent it would be really helpful.

**Comment by Miffyli** [comment]
As @araffin mentioned, this would be a [custom policy](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html). The "multi-agent" part might not be do-able (not supported to any extent in stable-baselines), but attention/graph-network could be done via custom policies. See the examples and info in docs.

**Comment by Ujwal2910** [comment]
Which example in the docs are you referring to?

**Comment by Miffyli** [comment]
@Ujwal2910 

The custom policy ones. These allow modifying the network structure as you please.

Anywho, the original issue has been handled (feature request), and these issues are not for technical support per say. If you have no more issues to raise, you may close this issue.
