### ISSUE TITLE
TD3 Not working since 2.10.0  [BUG]

### ISSUE THREAD

**Issue by Mindgames** [hill-a/stable-baselines#799]
**Describe the bug**
TD3 not seem to be working since 2.10.0 
_(since 2.8.0 it have been producing strange results)_

```python
# Stable baselines
from stable_baselines import TD3
from stable_baselines.td3.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.ddpg.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise
from stable_baselines.common.vec_env import VecVideoRecorder, SubprocVecEnv, DummyVecEnv
from stable_baselines.common.evaluation import evaluate_policy

```

```bash
<ipython-input-14-53f8169fc3e2> in <module>()
     14 
     15 # Stable baselines
---> 16 from stable_baselines import TD3
     17 from stable_baselines.td3.policies import MlpPolicy
     18 from stable_baselines.common.vec_env import DummyVecEnv

ImportError: cannot import name 'TD3'

```

**Additional context**
Available here: https://colab.research.google.com/drive/1Zyn9Q_Gf3KnVIhdl9t2ond5IjJNaTriL#scrollTo=2pToLfvOzCKQ

**Comment by araffin** [comment]
Hello,
The issue comes from colab... you need to do the pip install after the tensorflow 1 magic. I don't know why, but the behavior changed.

Currently, if you print stable-baselines version, it will be 2.2.1 (which is installed by default in colab).

**Comment by Mindgames** [comment]
@araffin Yes that solved it. Thanks!
