### ISSUE TITLE
Stacking ACER

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#8]
We should either make n_stack=1 the default or warn the users about frame stacking for ACER. (also in the predict method)

Also, in the predict function, stacking is not done properly (it is a valid input but there is zeros instead of correct frame stacking).

acer_simple, line 477:
```python
stacked_obs = np.array(observation).reshape((-1,) + (obs_shape[-1] * self.n_stack,))
```
why ? if stacking is not needed, you should not tweak observation, no ? Or is this only valid for MlpPolicies ? (it breaks things with images)

**Comment by hill-a** [comment]
Good point, I had not realised that ACER did not necessarily require a frame stacking in the original article. 

The stacking should probably be removed from ACER, and simply let the ```stable_baselines.common.vec_env.VecFramestack``` wrapper do its job.

As a side note: yes, I got the reshaping wrong, it should be 
```python
stacked_obs = np.array(observation).reshape((-1,) + obs_shape[1:-1] + (obs_shape[-1] * self.n_stack,))
```

**Comment by hill-a** [comment]
stacking removed from ACER 5b4e33e. 

Now the new notation:
```python
env = VecFramestack(env, n_stack=4)
model = ACER(MlpPolicy, env)
```
should have the same effect as the old notation:
```python
model = ACER(MlpPolicy, env,  n_stack=4)
```
