### ISSUE TITLE
Which Wrapper to use for SAC+HER? 

### ISSUE THREAD

**Issue by PeiSeng** [hill-a/stable-baselines#800]
Hi, I would like to ask a question. 

In rl-baselines-zoo config file, it is mentioned that I should use utils.wrappers.DoneOnSuccessWrapper. However, the default wrapper for HER will be using HERGoalEnvWrapper. How do I change it. Will it influence? 

Thanks.

**Comment by araffin** [comment]
Hello,
this is an issue for the zoo.
you can use multiple wrappers (that's what is done).

**Comment by PeiSeng** [comment]
May I know how to use multiple wrappers? Sorry I cant find any guideline on that.

**Comment by Miffyli** [comment]
You keep wrapping the wrapped environment, [like done in this function](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L277).

You can close this issue if you have no further questions.

**Comment by PeiSeng** [comment]
Ya, one more question. So currently for rl-baselines-zoo SAC+HER, only use DoneOnSuccessWrapper or both?

**Comment by Miffyli** [comment]
Answers [seem to be here](https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/her.yml). In any case, this is a rl-zoo issue, not stable-baselines one, so I am going to close this.
