### ISSUE TITLE
Question SAC entropy loss

### ISSUE THREAD

**Issue by surbhi1944** [hill-a/stable-baselines#801]
Hello sir,

I want to ask that in below code (in sac.py) log_ent_coef is used:
![image](https://user-images.githubusercontent.com/51375621/79141132-cd5b2f80-7dd6-11ea-9afe-64f6c341a884.png)

While as per the below equation mentioned in softlearning paper instead of self.log_ent_coef there should be self.ent_coef 
![image](https://user-images.githubusercontent.com/51375621/79141218-f4b1fc80-7dd6-11ea-962e-38e0aa2fa4b3.png)
Will presence of self.log_ent_coef not affect the performance?

Thanks..

**Comment by araffin** [comment]
Hello,
You have the answer in the repo from the original implementation: https://github.com/rail-berkeley/softlearning/issues/37

**Comment by surbhi1944** [comment]
Thanks
