### ISSUE TITLE
Getting Nan and inf in PPO2

### ISSUE THREAD

**Issue by pirate-lofy** [hill-a/stable-baselines#806]
![Screenshot from 2020-04-14 21-07-35](https://user-images.githubusercontent.com/27896633/79264160-6308c480-7e94-11ea-9ee6-8d9d97ac0349.png)

I saw some previous issues that talked about getting nans during training ppo2 like https://github.com/hill-a/stable-baselines/issues/634 but previous solutions didn't work for me, so I tried to trace where the nans come from and I found that the sampling from the DiagGaussianProbabilityDistributionType may be the problem..
actions and neglog sampled from the Gaussian class are getting bigger by the time, so finally the become inf 
![Screenshot from 2020-04-14 21-08-21](https://user-images.githubusercontent.com/27896633/79264201-73b93a80-7e94-11ea-98a3-b912847135a3.png)
![Screenshot from 2020-04-14 21-09-26](https://user-images.githubusercontent.com/27896633/79264213-787dee80-7e94-11ea-821b-ec0cd7bdf01c.png)

Note:
I'm using a custom environment and implemented the algorithm myself (using stable_baselines code) so i could use other complicated policies

**Comment by Miffyli** [comment]
Check documentation on [dealing with nans](https://stable-baselines.readthedocs.io/en/master/guide/checking_nan.html) and [tips for custom envs](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment), especially the part about normalizing actions.
