### ISSUE TITLE
error assert action.shape == self.env.action_space.shape!When running the following example，The dimension of random sampling is different from that of network output. It's curious！！

### ISSUE THREAD

**Issue by BlackDeal** [hill-a/stable-baselines#807]
import gym
import numpy as np

from stable_baselines.sac.policies import MlpPolicy
from stable_baselines import SAC

env = gym.make('Pendulum-v0')

model = SAC(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=50000, log_interval=10)
model.save("sac_pendulum")

del model # remove to demonstrate saving and loading

model = SAC.load("sac_pendulum")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

**Comment by araffin** [comment]
Hello,

I'm not sure to get what's wrong and where...
The code runs and the shape of the action space is `(1,)` which is the shape of the action that `.predict()` output given only one observation (this will be different if given multiple observations).
