### ISSUE TITLE
Better argparse description in train_mountaincar.py

### ISSUE THREAD

**Issue by aakash94** [hill-a/stable-baselines#814]
**Improving description for `argparse.ArgumentParser` in `stable_baselines\deepq\experiments\train_mountaincar.py`**

Line 34 in the file goes like 
```python

parser = argparse.ArgumentParser(description="Train DQN on cartpole")

```
since the file trains for the `MountainCar-v0` environment as seen in line 14 `env = gym.make("MountainCar-v0")` and is named accordingly, a better description could be 
```python

parser = argparse.ArgumentParser(description="Train DQN on MountainCar")

```

**System Info**
Describe the characteristic of your environment:
 * How the library was used : from source on Windows10, libraries installed using Conda, Code ran and edited in Visual Studio Code
 * GPU model and configuration : GeForce GTX 1050 mobile
 * Python version : 3.7.6 
 * Tensorflow version : 1.14.0

**Comment by Miffyli** [comment]
Good to see I am not the only one getting into trouble copy-pasting code :D. Good catch.

I wonder if this should be accompanied with other typo/grammar checking of the documentation. I can not find the specific issue, but IIRC there was something similar suggested by @erniejunior a while back. Such cleanup could be nice for the archival of this version of SB.

**Comment by araffin** [comment]
> I can not find the specific issue

That was this one ;) #686

> there was something similar suggested by @erniejunior a while back.

this was a bit different: #680 

> Such cleanup could be nice for the archival of this version of SB. @araffin comments?

not much to add, I wanted to delete all those files (including the `run_atari` `run_mujoco`) at some point as we now have the zoo to train/test the agents and store the hyperparameters.
