### ISSUE TITLE
[question] Definition of observation space without knowing low and high values

### ISSUE THREAD

**Issue by kosmylo** [hill-a/stable-baselines#820]
I would like to ask what is the proper way to define the observation space if we do not know the values that the different observations could take during training.

I tried to define them by using some large values, in which they will for sure be in, but when I try to check the environment with check_env, I get the following warning:

```bash
warnings.warn("We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) 

```

Even if I define them to be in [-1, 1], then I will have to normalize them before pass the values to the agent, but again I need their maximum and minimum values.

Do I miss something?

**Comment by araffin** [comment]
>I would like to ask what is the proper way to define the observation space if we do not know the values that the different observations could take during training.

You are talking about observation space or action space? (the warning is about the action space)
Have you read the doc (RL tips and tricks)?

**Comment by kosmylo** [comment]
Yes, it is true that the warning is referred to the action space, but I thought that the same should hold for the observation space for the training to be stable. I know how to handle the action space with some advice written in the RL tips and tricks, but it says there that I can normalize the observation space if I know the boundaries. Now I do not know them, so how can I deal with that?

**Comment by Miffyli** [comment]
Use [VecNormalize](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecnormalize) for this. It automatically rescales observations (and rewards, if you so desire) with running mean and variance of observed observations.

**Comment by araffin** [comment]
For a complete answer, when you use `VecNormalize`, usually `low=-np.inf` and `high=np.inf` for the observation space.

**Comment by kosmylo** [comment]
Yes, the combination of ```VecNormalize``` with ```low=-np.inf``` and ```high=-np.inf``` gave the solution. Now I have a problem regarding the testing of my policy. Is there a way to check during testing the actual values of the observations and not the normalized ones? The root of my problem is that again I do not know the bounds, so to scale them back.

**Comment by Miffyli** [comment]
I am not sure if I follow, but you can get the original observation (without normalization) with this function:

https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/vec_normalize.py#L132

You can also get the statistics used to normalize from these attributes:

https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/vec_normalize.py#L31

**Comment by araffin** [comment]
I think that you should read the doc about `VecNormalize` (even its code) and take a look at the rl zoo to understand how normalized env are handled.

**Comment by kosmylo** [comment]
After training is done I am saving the model. If then I load the model and I create the environment again without wrapping it with ``` VecNormalize ``` is it a fine approach to do the testing?

**Comment by araffin** [comment]
You will find your answer here: https://github.com/hill-a/stable-baselines/issues/779 and the rl zoo ;)

**Comment by kosmylo** [comment]
Thank you very much! I think I found it!

**Comment by kosmylo** [comment]
I did the following for loading the environment for testing:

```
log_dir = "/tmp/"

env = ChargingStation()
env = DummyVecEnv([lambda: env])
env = VecNormalize.load(log_dir + "vec_normalize.pkl", env)
env.training = False
env.norm_reward = False
env = VecFrameStack(env, n_stack = 4)

# Load the trained agent
model = PPO2.load(log_dir + "ppo_ev_charging")
model.set_env(env)
```
However, I tried to combine it with the function ```get_original_obs``` of ``VecNormalize``` and I got an error. Specifically, some observations are crucial to check my policy, so I want to have their original values for plotting. So I thought that I can use ```get_original_obs``` as follows:

```
for i in range(n_time_steps_test):
    action, _states = model.predict(obs)       
    obs, rewards, dones, info = env.step(action)
    obs = VecNormalize.get_original_obs()
```
But I get the following error:

```
TypeError: get_original_obs() missing 1 required positional argument: 'self'
```
I searched for ```get_original_obs``` both in the documentation and in the RL zoo, but I could not find an example that uses it.

**Comment by araffin** [comment]
It is a python error... you should use `env.get_original_obs()`

**Comment by philippwulff** [comment]
Unfortunately I cannot use the `VecNormalize` wrapper for my custom gym environment because I cannot convert it to a vector environment using `DummyVecEnv`. It throws an error that it cannot pickle a `socket` module which my environment uses.

If I know the `high` and `low` values of the observation space, then I can just normalize the observation using `(obs - low) / (high - low) * 2 - 1`, right? I do not need to use a rolling mean and calculate it the way the wrapper class in stable baselines 3 does it, or is there a benefit to that?

**Comment by Miffyli** [comment]
> If I know the high and low values of the observation space, then I can just normalize the observation using (obs - low) / (high - low) * 2 - 1, right? I do not need to use a rolling mean and calculate it the way the wrapper class in stable baselines 3 does it, or is there a benefit to that?

Yes, this works mostly too. Using rolling mean/std does make things a touch easier for network (the inputs are always roughly normally distributed), but if you manage to do the same manually then you should be fine.

**Comment by philippwulff** [comment]
Thanks, this is great! I could not find information on how to do this. It works now! I have not used VecEnvs before but noticed, the `step` method returns a `list` which contains the the observation `np.array`s. Thus, when I want to pass this observation to the model, should I call `agent.predict(obs)` in a loop or is there a defined way for doing this?

**Comment by Miffyli** [comment]
> Thanks, this is great! I could not find information on how to do this. It works now! I have not used VecEnvs before but noticed, the step method returns a list which contains the the observation np.arrays. Thus, when I want to pass this observation to the model, should I call agent.predict(obs) in a loop or is there a defined way for doing this?

Yes, if you are manually running the environments (e.g. manual evaluation), you might need to do that.

PS: I recommend migrating to [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) if possible, as it is more actively supported.

**Comment by philippwulff** [comment]
I trained PPO with the environment and a `VecNormalize` wrapper. However compared to my "naive" normalization, this agent does not learn at all, when I test the trained agent in a test environment. I did also wrap the test environment with the normalization wrapper and loaded the stats for it.

```
env = AccelEnv(network=net, params=params)
env = DummyVecEnv([lambda: env])
env = VecNormalize(env)
agent = PPO("MlpPolicy", env)

agent.learn(12000000)
agent.save(save_path)
env.save(stats_path)
```

And then for testing I ran:

```
test_env_1 = AccelEnv(network=test_net_1, params=test_params_1)
test_env_1 = DummyVecEnv([lambda: test_env_1])
test_env_1 = VecNormalize.load(stats_path, test_env_1)
test_env_1.training = False
test_env_1.norm_reward = False
agent = PPO.load(save_path, env=test_env_1)

obs = test_env_1.reset()

for s in range(5000):
    action, _ = agent.predict(obs)
    obs, reward, done, info = test_env_1.step(action)
    if done:
        obs = test_env_1.reset()
```

This is probably difficult for you to help here, because I cannot really paste all of the environment code (as it is way too long). However do you spot something that I am doing wrong or do you have some intuition what the problem may be?

**Comment by Miffyli** [comment]
Compared to the example code this seems to check out (note: I have not used normalize wrappers myself). I would double check that the observation statistics do not change wildly between creating different envs.

What do the training stats tell you (`verbose=2` in creation of agent)? With PPO, this gives you a good idea of the agent's performance even before separate evaluation. 

> Also, looking at the code of the VecNormalize wrapper I see, that the parameters clip_obs and clip_reward are only used to clip the values after they were normalized. Therefore it does not clip anything if they are larger than 1, right?
When I look at the values in obs, some are larger than 1 or smaller than -1.

Those >1 and <-1 values would be clipped if you set it to clip at 1, yes. But by default it clips to [-10, 10], so no clipping probably happens in your case.

Note that we do not have time to offer per-user tech support, so my answers are short. If you continue having bugs, I still recommend using SB3 if possible. If you spot a bug or confusing behaviour, feel free to open an issue about fixing it :)
