### ISSUE TITLE
validation episode_reward plot for Tensorboard  [question]

### ISSUE THREAD

**Issue by soleaf** [hill-a/stable-baselines#823]
Hello, 
I'm using eval_callback and tb_log_name option for model training.
It's cool tools for tracing training result.

But I can't find a validation episode reward plot on Tensorboard.
To check overfitting, I would like to plot the validation reward with training reward plot.

**Comment by Miffyli** [comment]
By default, algorithms do not evaluate their performance in validation episodes (with exploration turned off). For this you can use callbacks [like this one](https://stable-baselines.readthedocs.io/en/master/guide/callbacks.html#evalcallback), and tips from [here](https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html#tensorboard) to integrate it with tensorboard.
