### ISSUE TITLE
[question][feature request] Is there any documentation or a sample code on using Optuna for a custom enviornment?

### ISSUE THREAD

**Issue by Ujwal2910** [hill-a/stable-baselines#826]
in documentation is there support doc or sample code which sheds some light on using optuna for a custom environment. I checked the zoo baselines but did not find any sample or example explaining on how to use optuna as such. Help would be appreciated.

**Comment by araffin** [comment]
Hello,

Your question does not seem related to stable-baselines but to optuna, no?

**Comment by Ujwal2910** [comment]
It certainly is so but in the documentation it has been mentioned that Optuna has been used in stable-baselines for hyper-parameter tuning.

**Comment by araffin** [comment]
In that case, have you read the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/rl_zoo.html#hyperparameter-optimization) and the [README](https://github.com/araffin/rl-baselines-zoo) of the rl zoo?
