### ISSUE TITLE
Monitoring models without access to storage

### ISSUE THREAD

**Issue by drose188** [hill-a/stable-baselines#836]
Reading here:
https://towardsdatascience.com/stable-baselines-a-fork-of-openai-baselines-reinforcement-learning-made-easy-df87c4b2fc82
and here:
https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/master/monitor_training.ipynb#scrollTo=hyyN-2qyK_T2
I see that monitoring relies on loading data from log:
x, y = ts2xy(load_results(log_dir), 'timesteps')
I am working with third party product and do not have access to storage. Everything is in memory. Is there a workaround to monitor and save best model?

**Comment by Miffyli** [comment]
Monitor helps to track training performance, which may be same as evaluation performance, depending on the environment algorithm. For proper performance tracking, check out using [callbacks](https://stable-baselines.readthedocs.io/en/master/guide/callbacks.html#evalcallback). You can create a custom callback that does the same trick, but just saves results in the memory.
