### ISSUE TITLE
Question: TRPO with action space using spaces.box()

### ISSUE THREAD

**Issue by blurLake** [hill-a/stable-baselines#842]
Hi, I read that TRPO that use discrete action. But it also support spaces.box() which gives a continuous action space. Is it needed in this case to set the resolutions of this action space?

Thank you very much!

**Comment by araffin** [comment]
> Is it needed in this case to set the resolutions of this action space?

hello, what do you mean?
Have you read the [documentation](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment) ?

**Comment by blurLake** [comment]
Thanks for the reply. I think I know what I want now. I wanted to ask how to add resolution on spaces.box to use TRPO with discrete actions. I need to use spaces.multidiscrete() in this case. Sorry for not read the doc throughly before post here.
