### ISSUE TITLE
SAC not taking any actions

### ISSUE THREAD

**Issue by C-monC** [hill-a/stable-baselines#843]
Hello,
I am using a custom environment. Pixel input with a continuous action space.

I've trained policies using TD3 and PPO/PPO2 in the custom env successfully. When I try SAC, even with a large step count, the policy doesn't take any actions. I've not been able to identify the reason for this. Does anyone have an idea what could cause this?

Thanks,
Simon

**Comment by Miffyli** [comment]
By "taking no actions", do you mean the actions are zeros?

I am not familiar with continuous action-spaces, so I can not give specific guidance. Have you tried tips and tricks [shown in the docs](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html)?

**Comment by C-monC** [comment]
When the env is reset the values assigned to the actions remain the same through the episode.

Oh thanks for that link. It's probably because I added to the reward function and forgot to re-normalize. Going to try that now.
