### ISSUE TITLE
Discrepancy between `DummyVecEnv` and a normally wrapped Atari env

### ISSUE THREAD

**Issue by alexsieusahai** [hill-a/stable-baselines#844]
**Describe the bug**
Building the same environment in what appears to be the same way results in _slightly_ different observations being generated. I apologise if I missed something in advance or misunderstood something.

**Code example**
If I build an atari environment doing the following:
```python3
env = make_atari_env('BreakoutNoFrameskip-v4', num_env=1, seed=414)
env = VecFrameStack(env, n_stack=4)
```

And I build another atari environment doing the following:
```python3
env = gym.make('BreakoutNoFrameskip-v4')
env = wrap_atari_dqn(env)  # from deepq.__init__.py
```
The following code results in agreement between the `obs` and `prev` variables using the second method for creating the environment, whereas it results in disagreement using the first method for creating the environment.
```python3
def observation(frame):  # from common.atari_wrappers, WarpFrame method
    """
    returns the current observation from a frame
    :param frame: ([int] or [float]) environment frame
    :return: ([int] or [float]) the observation
    """
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
    frame = cv2.resize(frame, (84, 84), interpolation=cv2.INTER_AREA)
    return frame[:, :, None]

prev, frames = None, []
agent = DQN.load('BreakoutNoFrameSkip-v4.pkl', env=env)  # just using pretrained Breakout from rl-baselines-zoo
for i in range(-3, 1):
    warped_frame = observation(np.array(env.ale.getScreenRGB2()))
    prev = obs
    obs, _, _, _ = env.step(agent.predict(obs))
    frames.append(warped_frame)

alt_obs = np.array([np.concatenate(frames, axis=2)])   # from FrameStack
assert agent.predict(alt_obs) == agent.predict(prev)
```

**System Info**
* Installed `stable_baselines` via pip, using version `2.10.0`
* Using python 3.7.5
* Using tensorflow 1.14.0

**Additional context**
While the differences in the generated images are quite small, they seem to have a pretty big effect on the behavior of the agent, which is surprising.

**Comment by araffin** [comment]
Hello,
I'm not sure to completely understand the issue... Could you also give you gym and atari-py version?

**Comment by Miffyli** [comment]
`make_atari_env` does quite a bit more than just the few steps in `wrap_atari_dqn`, see [here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/cmd_util.py#L76). It is quite expected the results are different. My guess is the [MaxAndSkipEnv](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L287) is the one that makes things different, as it just does not do frameskipping but also maxes over the skipped frames.

**Comment by alexsieusahai** [comment]
Yup, I was just about to note this and close the issue. Thanks!
