### ISSUE TITLE
Continual learning becomes really slow.

### ISSUE THREAD

**Issue by blurLake** [hill-a/stable-baselines#845]
Hi, I am using following code to resume an interrupted training using TD3.load(). However, the training speed is much slower than before. Here environment is the same as before.  Each episode (with the same length) takes 10 times more than the original one. Could anyone suggest what can be the problem? Thanks!

```
env = gym.make('gym_environment:FullEnv-v0')
env = Monitor(env, log_dir)
check_env(env)


model = TD3.load("td3_logger/best_model.zip")

model.set_env(env)

callback = SaveOnBestTrainingRewardCallback(check_freq=100, log_dir=log_dir)
time_steps = 1e6
model.learn(total_timesteps=int(time_steps), callback=callback)
```

**Comment by araffin** [comment]
Hello,
It sounds like a duplicate of https://github.com/hill-a/stable-baselines/issues/734
Can you try with SB3: https://github.com/DLR-RM/stable-baselines3? (it has a different replay buffer implementation)

**Comment by blurLake** [comment]
Hi, 
Finally got one trained model and test the resume the training with SB3. But it seems SB3 can not retrain a model produced by SB2. Is there a way to fix this? Thank you very much!

`File "TD3_resumer.py", line 62, in <module>
    model = TD3.load("td3_trained_models/best_model.zip")
  File "/home/eejiiew/train_resumer/venv/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 359, in load
    model = cls(policy=data["policy_class"], env=env, device='auto', _init_setup_model=False)
KeyError: 'policy_class'
`

**Comment by araffin** [comment]
>Finally got one trained model and test the resume the training with SB3.

I meant train with SB3 and retrain with SB3. SB3 backend is based on pytorch, we have some documentation to convert tf models to pytorch (cf "exporting models").

**Comment by blurLake** [comment]
Thanks a lot for the help. I did a test with a SB3 TD3 model, indeed the retrain is much faster (similar to the original training process).
