### ISSUE TITLE
Is double Q network updated independently in SAC？

### ISSUE THREAD

**Issue by BlackDeal** [hill-a/stable-baselines#846]
- qf1, qf2, value_fn = self.policy_tf.make_critics(self.processed_obs_ph, self.actions_ph,

                                                                     create_qf=True, create_vf=True)

-  qf1_loss = 0.5 * tf.reduce_mean((q_backup - qf1) ** 2)
    qf2_loss = 0.5 * tf.reduce_mean((q_backup - qf2) ** 2)

- values_losses = qf1_loss + qf2_loss + value_loss
 Are two Q networks just initialized differently?If so, does it improve the effect significantly?

**Comment by Miffyli** [comment]
Yes, that's one of the tricks in SAC. See [SpinningUp description of SAC](https://spinningup.openai.com/en/latest/algorithms/sac.html). You may close this issue if you have no further questions related to stable-baselines.

**Comment by araffin** [comment]
> Are two Q networks just initialized differently?If so, does it improve the effect significantly?

I recommend you to read TD3 (which introduces the clipped double q-learning) and SAC paper for a better understanding.
In short, yes, they are initialized differently and it allows to reduce overestimation of the q-value by taking the min of the two.

**Comment by BlackDeal** [comment]
Thank you!!!
