### ISSUE TITLE
Iterate over pandas dataframe

### ISSUE THREAD

**Issue by 3ventHoriz0n** [hill-a/stable-baselines#850]
I'm passing a pandas dataframe to my custom environment and one row is advanced every time-step. My data frame has about 4000 rows.
I make the call to train as follows:
`model = PPO2(MlpPolicy, env).learn(total_timesteps=TRAIN_STEPS)`

If I want the algorithm to iterate over my training data 5 times, I have to set `TRAIN_STEPS=20000`

I've set `TEST_STEPS=1000`

Does this mean the `step` function of my environment will be called 20000 times for train and 1000 times for test?

**Comment by Miffyli** [comment]
`model = PPO2(MlpPolicy, env).learn(total_timesteps=TRAIN_STEPS)` means you will _train_ for `TRAIN_STEPS` steps (i.e. `TRAIN_STEPS` amount of calls to `step` function of the environment). There is no testing done. You need to use e.g. [callbacks](https://stable-baselines.readthedocs.io/en/master/guide/callbacks.html#) to achieve that.

**Comment by 3ventHoriz0n** [comment]
Thanks! My bad, didn't include the test block. Here it is:
<pre>
# Train code here
for i in range(TEST_STEPS):
    action, _states = model.predict(obs, deterministic=True)
    obs, rewards, done, info = env.step(action)
    env.render()
</pre>

**Comment by Miffyli** [comment]
Yes that would be how evaluation is usually done (sometimes with `deterministic=False`, but which one works better depends on your environment and you have to test it out).

If you have no further issues/enhancements related to stable-baselines, you can close this issue.
