### ISSUE TITLE
Normalize only parts of the observation space

### ISSUE THREAD

**Issue by stefanbschneider** [hill-a/stable-baselines#856]
I have a custom environment where the first of the observation space are large floats and the second are binary values. This is how I defined the observation space:

```python
part1_low = np.zeros(5)
part1_high = np.full(shape=(5,), fill_value=200)
# part 2 is binary
part2_low = np.zeros(5)
part2_high = np.ones(5)
self.observation_space = gym.spaces.Box(low=np.concatenate([part1_low, part2_low]), high=np.concatenate([part1_high, part2_high]))
```

I use `VecNormalize` to normalize the observations and it works great. However, it always normalizes all observations in the observation space. Is there any way to restrict normalization to the first part? That way, the 2nd part with the binary values would stay untouched. I believe that would make learning easier.

I'm using Python 3.6 and stable_baselines 2.10.0 on Windows 10.

**Comment by araffin** [comment]
>Is there any way to restrict normalization to the first part? 

Why don't you write a custom `VecNormalize` that derives from the base one?
Sounds like the easiest solution.

**Comment by stefanbschneider** [comment]
True, should be doable. Does it sound like reasonable idea to exclude binary parts of the observation space from normalization?

**Comment by araffin** [comment]
>Does it sound like reasonable idea to exclude binary parts of the observation space from normalization?

yes as values are only 0 or 1, they are already normalized. Closing this issue then ;).
