### ISSUE TITLE
Inter episode performance optimization

### ISSUE THREAD

**Issue by yizhoucc** [hill-a/stable-baselines#862]
suggest an enhancement or feature request:  

Regarding the td3.py file, but this applies to all other algorithms using replay buffer as well.
Right now, the algorithm learns using the replay buffer, and if the done==1., in other words the episode ends, the algorithm does not update the Q.
this part is in line 180: `(1 - self.terminals_ph) * self.gamma * min_qf_target`

This produce a 'problem', if I hope the agent to learn to skip some 'hard' episode to maximize the total reward yield in given time, the agent fails to learn this skipping behavior.

Would it be a good idea to add an arg in to modify this part?

**Comment by araffin** [comment]
> Right now, the algorithm learns using the replay buffer, and if the done==1., in other words the episode ends, the algorithm does not update the Q.

In an episodic setting, this is the definition of a q-value.

>This produce a 'problem', if I hope the agent to learn to skip some 'hard' episode to maximize the total reward yield in given time, the agent fails to learn this skipping behavior.

Could you elaborate on that one?

**Comment by yizhoucc** [comment]
> > Right now, the algorithm learns using the replay buffer, and if the done==1., in other words the episode ends, the algorithm does not update the Q.
> 
> In an episodic setting, this is the definition of a q-value.
> EDIT: it does update the q-value but the target value is only the terminal reward.
> 
> > This produce a 'problem', if I hope the agent to learn to skip some 'hard' episode to maximize the total reward yield in given time, the agent fails to learn this skipping behavior.
> 
> Could you elaborate on that one?

In a task that Im testing on, reward is given only at the end of episode.
there are 'hard' episode that takes longer to complete, and has a lower chance to get reward (same reward amount as easy episode, so reward expectation is lower).
there are also 'easy' episodes, that takes much shorter steps and reward expectation is larger.
In this case, I would expect the agent to skip hard episodes and maximize the total reward expectation / total steps.

So, if the agent 'skips' without getting a reward, according to the original Q, the Q is 0 (because reward is 0) and agent will learn not to skip.
if we treat 'done' step as normal step, the Q will be close the initial state in the next episode.
If the next episode is 'easy', Q will be relative large.
In this way, agent learns if it skips, it can potentially maximize the future expectation of reward, and learns this skipping behavior.

**Comment by araffin** [comment]
Sounds like a very specific problem, why don't you write a custom td3 that derives from the base td3 class?

**Comment by yizhoucc** [comment]
yes that's what im doing now. just let other people know they can do something like this when having the same problem.
