### ISSUE TITLE
cannot train environment 'HandReach-v0' or any Robotic Hand related environments with PPO2(that I have tested so far)

### ISSUE THREAD

**Issue by roobooot** [hill-a/stable-baselines#865]
* I have tried to simply test PPO2 using 'HandReach-v0' environment, but it's not working.
```python
import gym
import numpy as np
from stable_baselines import PPO2
from stable_baselines.common.policies import MlpPolicy

env = gym.make('HandReach-v0')

model = PPO2(MlpPolicy, env, verbose=1)
```
The Error shows:
```bash
NotImplementedError: Error: the model does not support input space of type Dict
```
* Then, I checked the env using check_env as suggested
```python
from stable_baselines.common.env_checker import check_env
env = gym.make('HandReach-v0')
check_env(env)
```
The Error shows:
```bash
AssertionError: The reward returned by `step()` must be a float
```

**Comment by roobooot** [comment]
One more thing is that **the original openai-baseline can train HandReach-v0 using PPO2.**
```bash
python -m baselines.run --alg=ppo2 --env=HandReach-v0 --num_timesteps=1e6
```

**Comment by araffin** [comment]
Hello,
As mentioned in the documentation, `GoalEnv` (with dict observation) are only supported for HER.
If you want to use PPO, you need to use a wrapper first to convert the `Dict` into a `Box` space.
You may take a look at `gym.wrappers.FlattenObservation` and at the [rl zoo](https://github.com/araffin/rl-baselines-zoo) that allows to use wrappers easily.
