### ISSUE TITLE
make_atari - Should frame max-ing be used for Atari RAM environment

### ISSUE THREAD

**Issue by Geetub** [hill-a/stable-baselines#870]
I noticed that on make_atari() there's a use of MaxAndSkipEnv wrapper.
I understand the need for max-ing bitmap frames, but does this reason also apply to RAM-snapshot frames?

**Comment by araffin** [comment]
Hello,

I think `make_atari` is only meant for the image version now.

**Comment by Geetub** [comment]
OK, thank you.
