### ISSUE TITLE
[question] how to specify a custom net arch(local connection)?

### ISSUE THREAD

**Issue by asdfqwer2015** [hill-a/stable-baselines#873]
Hi:
  How to specify a custom policy net with different branch of fc to transform groups of features and concat them then do fc? My experiment: PPO2, mlp policy. I think simply specify `net_arch` can not handle this feature.
  Desired arch:    x0, x1, x2, ......., xn-2, xn-1
                             |--fc----|          |--fc--|
                             |---------concat-----|
                             |----------fc----------|
                             |----------fc----------|
                             |-------softmax------|
'local connection's to transform related features and split irrelevant features.
e.g. openai five model arch for Dota2.
  
  Thanks.

**Comment by araffin** [comment]
Hello,
As mentioned in the documentation, you need to define a custom policy for that kind of special needs.
`net_arch` is only for the common case (no fancy branching with the features).

**Comment by asdfqwer2015** [comment]
Thanks for your quick reply.
:)
I'll implement my custom policy.
