### ISSUE TITLE
CustomEnv Observation Shape Error

### ISSUE THREAD

**Issue by DroneMesh** [hill-a/stable-baselines#875]
I am running into small issue with my observation space shape 

```
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf,shape=(6,),
                                           dtype=np.float32)
```

What do i need to modify to fix this issue.

Error with check_env is 

`AssertionError: The observation returned by the `reset()` method does not match the given observation space
`

Without check_env
`ValueError: Cannot feed value of shape (1, 14) for Tensor 'input/Ob:0', which has shape '(?, 6)'
`

**Comment by Miffyli** [comment]
As error suggests, your `reset()` function returns an observation of wrong shape. Double check what it returns.

**Comment by DroneMesh** [comment]
It returns 0,0,0,0,0,0 a 6 float array

**Comment by Miffyli** [comment]
According to the both errors, that changes to something else at some point when environment has been used.

You may close this issue if there are no issues or enhancement-suggestions that consider stable-baselines code.

**Comment by DroneMesh** [comment]
Solved it my OBS was returning (14,) Thank you for the help

**Comment by howziin** [comment]
Can I ask you what the OBS is exactly?

**Comment by leo2r** [comment]
> Can I ask you what the OBS is exactly?

I guess it's their 'observation'? :)

**Comment by GF-Huang** [comment]
I have same issue.

![image](https://user-images.githubusercontent.com/4510984/178982309-5453051d-650e-4f2f-8496-63126777244c.png)

![image](https://user-images.githubusercontent.com/4510984/178982595-8bfaaed1-65dd-42e3-95da-fc026b1e366b.png)

![image](https://user-images.githubusercontent.com/4510984/178982564-1c92eb17-2226-4c97-acce-fe2f7179274c.png)

**Comment by Miffyli** [comment]
@GF-Huang You are missing "-" in front of the `np.inf` in the `high` entry of the observation space.

**Comment by GF-Huang** [comment]
> @GF-Huang You are missing "-" in front of the `np.inf` in the `high` entry of the observation space.

No, that's my intent. My obs: [ 0 ~ inf, -inf ~ inf ].

**Comment by Miffyli** [comment]
Yes, but at line 9, the first `np.inf` is missing a "-" in front of it :)

**Comment by Miffyli** [comment]
Oh derp, you are right, I was completely wrong: your observation space seems right. Sorry for wasting your time like this!

The issue probably lies that the `np.array([0, 0])` is probably an array of integers, not floats. Try `np.array([0.0, 0.0])`.

**Comment by Miffyli** [comment]
Oh :D. I am not sure why that solved the issue: I was referring to line 15 (`return np.array([0, 0])`), where the numpy array is likely of  integers instead of floats, so changing that to floats should also have fixed the issue. Anywho, good that you managed to solve it!

**Comment by GF-Huang** [comment]
I had try `return np.array([0.0, 0.0])` but not work. But `dtype=np.float64` works.

**Comment by ReHoss** [comment]
Hello:),

I had the same issue solved with @GF-Huang , could be convenient to add a data type checker in the tool.

**Comment by BruceXing24** [comment]
> I had try `return np.array([0.0, 0.0])` but not work. But `dtype=np.float64` works.

yes, you are right. I use np.pi, even though float32 doesn't work, but float64 works.

**Comment by yapanliu** [comment]
> 

Changed data type to float64 solved my issue. Thanks for sharing.

**Comment by jzhangCSER01** [comment]
> > I had try `return np.array([0.0, 0.0])` but not work. But `dtype=np.float64` works.
> 
> yes, you are right. I use np.pi, even though float32 doesn't work, but float64 works.

yeah, I had the same error, then I changed np.float32 to np.float64, it worked

**Comment by topp** [comment]
Same here, a bit annoying, I had to change any float to np.float64 to get rid of the (not much telling) warning. Thanks for sharing.
