### ISSUE TITLE
[question] Why am I getting an unexpected activation, even before training ?

### ISSUE THREAD

**Issue by bgirschig** [hill-a/stable-baselines#877]
**note:** I understand this is probably not the best place to ask this question. However I couldn't find an official or recommended forum for this...

I am working on creating a custom environment and training a RL agent on it.

My environment has an action space of size 127, and interprets it as a one-hot vector: Taking the index of the highest value in the vector as an input value.
For debugging, I create a bar chart, showing how many times each value has been "called"

Before training, I would expect the graph to show a roughly uniform distribution of "events", but instead the "events" in the lower end of the action spec are massively more likely than the others

I have created a colab to explain and reproduce the "issue" [here](https://colab.research.google.com/drive/12Lj5VjiArqxa5DfXnjYAUkU78qWwn7on?usp=sharing)

Here is a short version, in case the colab doesn't work

```python
note_dims = 127
note_counters = np.zeros((note_dims))

class CustomEnv(gym.Env):
  def __init__(self):
    self.action_space = spaces.Box(-1, 1, [note_dims], dtype=np.float32);
    self.observation_space = spaces.Box(-1, 1, [10], dtype=float);
    self._state = np.zeros([10])

  def reset(self):
    self._step_count = 0
    self._state = np.zeros([10])
    return self._state;

  def render(self, *args):
    pass

  def step(self, action):
    self._step_count += 1

    # map actions from -1,1 to 0,1
    action = action * 0.5 + 0.5

    pitch = np.argmax(action)
    note_counters[pitch] += 1

    reward = 0
    isdone = self._step_count > 500
    observation = self._state

    return observation, reward, isdone, {}

# Make sure the environment is properly configured
env = CustomEnv()
check_env(env, warn=True)
# vectorize the environment
env = make_vec_env(lambda: env, n_envs=1)

# I have tried multiple model architectures here but the results are always the same
model = PPO2('MlpPolicy', env, verbose=1)

obs = env.reset()
note_counters = np.zeros((note_dims))

for step_idx in range(1000):
  action, _states = model.predict(obs)
  env.step(action)

plt.bar(np.arange(0, note_dims), note_counters)
```

**system info**
default colab instance

**Comment by Miffyli** [comment]
>note: I understand this is probably not the best place to ask this question. However I couldn't find an official or recommended forum for this...

You are right about this, but also on how we do not have any official forum for this. We usually recommend asking on stackoverflow or /r/reinforcementlearning, but I am starting to wonder if (yet another) Discord server or gitter page would be useful...

**To your question**: This is expected behaviour. Randomly initializing neural networks does not usually end up with uniform guessing. See [this paper (figure 7)](https://arxiv.org/abs/2002.02405) for an example with ResNets and Gaussian initialization. Same behaviour happens, more or less, with other network types and initializations. 

This is why we have the entropy term for policy-gradient based methods, which encourages taking different actions. As you continue training, you _should_ start seeing more uniform actions, if not "optimal".

**Comment by araffin** [comment]
>My environment has an action space of size 127, and interprets it as a one-hot vector

Why do you use a `Box` space and not a `Discrete` space?

**Comment by PartiallyTyped** [comment]
Your issue isn't with `SB` but with `np.argmax`.
See here:
https://colab.research.google.com/drive/12Lj5VjiArqxa5DfXnjYAUkU78qWwn7on?usp=sharing

The tl:dr is that argmax picks the index using strictly greater, not greater or equal, hence you see this.

Counting all the elements equal to argmax yields this:

![image](https://user-images.githubusercontent.com/52372765/83619531-aa5a2a00-a594-11ea-85f2-dde4b02d8319.png)

**Comment by bgirschig** [comment]
Thank you all for your answers.

@Miffyli 
- Would you like me to close this issue and ask it again on stackoverflow ?
- I'll need some time to read and understand that paper, then I'll look into the entropy parameter (it sounds similar to the "exploration" parameter. Are they the same ?)

@araffin
- I'm using a box because the actual problem I'm trying to solve requires some controls that are not discrete
- I couldn't find the part you mention in the documentation, or I don't quite understand your point: isn't the gaussian distribution applied to each dimension individually, rather than across them ?

@PartiallyTyped 
- It looks like your changes were not saved in the colab. Could you add you example here ?
- Also, I don't see how this would make a difference unless a lot of values in the action vectors were equal, which is not what I expect either.
- Furthermore, if my use of argmax was the issue, why would my test with the random actions give me the uniform distribution ?

Again, thank you all for taking the time to answer me and being so reactive

**Comment by Miffyli** [comment]
@bgirschig 

I would ask this somewhere else, as this is not specifically a stable-baselines issue, and we do not have much time to devote on providing technical support like this (sorry ^^'). See other replies for better answers (e.g. using Box and then turning into discrete actions is probably a wonky idea).

**Comment by PartiallyTyped** [comment]
All of this is a consequence of the distributions used. 

If you take the the action vector and reverse it. You will see the same poison like distribution when using an untrained model.
