### ISSUE TITLE
Stable Baselines testing a model is not working as intended?

### ISSUE THREAD

**Issue by jandevries123** [hill-a/stable-baselines#879]

**Comment by jandevries123** [comment]
@araffin , sorry to bother. Although you may not be able to help me out on my rather... specific issue. Could you perhaps provide me with the information needed to print the output of the network, softmax/tanh? The only output i am getting now is the actual action, though i want to check whether my network is saturated or not which could cause this weird behaviour to create?

**Comment by Miffyli** [comment]
You can get the action probabilities with [this function](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.action_probability).

Two suggestions:
- Did you use LSTM policies? If you did, [the prediction loop gets bit more terms](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#recurrent-policies). 
- Check that environment has same behaviour during training and testing, e.g. some seed does not change this too much.
- Check [RL tips in docs](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html) if that would bring up some ideas that could be wrong.

Apart from that I do not know what suggestions to give. Stable-baselines side seems to work, and we do not have too much time to delve into individual problems like these.

**Comment by jandevries123** [comment]
> You can get the action probabilities with [this function](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#stable_baselines.ppo2.PPO2.action_probability).
> 
> Suggestions:
> 
> * Did you use LSTM policies? If you did, [the prediction loop gets bit more terms](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#recurrent-policies).
> * Check that environment has same behaviour during training and testing, e.g. some seed does not change this too much.
> * Check [RL tips in docs](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html) if that would bring up some ideas that could be wrong.
> 
> Apart from that I do not know what suggestions to give. Stable-baselines side seems to work, and we do not have too much time to delve into individual problems like these.

Understood

**Comment by jandevries123** [comment]
Please delete issue
