### ISSUE TITLE
policy.step

### ISSUE THREAD

**Issue by Jeevi10** [hill-a/stable-baselines#881]
env = gym.make('CartPole-v1')

model = DQN(MlpPolicy, env , double_q=False, verbose=0, policy_kwargs=dict(dueling=True))

def evaluate(model, num_episodes=100):
    """
  
    env = model.get_env()
    all_episode_rewards = []
    for i in range(num_episodes):
        episode_rewards = []
        done = False
        obs = env.reset()
        while not done:
           
            action, _states = model.predict(obs)
            print(model.policy.step(obs))
            obs, reward, done, info = env.step(action)
            episode_rewards.append(reward)

        all_episode_rewards.append(sum(episode_rewards))

    mean_episode_reward = np.mean(all_episode_rewards)
    print("Mean reward:", mean_episode_reward, "Num episodes:", num_episodes)

    return mean_episode_reward

mean_reward_before_train = evaluate(model, num_episodes=100)

TypeError                                 Traceback (most recent call last)
<ipython-input-22-d3ff4f403989> in <module>
----> 2 mean_reward_before_train = evaluate(model, num_episodes=100)

<ipython-input-21-1fd8bed000c1> in evaluate(model, num_episodes)
     17             action, _states = model.predict(obs)
---> 18             print(model.policy.step(obs))

TypeError: step() missing 1 required positional argument: 'obs'

I am getting this error when I ran above code can anyone help me on this?

**Comment by Miffyli** [comment]
`model.policy.step` has different call signature from `model.step`. You should mainly use `model.predict` to get an action to observation.
