### ISSUE TITLE
[QUESTION] DQN Policy Kwargs depreciated?

### ISSUE THREAD

**Issue by jandevries123** [hill-a/stable-baselines#888]
SOLVED

**Comment by Miffyli** [comment]
I am not quite sure what is the problem. DQN does still accept `policy_kwargs` [as before](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/deepq/dqn.py#L63) (although it seems to be missing from the docstring, wups), which is then passed on to the policy that is created. There was discussion on the confusion of how dueling architecture works (#587), however, so you have to be careful on what the different parameters will actually do to the network.

**Comment by araffin** [comment]
my guess is replacing "net_arch" by "layers" should solve your issue ;) (cf dqn doc)

**Comment by jandevries123** [comment]
> my guess is replacing "net_arch" by "layers" should solve your issue ;) (cf dqn doc)

Yes, but it just doesn't accept the policy_kwargs argument at all, so i can't input net_arch nor layers.

**Comment by jandevries123** [comment]
Sorry for semi wasting your time, it got solved by simply reinstalling Stable Baselines. Yes i was using the correct version of SB, somehow reinstalling solved the issue. Don't ask me how.. Sad time. 

I'd like to end with that i appreciate the work you put in Stable Baselines, thanks!

**Comment by jandevries123** [comment]
Please delete issue
