### ISSUE TITLE
[question] Use of UnVecWrapper

### ISSUE THREAD

**Issue by PierreExeter** [hill-a/stable-baselines#889]
Hello,

I have some trouble understanding UnVecWrapper. When training with SAC, using the scripts provided in [Stable Baselines Zoo](https://github.com/araffin/rl-baselines-zoo)

```bash
python train.py --algo sac --env Pendulum-v0 -n 10000
```

I get the following warning:
```bash
UserWarning: Training and eval env are not of the same type<stable_baselines.common.base_class._UnvecWrapper object at 0x7fbf90f6b748> != <stable_baselines.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fbf90f6b3c8>
```
This is due to the training environment being wrapped with `UnVecWrapper` but not the evaluation environment, see the following 2 snippets.

https://github.com/hill-a/stable-baselines/blob/0c956eb9b10c9bd927331da62d26b85c8b5f0662/stable_baselines/common/callbacks.py#L49

https://github.com/hill-a/stable-baselines/blob/0c956eb9b10c9bd927331da62d26b85c8b5f0662/stable_baselines/common/base_class.py#L86-L92

I understand that this wrapper is required to un-vectorize environments with only one instance.

Now my questions are:
- Why is the training environment wrapped with UnVecWrapper but not the evaluation environment?
- Should I also un-vectorize the evaluation environment with UnVecWrapper or should I keep the training environment vectorized?
- Is it OK to ignore this warning if I only train with one environment?

Thanks,
Pierre

PS: I'm using Stable-Baselines 2.10.0.

**Comment by araffin** [comment]
First, as a disclaimer, `UnVecWrapper` was a hack meant to use `VecEnv` and their wrappers with DQN/DDPG/SAC/TD3/HER without changing their code. On the longer term, it was a big mistake and brought many issues. That's also why SB3 got rid of that.
I don't know how much work it would be to remove it from SB2 too, but would be a good thing.

>Why is the training environment wrapped with UnVecWrapper but not the evaluation environment?
>Should I also un-vectorize the evaluation environment with UnVecWrapper or should I keep the training environment vectorized?

You cannot have more than one evaluation env. So wrapping it into a `UnVecWrapper` or using it alone should be the same. I also always prefer to work with as little wrapper as possible. That being said, I agree this is an inconsistency that we should maybe solve.

>Is it OK to ignore this warning if I only train with one environment?

If you are using the zoo, it should be fine to ignore the warning.

**Comment by PierreExeter** [comment]
Ok I'm happy with ignoring warnings ;) thanks
