### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by SuperMan-bit-byte** [hill-a/stable-baselines#891]
Is it my fault or is it not training enough ,few days back I thought I give a try to stable baselines after a few hours I noticed the agent the bipedal walker Was not making any progress I trained it on a million time steps and I did this with some other gym environments too it's not working or should I change my code Please reply soon!.  And I always get this Loading a model without a environment cannot be trained

**Comment by araffin** [comment]
Hello,
Please fill the issue template completely. Make sure to also read the "tips and trick" section in the documentation.
