### ISSUE TITLE
Problems with Tensorboard in Google Colab and Tensorflow version 1.x [question]

### ISSUE THREAD

**Issue by josiahcoad** [hill-a/stable-baselines#896]
**Describe the bug**
I am trying to run tensorboard on google colab using your example from [here](https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html).

My Full code is as follows:
```
%tensorflow_version 1.x
!pip install stable-baselines[mpi]==2.10.0
from stable_baselines import A2C

model = A2C('MlpPolicy', 'CartPole-v1', verbose=1, tensorboard_log="./a2c_cartpole_tensorboard/")
model.learn(total_timesteps=10000)

%load_ext tensorboard
!tensorboard --logdir ./a2c_cartpole_tensorboard/
```

And the output is:
```
W0617 19:56:14.979392 140125179291392 plugin_event_accumulator.py:294] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
TensorBoard 1.15.0 at http://9e12e4148db4:6006/ (Press CTRL+C to quit)
```

I try navigating to [http://9e12e4148db4:6006/](http://9e12e4148db4:6006/) but get the error message "this site can not be reached"
You can see the google colab [here](https://colab.research.google.com/drive/1aD56hiMBYamkOJb5LXTGRmvIwglICvcD?usp=sharing)

**Comment by josiahcoad** [comment]
Found out what I was doing wrong. For anyone else interested, replace
```
!tensorboard --logdir ./a2c_cartpole_tensorboard/
```
with
```
%tensorboard --logdir ./a2c_cartpole_tensorboard/
```

**Comment by AdamClarkStandke** [comment]
nice
