### ISSUE TITLE
[Question] DDPG Parameters

### ISSUE THREAD

**Issue by mdev11** [hill-a/stable-baselines#897]
Hi I'm new to RL and currently working on my project using DDPG from stable baselines. And I have some questions about the parameters:
1. What is the difference between timesteps and nb_train_steps? If I didn't change the nb_train_steps, would it affect my model?
2. I set the verbose parameter to verbose=1, but the training information only appear every 10k steps, can I change it? like every 1k steps maybe?

Thank you.

**Comment by araffin** [comment]
>What is the difference between timesteps and nb_train_steps?

See https://github.com/hill-a/stable-baselines/issues/776#issuecomment-606726393

> but the training information only appear every 10k steps, can I change it? like every 1k steps maybe?

you can change `log_interval` in the `learn()` method (cf doc)

it also depends on `nb_training_steps` (see https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ddpg/ddpg.py#L866)

**Comment by mdev11** [comment]
Okay thank you so much :)
More question please.. its kind out of topic but, my actor keep getting negative loss, is it normal?

**Comment by araffin** [comment]
>my actor keep getting negative loss

Please take a look at the resources in our documentation to understand more about the meaning of the losses (notably take a look at spinning up).
Usually actor loss value does not have much sense.

Closing this issue then.
