### ISSUE TITLE
SubprocVecEnv does not correcly close environments.

### ISSUE THREAD

**Issue by NeoExtended** [hill-a/stable-baselines#898]
Basically the title. Upon receiving the _close_ command the subprocess worker only closes its remote, but does not propagate the close command down the wrapper stack. This may produce problems if wrappers like the Monitor still hold open file handles.

Suggested fix is to change 

```python
elif cmd == 'close': 
    remote.close()
    break
```

to 
```python
elif cmd == 'close':  
    env.close()  
    remote.close()  
    break
```

Should i create a pull request?

**Comment by araffin** [comment]
>Should i create a pull request?

Please do ;) Thanks for pointing out the issue. I think the problem is also that `close()` is not well defined by gym api. It is mainly used to close the viewer but as you remarked it, some wrappers use it differently.

**Comment by araffin** [comment]
Could you also submit the same PR afterward to SB3? (should be more or less the same edits)

https://github.com/DLR-RM/stable-baselines3

**Comment by NeoExtended** [comment]
Both done :).
