### ISSUE TITLE
Notion of LSTM cells is deeply rooted in the BasePolicy class

### ISSUE THREAD

**Issue by erniejunior** [hill-a/stable-baselines#90]
For some reason, the number of LSTM cells is a parameter of the constructor of the BasePolicy ([see here](https://github.com/hill-a/stable-baselines/blob/834de7d74327639dd8032d3f8bb9f57a3e6ad10b/stable_baselines/common/policies.py#L46)). I see that it is used there to construct some placeholder for possible LSTM cell states. There is a 'magic number' factor 2 by which the number of LSTM cells is multiplied for no obvious reason. The same 'magic number' can be found in the LstmPolicy class. If we use those 'magic numbers', we might as well keep them together in one class.

Is it really necessary to have such a specific parameter to an abstract base class? Maybe a more generale 'state size' parameter would also work?

What happens if I want more than one LSTM layer in my policy?

**Comment by araffin** [comment]
>There is a 'magic number' factor 2 by which the number of LSTM cells is multiplied for no obvious reason. 

I think I understand now why there a factor 2: for the states of an LSTM, you have the cell state and the hidden state (see https://github.com/hill-a/stable-baselines/blob/834de7d74327639dd8032d3f8bb9f57a3e6ad10b/stable_baselines/a2c/utils.py#L234), which is something you don't have when using a GRU for instance.
Also, if you look at the code, n_lstm is really the number of units in the lstm:
https://github.com/hill-a/stable-baselines/blob/834de7d74327639dd8032d3f8bb9f57a3e6ad10b/stable_baselines/common/policies.py#L201

So, the only thing missing is having more customization for the number of lstm layers.
