### ISSUE TITLE
Loading a model without an environment, this model cannot be trained until it has a valid environment.

### ISSUE THREAD

**Issue by istakaitis** [hill-a/stable-baselines#901]
Hello

Using the example code below (found in the documentation), I get the following message:

"Loading a model without an environment, this model cannot be trained until it has a valid environment."

The code runs fine if I don't save and load the model, but I do need to be able to save and load. I'm using PyCharm, Python 3.6.9.

```python
import gym

from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.deepq.policies import MlpPolicy
from stable_baselines import DQN

env = gym.make('CartPole-v1')

model = DQN(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
model.save("deepq_cartpole")

del model # remove to demonstrate saving and loading

model = DQN.load("deepq_cartpole")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

**Comment by araffin** [comment]
Hello,

This is just a warning, everything is fine and expected ;)
This is to prevent error when you want to continue training after loading a model.

**Comment by istakaitis** [comment]
thank you
