### ISSUE TITLE
[question] How is the episode reward reported in tensorboard calculated

### ISSUE THREAD

**Issue by stheid** [hill-a/stable-baselines#905]
- Custom Env
- PPO agent

The episode reward reported in tensorboard is 2 orders of magnitude higher than using the model and running it in the environment for one episode.

I have a lot of internal state in my environment. I suspect that some part of the batch calculation is interfering with my assumptions.

I have problems understanding the MPI calls in the learn function, as this is where stable baselines seems to calculate the reward

https://github.com/hill-a/stable-baselines/blob/d288b6d911094268b17abb61dbe9ac3ca05e1ce3/stable_baselines/ppo1/pposgd_simple.py#L324-L327

**Comment by araffin** [comment]
Hello,
Please fill the issue template completely.
There are several issues related to that: https://github.com/hill-a/stable-baselines/issues/143 (and related)

In short: use a Monitor wrapper instead and look at `ep_rew_mean` or even better: use an `EvalCallback` (cf doc).

**Comment by stheid** [comment]
Sorry for not using the template, but i thought as it was only a question my formulation was sufficient. I will have a look at the other issue.

It confuses me why calculating the reward using the monitor wrapper makes a difference to the reward, but i can check that. Find it a little unintuitive.
