### ISSUE TITLE
[question] how to train model in multi gpus?

### ISSUE THREAD

**Issue by wujiren** [hill-a/stable-baselines#907]
hi. i want to train my model in a public server in out lab, there are 4 gpus, but somttimes some of the gpus are occupied. if some are available, i want train model on all of the remain gpus, take example ,if the gpu 0,1 are taken and gpu 2,3 are free, how to set the model to run on these specific gpus?  is there any demo or guidance?

**Comment by Miffyli** [comment]
Quick googling gives [this](https://stackoverflow.com/questions/40069883/how-to-set-specific-gpu-in-tensorflow), which I have used. Set environment variable `CUDA_VISIBLE_DEVICES="0,1"` to use GPUs 0 and 1, or `CUDA_VISIBLE_DEVICES=""` to not use GPUs at all (good for small environments).

**Comment by wujiren** [comment]
sorry for bothered you and thanks for reply. at first the gpu did not take effect and i debuged for a very long time, almost collapsed, so i  asked the question. finial i find out that the version of cuda has been upgraded to 10.1, and i installed tensorflow 1.15 by pip, it did not install appropriate cuda in the env, so no visible devices could found by os. i find out by using tf.config.experimental.list_physical_devices('GPU') , it returns an empty list. so if anyone has the same problem ,it may help.
thank you  again.
