### ISSUE TITLE
[question] About saving VecNormalize statistics periodically

### ISSUE THREAD

**Issue by liyan2015** [hill-a/stable-baselines#910]
Hi, I was using `CheckpointCallback` to monitor the DQN model states in case the episode reward suddenly collapses (e.g., falls from best to a low value after some timesteps) before the given end timestep.  However, the checkpoint zip files did not include the VecNormalize statistics, which are necessary for evaluation according to [examples](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features). 

The doc says VecNormalize statistics can be saved by below codes AFTER training:
```
stats_path = os.path.join(log_dir, "vec_normalize.pkl")
env.save(stats_path)
```
I also checked `train.py` in rl-baselines-zoo but the `pkl` file there is also saved after training.

 One possible solution I have in mind is to create a custom CallBack class like `CheckpointCallback` and save the `pkl` file in `_on_step` function with `self.model.get_env().save(stas_path+steps+'.pkl')`. But is there any off-the-shelf method that I can use to periodically save the `pkl` file during learning? Or the VecNormalize statistics can be restored from the checkpoint zip files? Any hints are greatly appreciated!

**Comment by Miffyli** [comment]
You are correct it is not saved automatically, and the solution you provided is closest to "off-the-shelf" solution there is right now (probably easiest to copy the original `CheckpointCallback` and do modifications to that). Indeed it becomes bit difficult to keep track of correct agent file + correct normalization. Technically it would be easy to add VecNormalize stats to the the zip-file, and I have also been wondering if there should be "wrappers for agents", which behave like traditional wrappers but are instead tied to agents and stored along with them.

**Comment by liyan2015** [comment]
> I have also been wondering if there should be "wrappers for agents", which behave like traditional wrappers but are instead tied to agents and stored along with them. Such feature could be planned for stable-baselines3.
If I understand it right, you mean adding a feature to `VecNormalize` wrapper, say automatically save `pkl` file whenever CallBack is used? Anyway, thank you for your lightning-fast response and this awesome repo. I really enjoyed playing around here!

**Comment by araffin** [comment]
> Hi, I was using `CheckpointCallback` to monitor the DQN model states in case the episode reward suddenly collapses (e.g., falls from best to a low value after some timesteps) before the given end timestep. However, the checkpoint zip files did not include the VecNormalize statistics, which are necessary for evaluation according to [examples](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features).
> 
> The doc says VecNormalize statistics can be saved by below codes AFTER training:
> 
> ```
> stats_path = os.path.join(log_dir, "vec_normalize.pkl")
> env.save(stats_path)
> ```
> 
> I also checked `train.py` in rl-baselines-zoo but the `pkl` file there is also saved after training.
> 
> One possible solution I have in mind is to create a custom CallBack class like `CheckpointCallback` and save the `pkl` file in `_on_step` function with `self.model.get_env().save(stas_path+steps+'.pkl')`. But is there any off-the-shelf method that I can use to periodically save the `pkl` file during learning? Or the VecNormalize statistics can be restored from the checkpoint zip files? Any hints are greatly appreciated!

The rl zoo also have an example on how to save intermediate stats: https://github.com/araffin/rl-baselines-zoo/blob/fd9d38862047d7fd4f67be8eb3f6736e093eac9f/utils/callbacks.py#L37
it is used in the eval callback.

**Comment by liyan2015** [comment]
> The rl zoo also have an example on how to save intermediate stats: https://github.com/araffin/rl-baselines-zoo/blob/fd9d38862047d7fd4f67be8eb3f6736e093eac9f/utils/callbacks.py#L37
> it is used in the eval callback.

Great! Thank you for this tip.
