### ISSUE TITLE
[question] How to access environment variables in a callback using SubprocVecEnv?

### ISSUE THREAD

**Issue by rgalljamov** [hill-a/stable-baselines#912]
Hi, I'm using `SubprocVecEnv` to train a PPO2 agent on multiple environments in parallel. 
I've implemented a custom `callback` to log environment specific variables to TensorBoard. This works perfectly fine when using a single environment with `DummyVecEnv` as I can directly access the environment by `self.training_env.venv.envs[0]`. Is there a way to do something similar with a `SubprocVecEnv`, i.e. to access a single environment? If not, can we get access to the outputs of the `env.step(action)` function? 

Thank you in advance and a heartful thanks for your great effort in general. 
This repository is very well thought out and amazingly useful!

**Comment by araffin** [comment]
Hello,
I think you can find your answers in the documentation:
- see `env_method()`, `get_attr` in https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#stable_baselines.common.vec_env.DummyVecEnv.get_attr
- for accessing `.step()`, this will be possible very soon: https://github.com/hill-a/stable-baselines/pull/787

**Comment by rgalljamov** [comment]
Hello @araffin, 

thank you very much for your very quick and helpful answer. `get_attr` worked like a charm. 
Excuse me for not having taken a closer look at the documentation.

Keep up the great work and support!
Best regards
