### ISSUE TITLE
[bug] Assertion error when generating expert trajectories in some vec envs

### ISSUE THREAD

**Issue by jbarsce** [hill-a/stable-baselines#913]
Hello, first of all, thanks for this great repo =)

**Describe the bug**
There is an assertion error (size of observation does not correspond to the size of actions) when trying to record expert trajectories in a vectorized environment where its observations are not images.

Inspecting the `generate_expert_traj` code, this assertion error occurs because when images are not recorded, [in this line](https://github.com/hill-a/stable-baselines/blob/b3b217c48752b50cca6a6eaac8264df5b8e88852/stable_baselines/gail/dataset/record_expert.py#L117), the observation for all the environments (and not only the first env as it does in line 109 with `obs_ = obs[0] if is_vec_env else obs`) is appended to the list. Therefore, when this happens and the observation array is reshaped in line 150, its len differs with the len of the actions.

**Code example**

```python
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common import make_vec_env
from stable_baselines.gail import generate_expert_traj
from stable_baselines import ACER

# multiprocess environment
env = make_vec_env('CartPole-v1', n_envs=4)

model = ACER(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)

generate_expert_traj(model, save_path='.', n_timesteps=0, n_episodes=5)

```

```bash
Traceback (most recent call last):
  File "/home/juan/.config/JetBrains/PyCharm2020.1/scratches/scratch_7.py", line 13, in <module>
    n_episodes=5)
  File "stable_baselines/gail/dataset/record_expert.py", line 163, in generate_expert_traj
    assert len(observations) == len(actions)
AssertionError

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: pip
 * GPU models and configuration: CPU (no GPU available)
 * Python version: 3.6.10
 * Tensorflow version: 1.15.2
 * Versions of any other relevant libraries: stable-baselines 2.10.0

**Comment by araffin** [comment]
Hello,

There is a warning: https://github.com/hill-a/stable-baselines/blob/b3b217c48752b50cca6a6eaac8264df5b8e88852/stable_baselines/gail/dataset/record_expert.py#L47

You should use only one env to record expert data.

That being said, this is a bug, thanks for reporting.
