### ISSUE TITLE
Issue for "fix single typo" pull request (PR #917)

### ISSUE THREAD

**Issue by ColinLeongUDRI** [hill-a/stable-baselines#918]
Opening an issue for the pull request https://github.com/hill-a/stable-baselines/pull/917, as described in the [Guidelines](https://github.com/hill-a/stable-baselines/blob/master/CONTRIBUTING.md)

Changed "Stabe" to "Stable".

**Comment by Miffyli** [comment]
Issues are only mainly required for functional bug-fixes and new features, but not for small documentation updates :). Closing this issue.
