### ISSUE TITLE
[question] Model Based RL with Stable Baselines?

### ISSUE THREAD

**Issue by josiahcoad** [hill-a/stable-baselines#924]
I would like to do some model based RL with stable baselines. From what I've read, it seems that to do this, I just have to train a model f to predict the next state, given the current state and action, i.e. s{t+1} <- f(s{t}, a{t}). I want to do this so that the RL can plan several steps into the future. 

Anyways, I need access to the *obs* and *actions* from the ```learn``` method in PPO2. Basically, after each rollout, I want to use the data collected to train f in a supervised manner. I am trying to use a callback to do this. Is this possible?

Thanks!

**Comment by Miffyli** [comment]
I am not sure if this is doable with callbacks alone, but modifying existing code should not be too difficult. Environment steps for learning [are done here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L482), and the surrounding code is about collecting states/actions/etc for next updates, which sounds like the part you want to modify.

PS: I am not a model-based-RL-guy, so I can not comment on the idea you suggested.

**Comment by josiahcoad** [comment]
Thank you for your quick reply! Sounds good, thanks!

**Comment by PartiallyTyped** [comment]
Hi, you can do that through callbacks. You need just to modify `callback.on_rollout_end` along these lines:

```
def _on_rollout_end(self):
        mb_obs = self.locals["mb_obs"]
        mb_rewards = self.locals["mb_rewards"]
        mb_obs = np.asarray(mb_obs, dtype=self.obs.dtype)
        mb_rewards = np.asarray(mb_rewards, dtype=np.float32)
```

The code that collects the transitions is here:

https://github.com/hill-a/stable-baselines/blob/9ce4155fec12db22ab53626f315fd8481d40e9cd/stable_baselines/ppo2/ppo2.py#L468-L499

**Comment by josiahcoad** [comment]
> Note: This is on the latest version of sb2. Not sure if it's been pushed to the pypi.
@PartiallyTyped thanks for the response. In fact, I had tried printing the locals but didn't see the obs in there. Makes sense if its not in the pypi yet.

**Comment by PartiallyTyped** [comment]
It’s not in pupil, the patch #787 was completed  recently (^^’).

**Comment by josiahcoad** [comment]
Thanks again for commenting. In case anyone wants to use the new patch, you can use 
```!pip install git+https://github.com/hill-a/stable-baselines.git```

**Comment by araffin** [comment]
> Thanks again for commenting. In case anyone wants to use the new patch, you can use
> `!pip install git+https://github.com/hill-a/stable-baselines.git`

this is actually already in the documentation ;)
https://stable-baselines.readthedocs.io/en/master/guide/install.html#bleeding-edge-version

**Comment by abesalom10** [comment]
I had the same question. First of all, I want to build a model-based RL agent. In my env when I am in state s and take action a, what will be next state is unknown, and want to estimate the next state and reward by model. From my knowledge, this is exactly what model-based RL does. 
If You have found already a solution in stable-Baseline, can you provide it? I can't found here model-based learning.

**Comment by Miffyli** [comment]
@abesalom10 stable-baselines focuses on model-free algorithms. There are no plans for model-based models, but some could be added to [contrib repo](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/) some day.

**Comment by abesalom10** [comment]
Thank you for your response. Can you give advice on frameworks where I can find model-based RL  algorithms?

**Comment by Miffyli** [comment]
@abesalom10 Sorry, I am not too familiar with that side of things. Your best bet might be to look for the very specific algorithm you want to use.
