### ISSUE TITLE
[Question] Suboptimal TRPO experts from generate_expert_traj (part 1 of 3)

### ISSUE THREAD

**Issue by prabhasak** [hill-a/stable-baselines#929]
Hello. My objective is to imitate an expert using GAIL. I train a gym env with an RL algo (say TRPO), generate expert data from the learned model (using [``generate_expert_traj``](https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/gail/dataset/record_expert.html#generate_expert_traj)), train GAIL using this expert. In short: **RL -> expert -> GAIL**. However...

1. There seems to be a stark difference between statistics of the trained model (using [``evaluate_policy``](https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/common/evaluation.html#evaluate_policy)) and the generated expert. Screenshot 1 & 2 below shows a comparison for two Gym envs (check: mean return, number of successful episodes)

Note: Afaik, this happens **only for TRPO and on specific envs** (worked fine on Pendulum-v0). Check screenshot 3 for SAC, looks fine

**TRPO on LunarLanderContinuous-v2** (learned model vs generated expert)
<img src="https://user-images.githubusercontent.com/25005912/86854757-a8e1bd00-c07e-11ea-9c10-1746e87bb2ae.png" height="60%" width="60%">

**TRPO on Hopper-v2** (learned model vs generated expert)
<img src="https://user-images.githubusercontent.com/25005912/86856697-78038700-c082-11ea-8657-4ff56e8ebba8.png" height="60%" width="60%">

**SAC on Hopper-v2** (learned model vs generated expert)
<img src="https://user-images.githubusercontent.com/25005912/86855865-daf41e80-c080-11ea-888b-5f957636e7d1.png" height="60%" width="60%">

2. To my surprise, GAIL did a good job on the 'suboptimal' TRPO-Hopper expert from earlier. Any thoughts on why this might be happening? (I need optimal experts for my experiments)

**GAIL on Hopper-v2** (generated expert vs learned model)
<img src="https://user-images.githubusercontent.com/25005912/86856689-74700000-c082-11ea-81c0-e8d9834e35aa.png" height="60%" width="60%">

I need to run GAIL on my CustomEnv and since GAIL uses TRPO (and since GAIL hasn't been able to imitate my CustomEnv expert in the last couple months!), I was worried if I was missing something in my experiments. A sample code to reproduce the screenshots is available [here](https://github.com/prabhasak/masters-thesis) (it is just running RL on a Gym env, really)

**System Info**
 * Windows 10
 * Python 3.7.0
 * Tensorflow 1.14.0

**Comment by araffin** [comment]
Hello,
I think this is due to deterministic evaluation (cf doc).
But we should maybe allow that parameter to be passed when recording the expert.

Related: https://github.com/hill-a/stable-baselines/issues/581#issuecomment-557984749

**Comment by prabhasak** [comment]
> I think this is due to deterministic evaluation

Makes sense. I use ``deterministic=True`` to evaluate the trained model

> But we should maybe allow that parameter to be passed

[Here](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/gail/dataset/record_expert.py#L120), right? I wonder why TRPO experts are more prone to being suboptimal 👀 (did not face this as consistently with SAC/PPO)

> Related: #581 (comment)

Thanks! You ask here if VecNormalize was used. I'd like to report that 'VecNormalize-d' experts (as in #931) have poorer stats compared to experts not using them. Any idea why?

**Comment by araffin** [comment]
>Here, right? I wonder why TRPO experts are more prone to being suboptimal eyes (did not face this as consistently with SAC/PPO)

yes. SAC `predict` is deterministic by default.

>Thanks! You ask here if VecNormalize was used. I'd like to report that 'VecNormalize-d' experts (as in #931) have poorer stats compared to experts not using them. Any idea why?

It highly depends on your env and is mosty beneficial for PPO/A2C. And you have to make sure to deactivate the reward normalization when evaluating the agent.

**Comment by prabhasak** [comment]
> And you have to make sure to deactivate the reward normalization when evaluating the agent

Yes, doing that :)

Thanks so much for the quick replies, @araffin! Closing this
