### ISSUE TITLE
[Question] Working with other formats of env and expert data (part 2 of 3)

### ISSUE THREAD

**Issue by prabhasak** [hill-a/stable-baselines#930]
Hello. My objective is to imitate an expert using GAIL. I train my custom env on RL, generate experts from the learned model, and train GAIL with this expert. In short: **RL -> expert -> GAIL**

You must be familiar with the [MineRL](https://github.com/minerllabs/minerl) challenge. It seems like they have a separate [package](https://minerl.io/docs/api/data.html) just to view and work with their [dataset](https://minerl.io/docs/tutorials/data_sampling.html#sampling-the-dataset). Their env obs, action spaces are [dictionaries](https://minerl.io/docs/environments/index.html#minerltreechop-v0). Their data is saved as .npz, but each trajectory is a folder in itself!

Can we find support from Stable Baselines for these envs and data? Are there any easy workarounds? Do you have any resources recommendations for repos I can work with? (possible related discussion on envs with dictionaries in [665](https://github.com/hill-a/stable-baselines/issues/665#issuecomment-579348334) and [23](https://github.com/araffin/rl-baselines-zoo/issues/23))

**Comment by Miffyli** [comment]
Moving discussion to #931.
