### ISSUE TITLE
[question] How can I find out the format of net_arch

### ISSUE THREAD

**Issue by juliangall** [hill-a/stable-baselines#938]
The [Custom Policy Network](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html) examples say to use net_arch to define the network architecture. Where can I find a description of how to specify a network in net_arch?

e.g. One of the examples has:

```python
net_arch=[dict(pi=[128, 128, 128], vf=[128, 128, 128])]
```

I cannot find, with much searching, what dict, pi, vf etc. mean. What is the full specification for how to describe a network this way? N.B. My background is Tensorflow.

Thank you.

Julian

**Comment by Miffyli** [comment]
The answer is [in same page bit lower](https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html#examples), with some crude visualization :)

**Comment by juliangall** [comment]
Thanks for your quick response. I take your RTFM point but it would be helpful to have a list of the parameters, what they mean and how they work, rather than having to guess from given "Examples". 

e.g. Looking at the CustomLSTMPolicy example, it has:

```python
net_arch=[8, 'lstm', dict(vf=[5, 10], pi=[10])]
```

I can guess that this is an LSTM layer with 8 units, but is that right?

**Comment by Miffyli** [comment]
Ah yes, I see where the confusion comes from, the documentation is not the clearest on that part.

That network would be a single layer of 8 units, followed by a LSTM layer of `n_lstm` units (additional parameter to policy) and then split into separate vf/pi heads.
