### ISSUE TITLE
[Feature Request] Huber loss for PPO2

### ISSUE THREAD

**Issue by erniejunior** [hill-a/stable-baselines#94]
Some people use huber loss for the value function (e.g. in [this paper](https://arxiv.org/abs/1707.05110)). I want that too plz!

**Comment by erniejunior** [comment]
I tried it and for the problem in the paper it seemed to make thinks worse. But this is not a definitive conclusion because I did not optimize the hyperparameters for that specific loss (e.g. I guess the `vf_coef` would need to be adapted) and for other problem domains it might actually be better.

**Comment by araffin** [comment]
Ok, I will try to play with it a bit and will see if I can notice any difference. Do you have an example of a "classic" gym env where it makes a difference?
Also, what kind of reward did they use in the paper? And did you try normalizing the reward?

**Comment by erniejunior** [comment]
First tests showed, that a `vf_coef` that is 10 times higher than usual might help. I have no example of gym envs where it would make sense. I just read about the huber loss in a number of places and right now try to reproduce the mentioned paper as closely as possible.

Even if huber loss does not help, I want to certain about it, do systematic tests and statistical analysis over multiple runs instead of just rejecting it based on some "playing around".

**Comment by araffin** [comment]
>Even if huber loss does not help, I want to certain about it, do systematic tests and statistical analysis over >multiple runs instead of just rejecting it based on some "playing around".

Sure, if your results are quantitative, then we will certainly merge the PR ;)

**Comment by erniejunior** [comment]
As I only work in the quadrotor problem, any results for MY problem domain can never be a base to reject the Huber loss. We would need to look at many other problem domains before we can make a decision. I can not do that (no time for that) but other people might try it if it is easy to do because its already implemented in their favorite RL library ...

**Comment by araffin** [comment]
closing this one as it will probably not be merged...
