### ISSUE TITLE
Single-step learning

### ISSUE THREAD

**Issue by troyappel** [hill-a/stable-baselines#942]
My use case involves a reward function with real-world values gathered every 10 seconds for a long period of time. I want to perform a single learning step every 10 seconds. Is there any way to do this easily?

**Comment by Miffyli** [comment]
The definition of a "learning step" varies from algorithm to algorithm, and also how the delay between training steps. E.g. A2C trains every `n_step` environment steps (usually between 5-20), and PPO2 does similar but with hundreds-to-thousands of steps per environment. 

In any case, that can not be fixed based on wall-clock as you are asking. The closest thing is to estimate how many steps there will be in 10 seconds and set `n_steps` accordingly.
