### ISSUE TITLE
evn.render() in doc examples don't run unless n_envs=1 in make_vec_env()

### ISSUE THREAD

**Issue by pstansell** [hill-a/stable-baselines#945]
This is possibly quite trivial, but the `evn.render()` lines of the code examples do not run for multiprocess environments unless unless `n_envs=1` in `make_vec_env()`.

For example, the code example on this page
* https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html

I'm using stable-baselines 2.10.0.

The error is
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 85, in render
    return super().render(*args, **kwargs)
TypeError: render() missing 1 required positional argument: 'mode'
```

**Comment by Miffyli** [comment]
Thanks for reporting this. Indeed the example code does not work. The issue seems to lie in VecEnv definition where [default render mode is not defined](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/base_vec_env.py#L158) but in Gym Env the [default is "human"](https://github.com/openai/gym/blob/master/gym/core.py#L66), and judging by the examples this should be default for vecenvs too.

However when I tried `env.render("human")` on the example something else broke regarding image stuff. That needs bit more time to look into.

**Comment by pstansell** [comment]
I quick work-around is to set the `n_envs=1` before running `env.render()`.

For example:
```
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2

# multiprocess environment
env = make_vec_env('CartPole-v1', n_envs=4)

model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
model.save("ppo2_cartpole")

del model # remove to demonstrate saving and loading

model = PPO2.load("ppo2_cartpole")

# Enjoy trained agent
env = make_vec_env('Pendulum-v0', n_envs=1)       # <------ NEW LINE
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

**Comment by Miffyli** [comment]
Yeah the code works for single environments but it should also work for multiple environments (draws a neat tiled image with cv2). I will look into this later today.

**Comment by araffin** [comment]
@Miffyli i think i forgot to push that to sb2 : https://github.com/DLR-RM/stable-baselines3/pull/43

**Comment by araffin** [comment]
@pstansell could you upgrade to master's version (cf doc) ?

**Comment by Miffyli** [comment]
@araffin Running with `master` it defaults to "human" as expected, but this error still rises:

```python
     13     """
     14     img_nhwc = np.asarray(img_nhwc)
---> 15     n_images, height, width, n_channels = img_nhwc.shape
     16     # new_height was named H before
     17     new_height = int(np.ceil(np.sqrt(n_images)))

ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by araffin** [comment]
@Miffyli what version are you using?

The following code works for me (using latest master version):
```python
from stable_baselines.common.cmd_util import make_vec_env

n_envs = 4
env = make_vec_env('CartPole-v1', n_envs=n_envs)
 
obs = env.reset()
for _ in range(100):
    env.step([env.action_space.sample() for _ in range(n_envs)])
    env.render()
```
(it works also with SB3)

**Comment by Miffyli** [comment]
Ah yes, I did a derp. I forgot to `reset` the environment before trying to render it :'). Everything works as expected.

**Comment by pstansell** [comment]
Thanks for the amazingly quick resolution!
