### ISSUE TITLE
Using MlpLstmPolicy with PPO2

### ISSUE THREAD

**Issue by aadnesd** [hill-a/stable-baselines#949]
**Describe the bug**
To start the training I need a vectorized environment so I use

`make_vec_env(id, n_envs = 2)`

But when the training finishes and I try 

`action, _states = model.predict(self.obs)`

I get this error:

![image](https://user-images.githubusercontent.com/36450347/87660463-6182bd00-c75f-11ea-8b0f-54ef3452f017.png)

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
pip
 * GPU models and configuration
gtx 1080 Ti
 * Python version
3.7.7
 * Tensorflow version
1.15.0 -gpu
 * Versions of any other relevant libraries

**Additional context**
I'm new to this and don't really understand the error message, but looks to me that it doesn't accept the input as it has (2,12) because of the 2 environments,  but then again I need at least that to get training started. I've tried loading with one environment and training with n_envs=nminibatches without any luck. Thanks

**Comment by Miffyli** [comment]
Please include a minimal code to replicate the issue, and also check docs on how to use recurrent policies (e.g. [here](https://stable-baselines.readthedocs.io/en/master/guide/examples.html?highlight=lstm#recurrent-policies)). It is hard to say with this information what might be wrong.

**Comment by aadnesd** [comment]
What type of code should I include, like my custom environment? 
I see now that I didn't call model.predict with state=state, mask=done . I will try that

**Comment by Miffyli** [comment]
> What type of code should I include, like my custom environment?

No need to include your full custom environment if you prefer not to share it, just a dummy one that manages to raise the error. The code should be complete in a sense that running it produces the error.

**Comment by aadnesd** [comment]
Hi, so I got it working by training with a dummy env with 2 environments and then creating a test environment with one env after finding #166 .  And also doing 
`new_obs, rewards, done, info = test_env.step(action)`
`self.xcoord.append(info[0]['x'])`

To extract what I needed
