### ISSUE TITLE
[Error] install inside conda environment

### ISSUE THREAD

**Issue by AlessandroZavoli** [hill-a/stable-baselines#954]
I'm trying to install stable-baselines on the Italian supercomputer Marconi100 (CINECA) via anaconda

i set up a conda environment, but once i try to install stable-baselines i get the following error:
"ERROR: Could not find a version that satisfies the requirement opencv-python (from stable-baselines) (from versions: none)
ERROR: No matching distribution found for opencv-python (from stable-baselines)"

Did anyone else ever experience something like that?

Alessandro

Cluster specs:
             IBM Power AC922 (Whiterspoon) -                                        
            Red Hat Enterprise Linux Server release 7.6 (Maipo)                 
                                                                                                               
 compute nodes with:                                                                            
        - 2x16 cores IBM POWER9 AC922 at 3.1 GHz                                
        - 4 x NVIDIA Volta V100 GPUs, Nvlink 2.0, 16GB

**Comment by araffin** [comment]
Hello,
you need to clone the repo and do an install from source (cf doc) after commenting the open cv dependency in the `setup.py`.
There is apparently no pre-built binary for the red hat os.
If you need opencv (e.g. for atari preprocessing), you need to build opencv and its python binding yourself.

**Comment by AlessandroZavoli** [comment]
Since I need to build from source many (if not all) depenance, do you suggest any specific version of python/tensorflow/scipy?

**Comment by AlessandroZavoli** [comment]
> Hello,
> you need to clone the repo and do an install from source (cf doc) after commenting the open cv dependency in the `setup.py`.
> There is apparently no pre-built binary for the red hat os.
> If you need opencv (e.g. for atari preprocessing), you need to build opencv and its python binding yourself.

even though i commented the opencv dependency in "stable-baselines/setup.py" the dependancy keep popping up:

    No matching distribution found for opencv-python (from gym[atari,classic_control]>=0.11->stable-baselines)

Any idea how to solve this issue?

**Comment by araffin** [comment]
Remove the atari dependency if not needed (from gym)

**Comment by AlessandroZavoli** [comment]
That worked! thank you!

**Comment by AlessandroZavoli** [comment]
By using 
    python setup.py install --user
do I just install stable-baseline without the mpi support?

Can/should I force installing the mpi version?

**Comment by Miffyli** [comment]
Only PPO1, TRPO and DDPG require MPI support. If you do not need those algorithms you can skip installing MPI-related libraries.

**Comment by AlessandroZavoli** [comment]
Thank you. Now I'm a bit confused how to allocate resources for (as an example) PPO2. It seems that the execution times on a vectorized environment (16 env) are exactly the same if I allocate 1 node or 8 nodes.
Does it just use openmp for parallel execution?

**Comment by AlessandroZavoli** [comment]
I'm not very familiar with the   `multiprocessing `. Do you mean that i have no control over where (on the cluster) the Python process are created. e.g., they might all be on the same node?

**Comment by Miffyli** [comment]
They will all probably be on the same node. I have no experience with multiprocessing on multi-node systems, either.

This falls more on the tech-support side, so you can close the issue if there are no more questions to raise that are specific to stable-baselines.

**Comment by AlessandroZavoli** [comment]
You're right. I close this issue and open a different one for PPO1
