### ISSUE TITLE
[Error] while calling EvalCallback

### ISSUE THREAD

**Issue by Rajawat23** [hill-a/stable-baselines#955]
Hi!
I am training a deepq agent, on Atari
As mentioned in the documentation, I have separate environments for training and evaluations. 
I ran into following error in evaluation callback.

`ValueError: Error: Unexpected observation shape (1, 84, 84, 4) for Box environment, please use (210, 160, 3) or (n_env, 210, 160, 3) for the observation shape.`

```
    env = make_atari_env(cfg.env, num_env=4, seed=cfg.seed)
    # Frame-stacking with 4 frames
    env = VecFrameStack(env, n_stack=4)
    policy = partial(CustomDQNPolicy, dueling=0)

    eval_env = make_atari_env(cfg.env, num_env=1, seed=cfg.seed)
    # Frame-stacking with 4 frames
    eval_env = VecFrameStack(eval_env, n_stack=4)
    eval_callback = EvalCallback(eval_env, n_eval_episodes=10,eval_freq=cfg.evaluation_steps, log_path=cfg.eval_log_dir,best_model_save_path=cfg.eval_save_dir,verbose=1)

    model = DQN(
        env=cfg.env,
        policy=policy,
        learning_rate=cfg.learning_rate,
        buffer_size=cfg.memory_capacity,
        exploration_fraction=0.1,
        exploration_final_eps=0.01,
        train_freq=cfg.train_freq,
        learning_starts=50000,
        target_network_update_freq=cfg.sync_freq,
        double_q=cfg.double_q,
        gamma=cfg.gamma,
        prioritized_replay=cfg.prioritized_replay,
        prioritized_replay_alpha=cfg.prioritized_replay_alpha,
        tensorboard_log=cfg.log_dir
    )
    model.learn(total_timesteps=int(cfg.num_timesteps), callback=eval_callback)
    model.save(os.path.join(cfg.save_dir, cfg.model_name))

    env.close()
```

**Comment by araffin** [comment]
Hello,
please look at the warning: your eval env is not the same as your training env.

**Comment by Rajawat23** [comment]
Hi @araffin 
in both env and eval_env I passed the same environment id string in my case `BreakoutNoFrameskip-v4`.

**Comment by araffin** [comment]
`env=cfg.env` should be `env=env`

**Comment by Rajawat23** [comment]
Thanks @araffin for pointing it out, but as per the documentation of the [DQN](https://stable-baselines.readthedocs.io/en/master/modules/dqn.html) it accepts `:param env: (Gym environment or str) The environment to learn from (if registered in Gym, can be str)` 
So I thought it didn't matter much tbh.

**Comment by araffin** [comment]
Please read carefully my two comments ;)

**Comment by Rajawat23** [comment]
Ah! yeah a novice mistake thanks a ton :D
