### ISSUE TITLE
minor bug of log in sac.py

### ISSUE THREAD

**Issue by YangRui2015** [hill-a/stable-baselines#958]
Hello, there is an incorrect log when running sac.py.  You can see in the following picture, the log_interval was set as 4(4 * 50=200 steps), but it didn't log at the expected time(n * 200 steps) because the last step of one episode was labeled as the first step of the next episode.
![截屏2020-07-23 上午10 37 27](https://user-images.githubusercontent.com/38036768/88249298-a5813f00-ccd6-11ea-84b5-3ec6fd590318.png)
 
It is because we appended a new reward 0 before log:
```
if done:
    if self.action_noise is not None:
         self.action_noise.reset()
    if not isinstance(self.env, VecEnv):
        obs = self.env.reset()
    episode_rewards.append(0.0)

    maybe_is_success = info.get('is_success')
    if maybe_is_success is not None:
        episode_successes.append(float(maybe_is_success))
```
It is easy to correct this issue, just to subtract 1 from num_episodes:
![截屏2020-07-23 上午11 09 02](https://user-images.githubusercontent.com/38036768/88249631-9b137500-ccd7-11ea-919f-8f73849f9fc6.png)

I have tested it and am ready for pull request.
![截屏2020-07-23 上午11 33 09](https://user-images.githubusercontent.com/38036768/88249887-5b00c200-ccd8-11ea-94c0-1ca15fb2c8cc.png)

**Comment by araffin** [comment]
Hello,

nice catch, we would appreciate a PR that solves this issue ;)

**Comment by YangRui2015** [comment]
> Hello,
> 
> nice catch, we would appreciate a PR that solves this issue ;)

I will commit a PR right now :)
