### ISSUE TITLE
PPO2 reward goes up, then goes down

### ISSUE THREAD

**Issue by matthew-jurewicz** [hill-a/stable-baselines#960]
Reward steadily increases to good range and peaks at 150,000 time steps, then steadily decreases to terrible range and bottoms out at 300,000 time steps. Also, reward variance seems to decrease over time. Any idea what's going on?

**Comment by Miffyli** [comment]
It is hard to say what is happening from this info alone. Please include full code to replicate the issue.

**Comment by matthew-jurewicz** [comment]
Unfortunately, I can't share my code. Rewards dramatically decrease as value function loss decreases. In another run, I was surprised to see rewards started very high with presumably random actions.

**Comment by Miffyli** [comment]
Such things can happen, e.g. you can get 100% reward in CartPole-v1 with correct network and random parameters. This does not sound like a stable-baselines issue/bug, so you may close this issue.

**Comment by matthew-jurewicz** [comment]
That's very odd, isn't that like a CNN randomly accurately classifying? That seems very unlikely, no?
