### ISSUE TITLE
[question] How to get intermediate layer activation

### ISSUE THREAD

**Issue by rachlee93** [hill-a/stable-baselines#964]
I know from #669 you can pull out the values of the model given an observation. I need to be able to get an intermediate layer activation (specifically, the features extracted from the cnn extraction function). Is there a way for me to get the intermediate layer activation? 

Previously when I used baselines, I was able to get the tensorflow graph and then just use .eval to pull out specific layer activations. 

**System Info**
Running Stable Baselines on Windows10.

**Comment by araffin** [comment]
Well, this is more a tensorflow question.

>Previously when I used baselines, I was able to get the tensorflow graph and then just use .eval to pull out specific layer activations.

Yes, that would work too. You need a custom version of SB2.
You can also take a look at V3 (in pytorch), where it should be easier to extract those: https://github.com/DLR-RM/stable-baselines3

**Comment by rachlee93** [comment]
Figured it out. I just added a `get_graph` function in the `a2c.py` to just return the graph. I'll probably put that together with the parameters that I can extract, assign them, and run from there.
