### ISSUE TITLE
[question] what is model/q? 

### ISSUE THREAD

**Issue by rachlee93** [hill-a/stable-baselines#965]
While looking into saving/loading parameters, I noticed that in stable baselines' A2C model, there are additional weights for `q` (in addition to `vf` and `pi`). What are these weights for? I've been searching the code for setting up the policy and for customizing policies, and I cannot find the reference for these `q` weights. 

I'm using A2C, CnnLstm Policy. 

**Code example**
```

model = A2C(CnnLstmPolicy, env)
params = model.get_parameters()
parameters.keys()
```

**Comment by Miffyli** [comment]
Answering based on the title: If you are talking about PPO/A2C, then these q-values are an artifact that is not being used by those algorithms (values are not being trained). They exist to be used by other algorithms, where they correspond to state-action values.

**Comment by rachlee93** [comment]
Yep! Pressed enter too soon. Thanks-- I was really wondering what those q-values were. Glad to know that they're just artifacts.
