### ISSUE TITLE
No one uses pyTorch / Torch in the Actual AI industry 

### ISSUE THREAD

**Issue by developeralgo8888** [hill-a/stable-baselines#966]
Please let me know if something has changed. In the last 5 years since Tensorflow hit the Open source community and AI industry has not looked back and No one uses Torch or PyTorch anymore. So why would Stable-baselines switch its backend to PyTorch , a dying library ?

**Comment by PartiallyTyped** [comment]
Most research is done in pytorch. The community also voted for pytorch and writing for Tf is a mess and, afaik, needs many optimizations for eager mode to reach pytorch’s dynamic graphs.

**Comment by araffin** [comment]
Hello,
The choice of pytorch for v3 was discussed and motivated in #366  and #733 (we even had an experimental tf2 version: https://github.com/Stable-Baselines-Team/stable-baselines-tf2/).

>No one uses Torch or PyTorch anymore. So why would Stable-baselines switch its backend to PyTorch , a dying library ?

@developeralgo8888 this is a first warning, issues are for bug report/feature requests/discussions, not for controversy, this is not reddit.
