### ISSUE TITLE
[question] Easiest way to do non-real-time training step parts (reward, step, etc.) custom env, ppo2

### ISSUE THREAD

**Issue by sblasher** [hill-a/stable-baselines#967]
I've created a custom gym environment for a specific ml problem and I'd like to train a ppo2 stable-baselines agent on it. However, the step function calls an external function, which takes a lot of time (contacts a server, waits for the response, downloads data...). Does this cause problems with the stable-baselines agents (do they have inbuilt time-outs) , or should it run smoothly? 

If it causes problems, what would be the best workaround? (i.e. calling the step/reset etc. functions manually, or altering ppo2's .learn method?)

Thankful for any input.

**Comment by araffin** [comment]
Hello,
It should work as there is no timeout, but it will be slow.

**Comment by sblasher** [comment]
Hi and thanks for the quick reply.
