### ISSUE TITLE
[Question]: Why RecurrentActorCriticPolicy State Placeholder Shape

### ISSUE THREAD

**Issue by bbrito** [hill-a/stable-baselines#975]
Dear stable-baselines team,

I am using the RecurrentActorCriticPolicy in PPO2. In line 347 of policies.py, you define the variable state_ph_shape = (self.n_env, ) + tuple(state_shape). Should it be state_ph_shape = (n_batch, ) + tuple(state_shape)?

Thank you so much for the clarification.

Best regards,
Bruno

**Comment by Miffyli** [comment]
When dealing with RNNs the training the training has to be done sequentially, i.e. you can not sample two different batches of data from the same environment and first train on one and then on another, as the hidden states do not make sense after the first update (they differ from what the network would now create). The only way to parallelize the computation is to use multiple envs, leading to the "batch dimension" being of size "n_env".

**Comment by bbrito** [comment]
Thanks for the explanation @Miffyli . As I understand each batch is modeled as a sequence hence, this implementation.

In the case, we want to consider a variable size of the observation space we would need to employ dynamic rnns and use the sequence dimension for the observation space, correct? In that case, we could not model the batch dimension as a sequence, correct? Is my point clear?

Thanks for the feedback.

Best regards,
Bruno

**Comment by Miffyli** [comment]
If by "variable size of observation space" you mean variable sequence length, then yeah that would require some dynamic rnns and more tuned handling of varying-length sequences. The current implementation does include treatment for episode boundaries (when episode ends, rest of the trajectory contains samples from a new trajectory and hidden state is reset).  I do not think implementation for this would be easy, though.

If there are no more issues/bugs to raise specifically about stable-baselines, you may close the issue.

**Comment by bbrito** [comment]
That is all! Thanks a lot!
