### ISSUE TITLE
Making Deeper models

### ISSUE THREAD

**Issue by NC25** [hill-a/stable-baselines#978]
Hello, 

I am relatively new to Reinforcement Learning. For the past months, I have been experimenting on base classes in the stable baselines documentation and tutorials. I was wondering how can I make even more complicated models that become more accurate that expand on these base classes. Also, how do I figure out the best hyper parameters for tuning? Is it just experimentation? 

 Any resources would help and your assistance is appreciated.

**Comment by Miffyli** [comment]
You need to create custom policies for custom networks (see docs on using custom policies). For hyperparameters see [rl-zoo](https://github.com/araffin/rl-baselines-zoo/) and how it optimized hyperparameters. There is also [stable-baselines3](https://github.com/DLR-RM/stable-baselines3) where modifying algorithms can be easier with its pytorch code.

I am closing this issue as there does not seem to be any stable-baselines issue/bug to report here, and this is not a place for tech-support.
