### ISSUE TITLE
Restrict value function search space

### ISSUE THREAD

**Issue by sophiagu** [hill-a/stable-baselines#980]
Does baselines support learning an agent/function that has constrained properties?
For example, in a problem whose state S and action A are both numeric values, I want to force the property that, at a higher S value, A should be smaller than at a lower S value, aka the output action A is a monotonic function of the state S.
Does baselines have a built-in functionality of that? If not, what may be a good way to do so?

**Comment by Miffyli** [comment]
There is no built-in functionality for that. You could define A to be offsets from S, i.e. agent outputs some value `a` that is non-negative (you can bound this with action-space and/or by mapping it to interval of your liking), you add the minimum value to it `A = S + a` and run that action on env. I have no guarantees any of these would be pretty solutions, and the whole concept of "invalid actions" is still an open-ish issue (see e.g. #453 ).

**Comment by sophiagu** [comment]
That's an interesting idea.
Because the scale of S to A is unknown in my problem and they may be of very different scales, so using A = S + a may be inappropriate. I'm thinking to incorporate the function property into the reward by adding a penalty term when the action predicted for the current state violates the property:
During training, I'll save all the past sampled state action pairs within the same episode, and then:
- for all the past states < current state, I expect their actions > the current action predicted, if not, penalize the reward;
- for all the past states > current state, I expect their actions < the current action predicted, if not, penalize the reward.
I haven't thought of a good way to define this penalty term yet (and which scale to use for this penalty compared to the original reward).

May I some opinions on whether this approach will work?

**Comment by Miffyli** [comment]
Unfortunately I do not have time to offer tech support like this (these issues are not designed for that). Sounds like this goes beyond standard algorithms and into somewhat unknown territories. You could ask help on stackoverflow or on reddit /r/reinforcementlearning.

Btw you might find [PyTorch version of stable-baselines](https://github.com/DLR-RM/stable-baselines3) easier to modify. The included algorithms have been tested to match the performance of algorithms here.

You may close the issue if there are no stable-baselines-specific bugs/issues/requests to raise.
