### ISSUE TITLE
I added TF2.x support for stable-baselines

### ISSUE THREAD

**Issue by sophiagu** [hill-a/stable-baselines#984]
This is not really an issue but I'd like to let you know that I created a repo for supporting stable-baselines in TF2.x with minimum amount of changes: https://github.com/sophiagu/stable-baselines-tf2
I've tested that repo both on a local machine and in a third party environment.

Hope this will be of help to other people who are using TF2 and Stable Baselines!

**Comment by araffin** [comment]
Hello,

Thank you for doing that =)
We would appreciate a PR that add your repo to the project page ;)

We also had an experimental tf2 version here: https://github.com/Stable-Baselines-Team/stable-baselines-tf2/
(working but far from complete).

**Comment by sophiagu** [comment]
np! I hope that helps other people.

Since I haven't been using GitHub extensively, idk how to add my repo to the project page? But if someone knows how to do that, I can add that person as a collaborator to my repo. Or if it's something simple that I can do on my own, I'd appreciate some steps that I can follow.

**Comment by Miffyli** [comment]
@sophiagu 

The [project page](https://github.com/hill-a/stable-baselines/blob/master/docs/misc/projects.rst) lists projects that use or are closely related to stable-baselines. @araffin suggests that you make a pull-request to add your project on that list. You can do that by making a fork of stable-baselines, creating a new branch, updating the file and submitting the PR (plenty of info on that online). Alternatively you can simply edit file here on Github and it does all the magic for you.

**Comment by sophiagu** [comment]
Thx! I created a update request to the project page: https://github.com/hill-a/stable-baselines/compare/master...sophiagu:patch-1

**Comment by Miffyli** [comment]
That's not a PR just yet. See e.g. [this doc](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

**Comment by deetungsten** [comment]
I created a fork of the original and merged sophiagu's changes so you can install it via pip (https://github.com/deetungsten/stable-baselines) to make life easier when installing it (such as google colab). @sophiagu Thank you so much for making the stablebaseline-tf2! I wanted to see what the performance will be on the new Apple M1 CPU and your work makes it a lot easier.
