### ISSUE TITLE
Broken pipe with custom env and SubprocVecEnv multiple envs

### ISSUE THREAD

**Issue by drose188** [hill-a/stable-baselines#988]
I was unable to run ppo2 with SubprocVecEnv and multiple envs. 
I get broken pipe always.
Is there a working code of a simple custom env with ppo2 and SubprocVecEnv (learning + running)?
I didn't find any working examples.

I tried:
self.env = DummyVecEnv([lambda: self.env])
self.env = VecNormalize(self.env, True, True, 10., 10.)

num_cpu = 2,4 or 12

self.env = SubprocVecEnv([lambda: self.env for i in range(num_cpu)])
or
self.env = SubprocVecEnv([self.make_env(self.env, i) for i in range(num_cpu)])

where 

def make_env(env_id, rank, seed=0):
      def _init():
            env = gym.make(env_id)
            env.seed(seed + rank)
            return env
        set_global_seeds(seed)
        return _init

**Comment by Miffyli** [comment]
Please format code in codeblocks for easier reading. Also include system information (python/library versions, OS info, etc). Meanwhile see [docs on vecenvs](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html).

**Comment by drose188** [comment]
Python 3.6.5 :: Anaconda, Inc.
Windows 10 pro N
Veriion 1903
Core i7, 16 GB
I read the docs. Is there a working example of custom gym env with ppo2ת subprocenv and multiple envs?

**Comment by Miffyli** [comment]
The [examples](https://stable-baselines.readthedocs.io/en/master/guide/examples.html) should work just by changing DummyVecEnv to SubProcVecEnv. Please include full code that raises the exception and full stacktrace of the error.

**Comment by drose188** [comment]
The multiprocessing example is not with custom env.
It works well with predefined envs but fails with custom env.

**Comment by Miffyli** [comment]
Ah, sorry, I completely missed the "custom env" part that was in the title... My bad!

Unfortunately we do not offer tech support for custom envs. VecEnvs work with custom environments (many examples around the issues here), but something in your environment is causing trouble with `multiprocessing` library. It could that something in OS does not like about your environment, or something can not be serialized or something completely different. Sorry for not being helpful.

**Comment by drose188** [comment]
I tried this:

`import gym
from gym import error, spaces, utils
from gym.utils import seeding

class basic_custom_env(gym.Env):
    metadata = {'render.modes': ['human']}
    def __init__(self):
        print('init basic')
        
    def step(self, action):
        print('step')
    
    def reset(self):
        print('reset')
    
    def render(self, mode='human'):
        print('render')
    
    def close(self):
        print('close')`

and then:

`import gym
import numpy as np

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines.common import set_global_seeds, make_vec_env
from stable_baselines import PPO2
from basic_custom_env import basic_custom_env

def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_global_seeds(seed)
    return _init

if __name__ == '__main__':
    #   env_id = "CartPole-v1"
    env_id = basic_custom_env()
    num_cpu = 4  # Number of processes to use
    # Create the vectorized environment
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
    
    # Stable Baselines provides you with make_vec_env() helper
    # which does exactly the previous steps for you:
    # env = make_vec_env(env_id, n_envs=num_cpu, seed=0)
    
    model = PPO2(MlpPolicy, env, verbose=1)
    model.learn(total_timesteps=10)
    
    obs = env.reset()
    for _ in range(10):
        action, _states = model.predict(obs)
        obs, rewards, dones, info = env.step(action)
        env.render()`

I get this error:

Process SpawnProcess-4:
Traceback (most recent call last):
  File "C:\Users\me\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\me\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\me\stable-baselines\stable_baselines\common\vec_env\subproc_vec_env.py", line 13, in _worker
    env = env_fn_wrapper.var()
  File "E:\test _basic_custom_env.py", line 20, in _init
    env = gym.make(env_id)
  File "C:\Users\me\Anaconda3\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Users\me\Anaconda3\lib\site-packages\gym\envs\registration.py", line 89, in make
    spec = self.spec(path)
  File "C:\Users\me\Anaconda3\lib\site-packages\gym\envs\registration.py", line 106, in spec
    if ':' in path:
TypeError: argument of type 'basic_custom_env' is not iterable

**Comment by Miffyli** [comment]
The code is still not in proper codeblocks \``` like this \```. Also this is not a place for technical support.

**Comment by drose188** [comment]
I suceeded to create SubprocVecEnv with 'fork' (only 'fork' works for me). Model is trained with multiprocessing, however when trying to predict, I do this:

env.training = False
env.norm_reward = False

obs = env.reset()
dones = False

action, _states = model.predict(obs, deterministic=deterministic)

I get this error:

ValueError : Error: Unexpected observation shape (12, 1, 1106) for Box environment, please use (1106,) or (n_env, 1106) for the observation shape.

I then tried this:

obs = obs[:,0,:] or obs = obs[0,0,:]

and still get an error.

How should I preprocess the observation for 12 env's?

**Comment by Miffyli** [comment]
Looking at the error and the fixes alone it should work. Again, this is not a place for tech support (bugs or issues or enhancements only), and you need to include **full** source code to get the error to get any help.

**Comment by drose188** [comment]
I had the observation as:
obs = obs[:,0,:]
Do I have to do the same with action? 
Since with subprocenv I get an array of n_envs * action and it doesn't work.
I tried 
obs = obs[:,0,:]
action, _states = model.predict(obs, deterministic=True)
obs, rewards, dones, info = self.env.step(action[0])
And it fails in the step.

**Comment by Miffyli** [comment]
You should probably index it with `obs = obs[0]`, not `obs = obs[:, 0, :]` because with multiple envs the observations from different envs is stacked on first axis.

Closing this as "no tech support".
