### ISSUE TITLE
Non-episodic problems

### ISSUE THREAD

**Issue by sophiagu** [hill-a/stable-baselines#992]
The algorithms (e.g. PPO2) implemented in stable-baselines seem to only support episodic problems. And if I understand correctly, the policy weights are only updated once per episode.
For problems that have no episodes and can be run forever (e.g. trading), they have to be forced to use episodes in order to use the stable-baselines agents, which increases the training time needed. For example, a continuous problem originally can reach the optimal policy using 1 million timesteps. If I force it into 1000 timesteps per episode, to get the same number of weight updates, I need to run the agent for 1000 * 1 million timesteps.

Is my reasoning correct? If so, are there easy tricks I can use for the stable-baselines agents to accept continuous training without episodes?

**Comment by Miffyli** [comment]
Some implementations work on based episodes (or, require an "end of episode" before they train). However PPO2 implementation here and in SB3 [run updates even if episodes do not end](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/ppo2/ppo2.py#L471).

**Comment by sophiagu** [comment]
I see. Does PPO2 updates the weights after each episode or after each timestep?

**Comment by Miffyli** [comment]
No. Updates are done _exactly_ after `n_step` calls to `env.step`.

**Comment by sophiagu** [comment]
So if I run all the time steps within one episode the weights would only be updated once? That doesn't sound like something I want...

**Comment by Miffyli** [comment]
Again, no. The updating is independent of how long the episodes are and the agent will be roughly updated for `total_timesteps / (n_step * n_envs)` times (`total_timestep` includes all steps to all environments, while `n_step` only reflects per-environment number of steps taken before agent is updated). I recommend reading through source around the part.

**Comment by sophiagu** [comment]
Thanks a lot for the explanation! (I'm outside so it's a bit difficult to read the code...sorry if I asked questions that are already documented in the code.)
Just to summarize your points: If I want my agent to run continuously and update its weights per time step in each env, I can just set the number of episodes to be one and n_steps to be one.
If that's correct, feel free to close this issue.

**Comment by Miffyli** [comment]
You can set your number of episodes to anything you like, but `n_step` should be a sensible amount for PPO. See e.g. [rl-zoo PPO2 hyperparameters file](https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/ppo2.yml) for some good values for `n_step`. It can be 256 or 512 or 2048 or even higher, it still will train as with "episodic" environments.

**Comment by sophiagu** [comment]
Thx! But the hyper parameters there are all used in games and they look too big? The smallest one is 16 used in MountainCart. I can imagine it's because you need to move the cart for awhile to determine a reasonable reward. But in my problem the reward from the previous day (or a very small number of previous days) is enough to tell the agent how to adjust its behavior.

In summary, from my problem's requirements:
- It needs to be trained continuously without resetting env in the middle -> So I should only have one episode;
- The weights are desired to be updated every time step -> So if the agent will be updated for total_timesteps / (n_step * n_envs) then n_step should also be one or close to one.

Unless you meant setting n_step to one is undesirable for PPO algorithmically?

**Comment by Miffyli** [comment]
Setting `n_step` low is generally bad for PPO, yes. It might work for some simple environments like mountain-car which have dense reward structure / "behaviour" where it works, but generally higher `n_step` leads to stabler learning at the cost of more samples needed. You need to experiment with different `n_step` values for your specific env to find the correct one. But the first part is satisfied regardless of what `n_step` you choose (it will learn inside that one episode).

This starts to feer off to the tech support side which we do not provide, and as originally question was answered I am going to close this issue.
