### ISSUE TITLE
testing model the second time gives UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by jandevries1421353151** [hill-a/stable-baselines#994]
When calling DQN.load() it works first time on a saved model, however when you call it a second time on the same model it gives UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

is this intended, i am just following the documentation, (Edit), meaning u could literally copy and paste the example code from the stable baselines website, run it and the run the loading function twice (not same session).

**Comment by jandevries1421353151** [comment]
is this sufficient?

**Comment by araffin** [comment]
Hello,
Please fill up the issue template completely.

**Comment by ThomasRochefortB** [comment]
I am having also the same issue using PPO1 on a custom environment. About 50% of the time, the saved model will be corrupt and I end up getting this message when trying to load it : UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

I have noticed that this does not happen when I train the model inside a Jupyter Notebook, only when I use "mpirun" inside a terminal.

**Comment by Miffyli** [comment]
As @araffin noted, please include the full code to replicate the issue. Also try using PPO2 rather than PPO1 (PPO2 is more refined version generally).

**Comment by jandevries1421353151** [comment]
Hello @araffin , would you be so kind to delete my issue? it is solved, kinda?

**Comment by ThomasRochefortB** [comment]
Hi @jandevries1421353151 , could you please explain how you managed to resolve your issue? Thanks!

**Comment by keshaviyengar** [comment]
> I am having also the same issue using PPO1 on a custom environment. About 50% of the time, the saved model will be corrupt and I end up getting this message when using PPO1.load() : BadZipFile: Bad CRC-32 for file 'data'
> 
> and also : UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.
> 
> I have noticed that this does not happen when I train the model inside a Jupyter Notebook, only when I use "mpirun" inside a terminal.

Did you manage to solve this issue?

**Comment by Miffyli** [comment]
@keshaviyengar I recommend moving to [stable-baselines3](https://github.com/DLR-RM/stable-baselines3), where saving/loading is more up-to-date.
