### ISSUE TITLE
[question] Agent not "getting it" for custom gym

### ISSUE THREAD

**Issue by AbdullahGheith** [hill-a/stable-baselines#998]
**Describe the question**
I am trying to train an agent for a game i made. The game is here: https://github.com/AbdullahGheith/BlockPuzzleGym
I tried mainly PPO2, but the agent is not "getting it". I've done 2500000 timesteps.

**Code example**

```python
import gym
import blockpuzzlegym
from stable_baselines import PPO2

env = gym.make("BlockPuzzleGym-v0")
model = PPO2('MlpPolicy', env, verbose=1)
model.learn(250000)

for _ in range(10000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

**System Info**
Describe the characteristic of your environment:
 * Library is installed through pip (i am using pycharm)
 * CPU: AMD Ryzen 9 3900X
 * GPU: GTX 2070 Super
 * Python version: 3.8
 * Tensorflow version: 1.14.0

**Additional context**
I am new to machine learning, and sorry for asking here. I don't know where else to ask. I've debugged the game alot and it seems to be working. Could be an issue with the game of course. Any help appreciated.
I've tried training other envs in the openai gym, and they worked fine.

**Comment by Miffyli** [comment]
Generally we do not provide tech support here, and these issues are designed for issues, bugs and feature requests. You could ask this on /r/reinforcementlearning or on Stackoverflow.

For a quick tip: Try changing other parameters of PPO2, not just the length of training. See [here](https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/ppo2.yml) for a list of hyperparameters for different environments that work for them. I see your environment does not match any of these, but at the very least it gives pointers to what the parameters could be like. Also check out "gridworld" environment and parameters people use for that.

Closing as "no tech support".
